import type { JutsuDefinition } from "@/lib/jutsu/types";

/** Estilo Água, Rank D — Anotações do Jiraya, p.160-167. */
export const aguaJutsu: JutsuDefinition[] = [
  {
    key: "quebra-do-golfinho",
    nome: "Quebra do Golfinho",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "15 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você manipula seu chakra do Estilo água para gerar uma besta aquática de sua escolha que parece investir contra uma criatura que você pode ver dentro do alcance. Faça um ataque de ninjutsu corpo a corpo. Em caso de sucesso, você causa 3d6 de dano frio e força a criatura alvo a fazer um teste de resistência de Constituição. Em caso de falha no teste, ela ganha 1 nível de Congelado.\n\nSe usado próximo a uma fonte suficiente de água, reduza o custo de chakra deste jutsu em 2 ou aumente o alcance para 45 pés.",
    emNiveisSuperiores:
      "Para cada rank acima de D, aumente o custo deste jutsu em 3. Ao lançar este jutsu no rank B, a quantidade de ataques que você realiza torna-se 2. Ao lançar este jutsu no rank S, a quantidade de ataques que você realiza torna-se 3.",
  },
  {
    key: "goticulas-estimulantes-sede",
    nome: "Gotículas Estimulantes: Sede",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu", "Médico"],
    descricao:
      "Você solidifica seu chakra do Estilo Água em água pura que flutua sobre sua mão. Quando conjurado, uma criatura disposta dentro do alcance pode, como parte da conjuração deste jutsu, beber a água. O alvo ganha pontos de vida temporários iguais ao seu CD de resistência de Ninjutsu e é curado de uma das seguintes condições causadas por um efeito de grau igual ou inferior: Sangrando, Queimado, Congelado, Atordoado ou Envenenado.\n\nAs criaturas que ganham pontos de vida temporários deste jutsu recebem uma ação especial chamada Impulso Encorajado, que desaparece ao final de seu próximo turno. Impulso Encorajado: Em seu turno, você pode usar esta ação especial para realizar as seguintes ações: Correr, Esconder-se, Desengajar-se ou Esquivar-se.",
    emNiveisSuperiores:
      "Para cada rank acima de D, aumente o custo deste jutsu em 3. Se conjurado no rank B, aumente o número de condições curadas para 2. Se conjurado no rank S, aumente o número de condições curadas para 3.",
  },
  {
    key: "aguas-curativas",
    nome: "Águas Curativas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você coleta uma massa de água e concede chakra a ela e começa a curar uma criatura disposta que você pode tocar com ela. Isso dissolve a água de ser usada no processo de cura das criaturas curadas. Role 2d8, curando a criatura alvo pelo total.\n\nSe usado próximo a uma fonte suficiente de água, reduza o custo de chakra deste jutsu em 2 ou você pode optar por remover uma das seguintes condições além de restaurar pontos de vida: condições de sangramento, queimadura, envenenamento ou choque.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o valor de cura em 1d8.",
  },
  {
    key: "asas-de-mantis",
    nome: "Asas de Mantis",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Auto",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você manifesta asas de água que tremulam ao seu comando. Até o final do seu turno, você ganha uma velocidade de voo de 30 pés.\n\nAo final da duração deste jutsu, se você não tiver pousado, suas asas desaceleram, trazendo-o suavemente para baixo sobre a superfície diretamente abaixo de você.",
    emNiveisSuperiores:
      "Para cada rank acima de D, aumente o custo deste jutsu em 3. Conjurar este jutsu no rank B dá a ele uma duração de Concentração, até 1 minuto. Conjurar este jutsu no rank A dá a ele uma duração de Concentração, até 10 minutos, sem custo adicional de chakra para manter a concentração.",
  },
  {
    key: "nevoa-oculta",
    nome: "Névoa Oculta",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (esfera de raio de 30 pés)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você conjura uma nuvem de partículas de água condensadas em uma grande nuvem de névoa. Criaturas dentro desta nuvem de névoa não conseguem enxergar mais do que 5 pés de distância delas, sofrendo desvantagem em testes de Sabedoria (Percepção) para ver e em ataques que dependem de visão enquanto estiverem dentro da nuvem de névoa. Criaturas fora da névoa também têm desvantagem ao atacar outras criaturas que estejam dentro da névoa.\n\nAlém disso, quando este jutsu é conjurado, selecione uma criatura que você possa ver. Essa criatura se torna marcada pela névoa. Durante a duração deste jutsu, uma criatura marcada pela névoa é sempre percebida por você enquanto estiver na névoa oculta, não pode se beneficiar de estar escondida enquanto estiver dentro da névoa oculta e você não tem desvantagem em rolagens de ataque contra ela. Se usado próximo a uma fonte suficiente de água, reduza o custo de chakra deste jutsu em 2 ou você pode escolher selecionar uma criatura adicional para ser marcada pela névoa.",
  },
  {
    key: "enxame-de-piranhas",
    nome: "Enxame de Piranhas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Água", "Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você manifesta uma bolha de água de tamanho médio e então convoca um enxame de piranhas dentro dela.\n\nQuando você conjura este jutsu, pode fazer um ataque de ninjutsu corpo a corpo contra uma criatura dentro de 5 pés do enxame. Em caso de acerto, o alvo sofre 2d4 de dano frio + 2d4 de dano perfurante.\n\nComo ação bônus em turnos subsequentes, você pode comandar o enxame para se mover até 30 pés e repetir o ataque contra uma criatura dentro de 5 pés dele. Se você lançar este jutsu enquanto estiver submerso na água, as piranhas podem ser comandadas para se mover até 60 pés em vez de 30.\n\nUma criatura que sofre dano deste jutsu deve fazer um teste de resistência de Constituição. Em caso de falha no teste, ela ganha 1 nível de Congelado. Uma criatura que falhar por 5 ou mais também ganha 1 nível de Sangramento.\n\nSe usado próximo a uma fonte suficiente de água, reduza o custo de chakra deste jutsu em 2 ou você pode optar por aumentar a quantidade de piranhas, aumentando seu dano em +1d6 de dano frio de cada tipo.",
  },
  {
    key: "mandibula-do-tubarao",
    nome: "Mandíbula do Tubarão",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "Auto",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você manifesta uma construção de chakra de liberação de água ao redor de suas mãos para assumir a forma de tubarões que prendem e mordem os alvos durante a duração. Você não pode perder a concentração neste jutsu como resultado de dano.\n\nDurante a duração, como uma ação, você pode fazer um ataque ninjutsu corpo a corpo. Em um acerto, você causa 3d8 de dano de frio e força o alvo a fazer um teste de resistência de Força, sendo agarrado pela cabeça do tubarão em uma falha.\n\nUma criatura agarrada por você dessa forma sofre 1d8 de dano de frio no início de cada um de seus turnos, pois os tubarões mordem mais profundamente. Se você conjurar este jutsu enquanto estiver submerso na água, os tubarões lhe concedem uma velocidade de nado de 60 pés e os ataques feitos com este jutsu são em vantagem.\n\nSe usado perto de uma fonte de água suficiente, reduza o custo de chakra deste jutsu em 2 ou pela duração, se o resultado do seu ataque corpo a corpo Ninjutsu for 10 maior que a CA do alvo, ele é tratado como um acerto crítico e cria uma onda de choque de chakra de água que causa 2d6 de dano de frio a todas as criaturas de sua escolha a até 10 pés de você.",
    emNiveisSuperiores:
      "Para cada nível que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o dano do ataque em 1d8 e o dano da onda de choque em 1d6, respectivamente. Se este jutsu for conjurado no Rank C ou superior, aumente o número de ataques que você pode fazer em +1.",
  },
  {
    key: "esfera-de-deteccao-de-agua",
    nome: "Esfera de Detecção de Água",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Minuto",
    alcance: "5 pés",
    duracao: "Concentração, até 1 dia",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu", "Sensorial"],
    descricao:
      "Você coleta uma massa de água em uma esfera com 5 pés de diâmetro a partir da área circundante. Durante a duração deste jutsu, você pode ver movimento e atividade em um raio de 250 pés centrado na esfera. Isso requer que a criatura em movimento perturbe alguma fonte de água (poças, corpos de água ou chuva). Esse movimento ou atividade cria bolhas dentro da esfera, indicando a direção do movimento em relação à localização da esfera.\n\nSe usado próximo a uma fonte suficiente de água, reduza o custo de chakra deste jutsu em 2 ou você pode optar por dobrar o alcance sensorial deste jutsu, permitindo que você veja movimento e atividade em um raio de 500 pés centrado na esfera.",
  },
  {
    key: "canhao-de-xarope-de-amido",
    nome: "Canhão de Xarope de Amido",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você molda chakra com sua saliva criando uma substância viscosa semelhante a xarope. Você cospe em uma criatura, diminuindo sua velocidade devido à natureza viscosa e pegajosa do líquido. Faça um ataque de ninjutsu à distância contra uma criatura que você possa ver dentro do alcance. Em caso de acerto, a criatura alvo ganha 1 nível da condição Lento até o final de seu próximo turno.\n\nSe usado próximo a uma fonte suficiente de água, reduza o custo de chakra deste jutsu em 2 ou você pode optar por selecionar uma criatura adicional para ser alvo deste jutsu ao lançá-lo.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de criaturas que você pode mirar em +1.",
  },
  {
    key: "martelo-de-tsunami",
    nome: "Martelo de Tsunami",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "10 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você manifesta uma construção de chakra do Estilo água na forma de um grande martelo, conforme o seu design e descrição. Este martelo é então imediatamente usado para realizar um ataque de ninjutsu corpo a corpo contra uma criatura alvo dentro do alcance. Em caso de acerto, você causa 3d6 de dano frio e a criatura alvo deve fazer um teste de resistência de Constituição, sofrendo Congelado em caso de falha no teste.\n\nSe o alvo deste jutsu já tiver níveis de Congelado, ele sofre uma penalidade de -2 em seu teste de resistência com desvantagem, e o dado de dano deste jutsu aumenta em 1 passo. Se o alvo tiver níveis de outra condição Elemental, ele sofre uma penalidade de -2 em seu teste de resistência, e o dado de dano deste jutsu aumenta em 1 passo.\n\nSe usado próximo a uma fonte suficiente de água, reduza o custo de chakra deste jutsu em 2 ou você pode optar por aumentar o dado de dano deste jutsu em 1 passo.",
    emNiveisSuperiores:
      "Para cada rank acima de D, aumente o custo deste jutsu em 3. Quando você conjura este jutsu no rank B, o número de ataques que você pode realizar aumenta em +1. Quando você conjura este jutsu no rank S, o número de ataques que você pode realizar aumenta em +2.",
  },
  {
    key: "massa-viscosa-de-agua",
    nome: "Massa Viscosa de Água",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "30 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você extrai água de uma área próxima a uma criatura disposta que você pode ver dentro do alcance, criando um escudo de água de tamanho médio para protegê-la. O alvo aumenta seu CA em +1 e reduz o dano recebido em 4. Se este jutsu reduzir dano de fogo, ele é reduzido em 6.\n\nSe você iniciar um choque com um Jutsu com a palavra-chave de choque, primeiro verifique se o dano seria reduzido a 0 como resultado da redução de dano deste jutsu. Se o dano de fogo for reduzido a 0, você pode então optar por iniciar um choque, se desejar.\n\nSe usado próximo a uma fonte suficiente de água, reduza o custo de chakra deste jutsu em 2.",
    emNiveisSuperiores:
      "Para cada rank acima de D, aumente o custo deste jutsu em 3. Se este jutsu for lançado no rank B, aumente o bônus de CA em +1 e a redução de dano em +2. Se este jutsu for lançado no rank S, aumente o bônus de CA em +2 e a redução de dano em +6.",
  },
  {
    key: "mistura-de-agua",
    nome: "Mistura de Água",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Concentração, até 10 minutos",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Uma criatura disposta que você toca se torna invisível durante a duração, onde a água do ambiente dobra a luz ao redor do alvo, ocultando sua presença. Qualquer coisa que o alvo esteja vestindo ou carregando se torna invisível enquanto estiver em seu corpo. O jutsu termina para um alvo que atacar, lançar um jutsu ou interagir fisicamente com outra criatura.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e você pode alvejar uma criatura adicional.",
  },
  {
    key: "garras-de-agua",
    nome: "Garras de Água",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você manifesta chakra de liberação de água na forma de duas garras que cercam suas mãos, de seu design e descrição. Faça dois ataques ninjutsu corpo a corpo contra um alvo dentro do alcance, enquanto você gira, cortando-o. Em um acerto bem-sucedido, você causa 2d6 de dano de Frio. As criaturas afetadas devem fazer um teste de resistência de Constituição, ganhando 1 nível de Sangramento, em um teste de resistência falho.\n\nSe usado perto de uma fonte suficiente de água, reduz o custo de chakra deste jutsu em 2 ou o número de ataques em +1.",
    emNiveisSuperiores: "Para cada nível que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o dano em 1d6.",
  },
  {
    key: "lamina-de-palma-dagua",
    nome: "Lâmina de Palma D'Água",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você gera duas lâminas de água energizadas com chakra sobre suas mãos que você lança em um arco. Realize um ataque de ninjutsu à distância causando 4d8 de dano frio em um acerto.\n\nUma criatura afetada por este jutsu fica envolta em água vibrante até o início do seu próximo turno. Se o alvo se mover ou for movido pelo menos 5 pés antes do início do seu próximo turno, ele explode, causando 1d6 de dano frio ao alvo afetado e a todas as criaturas de sua escolha dentro de 5 pés do alvo original.\n\nSe usado próximo a uma fonte suficiente de água, aumente o dano em 1d8.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e aumente o dano deste jutsu em 1d6.",
  },
  {
    key: "formacao-de-agua-poca",
    nome: "Formação de Água: Poça",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você gera uma grande poça de água de seu estômago e a expulsa no chão à sua frente. Esta poça contém no máximo 10 galões de água. Você pode usar esta poça como fonte de água potável, preparar uma armadilha ou usá-la como fonte para ninjutsu de Água mais complexos. Você pode usar a água produzida por este jutsu como fonte de água para até 2 ninjutsu do Estilo água de rank C ou inferior, após o que a poça não é mais utilizável.",
  },
  {
    key: "arapuca-de-selagem-dagua-submersao",
    nome: "Arapuca de Selagem D'Água: Submersão",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "120 pés",
    duracao: "10 minutos",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Água", "Ninjutsu", "Fuinjutsu"],
    descricao:
      "Como parte da conjuração deste jutsu, o alvo deste jutsu deve estar totalmente submerso em qualquer tipo de líquido.\n\nVocê tece um selo de chakra feito do Estilo água que você então coloca na superfície de um líquido.\n\nUma criatura atualmente submersa dentro deste líquido torna-se aprisionada pela própria água. A criatura alvo deve realizar um teste de resistência de Força. Em caso de falha, ela fica Restrita e incapaz de realizar selos de mão durante a duração. O alvo não pode se afogar enquanto estiver restrito por este jutsu.\n\nUma criatura restrita por este jutsu refaz seu teste de resistência no final de cada um de seus turnos. Em caso de sucesso, o jutsu é encerrado imediatamente.",
  },
  {
    key: "shuriken-de-agua-dagua",
    nome: "Shuriken de Água D'Água",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "18 Metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você cria vários shurikens feitos de água e os lança em um alvo que você pode ver dentro do alcance. Realize um ataque de ninjutsu à distância, causando 4d4 de dano frio em um acerto. Se você obtiver um acerto crítico com este jutsu, o dado de dano aumenta para d8, transformando-se em monstruosos shurikens de água.\n\nSe usado perto de uma fonte de água suficiente, reduza o custo de chakra deste jutsu em 2, ou você pode optar por realizar um ataque adicional contra outro alvo dentro do alcance.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e aumente o dano em 1d4.",
  },
  {
    key: "impulso-do-pilar-dagua",
    nome: "Impulso do Pilar D'Água",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você cria uma onda de água que irrompe de baixo de uma criatura que você pode ver dentro do alcance. Este jutsu ignora cobertura. O alvo deve realizar um teste de resistência de Destreza, sofrendo 3d10 de dano frio e sendo Chilled em caso de falha no teste, ou metade desse dano em caso de sucesso e nenhum efeito adicional.\n\nSe usado próximo a uma fonte suficiente de água, reduza o custo de chakra deste jutsu em 2 ou você pode optar por afetar todas as criaturas dentro de 5 pés do alvo também. Uma criatura só pode ser afetada por este jutsu uma vez por conjuração.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3, aumente o número de alvos que este jutsu pode afetar em +1 e aumente o dano em 1d8.",
  },
  {
    key: "purificacao-putreficacao-dagua",
    nome: "Purificação/Putreficação D'Água",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você manipula e molda chakra para reverberar através de uma fonte de fluido, seja lama, águas envenenadas, ou qualquer coisa intermediária. Fluidos de até 10 galões que têm seu chakra fluindo através deles se tornam purificados e transformam-se em água potável pura, livre de todas as impurezas, ou se tornam pútridos, não potáveis e venenosos para beber (Sua escolha).\n\nSe um fluido for artificial ou especial de alguma forma, faça um Teste de Habilidade de Ninshou contra a dificuldade estabelecida pelo Mestre para ver se você pode purificar/putrefazer ou não.",
  },
  {
    key: "chicote-de-agua",
    nome: "Chicote de Água",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "9 Metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você cria um longo chicote de água moldando seu chakra através dele. Realize um ataque de ninjutsu corpo a corpo contra um alvo dentro do alcance, causando 2d6 de dano frio. Além disso, puxe a criatura 3 metros mais perto de você e force o alvo a fazer um teste de resistência de Constituição, ganhando 1 nível de frio em caso de falha.\n\nSe usado perto de uma fonte de água suficiente, reduza o custo de chakra deste jutsu em 2. Em caso de falha no teste de resistência de Constituição, o alvo ganha 1 nível de machucado.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3, o dano em 1d6 e estenda o alcance em 3 metros adicionais.",
  },
  {
    key: "onda-selvagem-de-agua",
    nome: "Onda Selvagem de Água",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "9 metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu", "Conflito"],
    descricao:
      "Você gera uma forte corrente de água e a expulsa como um jato. Faça um ataque de ninjutsu à distância. Em um acerto, a criatura alvo sofre 2d8 de dano frio e é empurrada para trás 3 metros. Se usado perto de uma fonte suficiente de água, reduza o custo de chakra deste jutsu em 2 ou force a criatura alvo a realizar um teste de resistência de Constituição, ganhando uma classificação de resfriado em caso de falha no teste.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3, aumente o dano em 1d8 e a distância de empurrão em +3 metros.",
  },
  {
    key: "escudo-dagua",
    nome: "Escudo D'Água",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Reação, que você realiza quando iria sofrer dano ou fazer um teste de resistência.",
    alcance: "Pessoal",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Água", "Ninjutsu", "Conflito"],
    descricao:
      "Você cria uma parede flutuante de água em espiral, capaz de empurrar criaturas para trás e bloquear ataques. Aumente sua CA em +2 até o início do seu próximo turno e reduza a próxima instância de dano que você receber em 4. Se este jutsu reduziria o dano de Fogo de outro jutsu, você pode iniciar um Choque e adicionar 1d4 ao seu teste de choque.\n\nSe você tiver uma fonte de água suficiente por perto, reduza o custo de chakra deste jutsu em 2 ou o primeiro teste de choque que você fizer com este jutsu será feito com vantagem.",
    emNiveisSuperiores: "Para cada nível que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e a RD em mais 4. Se este jutsu for conjurado no Rank B, aumente o bônus de CA em +1. Se este jutsu for conjurado no Rank S, aumente o bônus de CA em +2.",
  },
  {
    key: "sorriso",
    nome: "Sorriso",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "27 metros",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Água", "Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você envia bolhas feitas de Chakra do Estilo Água para preencher o ouvido interno de seus aliados durante a duração. Selecione até 3 criaturas dispostas dentro do alcance para ganhar os benefícios deste jutsu.\n\nDurante a duração, as criaturas afetadas que realizarem um teste de Sabedoria (Percepção) adicionam seu Modificador de Habilidade em Ninjutsu ao teste. Efeitos ambientais baseados em som que forçam um teste de resistência de qualquer tipo são feitos com vantagem.\n\nAlém disso, o primeiro teste de resistência realizado contra um Genjutsu com a Palavra-chave Auditivo adiciona seu Modificador de Habilidade em Ninjutsu ao teste de resistência. Este jutsu termina imediatamente após este teste de resistência.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de criaturas afetadas por este jutsu em +2.",
  },
  {
    key: "torrente-de-baleias",
    nome: "Torrente de Baleias",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Reação, que você realiza quando você ou uma criatura dentro do alcance sofre dano ou faz um teste de resistência de qualquer tipo.",
    alcance: "Raio de 4,5 metros",
    duracao: "1 Minuto",
    componentes: ["SM", "MC", "SC"],
    // Fonte lista "Custo: Especial (28 Chakra)" — custo fixo de jutsu de Combinação, não o valor normal por rank.
    custoChakra: 28,
    palavrasChave: ["Estilo Água", "Ninjutsu", "Fuinjutsu", "Combinação"],
    descricao:
      "Você e outros conjuradores tecem juntos uma mistura altamente intricada de Chakra do Estilo Água até conjurarem uma Barreira maciça de Água que protege todas as criaturas dentro do raio deste jutsu.\n\nEsta Barreira possui um número de pontos de vida igual a 24d6. Resistente a Dano de Fogo, Vulnerável a Dano de Terra.\n\nEsta Barreira intercepta todos os ataques e Jutsu que cruzariam seu espaço pela duração ou até que atinja 0 pontos de vida.\n\nAs criaturas não podem entrar, sair ou cruzar voluntariamente por esta barreira. Esta Barreira dura pela duração e não pode ser encerrada antecipadamente voluntariamente pelos conjuradores.\n\nAs criaturas não podem ver dentro da barreira, mas as criaturas podem ver do lado de fora da barreira.\n\nCombinação: Se este jutsu for lançado como um jutsu de Combinação com 2 ou mais conjuradores, aumente seus pontos de vida em 2d6.\n\nQualquer criatura que ajude a lançar este jutsu como um jutsu de combinação aumenta a potência defensiva deste jutsu com base no Modificador de Carisma mais alto dentro do grupo de conjuradores. (+0-1: Sem mudança, +2-3: Aumente o dado de pontos de vida para d8, +4-5: Aumente o dado de pontos de vida para d10.)",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de criaturas afetadas por este jutsu em +2.",
  },
  {
    key: "onda-selvagem-de-bolhas",
    nome: "Onda Selvagem de Bolhas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "agua",
    tempoConjuracao: "1 Ação",
    alcance: "Cone de 4,5 metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Água", "Ninjutsu"],
    descricao:
      "Você cria uma massa viscosa de bolhas e as pulveriza em um cone de 4,5 metros à sua frente, criando um terreno escorregadio. Cada criatura de pé na área do jutsu deve realizar um teste de resistência de Destreza, caindo prostrada em caso de falha no teste. Uma criatura que entrar ou terminar seu turno em um espaço na área-alvo também deve realizar o teste de resistência ou cair prostrada. Esta massa de bolhas permanece por 1 minuto, ou até ser lavada.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e aumente o tamanho do cone em 3 metros.",
  },
];
