import type { JutsuDefinition } from "@/lib/jutsu/types";

/** Bukijutsu, Rank D — Anotações do Jiraya, p.370-403 (duas leituras combinadas). */
export const bukijutsuJutsu: JutsuDefinition[] = [
  {
    key: "1-golpe-de-gume",
    nome: "1 Golpe de Gume",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["A (Corte em Combate Corpo a Corpo)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você realiza um golpe amplo e arqueado com sua arma, cortando o alvo com movimentos mínimos desperdiçados. Faça um ataque de taijutsu corpo a corpo usando sua arma, causando o dano da sua arma + 2d6. Em um acerto, o alvo também deve ser bem-sucedido em um teste de resistência de Constituição, sofrendo 1 rank de sangramento em caso de falha no teste.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o dano em 1d6.",
  },
  {
    key: "golpe-esmagador-de-um-so-golpe",
    nome: "Golpe Esmagador de um Só Golpe",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["A (Contusão em Combate Corpo a Corpo)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você realiza um golpe ascendente com sua arma, golpeando e esmagando o alvo de baixo para cima. Faça um ataque de taijutsu corpo a corpo usando sua arma, causando o dano da sua arma + 2d6. Em um acerto, o alvo também deve ser bem-sucedido em um teste de resistência de Força, reduzindo sua CA em 1d4 até o início do próximo turno dele.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o dano em 1d6.",
  },
  {
    // NOTE: fonte lia "36 PSI CANHÃO DE AR" — "36 PSI" parece artefato de OCR/diagramação e foi removido.
    key: "canhao-de-ar",
    nome: "Canhão de Ar",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 ação",
    alcance: "9 metros (30 pés)",
    duracao: "Instantâneo",
    componentes: ["A (Qualquer Lâmina)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Cadeia X", "Confronto"],
    descricao: "Você utiliza o próprio ar para cortar o alvo à distância. Ao balançar sua espada, você lança um projétil comprimido de ar em espiral na direção do alvo. Faça um ataque Taijutsu à distância contra uma criatura dentro do alcance. Em caso de acerto, você causa [dano da arma] + 1d12. A criatura deve realizar um teste de resistência de Destreza. Em caso de falha, ela recebe 1 nível de Lentidão. Se este jutsu for lançado como uma Cadeia 2, ele causa um dano adicional de 2d12. Se for lançado como uma Cadeia 3, o alvo recebe um nível adicional de Lentidão.",
    emNiveisSuperiores: "Para cada rank acima do Rank D em que este jutsu for lançado, aumente o custo em 3 e o dado de dano em +1.",
  },
  {
    key: "2-golpes-cruzados",
    nome: "2 Golpes Cruzados",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["A (Contusão em Combate Corpo a Corpo)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: 'Você realiza dois golpes de corte duplos com sua arma, atacando de ângulos diferentes formando um "X" nas interseções do ataque. Faça dois ataques de taijutsu corpo a corpo usando sua arma, causando o dano da sua arma. Em cada acerto, o alvo também deve ser bem-sucedido em um teste de resistência de Constituição, sofrendo 1 rank de contusão em caso de falha no teste.',
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o alvo sofre uma penalidade de -1 no seu teste.",
  },
  {
    key: "perfuracao-de-2-pontos",
    nome: "Perfuração de 2 Pontos",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["A (Perfuração em Combate Corpo a Corpo)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você realiza um duplo golpe atacando os ombros ou pernas do seu oponente na tentativa de desestabilizá-lo. Faça dois ataques de taijutsu corpo a corpo usando sua arma, causando o dano da sua arma. Se um alvo for atingido pelo menos uma vez, ele também deve ser bem-sucedido em um teste de resistência de Constituição, reduzindo sua velocidade em 10 pés para cada ataque bem-sucedido, até o final do próximo turno dele.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o alvo sofre uma penalidade de -1 no seu teste.",
  },
  {
    key: "3-cortes-laterais",
    nome: "3 Cortes Laterais",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["A (Corte em Combate Corpo a Corpo)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você realiza três ataques de corte atacando as articulações do seu oponente na tentativa de desarmá-lo e incapacitá-lo. Faça três ataques de taijutsu corpo a corpo usando sua arma, causando o dano da sua arma. Uma vez, se você causaria dano com este jutsu, o alvo também deve ser bem-sucedido em um teste de resistência de Constituição, largando qualquer arma que tenha, sendo então afastado 10 pés dela, e ficando atordoado até o final do próximo turno dele.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o alvo sofre uma penalidade de -1 no seu teste.",
  },
  {
    key: "corte-de-entalhe-de-flecha",
    nome: "Corte de Entalhe de Flecha",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 ação",
    alcance: "Alcance da arma",
    duracao: "Instantâneo",
    componentes: ["A (Qualquer Lâmina)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você golpeia uma criatura com um corte instantâneo, sem deixar espaço para interferências. Apenas a criatura alvo pode reagir a este jutsu. Faça um ataque Taijutsu corpo a corpo contra uma criatura dentro do alcance. Em caso de acerto, você causa [dano da arma] + 2d4 e pode escolher mover-se 3 metros (10 pés) para longe da criatura antes que o dano seja rolado.",
    emNiveisSuperiores: "Para cada rank acima do Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 2d4.",
  },
  {
    key: "perfuracao-de-3-pontos",
    nome: "Perfuração de 3 Pontos",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["A (Perfuração em Combate Corpo a Corpo)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você realiza um ataque de três pontos em múltiplos pontos feitos para penetrar na defesa do alvo. Faça três ataques de taijutsu corpo a corpo usando sua arma, causando o dano da sua arma. O alvo também deve fazer um teste de resistência de Constituição. Em caso de falha, ele ganha um rank de enfraquecido até o final do próximo turno dele.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o alvo sofre uma penalidade de -1 no seu teste.",
  },
  {
    key: "postura-de-furia-contida",
    nome: "Postura de Fúria Contida",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Pessoal",
    duracao: "1 minuto",
    componentes: ["A (Qualquer Arma)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: 'Você adota uma postura que permite absorver o dano recebido para revidar com ainda mais força. Sempre que você for atingido ou reagir a um ataque para fazê-lo errar, você ganha 1 Fúria. Você pode acumular uma quantidade de Fúria igual ao seu nível. Essa Fúria pode ser gasta em outros jutsus que tenham o prefixo "Fúria Contida-".',
  },
  {
    key: "calcanhar-de-aquiles",
    nome: "Calcanhar de Aquiles",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "9 metros (30 pés)",
    duracao: "1 minuto",
    componentes: ["A (Arma Corpo a Corpo Perfurante)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você busca incapacitar seu alvo mirando no ponto fraco de sua armadura. Escolha uma criatura dentro do alcance que esteja vestindo armadura. Faça um teste de Artes Marciais contra a CA dela. Se você obtiver um resultado maior que a CA do alvo, percebeu os pontos fracos em sua armadura. Durante a duração deste jutsu, você ignora qualquer RD fornecida pela armadura da criatura, e a CA dela é reduzida em 1. Este jutsu termina antecipadamente se você perder a visão do alvo.",
  },
  {
    key: "furia-contida-rajada-do-dragao",
    nome: "Fúria Contida: Rajada do Dragão",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "1 minuto",
    componentes: ["A (Qualquer Arma)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "(É necessário estar sob os efeitos da Postura de Fúria Contida para conjurar) Você realiza uma rápida sequência de ataques para desgastar seu inimigo. Faça dois ataques Taijutsu corpo a corpo, causando [dano da arma] + 1d4 em cada acerto. Se acertar ambos os ataques, você pode gastar 2 ou mais pontos de Fúria para realizar um ataque adicional para cada ponto de Fúria gasto, até um máximo de 4 ataques adicionais.",
  },
  {
    key: "golpe-contundente",
    nome: "Golpe Contundente",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantâneo",
    componentes: ["A (Qualquer Arma à Distância Contundente)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você prepara sua arma, imbuindo-a com chakra, antes de atacar o alvo, mirando no centro do peito dele. Faça um ataque Taijutsu à distância usando sua arma, causando [dano da arma] + 2d4 como dano contundente. Em caso de acerto, o alvo deve realizar um teste de resistência de Constituição. Em caso de falha, ele fica Atordoado e, se tiver que fazer um teste de concentração para manter um Genjutsu ou Ninjutsu, rola um dado adicional de 1d8, reduzindo o resultado do teste pelo valor obtido.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 2d4.",
  },
  {
    key: "furia-contida-bloqueio-horizontal",
    nome: "Fúria Contida: Bloqueio Horizontal",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Reação ao sofrer dano",
    alcance: "Alcance da arma",
    duracao: "1 minuto",
    componentes: ["A (Qualquer Arma)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "(É necessário estar sob os efeitos da Postura de Fúria Contida para conjurar) Quando você seria atingido por um ataque, pode gastar 2 ou mais pontos de Fúria para tentar aparar o dano. Role o dado de dano da sua arma um número de vezes igual à quantidade de Fúria gasta e reduza o dano recebido pelo valor total obtido. Se você reduzir o dano a 0, faça um número de ataques igual a cada 2 pontos de Fúria gastos, causando o dano do dado da sua arma em cada acerto.",
  },
  {
    key: "lamina-do-pecado-preguica",
    nome: "Lâmina do Pecado: Preguiça",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantâneo",
    componentes: ["A (Qualquer Lâmina)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você busca emular o poder de um dos Sete Pecados Capitais da Humanidade em sua lâmina, imbuindo o Pecado da Preguiça na borda da arma. Faça um ataque Taijutsu corpo a corpo contra uma criatura no alcance. Em caso de acerto, você causa [dano da arma] + 1d8. A criatura alvo deve realizar um teste de resistência de Constituição. Em caso de falha, ela desce na ordem de iniciativa, perdendo motivação para agir rapidamente. Se este jutsu for lançado como uma Cadeia 2, ele causa 2d8 de dano adicional. Se for lançado como uma Cadeia 3, a criatura sofre desvantagem no teste de resistência de Constituição.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d12. A partir do Rank A, se o alvo estiver em último na iniciativa e falhar no teste de resistência, ele não poderá se mover ou agir até o final de seu próximo turno.",
  },
  {
    key: "ricochete-em-cadeia",
    nome: "Ricochete em Cadeia",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantâneo",
    componentes: ["A (Qualquer Arma Lançada)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você realiza seu ataque com o objetivo de atingir o maior número possível de alvos. Faça um ataque Taijutsu à distância contra uma criatura no alcance. Em caso de acerto, você causa [dano da arma] + 1d8. Após acertar, você pode realizar um segundo ataque Taijutsu à distância contra outra criatura no alcance, com uma penalidade de -2 na rolagem de ataque. Se este segundo ataque acertar, você pode realizar um terceiro ataque contra uma criatura no alcance, desta vez com uma penalidade adicional de -2.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d8.",
  },
  {
    key: "respiracao-das-feras-dente",
    nome: "Respiração das Feras: Dente",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você começa a coletar e manifestar chakra até que ele envolva a parte de impacto de sua arma. O chakra se manifesta na forma de uma besta à sua escolha, em qualquer cor que seja claramente visível para os outros. Você começa a atacar de forma selvagem e imprevisível, movido por instintos e impulsos primais. Faça dois ataques Taijutsu corpo a corpo, causando [dano da arma] + 1d6. Você não adiciona seu modificador de habilidade ao dano rolado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e aumente em +1 o número de criaturas que você pode alvejar com este jutsu.",
  },
  {
    key: "ponto-cego",
    nome: "Ponto Cego",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["A (Perfuração ou Corte à Distância)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você prepara sua arma antes de golpear as bordas afiadas com seu chakra e mira no núcleo do seu alvo, atacando o centro do peito. Faça um ataque de taijutsu à distância usando sua arma, causando o dano da sua arma + 3d4 de dano contundente. Em um acerto, o alvo deve fazer um teste de resistência de Força. Em caso de falha, o alvo fica atordoado e, se precisar fazer um teste de concentração, rola um dado adicional de 1d6, reduzindo o resultado do teste.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3. Se este jutsu for lançado no Rank C ou superior, aumente o dano em 1d6. Se for lançado no Rank B, aumente o número de ataques em +1. Se for lançado no Rank S, aumente o número de ataques em +2.",
  },
  {
    key: "respiracao-das-cinzas-torrar",
    nome: "Respiração das Cinzas: Torrar",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer a Distância)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Estilo Fogo"],
    descricao: "Você começa a coletar e manifestar chakra de Estilo Fogo, envolvendo a parte de impacto de sua arma. O chakra de Estilo Fogo se transforma em torrentes de cinzas que emanam de sua arma, criando uma névoa ameaçadora. Selecione uma criatura que você possa ver dentro do alcance e faça um único ataque Taijutsu à distância, com um bônus de +1 em sua margem de ameaça de crítico. Em caso de acerto, você causa [dano da arma] + 2d6 de dano de fogo, e o alvo é sufocado pelas cinzas, ficando Cego até o início do próximo turno dele ou até que seja atacado pela primeira vez antes do próximo turno.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d6. Se este jutsu for lançado no Rank B, você pode escolher um segundo alvo. Se este jutsu for lançado no Rank S, você pode escolher um terceiro alvo.",
  },
  {
    key: "respiracao-de-poeira-sokusei",
    nome: "Respiração de Poeira: Sokusei",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer a Distância)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Estilo Terra"],
    descricao: "Você começa a coletar e manifestar chakra de Estilo Terra até que ele envolva a parte de impacto de sua arma. O chakra de Estilo Terra começa a aumentar o peso e o poder de impacto dos seus ataques, permitindo que você destrua qualquer coisa em seu caminho com facilidade. Faça um único ataque Taijutsu à distância contra uma criatura que você possa ver dentro do alcance. Este jutsu não pode causar um acerto crítico. Em caso de acerto, você causa [dano da arma] + 1d12 de dano de terra e o alvo é empurrado para trás 1,5 metros.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d12.",
  },
  {
    key: "respiracao-da-terra-esmagar",
    nome: "Respiração da Terra: Esmagar",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (raio de 10 pés)",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Estilo Terra"],
    descricao: "Você começa a coletar e manifestar chakra de Estilo Terra até que ele envolva a parte de impacto de sua arma. O chakra de Estilo Terra começa a aumentar o peso e o poder de impacto dos seus ataques, permitindo que você destrua qualquer coisa em seu caminho com facilidade. Você engana seu(s) oponente(s), fazendo-os acreditar que está atacando de uma direção, mas subitamente altera a trajetória do seu golpe para outro ângulo. Todas as criaturas dentro do alcance, cujo valor de habilidade em Taijutsu seja menor que o seu, sofrem uma penalidade de 1d4 na jogada de salvamento deste jutsu. Todas as criaturas de sua escolha devem fazer um teste de resistência de Destreza. Em caso de falha, elas recebem [dano da arma] + 2d6 de dano de terra e ficam derrubadas e contusas, ou metade do dano e sem outros efeitos em caso de sucesso.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3, o dano em 1d6 e o raio em 1,5 metros. Se este jutsu for lançado no Rank B, as criaturas sofrerão uma penalidade de 1d6 na jogada de salvamento deste jutsu. Se este jutsu for lançado no Rank S, as criaturas sofrerão uma penalidade de 1d8 na jogada de salvamento deste jutsu.",
  },
  {
    key: "respiracao-do-eco-reverberacao",
    nome: "Respiração do Eco: Reverberação",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer a Distância)", "FN (Qualquer ferramenta explosiva)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você começa a coletar e manifestar chakra até que ele tome a forma de uma nota sonora de sua escolha, pairando sobre a parte de impacto de sua arma. Essa nota pode ser vista claramente por qualquer outra criatura que possa manipular chakra. Você dispara dois tiros poderosos, criando uma explosão de som capaz de desorientar seus inimigos no impacto. Realize dois ataques de Taijutsu à distância, causando o [dano da sua arma]. Em cada acerto, o alvo e todas as criaturas em um raio de 1,5 metros dele devem fazer um teste de resistência de Sabedoria, ficando deslumbrados em caso de falha.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d4. Se este jutsu for lançado no Rank C ou superior, aumente o número de ataques em +1. Se este jutsu for lançado no Rank B ou superior, o alvo também fica atordoado em caso de falha no teste de resistência.",
  },
  {
    key: "respiracao-de-enoki-infestar",
    nome: "Respiração de Enoki: Infestar",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Pessoal",
    duracao: "Concentração, até 1 minuto",
    componentes: ["MC", "A (Qualquer a Distância)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Médico"],
    descricao: "Você começa a coletar e manifestar chakra médico até que ele envolva a porção golpeadora de sua arma. O chakra médico começa a fazer sua arma brilhar com um suave tom rosa. Durante a duração, quando você causar dano com um ataque de arma ou ataque de taijutsu usando esta arma, uma vez por turno o alvo deve fazer um teste de resistência de Constituição, reduzindo sua CA em 1 por toda a duração. Uma criatura só pode ter sua CA reduzida por este jutsu duas vezes.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o limite de redução de CA aumenta em 1.",
  },
  {
    key: "respiracao-da-chuva-cumulo",
    nome: "Respiração da Chuva: Cúmulo",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer Alcance)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Estilo Água"],
    descricao: "Você começa a coletar e manifestar chakra de Estilo Água até que ele se infunda na parte ofensiva de sua arma. O chakra de Estilo Água começa a se transformar em correntes de água, capazes de ser vistas e sentidas, enquanto você libera sua arma, que flui ao redor dela com um golpe aprimorado. Realize um único ataque de Taijutsu à distância contra uma criatura que você possa ver. Em caso de acerto, você causa o dobro do [dado de dano da sua arma] + o modificador de sua habilidade de Taijutsu em dano de frio, e o alvo deve fazer um teste de resistência de Constituição, ficando atordoado em caso de falha. A rolagem de ataque deste jutsu não pode ser feita com desvantagem ou com penalidades para acertar devido a uma condição ou Jutsus, traços ou características de criaturas hostis.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o [dado de dano da sua arma] em +1. Se este jutsu for lançado no Rank C ou superior, caso o alvo de seu ataque esteja caído ou atordoado, você ganha um bônus de +1d4 para acertar. Se este jutsu for lançado no Rank B ou superior, e o alvo do seu ataque estiver caído, enfraquecido ou atordoado, você ganha um bônus de +1d6 para acertar. Se este jutsu for lançado no Rank S, a rolagem de ataque deste jutsu também é feita com vantagem, independentemente das circunstâncias.",
  },
  {
    key: "respiracao-da-chama-ignorancia",
    nome: "Respiração da Chama: Ignorância",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Especial",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Estilo Fogo"],
    descricao: "Você começa a coletar e manifestar chakra de Estilo Fogo até que ele se infunda na parte ofensiva de sua arma. O chakra de Estilo Fogo começa a se transformar em jorros de chamas que explodem de sua arma com um brilho magnífico. Você então avança em direção ao seu alvo e realiza um golpe poderoso, tentando decapitá-lo em um único ataque. Selecione uma criatura que você possa ver e alcançar usando todo o seu deslocamento. Mova-se para um espaço adjacente à criatura alvo dentro do alcance do seu movimento. Realize um único ataque de Taijutsu corpo a corpo contra uma criatura que você possa ver, com um bônus de +1 na margem de ameaça crítica. Em caso de acerto, você causa o [dano da sua arma] + 2d6+2 de dano de fogo. Se este jutsu obtiver um acerto crítico, o alvo recebe 1 rank de queimado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e sua margem de ameaça crítica em +1. Se este jutsu for lançado no Rank B, aumente o dano causado por este jutsu em 1d6+1. Se este jutsu for lançado no Rank S, quando você obtiver um acerto crítico com este jutsu, você quadruplica o dano de fogo deste jutsu.",
  },
  {
    key: "respiracao-das-rosas-ameixa",
    nome: "Respiração das Rosas: Ameixa",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você toma quando sofre dano, excluindo de um Genjutsu",
    alcance: "Pessoal (5 Pés)",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Médico"],
    descricao: "Você começa a coletar e manifestar chakra médico até que ele se infunda na parte ofensiva de sua arma. O chakra médico faz com que sua arma brilhe com um suave tom rosado. Quando você estiver prestes a receber dano, começa a realizar uma série de golpes rotativos para desviar o máximo de dano possível. Reduza o dano que você receberia em [dano da sua arma] + 2d8. Adicionalmente, todas as criaturas hostis adjacentes a você devem fazer um teste de resistência de Destreza, recebendo dano de veneno igual à quantidade de dano reduzido como resultado deste jutsu, ou metade desse valor em caso de sucesso no teste.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano reduzido em 1d8. Se este jutsu for lançado no Rank C ou superior, aumente para 3 metros (10 pés) o alcance em que criaturas hostis podem sofrer dano deste jutsu. Se este jutsu for lançado no Rank B ou superior, aumente o dado de redução de dano para d10. Se este jutsu for lançado no Rank S, as criaturas que falharem no teste de resistência como resultado deste jutsu recebem o dobro do dano.",
  },
  {
    key: "respiracao-do-som-rugido",
    nome: "Respiração do Som: Rugido",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (esfera de 15 pés de raio)",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer Corpo a Corpo)", "FN (Qualquer ferramenta explosiva)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Sensorial"],
    descricao: "Você começa a coletar e manifestar chakra até que ele tome a forma de uma nota sonora de sua escolha, pairando sobre a parte ofensiva de sua arma. À medida que seu chakra se manifesta, todo som ao redor é abafado, e você entra em um estado profundo de concentração. Você anexa a ferramenta explosiva à sua arma e executa uma sinfonia de golpes enquanto a tag se prepara para detonar. Todas as criaturas, excluindo você, devem realizar um teste de resistência de Sabedoria, sofrendo [dano da sua arma] + 1d12 e ficando deslumbradas e cegas em caso de falha, até o início do próximo turno delas. Para cada rank de qualidade que sua ferramenta explosiva estiver acima da qualidade base, as criaturas sofrem -1d4 no teste de resistência.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d12. Se este jutsu for lançado no Rank B ou superior, as criaturas ficam cegas até o final do próximo turno delas.",
  },
  {
    key: "respiracao-dos-ceus-queda-das-nuvens",
    nome: "Respiração dos Céus: Queda das Nuvens",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer Alcance)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Estilo Vento"],
    descricao: "Você começa a coletar e manifestar chakra de liberação de vento até que ele se infunda na parte ofensiva de sua arma. O chakra de vento começa a girar em torno da arma do usuário, criando torrentes cortantes de vento. Esse vento impulsiona sua habilidade de arremessar a arma com força suficiente para cortar uma nuvem e perfurar o céu. Realize dois ataques de Taijutsu à distância contra uma criatura que você possa ver dentro do alcance. Em um acerto, você causa [dado de dano da sua arma] em dano de vento, infligindo um rank de sangramento no alvo. Você não adiciona seu modificador de habilidade às jogadas de dano deste jutsu.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o número de ataques em +1.",
  },
  {
    key: "respiracao-do-trovao-clarao",
    nome: "Respiração do Trovão: Clarão",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Especial",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Estilo Relâmpago"],
    descricao: "Você começa a coletar e manifestar chakra de liberação de relâmpago até que ele envolva a parte ofensiva de sua arma. O chakra de liberação de relâmpago começa a se acumular e faíscar fora de sua arma com choques violentos. Você se prepara para um único golpe poderoso. Selecione uma criatura que você pode ver e que você consiga alcançar com seu movimento completo. Mova-se para um espaço adjacente à criatura alvo dentro do seu alcance de movimento. Realize um ataque de Taijutsu corpo a corpo contra a criatura alvo. Em caso de acerto, você causa o [dano da sua arma] + 2d10 de dano de relâmpago e, se o alvo estiver se beneficiando de pontos de vida temporários, você causa dano tanto nos pontos de vida quanto nos pontos de vida temporários da criatura simultaneamente. Você não adiciona o modificador de habilidade ao dano causado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d10. Se este jutsu for lançado no Rank C, você pode selecionar uma segunda criatura dentro de 9 metros do alvo original e se mover para um espaço adjacente a ela, realizando um segundo ataque. Se este jutsu for lançado no Rank B, selecione uma terceira criatura dentro de 9 metros do segundo alvo e se mova para um espaço adjacente a ela, realizando um terceiro ataque. Se este jutsu for lançado no Rank A ou superior, selecione uma quarta criatura dentro de 9 metros do terceiro alvo e se mova para um espaço adjacente a ela, realizando um quarto ataque.",
  },
  {
    key: "respiracao-das-faiscas-relampago",
    nome: "Respiração das Faíscas: Relâmpago",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer Alcance)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Estilo Relâmpago"],
    descricao: "Você começa a coletar e manifestar chakra de liberação de relâmpago até que ele envolva a parte ofensiva de sua arma. O chakra de liberação de relâmpago começa a se acumular e a faíscar fora de sua arma com choques violentos. Você se prepara para vários disparos poderosos. Role 1d4, registrando o resultado. Selecione um número de criaturas que você pode ver dentro do alcance igual ao resultado, enquanto dispara uma salva de tiros carregados de relâmpago para cada uma delas. Realize um ataque de Taijutsu à distância contra cada criatura alvo, causando o dobro do [dano da sua arma] + 1d8 de dano de relâmpago. Você não adiciona o modificador de habilidade ao dano causado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo desse jutsu em 3 e o dado inicial usado para determinar o número de criaturas-alvo em 1 passo (D4>D6>D8>D10>D12). Se este jutsu for lançado no Rank C ou superior, aumente o dano em 1d8. Se este jutsu for lançado no Rank B ou superior, aumente o dado de dano da sua arma em 1. Se este jutsu for lançado no Rank A ou superior, aumente o dano em 1d8. Se este jutsu for lançado no Rank S, aumente o dado de dano da sua arma em 1.",
  },
  {
    key: "fogo-rapido",
    nome: "Fogo Rápido",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (cone de 13,5 metros)",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma de Longo Alcance)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você prepara vários ataques antes de dispará-los à sua frente. Todas as criaturas em um cone de 9 metros originado de você devem fazer um teste de resistência de Destreza. Em caso de falha, você causa o [dano da sua arma] + 1d6. Em caso de sucesso, causa metade do dano. Se você precisar rolar o dado de munição de sua arma, role duas vezes e considere o menor resultado. Se este jutsu for conjurado como uma Cadeia 2, ele causa 1d6 de dano adicional. Se este jutsu for conjurado como uma Cadeia 3, o dano adicional se torna 2d8.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d6.",
  },
  {
    key: "respiracao-da-agua-superficie",
    nome: "Respiração da Água: Superfície",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Estilo Água"],
    descricao: "Você começa a coletar e manifestar chakra de liberação de água até que ele envolva a parte ofensiva de sua arma. O chakra de liberação de água começa a se transformar em correntes de água, capazes de ser vistas e sentidas, enquanto você se move para desferir um golpe concentrado e poderoso. Realize um ataque de Taijutsu corpo a corpo contra uma criatura que você possa ver. Em caso de acerto, você causa o [dano da sua arma] + 1d10 de dano de frio e o alvo deve fazer um teste de resistência de Força, ficando atordoado em caso de falha. O rolamento de ataque deste jutsu não pode ser feito com desvantagem ou com penalidades para acertar devido a condições ou jutsus, traços ou habilidades de criaturas hostis.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d10. Se este jutsu for lançado no Rank C ou superior, se o alvo do seu ataque estiver caído ou atordoado, você ganha um bônus de +1d4 para acertar. Se este jutsu for lançado no Rank B ou superior, e o alvo do seu ataque estiver caído, enfraquecido ou atordoado, você ganha um bônus de 1d6 para acertar. Se este jutsu for lançado no Rank S, o rolamento de ataque deste jutsu também será feito com vantagem, independentemente das circunstâncias.",
  },
  {
    key: "puxao-em-cadeia",
    nome: "Puxão em Cadeia",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["A (Corpo a Corpo, Alcance, Agarrar)", "M"],
    custoChakra: 3,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você arremessa sua arma, enrolando-a em torno de um alvo e puxando-o para si. O alvo deve realizar um teste de resistência de Força. Em caso de falha, ele é movido 3 metros em direção a você em linha reta, não pode fazer selos de mão até o início do próximo turno dele e também fica restrito por você. No final do turno da criatura, ela pode fazer um teste de resistência de Força para escapar da restrição. Se este jutsu for conjurado como uma Cadeia 2, você pode escolher um alvo adicional dentro do alcance. Se este jutsu for conjurado como uma Cadeia 3, os alvos têm desvantagem no teste de resistência inicial.",
  },
  {
    key: "respiracao-do-vento-cortador",
    nome: "Respiração do Vento: Cortador",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["MC", "A (Qualquer Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Estilo Vento"],
    descricao: "Você começa a coletar e manifestar chakra de liberação de vento até que ele envolva a parte ofensiva de sua arma. O chakra de liberação de vento começa a girar ao redor da arma do usuário, criando poderosas rajadas de vento. Você usa esse campo aprimorado de vento para se impulsionar em direção ao seu inimigo. Realize três ataques de Taijutsu corpo a corpo contra uma criatura que você possa ver dentro do alcance. Em caso de acerto, você causa o [dano da sua arma], em dano de vento, mas você não adiciona seu modificador de habilidade ao [dano da sua arma].",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o número de ataques em +1.",
  },
  {
    key: "municao-tocada-por-chakra",
    nome: "Munição Tocada por Chakra",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Toque",
    duracao: "Concentração, até 1 minuto",
    componentes: ["A (Qualquer Munição)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você infunde todo o seu conjunto de munições com chakra, aprimorando tanto sua letalidade quanto sua eficiência. Durante a duração, sempre que você causar dano com a arma afetada pela propriedade de munição, adicione 1d4 de dano adicional do tipo da arma, até duas vezes por turno. Além disso, quando você rolar o dado de munição, role um dado adicional e considere o maior resultado. Por fim, se você conjurar um jutsu que consuma um dado inteiro de munição, pode optar por encerrar este jutsu em vez de gastar o dado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e ambos os danos em 1d6.",
  },
  {
    key: "lancamento-explosivo",
    nome: "Lançamento Explosivo",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "27 metros",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma Arremessada)", "M", "MC"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você imbuí sua arma com chakra, transformando-a em um perigo, mesmo após o impacto. Faça um ataque de Taijutsu à distância. Em caso de acerto, você causa o [dano da sua arma] + 1d6. Independentemente do resultado, a arma se despedaça, e seus fragmentos criam um campo minado em um raio de 3 metros ao redor do alvo, que dura até o início do seu próximo turno. A primeira vez que uma criatura se mover dentro desse raio, ela sofrerá 2d4 de dano cortante.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3. Rank C: Aumente o dano para 2d4. Rank A ou superior: Aumente o dano para 3d4.",
  },
  {
    key: "carpete-de-aco",
    nome: "Carpete de Aço",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "13,5 metros (Cubo de 6 metros)",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Munição)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você prepara um conjunto de suas armas e as espalha pelo chão em uma área de até 13,5 metros de distância em um cubo de 6 metros. A área se torna terreno difícil, e criaturas que se movem dentro dela sofrem 1d4 de dano perfurante para cada 1,5 metro que se movimentarem na área. Espaços que já foram atravessados deixam de ser terreno difícil e não causam mais dano ao serem percorridos novamente.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o raio do jutsu em 1,5 metro.",
  },
  {
    key: "golpe-debilitante",
    nome: "Golpe Debilitante",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantâneo",
    componentes: ["A (Qualquer)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você concentra o ataque de sua arma para debilitar seu inimigo, tornando-o muito menos eficaz do que atualmente. Faça um ataque de Taijutsu corpo a corpo ou à distância, dependendo da arma utilizada para este jutsu, causando o [dano da sua arma]. Em caso de acerto, o alvo deve fazer um teste de resistência de Força. Em caso de falha, ele fica atordoado, enfraquecido e é derrubado no chão (prone). Além disso, se você acertar um golpe crítico com este jutsu, o alvo faz o teste de resistência com desvantagem.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o [dado de dano da arma] em 1.",
  },
  {
    key: "performance-da-danca-postura-neutra",
    nome: "Performance da Dança: Postura Neutra",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Auto",
    duracao: "1 Rodada",
    componentes: ["A (Qualquer Corpo a Corpo)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: 'Você empunha sua arma, adotando uma postura leve, semelhante à de um dançarino. Durante a duração deste jutsu, qualquer Bukijutsu que você conjurar com "Performance de Dança" em seu nome terá um aumento no alcance crítico. Aumente o alcance crítico das rolagens de ataque de Taijutsu dos jutsus mencionados acima em +1. Se o jutsu exigir um teste de resistência, uma criatura que rolar 1 ou 2 no dado de 20 para a resistência sofrerá dano dobrado se falhar.',
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3. Se este jutsu for lançado no Rank C, aumente o alcance crítico em +1. Se este jutsu for lançado no Rank A, aumente o alcance crítico em +2, e se a criatura rolar 5 ou menos no dado de 20 para o teste de resistência, ela será considerada vulnerável.",
  },
  {
    key: "corte-curvado",
    nome: "Corte Curvado",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma de Corte à Distância)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você realiza um único arremesso que curva e corta com precisão assustadora. Faça um ataque de Taijutsu à distância contra uma criatura que você possa ver dentro do alcance, causando o [dano da sua arma] + 2d8. Em caso de acerto, a criatura deve fazer um teste de resistência de Constituição ou ficará cega até o final do próximo turno dela. Se falhar por 5 ou mais, ela ficará cega até o final do seu próximo turno.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d8.",
  },
  {
    key: "vibracoes-cortantes",
    nome: "Vibrações Cortantes",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Concentração, 1 minuto",
    componentes: ["A (Arma Corpo a Corpo Cortante)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você canaliza seu chakra em sua arma, fazendo-a vibrar em velocidades supersônicas, aprimorando suas capacidades de corte. Durante a duração, sempre que você causar dano cortante com sua arma a um alvo usando armadura, você reduz o bônus de armadura da criatura alvo em 1. Isso só pode ocorrer uma vez por rodada. Se isso reduzir o bônus de armadura do alvo a 0, você causa um dado extra de [dano da sua arma].",
  },
  {
    key: "danca-do-tolo",
    nome: "Dança do Tolo",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Corrente)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você gira sua arma em um amplo arco, atingindo todas as criaturas dentro desse arco. Faça um ataque de Taijutsu corpo a corpo. Todas as criaturas de sua escolha, dentro do alcance da sua arma, originado de você, tornam-se alvo deste ataque, comparando o resultado do seu ataque à CA delas como se estivesse atacando cada uma individualmente. Em um acerto, você causa o [dano da sua arma] + 2d4 e cada criatura deve fazer um teste de resistência de Destreza. Em caso de falha, ela fica derrubada.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 2d4.",
  },
  {
    key: "tiro-debilitante",
    nome: "Tiro Debilitante",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "1 Rodada",
    componentes: ["A (Qualquer Arma Arremessada)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você começa a arremessar suas armas rapidamente, mirando nos pontos de pressão de seus inimigos para perfurá-los. Realize um Ataque Taijutsu à distância causando seu [dano da arma] + 4d4. O alvo também deve fazer um teste de resistência de Constituição, ganhando 1 nível de enfraquecido em caso de falha enquanto suas senbons se alojam em suas articulações, ou metade do dano em caso de sucesso. Uma criatura enfraquecida por este jutsu pode, como uma ação, fazer um teste de Sabedoria (Sobrevivência) contra sua CD de Taijutsu para remover as senbons alojadas, caso tenha sucesso.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o número de criaturas que você pode atingir em +1.",
  },
  {
    key: "chicote-do-tolo",
    nome: "Chicote do Tolo",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "4,5 metros",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Corrente)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você estica sua arma com força suficiente para rachar o chão com o impacto. Criaturas em um cubo de 4,5 metros originado de você devem fazer um teste de resistência de Destreza, sendo chicoteadas repetidamente por sua arma. Em caso de falha, a criatura recebe seu [dano da arma] + 2d4 e ganha a condição de sangramento. Em caso de sucesso, ela recebe apenas metade do dano e sem efeitos adicionais.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d4.",
  },
  {
    key: "zona-de-perigo",
    nome: "Zona de Perigo",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "O dobro do alcance da sua arma",
    duracao: "Instantânea",
    componentes: ["A (Corte Corpo-a-Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você gira rapidamente sua arma ao seu redor, usando chakra para estender seu alcance. Todas as criaturas dentro do alcance devem fazer um teste de resistência de Destreza. Em caso de falha, elas recebem 3d6 de dano Cortante e ganham um nível de sangramento.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 2d6. Se este jutsu for lançado em Rank A, as criaturas-alvo recebem metade do dano em caso de sucesso.",
  },
  {
    key: "danca-demoniaca",
    nome: "Dança Demoníaca",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Perfurante Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você gira com sua arma, realizando um ataque parecido com uma dança que confunde os inimigos. Realize um Ataque Taijutsu Corpo a Corpo contra todas as criaturas no alcance. Em um acerto, você causa seu [dano da arma], e esse dano aumenta em 1d4 para cada criatura atingida.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o alcance deste jutsu em 1,5 metros. Se este jutsu for lançado em Rank A, o alcance se torna sua Velocidade de movimento atual.",
  },
  {
    key: "duas-dificuldades",
    nome: "Duas Dificuldades",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma de Longo Alcance Corpo a Corpo)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você executa uma rápida rajada de 2 disparos que deixam o inimigo cambaleando. Realize dois Ataques Taijutsu à distância usando sua arma, causando seu [dano da arma] + 1d6. Se um alvo for atingido ao menos uma vez, ele deve também realizar um teste de resistência de Força, reduzindo sua velocidade em 3 metros para cada ataque bem-sucedido, até o final de seu próximo turno.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o alvo sofre uma penalidade de -1 em seu teste de resistência.",
  },
  {
    key: "jogo-do-diabo",
    nome: "Jogo do Diabo",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "1 Rodada",
    componentes: ["A (Qualquer)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você faz uma aposta digna de um diabo. Ao custo de aumentar a letalidade e precisão da sua arma, você joga a cautela ao vento. Até o início do seu próximo turno, o primeiro ataque de arma ou Taijutsu feito como resultado de um Bukijutsu que você lançar terá vantagem, e você aumenta o dado de dano da sua [arma] em 1. Mas, em troca dessa aposta, o primeiro ataque feito por qualquer criatura contra você será feito com vantagem.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3. Se este jutsu for lançado em Rank B, aumente o dado de dano da sua [arma] em 3. Se este jutsu for lançado em Rank S, aumente o dado de dano da sua [arma] em 5.",
  },
  {
    key: "tiro-duplo",
    nome: "Tiro Duplo",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "1 Rodada",
    componentes: ["A (Qualquer Arma de Longo Alcance)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você prepara dois ataques separados para serem executados em um único movimento. Antes do final do seu turno atual, a próxima vez que você fizer um ataque de arma de longo alcance, você fará um ataque adicional como parte da mesma ação, o qual deve atingir outra criatura. Além disso, este ataque adicional se beneficia de quaisquer efeitos que normalmente afetariam apenas o primeiro ou um ataque de arma.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3. Se este jutsu for lançado em Rank B, aumente o número de ataques adicionais para dois. Se este jutsu for lançado em Rank S, aumente o número de ataques adicionais para três.",
  },
  {
    key: "corrida-do-dragao-voador",
    nome: "Corrida do Dragão Voador",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "18 metros",
    duracao: "Instantânea",
    componentes: ["A (Qualquer)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você lança sua arma em direção a uma criatura aliada que você pode ver no alcance, ordenando que ela ataque com ela em seu lugar. Selecione uma criatura disposta que você possa ver no alcance e você joga sua arma escolhida para ela. Até o final do turno atual, a arma lançada mantém todos os bônus e efeitos como se você estivesse empunhando-a. A criatura alvo pode gastar sua reação para realizar um ataque de Taijutsu corpo a corpo, mirando em uma criatura no alcance, causando o [dano da arma] + seu modificador de habilidade. Como parte da mesma reação, a criatura aliada pode escolher devolver sua arma para você.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o número de ataques realizados pela criatura alvo em +1.",
  },
  {
    key: "agulhas-debilitantes",
    nome: "Agulhas Debilitantes",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "1 Rodada",
    componentes: ["A (Senbon)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você começa a lançar agulhas Senbon rapidamente, mirando nos pontos de pressão de seus inimigos para perfurá-los. Faça um ataque taijutsu à distância causando o dano da sua arma + 4d4. O alvo também deve fazer um teste de resistência de Constituição, ganhando 1 rank de enfraquecido em caso de falha enquanto os Senbons se alojam em suas articulações, ou metade desse dano em caso de sucesso no teste de resistência. Uma criatura enfraquecida por este jutsu permanece enfraquecida até remover os Senbons alojados nas articulações. Como uma ação, a criatura pode fazer um teste de Destreza (Sobrevivência) contra seu CD de salvaguarda de Taijutsu para remover os Senbons alojados com sucesso.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de Rank D, aumente o custo em 3 e o número de ataques em +1.",
  },
  {
    key: "soco-de-longo-alcance-do-dragao",
    nome: "Soco de Longo Alcance do Dragão",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma de Bludgeoning à Distância)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você executa dois disparos rápidos que desorientam e debilitam o inimigo. Realize dois Ataques Taijutsu à distância contra uma criatura que você possa ver dentro do alcance, causando seu [dano da arma]. Em cada acerto, o alvo deve também fazer um teste de resistência de Constituição, ficando atordoado em caso de falha.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o alvo sofre uma penalidade de -1 em seu teste de resistência.",
  },
  {
    key: "pouso-da-libelula",
    nome: "Pouso da Libélula",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Perfurante Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você salta e depois desce cravando sua arma em uma série incontável de estocadas. Realize 3 Ataques Taijutsu Corpo a Corpo contra uma criatura alvo no alcance. Em um acerto, você causa seu [dano da arma]. Se você acertar a criatura ao menos 3 vezes, ela ficará derrubada enquanto você aterrissa sobre ela.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o número de ataques em 1.",
  },
  {
    key: "empurrao-matador-de-dragoes",
    nome: "Empurrão Matador de Dragões",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "4,5 metros",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Lança)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você carrega um ataque de empurrão antes de desferir um golpe mortal no momento certo para atingir seu inimigo. Faça um teste de Artes Marciais contra a CA da criatura alvo no alcance. Se você rolar um valor maior, este jutsu ganha vantagem no teste de ataque. Movimente-se até a criatura alvo e realize um Ataque Taijutsu Corpo a Corpo. Esse movimento não pode provocar um ataque de oportunidade. Em um acerto, você causa seu [dano da arma] e a criatura deve fazer um teste de resistência de Constituição. Se falhar, ela não poderá reagir até o final do turno atual. Se este jutsu for lançado como uma Cadeia 2, você ganha vantagem no seu teste de Artes Marciais. Se este jutsu for lançado como uma Cadeia 3, você causa o dobro do dano da sua arma em um acerto.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d8.",
  },
  {
    key: "lamina-eterna",
    nome: "Lâmina Eterna",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "1 minuto",
    componentes: ["A (Qualquer)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você afia sua arma com uma lâmina de chakra, protegendo-a contra qualquer dano. Sua arma não sofrerá penalidades de qualquer traço, característica ou jutsu de igual rank ou inferior que causaria destruição ou dano à arma, ou que reduziria seus rolos de ataque.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3. A partir de Rank C, a duração se torna 10 minutos. A partir de Rank B, a duração se torna 1 hora. A partir de Rank A, a duração se torna 8 horas. A partir de Rank S, a duração se torna 24 horas.",
  },
  {
    key: "empurrao-echo",
    nome: "Empurrão Echo",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Concentração, 1 Minuto",
    componentes: ["A (Perfurante Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você canaliza chakra para o seu antebraço, permitindo que você desferir dois golpes em um único movimento. Na primeira vez em que você acertar uma criatura com um ataque de arma em cada um dos seus turnos, você pode causar dano a uma segunda criatura que esteja dentro de 1,5 metros tanto de você quanto do alvo original.",
  },
  {
    key: "bloqueio-aprimorado",
    nome: "Bloqueio Aprimorado",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Concentração, até 1 minuto",
    componentes: ["A (Qualquer Lança)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você se prepara com sua arma e adota uma postura mais defensiva. Você não perde a concentração neste jutsu devido a dano. Durante a duração, enquanto você estiver empunhando uma arma do tipo Lança, você ganha um bônus adicional de +1 na sua CA. Além disso, quaisquer bônus para a CA que você tenha como resultado de propriedades de bloqueio ou selos de armas, você adiciona esse bônus ao primeiro teste de resistência de Força ou Destreza que você faria a cada rodada. Além disso, durante a duração deste jutsu, você pode usar sua reação quando for receber dano para reduzir o dano em duas vezes o [dano da arma]. Se você reduzir o dano a 0, você ganha uma reação adicional até o início do seu próximo turno, que pode ser usada apenas para lançar este jutsu novamente.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano que você reduz em 1 [dano da arma].",
  },
  {
    key: "exterminar",
    nome: "Exterminar",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Corte Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você ataca duas vezes em forma de X, tentando prejudicar a capacidade de seu oponente de contra-atacar. Faça dois ataques de Taijutsu corpo a corpo. Em um acerto, você causa o [dano da arma] +1d12. Se ambos os ataques forem bem-sucedidos, seu oponente deve fazer um teste de resistência de Constituição. Em caso de falha, ele sofre uma penalidade de -2 em todos os rolos de ataque até o final do próximo turno.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3, o dano em 1d12, e a penalidade no rolo de ataque em 1.",
  },
  {
    key: "voadora-corte-em-cruz",
    nome: "Voadora: Corte em Cruz",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma Corpo a Corpo de Dupla Empunhadura)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Como parte da ativação deste jutsu, você deve estar com uma arma em ambas as mãos que atendam aos requisitos de componentes deste bukijutsu. Você faz dois cortes em um único golpe, balançando ambas as suas armas para dentro. Faça dois ataques de Taijutsu contra até dois inimigos a até 1,5 metros de você, causando [dano da arma] +1d4, e o alvo deve fazer um teste de resistência de Força para evitar ser desarmado da arma ou item que está segurando.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d4.",
  },
  {
    // NOTE: fonte lia "FANGUE LONGO" — grafia não padrão, mantida como no OCR (possivelmente "Presa Longa" no original).
    key: "fangue-longo",
    nome: "Fangue Longo",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "O dobro do alcance da sua arma",
    duracao: "Instantânea",
    componentes: ["A (Perfurante à Distância)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Sua arma é apenas uma extensão de si mesmo, é sua presa para defender o que precisa ser defendido. Você preenche sua arma com chakra para aumentar seu alcance e poder de dano. Faça um ataque de Taijutsu à distância contra uma criatura no alcance. Em um acerto, você causa o [dano da arma] +2d10 e a criatura alvo deve fazer um teste de resistência de Força ou ser empurrada 4,5 metros para trás. Se bater em uma estrutura ou construção, ela fica presa a ela, sendo imobilizada até que use uma ação para se libertar.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d8. Se for lançado no rank Rank B, a criatura é empurrada 4,5 metros adicionais. Se for lançado no rank Rank S, a criatura é empurrada 4,5 metros adicionais.",
  },
  {
    key: "raios-cintilantes",
    nome: "Raios Cintilantes",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (18 metros)",
    duracao: "Instantânea",
    componentes: ["A (Corte à Distância)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você se prepara para lançar suas armas em altas velocidades, criando trilhas de luz no ar. Faça um ataque de Taijutsu à distância contra um número de criaturas no alcance igual ao seu modificador de habilidade de Taijutsu. Em um acerto, você causa o [dano da arma] +2d4 de dano cortante e a criatura alvo deve fazer um teste de resistência de Destreza ou ganhar 2 classificações de sangramento.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d4.",
  },
  {
    key: "voadora-piao-giratorio",
    nome: "Voadora: Pião Giratório",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma Corpo a Corpo de Dupla Empunhadura)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Como parte da ativação deste jutsu, você deve estar com uma arma em ambas as mãos que atendam aos requisitos de componentes deste bukijutsu. Você gira como um pião, atingindo todas as criaturas em sua proximidade imediata. Todas as criaturas dentro do alcance de suas armas devem fazer um teste de resistência de Destreza. Em um fracasso, elas sofrem o [dano da arma] +2d6 ou metade do dano em um sucesso. Dependendo do tipo de dano das armas escolhidas, as criaturas que falharem no teste de resistência sofrem efeitos adicionais. Contusão: As criaturas afetadas ficam derrubadas. Perfurante: As criaturas afetadas ganham 1 classificação de enfraquecido até o final do próximo turno. Corte: As criaturas afetadas ganham 1 classificação de sangramento.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d6.",
  },
];
