import type { JutsuDefinition } from "@/lib/jutsu/types";

export const bukijutsuJutsuParte2: JutsuDefinition[] = [
  {
    key: "cortante-de-grama",
    nome: "Cortante de Grama",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Corte Corpo a Corpo)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você balança sua arma para baixo, na tentativa de imobilizar o inimigo. Faça um ataque de Taijutsu corpo a corpo visando uma criatura no alcance. Em um acerto, você causa [dano da arma] +2d4 e reduz a velocidade do oponente pela metade até o final do seu próximo turno, ao cortar seus tornozelos. Se este jutsu for lançado como um Cadeia 2, ele causa 3d4 de dano adicionais. Se for lançado como um Cadeia 3, o dado de dano deste jutsu se torna d8.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d8.",
  },
  {
    key: "grande-onda-de-choque-do-dragao",
    nome: "Grande Onda de Choque do Dragão",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Lâmina)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você rapidamente levanta e corta para baixo com sua lâmina com tanta força que cria uma onda de choque. Faça um ataque de Taijutsu corpo a corpo contra uma criatura alvo no alcance. Em um acerto, você causa [dano da arma] +1d8. Todas as criaturas dentro do alcance, além do alvo, devem fazer um teste de resistência de Força ou serem empurradas para trás em 4,5 metros.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dado de dano em +1.",
  },
  {
    // NOTE: a atribuição das duas colunas da OCR indica que este jutsu termina sem um parágrafo "Em Ranks Superiores" próprio na página 387; o texto de escala encontrado no topo da página 388 (bônus na faixa crítica +2/+3) foi atribuído a este jutsu por continuidade estrutural de coluna (nenhum título o precede), mas não corresponde a nenhum mecanismo de crítico mencionado na descrição reconstruída — pode pertencer, na verdade, a "Armas Ocultas" (que menciona "+1 na faixa crítica" na própria descrição). Mantido aqui por ser a atribuição estruturalmente mais provável.
    key: "alvoroco-celestial",
    nome: "Alvoroço Celestial",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Potência)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você balança para cima com uma força ascendente para os céus antes de balançar para baixo, trazendo seu oponente para o chão. Faça um ataque de Taijutsu corpo a corpo contra uma criatura no alcance. Em um acerto, você causa [dano da arma] e a criatura deve fazer um teste de resistência de Força. Em um fracasso, você realiza um segundo ataque de Taijutsu corpo a corpo que causa [dano da arma] +1d12 em um acerto. Em um sucesso, você faz o ataque, mas com desvantagem, e não pode ganhar vantagem neste ataque por nenhum meio.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3. Se for lançado no rank B, aumente o bônus na faixa crítica para +2. Se for lançado no rank S, aumente o bônus na faixa crítica para +3.",
  },
  {
    key: "voadora-linha-reta",
    nome: "Voadora: Linha Reta",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (linha de 9 metros)",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma Corpo a Corpo de Dupla Empunhadura)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Como parte da ativação deste jutsu, você deve estar com uma arma em ambas as mãos que atendam aos requisitos de componentes deste bukijutsu. Você avança em linha reta, até 9 metros, movendo-se através do espaço de qualquer criatura hostil que encontrar, terminando seu movimento em um espaço até 9 metros de distância, em linha reta. Faça dois ataques de Taijutsu corpo a corpo. Todas as criaturas, de sua escolha, cujo espaço você passou devido a este jutsu, contam como alvos para esses dois ataques de Taijutsu, comparando seus resultados com a CA de cada criatura. Em um acerto, você causa [dano da arma] +1d4 e as criaturas atingidas devem fazer um teste de resistência de Força. Em um fracasso, elas ficam derrubadas; em um sucesso, não há outros efeitos.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d4.",
  },
  {
    key: "tiro-sombrio-oculto",
    nome: "Tiro Sombrio Oculto",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer 2 Arremessáveis)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você arremessa sua arma, mas escondido em sua sombra está o verdadeiro ataque. Faça um ataque de Taijutsu à distância contra uma criatura no alcance. A criatura alvo deve fazer uma verificação de Percepção contra um DC de 10 + seu Prestidigitação. Em um fracasso, este ataque ganha vantagem e a criatura não pode reagir. Em um acerto, você causa [dano da arma]. Se este jutsu for lançado como um Cadeia 2, ele causa 2d6 de dano adicionais. Se for lançado como um Cadeia 3, o dano adicional se torna 2d8.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3. Se for lançado no rank B, aumente o número de ataques em 1. No rank S, este jutsu ganha um ataque adicional.",
  },
  {
    key: "furos-da-desolacao",
    nome: "Furos da Desolação",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Perfuração Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "(Este jutsu não pode causar acertos críticos) Você estoca sua arma em diferentes ângulos enquanto busca perfurar seu oponente com buracos. Faça três ataques de Taijutsu corpo a corpo, causando o [dano da arma] em cada acerto. Se pelo menos dois ataques forem bem-sucedidos, a criatura alvo ganha uma classificação de sangramento. Se este jutsu for lançado como um Cadeia 2, aumente a classificação de sangramento em 1. Se for lançado como um Cadeia 3, faça um ataque adicional.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e a classificação de sangramento em 1. Se este jutsu for lançado no rank A ou superior, ele poderá voltar a causar um acerto crítico.",
  },
  {
    // NOTE: nenhum parágrafo "Em Ranks Superiores" foi encontrado para este jutsu no texto-fonte (a página termina e a próxima entrada começa sem ele).
    key: "armas-ocultas",
    nome: "Armas Ocultas",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Oculto)", "M"],
    custoChakra: 3,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você é capaz de sacar e guardar sua arma rapidamente de forma que seja quase impossível rastrear ou reagir. Até o final do próximo turno, a primeira vez que você fizer um ataque com arma ou Taijutsu usando uma arma que atenda aos requisitos de componente deste jutsu, você faz o ataque com vantagem, e com um bônus de +1 na faixa crítica do ataque. Depois de causar dano a uma criatura com uma arma que esteja ganhando o benefício deste jutsu, como parte da mesma ação utilizada para atacar, você pode fazer um teste de Destreza (Prestidigitação) contra a Percepção Passiva do alvo. Em um sucesso, você consegue esconder a arma antes que eles percebam com o que foram atacados. Se você falhar no teste, as armas que você usa não podem obter o benefício deste jutsu enquanto estiverem mirando naquela criatura até que você complete um descanso de qualquer tipo.",
  },
  {
    key: "iaijutsu-cancao-do-leao",
    nome: "Iaijutsu: Canção do Leão",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Corte Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Conflito"],
    descricao: 'Colocando uma espada embainhada verticalmente e ouvindo a "respiração" do seu oponente, você rapidamente desembainha, ataca ao passar pelo alvo e então reembainha sua espada. Faça um ataque de Taijutsu corpo a corpo contra uma criatura no alcance. Em um acerto, você causa seu [dano da arma] +1d10. Se você superar a Classe de Armadura (CA) do seu oponente por 10, ele não poderá reagir a este jutsu.',
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d10. Se este jutsu for lançado no rank B, você só precisa superar a CA por 5 para tornar o ataque irrespondível. Se for lançado no rank S, você ganha vantagem no rolo. Se já tiver vantagem, a conjuração deste jutsu não poderá ser reagida.",
  },
  {
    key: "deflexao-da-teia-de-ferro",
    nome: "Deflexão da Teia de Ferro",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você toma ao sofrer dano",
    alcance: "Próprio",
    duracao: "1 Rodada",
    componentes: ["A (Qualquer Mola)"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você rapidamente se envolve na corrente ou fio da sua arma para suavizar o golpe de um ataque antes que ele realmente o atinja. Role o [dano da arma] duas vezes, depois adicione seu modificador de habilidade. Reduza o dano que ativou este jutsu pelo resultado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e role o [dano da arma] duas vezes a mais.",
  },
  {
    key: "estocada-impaladora",
    nome: "Estocada Impaladora",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Perfuração Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você enfia sua arma no inimigo e a mantém lá. Faça um ataque de Taijutsu corpo a corpo. Em um acerto, você causa o [dano da arma]. Você pode escolher manter a arma lá. Ao fazer isso, você não poderá atacar com a arma enquanto ela estiver impalada, no entanto, a criatura alvo se torna agarrada pela sua arma. Enquanto ela estiver agarrada, você pode usar sua ação bônus para torcer a arma, causando o [dano da arma]. Você também pode adicionar o [dano da arma] a todas as jogadas para manter o agarro. Uma criatura pode escolher, como ação, se soltar da arma de forma forçada, escapando automaticamente do agarro, mas ganhando 2 classificações de sangramento.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dado de dano em 1. Se este jutsu for lançado no rank B, você terá vantagem nas verificações para manter o agarro. Se for lançado no rank S, a criatura ganha duas classificações de Laceração ao terminar o agarro de forma forçada.",
  },
  {
    key: "assalto-de-kunai",
    nome: "Assalto de Kunai",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (cone de 30 pés)",
    duracao: "Instantâneo",
    componentes: ["A (Kunai, Shuriken ou Senbon)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você gasta um dado completo de munição para sobrecarregar seu inimigo com uma parede de shurikens, kunais ou senbons. Todas as criaturas em um cone de 30 pés que se origina de você devem fazer um teste de resistência de Destreza. Em caso de falha, elas sofrem Xd4 de dano do tipo de arma escolhido, onde X é igual ao tamanho do dado gasto. (D4=4, D6=6, D8=8, D10=10, etc.) Se uma criatura afetada tentar conjurar um jutsu que requer selos manuais (SM) antes do final de seu próximo turno, ela ganha 1 rank de sangramento.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e aumente o dado de dano em 1 passo. (D4>D6>D8>D10>D12)",
  },
  {
    key: "impulso-linear",
    nome: "Impulso Linear",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Dobre sua velocidade de movimento restante",
    duracao: "Instantânea",
    componentes: ["A (Perfuração Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você adota uma posição ampla com sua arma antes de correr para entregar uma estocada única com grande velocidade, com a intenção de empurrar o inimigo para trás. Faça um ataque com a arma contra uma criatura alvo no alcance. Você ganha +1 no seu rolo de ataque para cada 9 metros que você se moveu, até um máximo de +5. Em um acerto, você causa o [dano da arma] e +1d10 para cada 9 metros que você se moveu para atingi-la, até um máximo de 3d10. Se você causar 20 pontos de dano ou mais com este jutsu, a criatura alvo também ganha 1 classificação de Sangramento e Lentidão até o final de seu próximo turno.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e sua velocidade de movimento em 9 metros.",
  },
  {
    key: "beijo-da-lua",
    nome: "Beijo da Lua",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma de Longo Alcance)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você envia seu ataque em um arco alto que desaparece dos olhos do seu oponente e cai como se viesse da própria lua. Faça um ataque de Taijutsu de longo alcance contra uma criatura no alcance. Ela deve fazer uma salvaguarda de Sabedoria igual à sua DC de Salvamento de Taijutsu. Em uma falha, este ataque ganha vantagem, pois a criatura perde de vista o ataque enquanto ele sobe e cai de volta. Em um sucesso, ele ganha desvantagem, pois a criatura mantém o controle do ataque. Em um acerto, você causa o [dano da arma] +2d6.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o número de criaturas que você pode atingir em 1.",
  },
  {
    key: "quebra-de-joelho",
    nome: "Quebra de Joelho",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Impacto Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Uma série de golpes baixos no corpo inferior do oponente com a intenção de prejudicar suas pernas. Faça 2 ataques de Taijutsu corpo a corpo contra uma criatura alvo no alcance. Em um acerto, você causa o [dano da arma]. Se acertar a criatura duas vezes com este jutsu, ela será derrubada. Uma criatura derrubada por este jutsu deve gastar todo o seu movimento para se levantar.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o alcance deste jutsu em 1,5 metros. Se este jutsu for lançado no rank B, aumente o número de ataques em 1. Se este jutsu for lançado no rank S, aumente o número de ataques em 1.",
  },
  {
    key: "ferramentas-manipuladas-chute-de-lamina",
    nome: "Ferramentas Manipuladas: Chute de Lâmina",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "13,5 metros",
    duracao: "Instantânea",
    componentes: ["A (Pergaminho de Arma)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você invoca uma série de espadas, facas e lanças que você chuta e lança em direção a uma criatura para perfurá-la. Role 1d4 e registre o resultado. Faça um ataque de Taijutsu à distância causando Xd4 de dano perfurante e infligindo 2 classificações de sangramento em um acerto. (X = o resultado do dado).",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dado rolado em 1 nível (1d4>1d6>1d8>1d10>1d12).",
  },
  {
    key: "barragem-de-kunai",
    nome: "Barragem de Kunai",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (esfera de raio de 15 pés)",
    duracao: "Instantâneo",
    componentes: ["A (Kunai, Shuriken)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você salta no ar e gira enquanto lança suas armas para atingir todos os alvos na área. Escolha até 10 criaturas que você possa ver dentro do alcance. Role sua pilha de munição duas vezes, escolhendo o resultado mais alto. Todas as criaturas selecionadas devem fazer um teste de resistência de Destreza. Em caso de falha, as criaturas selecionadas sofrem Xd4 de dano do tipo de arma escolhido e 1 rank de sangramento. (X = o resultado da sua pilha de munição.) Ou metade desse dano e nenhum efeito adicional em caso de sucesso no teste. Você então pousa em um espaço desocupado que você possa ver dentro do alcance deste jutsu. Este jutsu consome completamente a pilha de munição.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o dano em 2d4.",
  },
  {
    key: "ferramentas-manipuladas-meteoro-de-amarracao",
    nome: "Ferramentas Manipuladas: Meteoro de Amarração",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "7,5 metros",
    duracao: "Instantânea",
    componentes: ["A (Pergaminho de Arma)", "M"],
    custoChakra: 3,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você invoca uma corrente pesada de seu pergaminho de armas e a usa para prender múltiplos alvos que você pode ver dentro do alcance. Faça um ataque de Taijutsu corpo a corpo contra até três alvos que estejam a até 7,5 metros de distância uns dos outros. Em um acerto, você os agarra e os amarra uns aos outros. Criaturas amarradas não podem se mover mais do que 7,5 metros uma das outras. Além disso, as criaturas amarradas podem, como ação, fazer um teste de Destreza (Acrobacia) ou (Manuseio) contra a sua DC de Salvamento de Taijutsu, escapando das correntes com um sucesso. Uma criatura que falhar nesse teste dificultará a fuga das outras criaturas amarradas. Todas as outras criaturas amarradas que tentarem escapar após outra falhar, sofrerão uma penalidade de -2 no seu teste até o final do próximo turno delas. Esta penalidade acumula.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o número de criaturas que você pode atingir em +1.",
  },
  {
    key: "ferramentas-manipuladas-chuva-de-laminas",
    nome: "Ferramentas Manipuladas: Chuva de Lâminas",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "18 metros (esfera de 4,5 metros de raio)",
    duracao: "Instantânea",
    componentes: ["A (Pergaminho de Arma)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você desenrola seu pergaminho de armas no ar e, reflexivamente, invoca uma série de espadas, facas e lanças que caem em uma chuva, bombardeando um espaço que você pode ver dentro do alcance. Todas as criaturas em uma esfera de 4,5 metros de raio, originada de um ponto que você pode ver dentro do alcance, devem fazer um teste de salvamento de Destreza. Em uma falha, elas sofrem 3d6 + seu modificador de Taijutsu em dano perfurante, ou metade disso em caso de sucesso. Além disso, a área afetada se torna terreno difícil até que a criatura se mova por ela. A primeira vez que uma criatura caminhar por qualquer espaço afetado, ela sofre 1d4 de dano devido às armas de lâmina espalhadas e deixadas no chão.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d6.",
  },
  {
    key: "ferramentas-manipuladas-parede-de-laminas",
    nome: "Ferramentas Manipuladas: Parede de Lâminas",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Raio de 3 metros)",
    duracao: "Instantânea",
    componentes: ["A (Pergaminho de Arma)", "M"],
    custoChakra: 3,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você desenrola seu pergaminho de armas em um círculo de 3 metros ao seu redor e simultaneamente invoca uma série de armas cortantes a partir dele. Todas as criaturas dentro de um raio de 3 metros a partir de você devem fazer um teste de salvamento de Destreza. Em uma falha, elas sofrem 3d8 de dano perfurante e não podem lançar jutsus até o final do próximo turno, além de ganhar a condição de sangramento. Em um sucesso, elas sofrem metade do dano e não há efeitos adicionais.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3, o raio em 1,5 metros e o dano em 1d8.",
  },
  {
    key: "posicao-do-rei-macaco",
    nome: "Posição do Rei Macaco",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "Especial (Quando você causar dano com uma arma contundente)",
    alcance: "Próprio",
    duracao: "Instantânea",
    componentes: ["A (Impacto Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: 'Você canaliza a energia do golpe para sua arma e mantém essa energia de forma passiva enquanto ela se acumula, assim como o próprio Rei Macaco. Você pode conjurar este jutsu quando causar dano com sua arma para assumir a postura, e seus efeitos mudam dependendo das circunstâncias em que você libera o jutsu. Você pode manter esse jutsu até o final do seu próximo turno, quando ele termina. Enquanto o jutsu estiver ativo, você não pode lançar outro jutsu além deste. Ação: Você salta e traz sua arma para baixo, atingindo a cabeça de seu inimigo. Faça um ataque de Taijutsu corpo a corpo contra uma criatura no alcance da sua arma. Em um acerto, você causa o [dano da arma] +2d8 e a criatura alvo deve fazer um teste de constituição, ficando Concussa em uma falha. Ação bônus: Você se lança para o lado e faz um golpe amplo nas pernas do seu oponente. Faça um ataque de Taijutsu corpo a corpo contra uma criatura dentro de 3 metros de você. Em um acerto, você causa o [dano da arma] +2d4 e a criatura alvo deve fazer um teste de Força, sendo derrubada em uma falha. Reação: Você golpeia rapidamente o lado do seu oponente, quebrando suas defesas. Faça um ataque de Taijutsu corpo a corpo contra uma criatura dentro de 1,5 metros de você. Em um acerto, você causa o [dano da arma]. Se seu oponente tiver um bônus em CA de um jutsu, recurso ou traço, esse ataque quebra a defesa e utiliza essa energia como força adicional. Este jutsu causa um dano adicional de 2d6 e ignora o bônus de CA. Em um acerto, você ganha esse bônus de CA até o final do seu próximo turno.',
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dado de dano do jutsu em 1 nível.",
  },
  {
    key: "cauda-do-rei-macaco",
    nome: "Cauda do Rei Macaco",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Impacto Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você gira sua arma ao redor de seu corpo antes de a travar atrás de suas costas com ambas as mãos, realizando uma rotação lateral, atingindo todas as criaturas à sua frente. Faça um ataque de Taijutsu corpo a corpo contra uma criatura que você possa ver dentro do alcance, causando o [dano da arma] + 2d6 e forçando o alvo a fazer um teste de salvamento de Constituição, ficando atordoado em uma falha. Além disso, dependendo do comprimento de sua arma, ela pode atingir várias criaturas em uma linha de 1,5 metros de largura, com o comprimento determinado pelos ranks de Alcance da arma. Para cada rank de Alcance que sua arma possui, ela se estende 1,5 metros em linha reta. Todas as criaturas, exceto o seu alvo original, que estiverem dentro deste alcance expandido, devem fazer um teste de salvamento de Destreza, sofrendo o [dano da arma] em uma falha ou nenhum dano em caso de sucesso. Se este jutsu for lançado como Cadeia 2, aumente o dado de dano em +2. Se este jutsu for lançado como Cadeia 3, faça um ataque adicional.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d6.",
  },
  {
    key: "10000-pelos-do-rei-macaco",
    nome: "10.000 Pelos do Rei Macaco",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Concentração, até 10 minutos",
    componentes: ["A (Impacto Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você envolve sua arma com chakra até que o chakra ao seu redor forme e se molde, lembrando o famoso Ruyi Jingu Bang, o bastão lendário usado pelo mítico Rei Macaco, Son Wukong. Você não perde a concentração devido a dano. Durante a duração, quando você tomar a ação de ataque ou lançar um Bukijutsu com o prefixo \"Rei Macaco\" com sua arma, você pode escolher dar a ela a propriedade Alcance X, onde X é igual ao seu modificador de Taijutsu. Além disso, duas vezes por turno, quando você causar dano com um ataque de arma ou Taijutsu, você causa dano adicional de 1d6.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3. Se este jutsu for lançado no rank B, aumente o dano bônus para 2d6. Se este jutsu for lançado no rank S, aumente o dano bônus para 3d6.",
  },
  {
    key: "presa-do-rei-macaco",
    nome: "Presa do Rei Macaco",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Impacto Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você gira sua arma acima da cabeça antes de balançá-la em direção ao alvo, em um ângulo descendente, seguido com a extremidade traseira da arma. Faça dois ataques de Taijutsu corpo a corpo, causando o [dano da arma] +1d6. Você não adiciona seu modificador de habilidade ao dano causado. Se dois ataques acertarem o alvo, ele deve fazer um teste de salvamento de Força, ficando atordoado em caso de falha.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o número de ataques feitos em +1.",
  },
  {
    key: "chuva-de-agulhas",
    nome: "Chuva de Agulhas",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "45 pés (Cubo de 20 pés)",
    duracao: "Instantâneo",
    componentes: ["A (Senbon)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você prepara uma pilha de Senbon e espalha-os pelo chão até 45 pés de distância em um cubo de 20 pés. A área se torna terreno difícil e criaturas que se movem enquanto dentro da área sofrem 1d6 de dano perfurante para cada 5 pés que se movem dentro da área. Esta área permanece por 1 minuto, ou até que a área afetada seja afetada por um jutsu que cria terreno difícil.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o tamanho do jutsu em 5 pés.",
  },
  {
    key: "peso-do-rei-macaco",
    nome: "Peso do Rei Macaco",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Concentração, até 1 minuto",
    componentes: ["A (Impacto Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você preenche sua arma com chakra suficiente para multiplicar seu peso em mais de 10 vezes o seu peso normal. Você não perde a concentração devido a dano. Durante a duração deste jutsu, você multiplica o peso da sua arma contundente imediatamente antes do impacto, enquanto a arma retorna ao seu peso normal após o impacto. Cada vez que você causar dano com um ataque de Taijutsu corpo a corpo sob os efeitos deste jutsu, aumente o dado de dano da arma em 1 nível (D4 > D6 > D8 > D10 > D12).",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3. Se este jutsu for lançado no rank B, aumente o dado de dano em 2 níveis. Se este jutsu for lançado no rank S, aumente o dado de dano em 3 níveis.",
  },
  {
    // NOTE: o fragmento "Todos os alvos,)" no meio da descrição-fonte parece ruído de OCR e foi omitido do texto reconstruído. Nenhum parágrafo "Em Ranks Superiores" próprio foi localizado para este jutsu.
    key: "coragem-de-nobunaga",
    nome: "Coragem de Nobunaga",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Raio de 9 metros)",
    duracao: "1 Minuto",
    componentes: ["A (Qualquer Arma de Haste)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você solta um rugido monstruoso, cheio de desprezo e raiva, enquanto empunha sua arma de haste. Isso preenche você com tamanha animosidade e raiva que você se torna muito mais corajoso e começa a imitar a aparência do famoso guerreiro Oda Nobunaga, causando grande medo nos inimigos e instilando grande honra em seus aliados. Todos os aliados dentro do alcance que puderem ouvir você, na primeira vez que ganharem qualquer um dos seguintes efeitos durante o próximo minuto (Encantado, Atordoado, Medo), não ganham os efeitos, tornando-se imunes ao jutsu, recurso, traço ou efeito que os afetou, até o final daquela rodada. Todas as criaturas hostis dentro do alcance que puderem ouvir você devem ter sucesso em um teste de salvamento de Carisma. Em caso de falha, na primeira vez que elas tomarem dano de qualquer ataque com arma que você faça usando sua arma de haste, elas ganham 1 grau de qualquer um dos seguintes efeitos (à sua escolha) pelo próximo minuto, ou até que gastem uma Ação para refazer o teste e terminar este efeito sobre elas: Atordoado, Medo, Enfraquecido.",
  },
  {
    key: "ataque-multiponto",
    nome: "Ataque Multiponto",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Multiataque Simples)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Conflito"],
    descricao: "Você desferiu uma série de ataques rápidos com o objetivo de sobrecarregar seu inimigo em um piscar de olhos. Você realiza uma série de golpes precisos em várias partes do corpo do alvo. Faça um único ataque de Taijutsu corpo a corpo ou à distância que se multiplica em eficácia conforme você repete o mesmo movimento várias vezes. Em um acerto, você causa o [dano da arma] + 2 dados de dano adicionais.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dado de dano bônus em +1.",
  },
  {
    key: "barragem-de-dor",
    nome: "Barragem de Dor",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Raio de 9 metros)",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Munição)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você salta no ar e gira enquanto atinge todos os alvos na área. Escolha até 10 criaturas que você possa ver dentro do alcance. Role o dado de munição duas vezes, tomando o maior resultado. Todas as criaturas selecionadas devem ter sucesso em um teste de salvamento de Destreza. Em caso de falha, as criaturas selecionadas tomam Xd4 + modificador de Taijutsu do tipo de dano da sua [arma escolhida]. (X = O resultado do dado de sua munição). Ou metade do dano em um sucesso. Você então aterrissa em um espaço desocupado que pode ver dentro do alcance deste jutsu. Este jutsu consome completamente a munição.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 2d4.",
  },
  {
    // NOTE: nenhum parágrafo "Em Ranks Superiores" foi encontrado para este jutsu; a entrada termina diretamente no título seguinte.
    key: "esquiva-ofensiva",
    nome: "Esquiva Ofensiva",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 reação quando você for alvo de um ataque corpo a corpo",
    alcance: "Alcance da arma",
    duracao: "Instantânea",
    componentes: ["A (Perfurante Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você pega sua arma com a empunhadura invertida e tenta atacar antes de ser atingido. Faça um ataque corpo a corpo contra a criatura que iniciou o ataque. Em um acerto, você causa o [dano da arma] + modificador de Taijutsu e aumenta sua CA contra o ataque que iniciou o movimento pelo valor do dado base de dano da arma rolado, enquanto arrasta sua arma ao longo do ataque, tentando desviar seu alvo.",
  },
  {
    key: "assalto-doloroso",
    nome: "Assalto Doloroso",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Cone de 9 metros)",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Munição)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você gasta um dado de munição completo para sobrecarregar seu inimigo com uma parede de flechas, dardos, virotes, shurikens, kunais ou Senbons. Todas as criaturas em um cone de 9 metros originado de você devem ter sucesso em um teste de salvamento de Destreza. Em caso de falha, elas tomam Xd4 de dano com o tipo de arma que você escolheu, onde X é o tamanho do dado gasto. (D4=4, D6=6, D8=8, D10=10, etc.)",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dado de dano em 1 nível. (D4 > D6 > D8 > D10 > D12)",
  },
  {
    key: "danca-da-dor",
    nome: "Dança da Dor",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Raio de 6 metros)",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Munição)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você lança uma explosão de armas ao seu redor, tentando atingir todas as criaturas ao seu redor. Todas as criaturas dentro de um raio de 6 metros de você devem ter sucesso em um teste de salvamento de Destreza, tomando o dano de sua [arma] + 2d8, e ficam atordoadas em caso de falha, ou metade do dano e sem efeitos adicionais em um sucesso. Após lançar este jutsu, diminua o dado de munição em 2.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d8.",
  },
  {
    key: "tiro-preparado",
    nome: "Tiro Preparado",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "Reação quando for alvo de um ataque corpo a corpo",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Arma Perfurante de Longo Alcance)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você reage ao ser atacado em combate corpo a corpo. Você dá um salto para trás de 1,5 metro, se possível, e imediatamente ataca a criatura que iniciou o ataque, perfurando-a indiscriminadamente, tentando interromper seu ataque. Faça um ataque à distância de Taijutsu, causando o dano de sua [arma] + 3d4 de dano Perfurante em um acerto. A criatura afetada deve fazer um teste de salvamento de Constituição, ficando atordoada até o final da sua rodada atual em caso de falha. Em um sucesso, ela avança 1,5 metro, se possível, e completa o ataque. Nenhum desses movimentos provoca um Ataque de Oportunidade.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 2d4.",
  },
  {
    // NOTE: custo listado sem valor fixo; a escala de dano depende da qualidade do item de pergaminho de bombas usado (não foi encontrado um parágrafo "Em Ranks Superiores" separado).
    key: "barragem-de-bombas-de-papel",
    nome: "Barragem de Bombas de Papel",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "9 metros",
    duracao: "Instantânea",
    componentes: ["NT (1 Bomba de Papel)"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você prepara um conjunto de bombas de papel que são consumidas durante a conjuração deste jutsu, entre seus dedos de ambas as mãos, e as lança em um único alvo, cobrindo-o com as bombas preparadas. Um alvo que você possa ver dentro do alcance deve fazer um teste de salvamento de Destreza, tomando 7d4 de dano de Fogo em caso de falha ou metade desse dano em um sucesso. Criaturas dentro de 3 metros do alvo, excluindo o próprio alvo, também fazem o teste de Destreza, tomando 5d4 de dano de Fogo em caso de falha ou metade desse dano em um sucesso. Para cada qualidade de item usada acima da qualidade básica do item, aumente o dano deste jutsu em 4d4.",
  },
  {
    key: "tiro-de-fixacao",
    nome: "Tiro de Fixação",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Especial",
    componentes: ["A (Qualquer Arma Perfurante de Longo Alcance)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você faz uma série de ataques à distância projetados para imobilizar seu inimigo de uma maneira de sua escolha. Faça um ataque à distância de Taijutsu usando a sua arma de escolha, causando o dano de sua [arma] + 1d10 e forçando a criatura alvo a fazer um teste de salvamento de Força, ficando restrita em caso de falha. Uma criatura restrita dessa maneira, ou outra criatura dentro de 1,5 metro da criatura restrita, pode gastar uma Ação para fazer um teste de Força (Atletismo) contra a sua CD de Salvamento, terminando essa condição em caso de sucesso.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o alvo sofre uma penalidade de -1 no teste de salvamento.",
  },
  {
    key: "tiro-impulsionado",
    nome: "Tiro Impulsionado",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma de Longo Alcance)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você realiza uma tripla sequência de ataques, a força por trás deles sendo suficiente para empurrar o alvo para trás. Faça três ataques à distância de Taijutsu usando sua arma, causando o dano de sua [arma], sem adicionar o modificador de habilidade ao dano. Se um alvo for atingido pelo menos uma vez, ele deve também realizar um teste de salvamento de Força, sendo empurrado 3 metros para trás para cada ataque bem-sucedido.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o número de criaturas que você pode atacar em +1. Se este jutsu for lançado em Rank B, aumente o dano em 2d10. Se for lançado em Rank S, aumente o dano em 4d10.",
  },
  {
    // NOTE: as duas descrições desta página (Tiro Sombrio / Extensor de Alcance) apareciam entrelaçadas na ordem oposta ao dos títulos na OCR; a atribuição abaixo segue o conteúdo temático ("sombra" combina com Tiro Sombrio) em vez da ordem bruta das colunas.
    key: "tiro-sombrio",
    nome: "Tiro Sombrio",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (27 metros)",
    duracao: "Instantânea",
    componentes: ["A (Arma de Cortante de Longo Alcance)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você lança sua arma como se fosse um único tiro, mas em sua sombra se esconde outra. Selecione uma criatura dentro do alcance e faça um Ataque de Taijutsu à distância. A criatura alvo deve fazer um teste de Percepção contra o seu roll de ataque. Em caso de falha, ela falha em ver a segunda arma, e toma um dano cortante igual ao dado de dano de sua [arma], independentemente de acerto ou erro. Em um acerto, você causa o dano de sua [arma].",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano do ataque que falhou no teste de Percepção em 1 dado.",
  },
  {
    // NOTE: nenhum parágrafo "Em Ranks Superiores" próprio foi localizado para este jutsu (ver nota em Tiro Sombrio sobre a troca de descrições).
    key: "extensor-de-alcance",
    nome: "Extensor de Alcance",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Concentração, até 1 Minuto",
    componentes: ["A (Qualquer Arma de Longo Alcance)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você concentra chakra em seus olhos, aumentando seu alcance perceptivo, permitindo que você trabalhe com um alcance muito maior. Durante a duração, a primeira vez que você fizer um ataque de Taijutsu à distância ou um ataque com arma por turno, você dobra o alcance do ataque.",
  },
  {
    key: "balanco-de-rebote",
    nome: "Balanço de Rebote",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus, quando você errar um ataque Corpo a Corpo com uma arma de Contusão",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Arma Corpo a Corpo de Contusão)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você tenta se recuperar rapidamente após o erro, bombeando chakra para seus braços para se lançar no sentido oposto. Você pode refazer o mesmo ataque com desvantagem, mirando na mesma criatura.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3. Se este jutsu for lançado em Rank B, você faz o ataque normalmente. Se for lançado em Rank S, você faz o ataque com vantagem.",
  },
  {
    key: "tiro-quebrador",
    nome: "Tiro Quebrador",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Dobre o Alcance de sua Arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma de Longo Alcance)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você derrama chakra em sua arma enquanto a dispara, a ponto de ela se fragmentar enquanto voa, causando dano em uma área ampla. Selecione uma área de 6 metros de raio. Criaturas hostis dentro dessa área devem fazer um teste de salvamento de Destreza. Em caso de falha, elas tomam 4d6 de dano do tipo de sua arma e ganham um nível de Desorientado, pois a explosão as desequilibra.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano de ambos os ataques e o teste de salvamento em 1d8.",
  },
  {
    // NOTE: as descrições de Dragão Voador e Estrela Cadente apareciam entrelaçadas na ordem oposta à dos títulos; a atribuição segue os componentes (Corte Corpo a Corpo = ataque corpo a corpo que leva ao ar; Arma Lançada = ataque à distância). A atribuição do parágrafo "Em Ranks Superiores" (custo +3, dano +2d4) entre este jutsu e Estrela Cadente é incerta.
    key: "dragao-voador",
    nome: "Dragão Voador",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Corte Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você balança o mais forte que pode para cima enquanto também pula, com o objetivo de cortar seu oponente e levá-lo para o ar junto com você. Faça um Ataque de Taijutsu corpo a corpo contra uma criatura dentro do alcance. Em um acerto, você causa o dano de sua [arma] + 2d4 e ela sobe no ar com você por 9 metros. Se este jutsu for lançado como Cadeia 2, aumente o dado de dano em 2. Se for lançado como Cadeia 3, faça um ataque adicional.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 2d4.",
  },
  {
    // NOTE: ver nota em Dragão Voador sobre a troca de descrições; nenhum parágrafo "Em Ranks Superiores" claramente próprio foi localizado para esta entrada.
    key: "estrela-cadente",
    nome: "Estrela Cadente",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma Lançada)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você lança sua arma com foco na velocidade em vez de poder. Faça um Ataque de Taijutsu à distância contra uma criatura dentro do alcance. Em um acerto, você causa o dano de sua [arma]. Se você estiver mirando em uma criatura dentro do alcance normal de sua arma, este ataque tem vantagem. Se for mirar em uma criatura no seu alcance longo, você faz o ataque com desvantagem e não pode ganhar vantagem, no entanto, este ataque causa 2d10 de dano adicional.",
  },
  {
    key: "lancamento-de-peso",
    nome: "Lançamento de Peso",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma Lançada de Contusão)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você realiza um único lançamento destinado a perfurar defesas. Faça um Ataque de Taijutsu à distância contra uma criatura que você possa ver dentro do alcance, causando o dano de sua [arma] + 2d6, mas como dano de contusão. Este jutsu ignora cobertura parcial e causa o dobro de dano a construtos e estruturas.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o dano em 1d6.",
  },
  {
    key: "caca-da-alma",
    nome: "Caça da Alma",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Concentração, até 1 Minuto",
    componentes: ["A (Arma de Longo Alcance, Perfurante)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Este jutsu não custa chakra para manter concentração. Você começa a impregnar suas armas com chakra antes de dispará-las. O primeiro ataque de arma de longo alcance feito com uma arma perfurante a cada turno, tem um bônus no alcance de ameaça crítica igual a +1.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3. Se este jutsu for lançado em Rank B ou superior, aumente o alcance de ameaça crítica em +1. Se for lançado em Rank S, aumente o alcance de ameaça crítica em +1.",
  },
  {
    key: "roubo-da-alma",
    nome: "Roubo da Alma",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Concentração, até 1 Minuto",
    componentes: ["A (Qualquer)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você aprende a mirar no espírito de um alvo, em vez de no corpo, permitindo que seus ataques sejam certeiros e profundos. A primeira vez a cada turno que um ataque de arma que você faça atingir um acerto crítico, o dano do seu modificador de habilidade é dobrado e você ignora pontos de vida temporários.",
    // NOTE: o texto de escala a seguir ("alcance do primeiro ataque de arma... a cada turno") tem correspondência temática imperfeita com a descrição acima (focada em críticos), mas foi mantido por ser a continuação estrutural direta desta entrada na coluna da OCR.
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o alcance do primeiro ataque de arma que você faça a cada turno em +1.",
  },
  {
    key: "marca-da-alma",
    nome: "Marca da Alma",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "36 metros",
    duracao: "1 minuto",
    componentes: ["A (Qualquer)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você ativa todos os receptores de sua mente e olhos, se concentrando em uma criatura que você possa ver dentro do alcance. Durante a duração, selecione uma criatura para marcar sua alma. A criatura selecionada não pode se beneficiar de cobertura de três quartos ou meio. Quando você causar dano com um ataque de arma, você causa 1d10 de dano adicional do tipo de sua [arma]. Uma criatura permanece marcada até atingir 0 pontos de vida ou você não conseguir mais vê-la. Uma vez que a criatura não está mais marcada, você deve recitar este jutsu para marcar a alma dela novamente. Enquanto este jutsu tiver um alvo, toda vez que você fizer um ataque de arma contra outra criatura que não esteja marcada, você reduz o dano causado em 1d6.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o número de criaturas que você pode marcar em +1.",
  },
  {
    // NOTE: nenhum parágrafo "Em Ranks Superiores" foi encontrado para este jutsu.
    key: "lago-tranquilo-rio-rapido",
    nome: "Lago Tranquilo, Rio Rápido",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (esfera de 4,5 metros de raio)",
    duracao: "Instantânea",
    componentes: ["A (Qualquer)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você mantém sua arma em uma posição perfeitamente perpendicular enquanto espera o momento certo para atacar. Quando uma criatura fizer um ataque com arma ou Taijutsu dentro do alcance de sua arma até o início de seu próximo turno, você ataca, puxando a criatura para você. Faça um Ataque de Taijutsu contra a criatura que iniciou o ataque. Em um acerto, você causa o dano de sua [arma] e se torna o novo alvo do ataque.",
  },
  {
    // NOTE: nenhum parágrafo "Em Ranks Superiores" foi encontrado para este jutsu antes do fim da página 399.
    key: "rasgacao-da-alma",
    nome: "Rasgação da Alma",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Corte Corpo a Corpo)", "M"],
    custoChakra: 6,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você mira sua arma para cortar a própria alma do seu oponente. Você prepara o golpe e o solta em uma rajada. Faça um Ataque de Taijutsu corpo a corpo com desvantagem contra uma criatura dentro do alcance. Em um acerto, você causa 4d6 de dano cortante e a criatura alvo ganha um nível de sangramento. Se este jutsu for lançado como Cadeia 2, a criatura alvo ganha um nível adicional de sangramento. Se for lançado como Cadeia 3, o dano se torna 6d12.",
  },
  {
    key: "tormenta-de-aco",
    nome: "Tormenta de Aço",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Qualquer)", "M"],
    // NOTE: fonte lê "Custo: Especial (28 Chakra)" — valor fixo informado entre parênteses usado diretamente.
    custoChakra: 28,
    palavrasChave: ["Bukijutsu", "Combinação"],
    descricao: "Você e qualquer aliado dentro de 9 metros da criatura alvo se preparam para liberar um redemoinho de ferro e aço sobre seu inimigo. Todas as criaturas participantes fazem um Ataque de Taijutsu contra a criatura em questão, uma de cada vez. Em um acerto, elas causam o dano da [arma] + 3d8. Após cada criatura atacar, os seguintes efeitos acontecem: Se o dano for de Impacto (Bludgeoning), a criatura deve fazer um teste de resistência de Força com uma penalidade de -1 para cada acerto com uma arma desse tipo contra a maior DC de Salvação de Taijutsu. Se falhar, ela ganha 1 nível de Machucado (Bruised) enquanto é espancada. Se o dano for de Corte (Slashing), a criatura deve fazer um teste de resistência de Destreza com uma penalidade de -1 para cada acerto com uma arma desse tipo contra a maior DC de Salvação de Taijutsu. Se falhar, ela ganha 1 nível de Sangramento (Bleeding) enquanto é cortada. Se o dano for de Perfurante (Piercing), a criatura deve fazer um teste de resistência de Constituição com uma penalidade de -1 para cada acerto com uma arma desse tipo contra a maior DC de Salvação de Taijutsu. Se falhar, ela ganha 1 nível de Atraso (Slowed) enquanto suas articulações são perfuradas. Combinação: Quando este jutsu for lançado, ele ganha efeitos adicionais dependendo de quem tem o maior modificador de Carisma entre ambos os conjuradores: +0-1: Sem Mudança. +2-3: O dado de dano do jutsu aumenta para d10. +4-5: O dado de dano do jutsu aumenta para d12.",
  },
  {
    // NOTE: fonte lê "Custo: Especial" sem valor numérico fixo; o custo real é a recuperação/redução baseada no dano do Bukijutsu cancelado, descrito no texto.
    key: "forma-de-pedra",
    nome: "Forma de Pedra",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 reação a uma criatura reagindo ao seu Bukijutsu",
    alcance: "Próprio",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Arma de Lança)", "M"],
    custoChakra: 0,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você rapidamente cancela seu Bukijutsu e usa essa energia para se preparar para outro. Você cancela seu último jutsu antes que seus efeitos ocorram e assume uma guarda cruzada. Se a criatura fizer um ataque como reação, você será atingido independentemente do rolar do dado. Se você for receber dano da reação da criatura, você reduz o dano pelo valor do dano do Bukijutsu que foi cancelado. Se você reduzir esse dano a 0, o próximo Bukijutsu que você lançar será automaticamente elevado em 1 rank.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano em 1d8.",
  },
  {
    // NOTE: os títulos "Língua de Réptil: Chicote de Ranhos" e "Lança Quebradora" apareciam na OCR seguidos por blocos de campos/descrição que, pelo conteúdo (arma Mangual = chicote; componente perfurante + "crava sua lança" = lança), estavam trocados em relação à ordem bruta das colunas; a atribuição abaixo segue o conteúdo.
    key: "lingua-de-reptil-chicote-de-ranhos",
    nome: "Língua de Réptil: Chicote de Ranhos",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Concentração, até 1 Minuto",
    componentes: ["A (Qualquer Mangual)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu"],
    descricao: "Este jutsu não custa chakra para manter a concentração. Você aprimora sua arma com chakra para controlar sua trajetória durante o ataque. Durante a duração, os ataques de arma que você faz com uma Arma Mangual recebem +1 nos rolos de ataque e dano, uma aplicação adicional de alcance, e um bônus de +2 nas tentativas de Derrubar e Agarrar.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3. Se for lançado em Rank C ou superior, a arma recebe +2 nos rolos de ataque e dano. Se for lançado em Rank B ou superior, a arma ganha uma aplicação adicional de alcance. Se for lançado em Rank A ou superior, a arma recebe +3 nos rolos de ataque e dano. Se for lançado em Rank S, a arma recebe um bônus de +10 nas tentativas de Derrubar e Agarrar.",
  },
  {
    // NOTE: ver nota em "Língua de Réptil: Chicote de Ranhos" sobre a troca de blocos. Nenhum parágrafo "Em Ranks Superiores" separado foi localizado (apenas a escala por Cadeia).
    key: "lanca-quebradora",
    nome: "Lança Quebradora",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Perfurante Corpo a Corpo)", "M"],
    custoChakra: 4,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você crava sua lança para frente, imbuída de chakra destinada a ferir a carne ou quebrar aço. Faça um Ataque de Taijutsu corpo a corpo contra uma criatura dentro do alcance. Em um acerto, você pode escolher entre causar o dano da sua [arma] ou reduzir a Redução de Dano da criatura em uma quantidade igual ao seu dano até o início do seu próximo turno. Se este jutsu for lançado como Cadeia 2, você pode fazer ambas as ações sem precisar escolher. Se este jutsu for lançado como Cadeia 3, faça um ataque adicional.",
  },
  {
    // NOTE: nenhum parágrafo "Em Ranks Superiores" foi encontrado para este jutsu.
    key: "aura-da-espada-vermelha",
    nome: "Aura da Espada: Vermelha",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "1 minuto",
    componentes: ["A (Qualquer Espada)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você começa a desbloquear a habilidade de criar uma Aura de Espada, um caminho que apenas mestres espadachins poderiam sequer sonhar em seguir. Você envia uma inundação controlada de chakra para sua espada, fazendo a parte cortante brilhar em vermelho devido ao chakra. Sua lâmina fura 4 dr (Dano de Resistência) durante a duração. Quando você causar dano a uma criatura com esta arma, uma vez por turno, você pode forçar a criatura a fazer um teste de resistência de Força. Se falhar, ela recebe 1d10 de dano de Fogo e é derrubada, à medida que sua lâmina explode com força.",
  },
  {
    key: "garras-de-tigre",
    nome: "Garras de Tigre",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Corte à Distância)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você arremessa sua arma de forma que ela acerte na diagonal, cortando seu inimigo com precisão. Faça um Ataque de Taijutsu à distância contra uma criatura dentro do alcance. Em um acerto, você causa o dano da [arma] + 1d8 e a criatura alvo deve fazer um teste de resistência de Constituição. Em caso de falha, ela é cortada profundamente no peito, recebendo 2d8 de dano cortante adicional.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo em 3 e o dano de ambos o ataque e o teste de resistência em 1d8.",
  },
  {
    // NOTE: nenhum parágrafo "Em Ranks Superiores" foi encontrado para este jutsu.
    key: "armadilha-de-fios",
    nome: "Armadilha de Fios",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "10 Minutos",
    alcance: "Cubo de 3 metros",
    duracao: "Instantânea",
    componentes: ["NT (Fio de Batalha e Kit de Caçador)"],
    custoChakra: 3,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você prepara uma armadilha em uma localização alvo. A armadilha tem uma área de ativação do tamanho de um cubo de 4,5 metros centrado na armadilha. Criaturas que entrarem nesta área ativam a armadilha. Uma vez ativada, a criatura que ativou a armadilha deve fazer um teste de resistência de Destreza, sendo restrita em caso de falha. Criaturas restritas fazem um teste de resistência de Força no início de cada um de seus turnos. Em caso de sucesso, elas quebram o fio, terminando a condição de restrição.",
  },
  {
    // NOTE: nenhum parágrafo "Em Ranks Superiores" foi encontrado para este jutsu.
    key: "quebra-de-arma",
    nome: "Quebra de Arma",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 reação, que você toma quando recebe dano de um ataque corpo a corpo",
    alcance: "Próprio",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Poder)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você reage rapidamente ao ser atingido, usando sua arma para pegar a arma do atacante em um ângulo vulnerável. A criatura que disparou essa reação deve ter sucesso em um teste de resistência de Destreza, fazendo com que sua arma se quebre em caso de falha. Se a arma da criatura disparadora tiver um bônus em rolos de ataque e/ou dano ou um selo de aprimoramento de arma, ela só pode ser quebrada por uma arma que tenha um bônus igual ou maior nos rolos de ataque e/ou dano ou um selo de aprimoramento de arma de igual ou maior rank.",
  },
  {
    key: "cortes-mutilantes",
    nome: "Cortes Mutilantes",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Alcance da Arma",
    duracao: "Instantânea",
    componentes: ["A (Corte Corpo a Corpo)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu"],
    descricao: "Você reveste sua arma com um manto de chakra irregular antes de desferir um golpe com a intenção de causar danos severos. Faça um Ataque de Taijutsu corpo a corpo com desvantagem contra uma criatura dentro do alcance. Em um acerto, você causa o dano da [arma] + 2d10 e inflige 1 nível de Sangramento.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o nível de Sangramento em 1.",
  },
  {
    key: "deflexao-de-arma",
    nome: "Deflexão de Arma",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 reação, que você toma quando é alvo de um ataque de arma corpo a corpo que você pode ver",
    alcance: "Próprio",
    duracao: "1 rodada",
    componentes: ["A (Qualquer Arma)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você entra em uma postura defensiva com sua arma, desviando qualquer ataque iminente. Você recebe um bônus de +2 à sua CA até o início do seu próximo turno. Até o final do seu próximo turno, o próximo Bukijutsu que você lançar com a palavra-chave Chain aumenta seu dano em +2 dados de dano.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo do jutsu em 3. Se este jutsu for lançado em Rank B, aumente o bônus de CA em +1 e o bônus de dano em +1 dado de dano. Se for lançado em Rank S, aumente o bônus de CA em +2 e o bônus de dano em +2 dados de dano.",
  },
  {
    // NOTE: fonte lê o título em "Golpe Yosaku" (não em versalete como os demais títulos) — mantido exatamente como grafado no OCR.
    key: "golpe-yosaku",
    nome: "Golpe Yosaku",
    tipo: "bukijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Cone de 4,5 metros)",
    duracao: "Instantânea",
    componentes: ["A (Qualquer Lança)", "M"],
    custoChakra: 5,
    palavrasChave: ["Bukijutsu", "Cadeia X"],
    descricao: "Você balança sua arma com força suficiente para criar uma onda lateral de força cortante. Criaturas em um cone de 4,5 metros à sua frente devem fazer um teste de resistência de Destreza. Em uma falha, você causa o dano da [arma] + 3d4, ou metade disso em caso de sucesso. Você não adiciona seu modificador de habilidade ao dano. Criaturas que estão a 1,5 metros de você quando lançar este jutsu fazem o teste com desvantagem. Se este jutsu for lançado como Cadeia 2, você pode adicionar seu modificador de habilidade ao rolo de dano. Se for lançado como Cadeia 3, aumente o dado de dano em 1 passo.",
    emNiveisSuperiores: "Para cada rank acima de Rank D em que este jutsu for lançado, aumente o custo deste jutsu em 3 e o alcance em 1,5 metros.",
  },
];
