import type { JutsuDefinition } from "@/lib/jutsu/types";

/** Estilo Fogo, Rank D — Anotações do Jiraya, p.134-140. */
export const fogoJutsu: JutsuDefinition[] = [
  {
    key: "absorcao-de-calor",
    nome: "Absorção de Calor",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Reação, que você realiza quando sofreria dano.",
    alcance: "Pessoal",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Você gera um vácuo de chakra absorvendo o calor da área ao redor e cria uma fina camada de chakra de fogo para se proteger. Você ganha resistência ao dano que causou a ativação.\n\nSe o dano que causou a ativação ou qualquer ataque posterior que o atinja forem ataques corpo a corpo e a criatura que causou o dano estiver a não mais de 3 metros de distância quando este jutsu foi lançado, a criatura que causou o dano sofre 6 de dano de fogo até o início do seu próximo turno.\n\nSe o dano que causou a ativação foi de fogo, você também ganha +5 de resistência contra dano de fogo até o início do seu próximo turno. Se o dano que causou a ativação foi de frio, este jutsu falha em ativar.",
    emNiveisSuperiores:
      "Para cada rank acima de D, aumente o custo deste jutsu em 3, o dano causado como resultado de um ataque corpo a corpo em +4 e o alcance da criatura que pode sofrer o dano em 1,5 metro.",
  },
  {
    key: "nuvem-de-cinzas",
    nome: "Nuvem de Cinzas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "9 metros (Nuvem de 9 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Você inala e molda chakra de fogo em seus pulmões para criar uma nuvem de cinzas. Você exala as cinzas em uma área alvo dentro do alcance que você pode ver. A nuvem de cinzas permanece até ser dissipada pelo vento ou dissipar-se, o que pode levar até 10 minutos.\n\nCriaturas dentro da área alvo têm desvantagem em ataques enquanto estiverem dentro da nuvem e são tratadas como se estivessem na escuridão total. Criaturas que realizam ataques à distância dentro da nuvem não conseguem ver outras criaturas dentro dela.",
  },
  {
    key: "fogo-azul",
    nome: "Fogo Azul",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Reação, que você realiza quando vê uma criatura sofrer dano dentro do alcance.",
    alcance: "9 metros",
    duracao: "1 Rodada",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Fogo", "Ninjutsu", "Conflito"],
    descricao:
      "Você manifesta uma chama de cor safira ao redor de uma criatura disposta que você pode ver dentro do alcance, protegendo-a. Uma erupção de chama azul quente surge ao redor dela, criando uma barreira de calor.\n\nAté o início do próximo turno da criatura, ataques à distância causam dano reduzido igual a 2d4+2. Ataques corpo a corpo causam dano reduzido igual a 2d4+2 e causam 3d6+3 de dano de fogo à criatura atacante uma vez por turno.\n\nSe a criatura atacante causaria Dano Frio, este jutsu é imediatamente extinto, encerrando-o antes que qualquer redução de dano ou dano possa ser causado.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3, a redução de dano em 1d4+1 e o dano causado em 1d6+1.",
  },
  {
    key: "brasa-flamejante",
    nome: "Brasa Flamejante",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "18 metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Você manifesta partículas de fogo nas palmas de cada uma de suas mãos. Faça dois ataques de Ninjutsu à Distância. Esses ataques podem ter como alvo uma ou duas criaturas. Se tiver como alvo várias criaturas, faça um único ataque de Ninjutsu à Distância contra cada uma delas.\n\nEm um acerto bem-sucedido, você causa 3d4+3 de dano de fogo. Se uma criatura afetada pela condição Queimado for atingida por ambos os ataques, ela imediatamente sofre o dano de sua condição.",
    emNiveisSuperiores:
      "Para cada nível que você conjura este jutsu acima do Nível D, aumente o custo deste jutsu em 3. Se este jutsu for conjurado no Nível B, aumente o número de ataques que você pode fazer em +1. Se este jutsu for conjurado no Nível S, aumente o número de ataques que você pode fazer em +2.",
  },
  {
    key: "maos-flamejantes",
    nome: "Mãos Flamejantes",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (cone de 6 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Você estende suas mãos e dispara uma rajada de chamas. Cada criatura em um cone de 4,5 metros deve realizar um teste de resistência de Destreza. Uma criatura sofre 5d4+5 de dano de fogo em um teste falho, ou metade desse dano em um teste bem-sucedido. Este fogo inflama objetos inflamáveis na área que não estão sendo usados ou transportados.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o dano em 1d4+1.",
  },
  {
    key: "lanterna-dos-demonios",
    nome: "Lanterna dos Demônios",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (raio de 1,5 metros)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      'Você conjura múltiplas chamas de chakra para cercá-lo. Essas chamas se transformam em faces de demônios conforme sua descrição. Você emite luz brilhante por 6 metros e luz fraca por mais 3 metros.\n\nComo reação, quando uma criatura se mover dentro de 1,5 metros de você, você pode forçar o alvo a realizar um teste de resistência de Destreza, pois essas Lanternas de Demônios tentam atingir o alvo. Em um fracasso no teste, o alvo é incendiado e ganha a condição "Queimado".',
  },
  {
    key: "chama-eruptiva",
    nome: "Chama Eruptiva",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "18 metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      'Você concentra chakra na área alvo e cria um ponto quente diretamente sob uma criatura alvo que você pode ver dentro do alcance. O alvo deve fazer um teste de resistência de Destreza ou sofrer 3d8+3 de dano de Fogo. O alvo não recebe benefícios de cobertura contra este jutsu.\n\nUma criatura que falhar em seu teste de resistência por 5 ou mais recebe 2 níveis da condição "queimado".',
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras e o dano em 1d8+1.",
  },
  {
    key: "aranha-carmesim",
    nome: "Aranha Carmesim",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "9 metros",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Você expele fogo que cerca uma criatura que você pode ver dentro do alcance. O fogo então se coleta em um espaço dentro de 9 metros da criatura alvo, formando uma Aranha de Chamas de tamanho médio. Esta Aranha de Chamas pode ser comandada como uma ação bônus em seu turno.\n\n" +
      "Aranha de Chama — Construto Médio, sem alinhamento. Classe de Armadura 10 + Modificador de Habilidade em Ninjutsu. Pontos de Vida 18 (4d8 + nível de personagem). Deslocamento 40 pés.\n" +
      "FOR 14 (+2), DES 16 (+3), CON 12 (+1), INT 1 (-5), SAB 10 (+0), CAR 1 (-5).\n" +
      "Imunidades a Dano: Ácido, Fogo, Psíquico, Contundente, Cortante. Imunidades a Condições: Encantado, Exaustão, Atordoado, Petrificado, Envenenado. Sentidos: Percepção Passiva 10. Vulnerabilidade a Dano: a Aranha de Chama sofre o dobro de dano de dano frio. Corpo Elemental: os ataques de arma da Aranha de Chama são aprimorados por chakra.\n" +
      "Ações — Multiataque: a Aranha de Chama pode atacar duas vezes com sua Mordida. Mordida: Ataque de Arma Corpo a Corpo: +(bônus de ataque em ninjutsu) para acertar, alcance 5 pés., uma criatura. Acerto: 2d4+2 de dano de fogo. Teia de Chamas (Recarga 9-10): Ataque de Arma à Distância: +(bônus de ataque em ninjutsu) para acertar, alcance 30/60 pés., uma criatura. O alvo é envolto em teias de chamas solidificadas e fica restrito por elas, sofrendo 2d6+2 de dano de fogo. Como uma ação, o alvo restrito pode fazer um teste de Força, rompendo as teias com sucesso. As teias também podem ser atacadas e destruídas (CA 10, PV: 5; Vulnerabilidade ao dano frio).",
  },
  {
    key: "raio-de-chama",
    nome: "Raio de Chama",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "18 metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Você expele um raio de chama em uma criatura ou objeto dentro do alcance. Realize um ataque de ninjutsu à distância contra o alvo. Em um acerto, o alvo sofre dano de fogo igual a 3d10+3. Um objeto inflamável atingido por este jutsu se incendeia se não estiver sendo usado ou carregado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras e aumente o dano em 1d10+1.",
  },
  {
    key: "revestimento-de-chama",
    nome: "Revestimento de Chama",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Toque",
    duracao: "Concentração, até 10 minutos",
    componentes: ["SM", "MC", "A (Qualquer arma)"],
    custoChakra: 5,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Você envolve uma arma em chakra de fogo, revestindo-a com uma chama que aumenta a letalidade da arma. Se você soltar a arma ou ela for retirada de você, o fogo se dispersa. Você não pode perder a concentração deste jutsu devido a danos.\n\nEnquanto você mantém a concentração neste jutsu, você pode envolver outra arma que estiver segurando como uma ação bônus. Uma arma inflamada por você causa um dano adicional de fogo de 1d8+1 duas vezes por turno. A chama emite luz intensa em um raio de 20 pés e luz fraca por mais 10 pés.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras, o dano em 1d6+1, e o raio em 1,5 metros.",
  },
  {
    key: "bola-de-fogo",
    nome: "Bola de Fogo",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "18 metros (esfera com raio de 4,5 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Fogo", "Ninjutsu", "Confronto"],
    descricao:
      "Você expele uma corrente de fogo na área alvo, que se expande formando uma bola de fogo que queima tudo dentro de seu alcance. Criaturas alvo na área devem fazer um teste de resistência de Destreza, sofrendo 4d6+4 de dano de Fogo em caso de falha no teste, ou metade desse dano em caso de sucesso. Objetos inflamáveis pegos no raio de alcance se incendeiam se não estiverem sendo segurados ou carregados.",
    emNiveisSuperiores:
      "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras. Se este jutsu for conjurado como Rank B ou superior, aumente o dano para 2d8+2. Se for conjurado como Rank S, aumente o dano para 3d8+3.",
  },
  {
    key: "golpe-de-chama",
    nome: "Golpe de Chama",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "18 metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      'Uma coluna vertical de chamas irrompe do chão em direção ao céu em uma localização que você especificar. Cada criatura em um cilindro com raio de 3 metros e altura de 6 metros centrado em um ponto dentro do alcance deve fazer um teste de resistência de Destreza, sofrendo 3d6+3 de dano de fogo e ganhando 1 nível da condição "queimado" em caso de falha no teste, ou metade desse dano em caso de sucesso.',
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras e aumente o dano em 1d6+1.",
  },
  {
    key: "fogo-verde",
    nome: "Fogo Verde",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "27 metros",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Você manifesta uma chama de cor esmeralda e marca uma criatura que você pode ver dentro do alcance com ela. Durante a duração, quando o alvo faria um teste de resistência contra um jutsu com a palavra-chave Estilo Fogo, ele rola um dado adicional de 1d4, reduzindo o teste de resistência pelo resultado.\n\nSe a criatura marcada sofrer dano de fogo de um ataque que você realizar, você causa um dano adicional de fogo de 1d6+1.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras e o número de criaturas marcadas em +1.",
  },
  {
    key: "chicote-de-chama",
    nome: "Chicote de Chama",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (6 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      'Você conjura um chicote flamejante para atacar uma criatura que você pode ver até 6 metros de distância de você. Realize um ataque de ninjutsu corpo a corpo, causando 2d10+2 de dano de fogo. O alvo deve fazer um teste de resistência de Destreza, sendo puxado 3 metros em direção a você. Se uma criatura que falhar no teste de resistência terminar seu movimento a até 1,5 metros de você, ela cai prostrada e ganha a condição "queimado".',
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras e aumente o dano em 1d10+1.",
  },
  {
    key: "raposa-de-fogo",
    nome: "Raposa de Fogo",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal",
    duracao: "Concentração, até 1 hora",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Uma chama bruxuleante aparece em sua mão. A chama permanece lá durante a duração e não causa dano a você nem ao seu equipamento. A chama emite luz brilhante em um raio de 20 pés e luz fraca por mais 10 pés. O jutsu termina se você dispensá-lo. Você também pode atacar com a chama.\n\nComo uma Ação, você pode fazer um ataque de Ninjutsu à Distância em uma criatura que você possa ver a até 30 pés de você. Em um acerto, o alvo começa a brilhar com uma radiância suave, quente e brilhante. Enquanto brilha dessa forma, a duração deste jutsu se torna Concentração, até o final do seu próximo turno, e as criaturas têm vantagem em ataques corpo a corpo que tenham como alvo a criatura.",
  },
  {
    key: "rejeicao-das-chamas-do-inferno",
    nome: "Rejeição das Chamas do Inferno",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Reação, que você realiza quando seria atingido por dano.",
    alcance: "4,5 metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Quando você é atingido por uma criatura que você pode ver, você libera uma explosão brilhante de chakra de fogo em uma esfera de 4,5 metros ao seu redor. Criaturas de sua escolha pegas no raio devem fazer um teste de resistência de Destreza, sofrendo 3d8+3 de dano de fogo em caso de falha no teste, ou metade desse dano em caso de sucesso.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras e aumente o dano em 1d8+1.",
  },
  {
    key: "chamas-reacendidas",
    nome: "Chamas Reacendidas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Fogo", "Ninjutsu", "Médico"],
    descricao:
      "Você manifesta uma chama dourada e a coloca em uma criatura moribunda que você pode ver dentro do alcance. A criatura alvo é imediatamente estabilizada e rola 3 dados de vida, gastando dois deles. Se o alvo tiver menos de 3 dados de vida, ele rola o que tiver restante, gastando todos. Se a criatura não tiver dados de vida, não pode ser estabilizada. A criatura recupera o resultado dos dados de vida rolados + o modificador de habilidade de Ninjutsu.\n\nApós conjurar, a criatura alvo ganha resistência a dano de Fogo até o final do seu próximo turno.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras e o número de dados de vida rolados e gastos em +1.",
  },
  {
    key: "chamas-apaixonadas",
    nome: "Chamas Apaixonadas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Fogo", "Ninjutsu", "Médico"],
    descricao:
      "Você manifesta uma chama cor de fúcsia e a coloca em uma criatura ferida que você pode ver dentro do alcance. A criatura alvo rola 2 dados de vida, gastando um deles. Quando o faz, ela recupera o resultado mais o modificador de habilidade de Ninjutsu.\n\nApós conjurar, a criatura alvo ganha resistência a dano de Fogo até o final do seu próximo turno.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras e o número de dados de vida rolados em +1.",
  },
  {
    key: "fogo-da-fenix",
    nome: "Fogo da Fênix",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "18 metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      'Você cospe 3 partículas de fogo em uma criatura dentro do alcance. Realize 3 ataques de ninjutsu à distância contra um alvo que você pode ver dentro do alcance. Em caso de acerto, o alvo sofre 1d6+1 de dano de fogo.\n\nSe você acertar pelo menos dois ataques com este jutsu no mesmo alvo, ele deve fazer um teste de resistência de Constituição, ganhando 1 nível da condição "queimado".',
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras e aumente a quantidade de ataques em +1.",
  },
  {
    key: "faisca",
    nome: "Faísca",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "1,5 metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Você manifesta uma brasa altamente inflamável de chakra do Estilo fogo. Você pode lançar esta brasa em qualquer material altamente inflamável não usado ou segurado, fazendo com que ele imediatamente se incendeie. As chamas criadas por este jutsu crescem de tamanho como fogo normal e não são controladas por você.\n\nEstas chamas são tão quentes que evaporam toda a água de fontes que não são criadas por um jutsu com a palavra-chave Estilo Água de pelo menos Rank D ou superior. As chamas se extinguem por si mesmas após 10 minutos.",
  },
  {
    key: "lanca-sanguinea",
    nome: "Lança Sanguínea",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "1,5 metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      'Você manifesta uma chama de cor sanguínea e a molda em uma arma corpo a corpo de sua escolha que você então usa para atacar um alvo dentro do alcance.\n\nRealize um ataque de ninjutsu corpo a corpo, causando 3d6+3 de dano de fogo em um acerto. Um alvo atualmente queimado ou congelado sofre efeitos exacerbados.\n\nQueimado: Uma criatura queimada ganha um nível adicional da condição "queimado".\n\nCongelado: Uma criatura congelada perde a condição congelada sofrendo todos os níveis de seus danos congelados. A condição congelada da criatura termina imediatamente.',
    emNiveisSuperiores:
      "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras. Se este jutsu for conjurado como Rank B, aumente o número de ataques de ninjutsu corpo a corpo em +1. Se for conjurado como Rank S, aumente o número de ataques de ninjutsu corpo a corpo em +2.",
  },
  {
    key: "metais-temperados",
    nome: "Metais Temperados",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "1 Minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      "Você superaquece uma única arma, pilha de armas ou munição. Pelos próximos minutos, essas armas brilham vermelho incandescente e são extremamente quentes ao toque para todas as criaturas, exceto você.\n\nAs armas afetadas por este jutsu ganham um bônus de +1 nas jogadas de ataque e dano, e seu dado de dano é aumentado em um passo durante a duração (D4 > D6 > D8 > D10 > D12). Ao final deste jutsu, a arma se torna frágil, inutilizável e se quebra.",
    emNiveisSuperiores:
      "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras. Quando este jutsu é conjurado como Rank B, o bônus se torna +2 e o dado de dano é aumentado em um passo adicional. Quando este jutsu é conjurado como Rank S, o bônus se torna +3 e o dado de dano é aumentado em um passo adicional.",
  },
  {
    key: "raio-escaldante",
    nome: "Raio Escaldante",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "fogo",
    tempoConjuracao: "1 Ação",
    alcance: "9 metros",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Fogo", "Ninjutsu"],
    descricao:
      'Você cria 8 raios de fogo e os lança em alvos dentro do alcance. Você pode lançar até 2 em um único alvo, caso contrário, pode mirar até 8 alvos diferentes. Realize um ataque de ninjutsu à distância para cada raio. Em um acerto, o alvo sofre 2d4+2 de dano de fogo. A cada duas vezes que você causa dano a uma criatura alvo, ela deve fazer um teste de resistência de Constituição, ganhando a condição "queimado" em caso de falha.',
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 chakras e você cria dois raios adicionais.",
  },
];
