import type { JutsuDefinition } from "@/lib/jutsu/types";

/** Genjutsu, Rank E + primeira metade do Rank D — Anotações do Jiraya, p.219-242. */
export const genjutsuPart1: JutsuDefinition[] = [
  // ===== RANK E (16 entries) =====
  {
    key: "eco-distante",
    nome: "Eco Distante",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "Até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 1,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você cria um som dentro do alcance que dura pela duração. O som também termina se você o dispensar como uma ação ou usar este jutsu novamente. O som que você cria pode ter qualquer volume, variando de um sussurro a um grito. Pode ser sua voz ou outro som que você já tenha ouvido antes, como a voz de outra pessoa, o rugido de um leão ou o barulho de um vaso quebrando. O som continua ininterrupto durante toda a duração ou você pode criar sons discretos em momentos diferentes antes do jutsu terminar.",
    emNiveisSuperiores: "A proficiência deste jutsu aumenta à medida que você sobe de nível. No 5º nível, selecione 1 local adicional para a origem do som. No 11º nível, 2 locais adicionais; no 17º nível, 3 locais adicionais.",
  },
  {
    key: "afeto",
    nome: "Afeto",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Concentração, até 1 Minuto",
    componentes: ["MC"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Pela duração, você tem vantagem em todos os testes de Persuasão dirigidos a uma criatura que você tocar e que não seja hostil em relação a você. Quando o jutsu termina, a criatura pode perceber que você usou um jutsu para influenciar seu humor se isso não condizer com seu relacionamento prévio. Uma criatura propensa à violência pode atacá-lo se perceber isso. Outra criatura pode procurar retaliação de outras formas (a critério do Mestre), dependendo da natureza de suas interações.",
  },
  {
    key: "mudanca-de-voz",
    nome: "Mudança de Voz",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 1,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você reveste sua língua em chakra, manipulando as vibrações que ela emite enquanto fala. Você imita a voz de qualquer criatura que tenha ouvido antes com incrível precisão. As criaturas precisariam realizar ativamente a ação de habilidade Ver através das mentiras para perceber que sua voz é fabricada.",
  },
  {
    key: "tecnica-de-clone",
    nome: "Técnica de Clone",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "A técnica de clone mais básica ensinada na maioria das academias ninja ao redor do mundo ninja. Usando esta técnica, o usuário cria 2 duplicatas de si mesmo. Os clones permanecem próximos a você e desaparecem quando atacados. Os clones aparecem ao lado do usuário e não podem se afastar mais que 5 pés do original. As duplicatas são idênticas ao usuário, mas não podem falar ou realizar qualquer ação que exija um corpo físico, como levantar um objeto ou atacar uma criatura. Quando tocados por outra criatura ou objeto, ou agitados violentamente, os clones desaparecem em uma nuvem de fumaça.\n\nApós a ativação, como reação, você faz com que uma criatura que esteja te atacando role um dado adicional de 1d6, subtraindo o resultado do total do seu teste de ataque. Fazendo isso, um de seus clones é atingido independentemente do ataque errar ou acertar você. Após a duração ou quando ambos os seus clones forem atingidos, este jutsu termina imediatamente. Qualquer criatura que use um jutsu com a palavra-chave Sensorial ou que possa enxergar através de Genjutsu não é afetada por este jutsu.",
    emNiveisSuperiores: "A proficiência deste jutsu aumenta à medida que você sobe de nível. Ao alcançar o 5º nível, crie 3 duplicatas; no 11º nível, 4 duplicatas; no 17º nível, 5 duplicatas.",
  },
  {
    key: "codificar-pensamentos",
    nome: "Codificar Pensamentos",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "8 Horas",
    componentes: ["SM", "MC"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "Você extrai uma memória, uma ideia ou uma mensagem de sua mente e a selam em uma série tangível de selos luminosos chamada de fio de pensamento, que persiste pela duração ou até você conjurar o jutsu novamente. O fio de pensamento aparece em um espaço desocupado em uma superfície de sua escolha, como uma parede, um pergaminho em branco, um livro ou na pele, na forma de texto ou imagens de seus designs de memória.\n\nSe você lançar este Genjutsu enquanto estiver concentrado em um Genjutsu ou habilidade que permita manipular os pensamentos de outros (como Dominação de Memória), você pode transformar o pensamento ou memórias que leu em um fio de pensamento.",
  },
  {
    key: "pensamentos-aprimorados",
    nome: "Pensamentos Aprimorados",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Reação, que você realiza quando falha em um teste de habilidade.",
    alcance: "Próprio",
    duracao: "1 Rodada",
    componentes: ["SM"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu"],
    descricao: "Você concentra chakra em diferentes partes de sua mente para aumentar sua capacidade de processar informações. Quando falha em um teste de habilidade usando um atributo mental (Inteligência ou Sabedoria), você pode adicionar +2 àquele teste falho, potencialmente transformando uma falha em um sucesso. Uma vez que você conjura este jutsu, não pode fazê-lo novamente por 10 minutos.",
    emNiveisSuperiores: "O reforço de habilidade deste jutsu aumenta conforme você sobe de nível. Este bônus aumenta em +2 no 5º nível (+4), 11º nível (+6), 17º nível (+8).",
  },
  {
    key: "duvida",
    nome: "Dúvida",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "1 Minuto",
    componentes: ["SC"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Pela duração, você tem vantagem em todos os testes de Intimidação dirigidos a uma criatura que você tocar e com a qual está interagindo. Quando o jutsu termina, a criatura pode perceber que você usou um jutsu para influenciar seu humor se isso não condizer com seu relacionamento prévio. Uma criatura propensa à violência pode atacá-lo se perceber isso. Outra criatura pode procurar retaliação de outras formas (a critério do Mestre), dependendo da natureza de suas interações.",
  },
  {
    key: "fenda-mental",
    nome: "Fenda Mental",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "1 Rodada",
    componentes: ["SM", "MC"],
    custoChakra: 1,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao: "Você injeta um pico desorientador de chakra na mente de uma criatura que você pode ver dentro do alcance. Faça um ataque de Genjutsu à distância, causando 1d6 de dano psíquico. O alvo também deve ter sucesso em um teste de resistência de Inteligência. Em caso de falha, até o final de seu próximo turno, ele deve rolar um d4 e subtrair o número do primeiro teste de resistência que fizer durante a duração.",
    emNiveisSuperiores: "A proficiência deste jutsu aumenta conforme você sobe de nível, rolando um dado adicional de 1d6 no 5º nível (2d6), 11º nível (3d6), 17º nível (4d6).",
  },
  {
    key: "explosao-de-penas",
    nome: "Explosão de Penas",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Reação, que você realiza quando receberia dano.",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu", "Visual", "Auditivo"],
    descricao: "Uma simples ilusão visual. Quando atingido por um ataque, o oponente vê você explodir em penas negras de corvo que se reformam em sua localização atual. Quando atingido por um ataque corpo a corpo, role 1d8, reduzindo o dano recebido pelo resultado e mova-se 10 pés para longe. Este movimento não provoca ataques de oportunidade.",
    emNiveisSuperiores: "A proficiência deste jutsu aumenta à medida que você sobe de nível, rolando 1d8 no 5º nível (2d8), 11º nível (3d8), 17º nível (4d8).",
  },
  {
    key: "luz",
    nome: "Luz",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "Instantâneo",
    componentes: ["SM", "FN (Fogos de Artifício)"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "Uma mistura de fogos de artifício e Chakra para intensificar o flash que produzem em 10 vezes. Selecione um espaço de até 30 pés de distância. Criaturas dentro de 5 pés desse espaço devem realizar um teste de Sabedoria. Em caso de falha, o próximo ataque direcionado a elas tem vantagem.",
  },
  {
    key: "ilusao-menor",
    nome: "Ilusão Menor",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "1 Minuto",
    componentes: ["SM"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu", "Visual", "Auditivo", "Desapercebido"],
    descricao: "Você cria um som ou uma imagem de um objeto dentro do alcance que dura pela duração. A ilusão também termina se você a dispensar como uma ação ou lançar este genjutsu novamente. Se você criar um som, seu volume pode variar de um sussurro a um grito. Pode ser sua voz, a voz de outra pessoa, o rugido de um leão, batidas de tambores, ou qualquer outro som que você escolher. O som continua ininterrupto durante toda a duração, ou você pode fazer sons discretos em momentos diferentes antes que o jutsu termine. Se você criar a imagem de um objeto — como uma cadeira, pegadas lamacentas, ou um pequeno baú —, ele não pode ser maior que um cubo de 5 pés. A imagem não pode criar som, luz, cheiro, ou qualquer outro efeito sensorial. A interação física com a imagem revela que é uma ilusão, pois as coisas podem passar através dela.\n\nSe uma criatura usar sua ação para examinar o som ou imagem, ela pode determinar que é uma ilusão com um teste bem-sucedido de Inteligência (Investigação) ou Sabedoria (Ilusão) contra o seu valor de CD de salvaguarda do genjutsu. Se uma criatura perceber a ilusão pelo que é, ela se torna tênue para a criatura.",
  },
  {
    key: "mensagem",
    nome: "Mensagem",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação",
    alcance: "120 Pés",
    duracao: "1 rodada",
    componentes: ["SM"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você aponta o dedo para uma criatura dentro do alcance que você pode ver e sussurra uma mensagem. A criatura alvo (e apenas ela) ouve a mensagem e pode responder em sussurros que somente você pode ouvir.\n\nVocê pode lançar este genjutsu através de objetos sólidos se estiver familiarizado com o alvo e souber que ele está além da barreira. Este jutsu não precisa seguir uma linha reta e pode se mover livremente ao redor de cantos ou através de aberturas.",
  },
  {
    key: "transformacao",
    nome: "Transformação",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Concentração, até 10 Minutos",
    componentes: ["SM"],
    custoChakra: 1,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "Esta técnica é ensinada a todos os alunos da academia. Usando esta técnica, o usuário assume a forma de uma criatura, objeto ou animal do mesmo tamanho ou menor. Eles podem livremente designar os detalhes de sua nova forma (como altura, peso, textura e cor do cabelo, tom de pele, etc.). Esta transformação é puramente cosmética e uma ilusão. Quando você usa uma ação de habilidade baseada em Carisma na tentativa de enganar, mentir ou confundir outra criatura, você usa esta nova forma, desde que seja relevante para seu ato, para aprimorar essa mentira com movimentos e gestos convincentes. Se você não estiver se beneficiando do Genjutsu de Mudança de Voz ativo, você ganha apenas metade do bônus a seguir.\n\nEnquanto transformado, quando você usa uma ação de habilidade baseada em Carisma na tentativa de enganar, mentir ou confundir outra criatura, você usa esta nova forma, desde que seja relevante para seu ato, você pode adicionar +4 nos testes feitos. Você pode ganhar este bônus uma vez por rodada, ou uma vez a cada minuto se estiver em combate ou em uma cena social.",
  },
  {
    key: "dor",
    nome: "Dor",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "60 Pés",
    duracao: "Concentração, até 1 Minuto",
    componentes: ["SM"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu", "Tátil"],
    descricao: "Você aponta para uma criatura dentro do alcance e o som de um sino doloroso enche o ar ao redor dela por um momento. Na próxima vez que o alvo sofrer dano, ele sofre um dano psíquico adicional de 1d4. Este jutsu então termina.",
    emNiveisSuperiores: "A eficácia deste jutsu aumenta em um dado quando você alcança o 5º nível (2d4), 11º nível (3d4), 17º nível (4d4).",
  },
  {
    key: "liberacao",
    nome: "Liberação",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu", "Fuinjutsu"],
    descricao: "Esta técnica permite ao usuário isolar e remover à força o efeito de um único Genjutsu, desde que possa ser dissipado. Você deve primeiro estar ciente de que você ou seu alvo está sob o efeito de um Genjutsu. Como parte da ativação deste jutsu, faça um teste de Ilusão com vantagem contra o CD de salvaguarda do Genjutsu. Em caso de sucesso, você liberta você mesmo ou seu alvo do Genjutsu.",
  },
  {
    key: "acerto-certo",
    nome: "Acerto Certo",
    tipo: "genjutsu",
    rank: "E",
    tempoConjuracao: "1 Reação, que você toma quando erra um ataque contra uma criatura que você alvejou com um rolagem de ataque.",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 2,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "Você concentra seu genjutsu em uma única criatura dentro do alcance. Seu genjutsu concede a você uma breve visão das defesas do alvo. Você ganha um bônus de +2 na rolagem de ataque que desencadeou isso, potencialmente transformando um erro em um acerto. Você pode obter o benefício deste jutsu uma vez por rodada.",
    emNiveisSuperiores: "O bônus deste jutsu aumenta em +1 quando você alcança o 5º nível (+3), 11º nível (+4), 17º nível (+5).",
  },

  // ===== RANK D (52 entries) =====
  {
    key: "causar-medo",
    nome: "Causar Medo",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "Concentração, até 1 Minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Inalação"],
    descricao: "Você desperta um sentido de mortalidade em uma criatura que você pode ver dentro do alcance após liberar alguns aromas potentes de incenso que você espalha e usa como catalisador para seu genjutsu. Construtos ou mortos-vivos são imunes a este efeito. O alvo deve fazer um teste de resistência de Sabedoria no início de cada um de seus turnos durante a duração.\n\nSucesso Crítico: Este jutsu termina nas criaturas afetadas, removendo todas as categorias de medo concedidas por este jutsu.\nSucesso: A criatura afetada não ganha uma categoria de medo.\nFalha: As criaturas afetadas ganham uma categoria de medo contra o conjurador até que este jutsu termine.\nFalha Crítica: As criaturas afetadas ganham duas categorias de medo contra o conjurador até que este jutsu termine e caem prostradas pelo choque.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e selecione 1 criatura adicional que deve estar a 30 pés uma da outra quando você as alvejar.",
  },
  {
    key: "companheiro-animal",
    nome: "Companheiro Animal",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "Concentração, até 10 Minutos",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você seleciona um animal que pode ver dentro do alcance e altera sua disposição em relação a você. Este animal o verá como um membro de sua matilha, seu filhote, seu pai ou sua mãe (à sua escolha). O animal será capaz de entender seus comandos e agirá de acordo com eles durante a duração. A criatura alvo deve fazer um teste de Carisma, ficando encantada por você durante a duração. O animal pode lutar em seu nome, uma vez que a criatura atinja metade de sua saúde, este jutsu termina. Eles podem então permanecer e lutar para sobreviver ou fugir, dependendo do tipo de animal que são (descrição do DM).",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e selecione um animal adicional que você pode ver.",
  },
  {
    key: "praga",
    nome: "Praga",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (30 Pés)",
    duracao: "Concentração, até 1 Minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Tátil"],
    descricao: "Você libera um pulso de chakra que visa todas as criaturas hostis dentro de 30 pés de você, fazendo com que sintam um profundo arrependimento ou medo. Todas as criaturas hostis de sua escolha dentro de 30 pés de você devem fazer um teste de resistência de Carisma, pois suas mentes são invadidas por pensamentos negativos.\n\nSucesso: Sem efeitos adicionais.\nFalha: As criaturas afetadas sofrem uma penalidade de 1d4 em todas as rolagens de ataque, testes de resistência e testes que elas fazem durante a duração.\nFalha Crítica: As criaturas afetadas sofrem uma penalidade de 1d6 em todas as rolagens de ataque, testes de resistência e testes de habilidade que elas fazem, e não podem obter o benefício de jutsus que fornecem bônus para elas do mesmo rank ou inferior durante a duração.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e o raio em 10 pés. Se conjurado no Rank B, o dado aumenta um passo. Se conjurado no Rank S, o dado aumenta dois passos.",
  },
  {
    key: "cor-saliente",
    nome: "Cor Saliente",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (cone de 15 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "Você manifesta uma deslumbrante variedade de luzes coloridas e cintilantes que surgem de sua mão. Criaturas em um cone de 15 pés, originado de você, devem fazer um teste de resistência de Inteligência.\n\nSucesso Crítico: A criatura ignora os efeitos deste jutsu.\nSucesso: A criatura afetada fica Deslumbrado.\nFalha: As criaturas afetadas ficam Cegas até o final de seu próximo turno.\nFalha Crítica: As criaturas afetadas ficam cegas e devem fazer novamente o teste de resistência de Inteligência ao final de cada um de seus turnos para perceber que na verdade não estão cegas, encerrando os efeitos deste jutsu sobre elas.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e o tamanho do cone em 10 pés.",
  },
  {
    key: "dissonancia-encantadora",
    nome: "Dissonância Encantadora",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você tenta suprimir emoções fortes em até 3 criaturas que podem ver e ouvir você dentro do alcance. Você fala com confiança reverberante que aplaca seus medos, raiva e confusão. Até 3 criaturas que você escolher devem fazer um teste de resistência de Carisma; uma criatura pode optar por falhar neste teste de resistência, se desejar. Se uma criatura falhar em seu teste de resistência, escolha um dos seguintes efeitos:\n\nVocê pode suprimir qualquer efeito que esteja fazendo com que o alvo seja encantado ou amedrontado. Quando este jutsu terminar, qualquer efeito suprimido é retomado, desde que sua duração não tenha expirado nesse meio tempo.\n\nAlternativamente, você pode fazer um alvo ficar indiferente em relação às criaturas de sua escolha contra as quais ele está hostil. Esta indiferença termina se o alvo ou seus aliados forem atacados. Quando este jutsu terminar, a criatura se torna hostil novamente.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e selecione uma criatura adicional.",
  },
  {
    key: "manto-de-sombras",
    nome: "Manto de Sombras",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual", "Inconsciente"],
    descricao: "Você envolve uma criatura voluntária que toca em trevas ilusórias, concedendo um bônus de +1d4 a tentativas de Esconder-se ou Furtividade contra criaturas que dependem da visão durante a duração. Além disso, se conjurado em Luz Fraca ou Escuridão, criaturas que tentam uma ação Identificar Genjutsu fazem sua verificação com desvantagem.",
    emNiveisSuperiores: 'Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3. Se conjurado no Rank B, a duração aumenta para "até 10 minutos" e não requer mais chakra para manter a concentração. Se conjurado no Rank A, a duração deste jutsu se torna 1 hora e não requer mais concentração.',
  },
  {
    key: "duelo-compelido",
    nome: "Duelo Compelido",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Visual"],
    descricao: "Você tenta compelir uma criatura a um duelo. Ela vê você como o único adversário digno na área e fará tudo o que puder para lutar apenas contra você, tornando-se indiferente a outros combatentes. Uma criatura que você pode ver deve fazer um teste de resistência de Sabedoria.\n\nSucesso: A criatura afetada ignora este jutsu e não sofre efeitos.\nFalha: A criatura afetada sente-se atraída por você, sofrendo uma penalidade de -1d6 em todos os rolagens de ataque contra criaturas que não sejam você durante a duração. Uma criatura compelida deve refazer seu teste de resistência no final de cada um de seus turnos para encerrar este efeito sobre ela. Este jutsu termina se você atacar qualquer outra criatura ou se uma criatura amigável a você ajudar você de qualquer maneira.\nFalha Crítica: As criaturas afetadas sentem-se atraídas por você, incapazes de alvejar qualquer outra criatura além de você durante a duração. Este jutsu termina se você atacar qualquer outra criatura ou se uma criatura amigável a você ajudar você.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e o raio da zona que estendem em um+2.",
  },
  {
    // Nota: o texto-fonte diz "Rank C" neste bloco de Em Níveis Superiores, provavelmente um erro de digitação do livro para "Rank D" (o próprio jutsu é Rank D). Transcrito como impresso.
    key: "comando",
    nome: "Comando",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "1 Round",
    componentes: ["MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você profere um comando de uma palavra para uma criatura que você pode ver dentro do alcance. O alvo deve fazer um teste de resistência de Sabedoria ou seguir o comando em seu próximo turno. Este jutsu não tem efeito se o alvo for um morto-vivo, se não entender seu idioma ou se seu comando for diretamente prejudicial a ele. Alguns comandos típicos e seus efeitos seguem. Você pode dar um comando diferente do descrito aqui. Se fizer isso, o Mestre determina como o alvo se comporta. Se o alvo não puder seguir seu comando, o jutsu termina.\n\nAproximar: O alvo se move em sua direção pela rota mais curta e direta, encerrando seu turno se se mover a 5 pés de você.\nSoltar: A criatura solta o que estiver segurando e depois encerra seu turno.\nProstrar-se: O alvo cai prostrado e depois encerra seu turno.\nFugir: O alvo vira-se e gasta seu turno movendo-se para longe de você da maneira mais rápida disponível.\nParar: O alvo não se move ou realiza ações. Uma criatura voadora permanece no ar, desde que seja capaz de fazê-lo. Se precisar se mover para permanecer no ar, ela voa a distância mínima necessária para permanecer no ar.",
    emNiveisSuperiores: "Para cada rank acima do Rank C que você conjura este jutsu, aumente o custo deste jutsu em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    // Nota: a frase final do texto-fonte ("você ganha acesso a +3") está truncada/vaga no original; transcrita como impressa.
    key: "compreender-idiomas",
    nome: "Compreender Idiomas",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Auto",
    duracao: "1 Hora",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Pela duração, você compreende o significado literal de qualquer linguagem falada que você ouve. Você também entende qualquer linguagem escrita que você vê, mas você deve estar tocando uma criatura que já pode entender a linguagem.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3. Se este jutsu é conjurado no Rank B, você ganha acesso a +3.",
  },
  {
    // Nota: o Em Níveis Superiores está corrompido no OCR-fonte (":ste jutsu, aumente..."); reconstruído usando a frase-padrão repetida na série "Corrupção".
    key: "corrupcao-asperidade",
    nome: "Corrupção: Asperidade",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando injetar um senso de aspereza em aliados, nos seus inimigos. Selecione uma criatura que você pode ver dentro do alcance, forçando-a a fazer um teste de resistência de Carisma.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: Se a criatura afetada conjurar um jutsu que permita omitir ou excluir seus aliados, para cada criatura hostil que eles selecionarem, eles também devem escolher um aliado como alvo, mesmo que tenham um número limitado de alvos que podem selecionar; o aliado escolhido conta como uma de suas escolhas. Uma vez que este efeito ocorra, este jutsu termina.\nFalha Crítica: O mesmo que falha, mas este efeito dura pela duração.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "confianca",
    nome: "Confiança",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você seleciona até três criaturas dispostas dentro do alcance, que você pode ver, reforçando sua confiança em si mesmas, permitindo que elas ajam com pouco ou nenhuma hesitação. Pela duração, sempre que uma criatura alvo faz um teste de habilidade, ela adiciona +2 ao resultado. A primeira vez que ela acertar em um teste de habilidade, este jutsu termina.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3. Se este jutsu for conjurado no Rank B, este bônus se torna um +3. Se este jutsu for conjurado no Rank S, este bônus se torna um +4.",
  },
  {
    key: "corrupcao-animus",
    nome: "Corrupção: Animus",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando desabilitar mentalmente a confiança e as forças de seus inimigos. Selecione uma criatura que você pode ver dentro do alcance, forçando-a a fazer um teste de resistência de Carisma.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: Criaturas afetadas que receberiam bônus baseados em dados como resultado de características ou traços em seus rolagens de ataque ou dano, em vez disso, tratam esses bônus como penalidades durante a duração.\nFalha Crítica: O mesmo que falha, mas essa inversão também se estende aos bônus baseados em jutsu.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "corrupcao-distancia",
    nome: "Corrupção: Distância",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando corromper mentalmente o sentimento de felicidade e estabilidade em seus inimigos. Selecione uma criatura que você pode ver dentro do alcance, forçando-a a fazer um teste de resistência de Carisma.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: Criaturas afetadas que tentarem conjurar um jutsu como uma reação, para interromper a conjuração de outro jutsu, devem rolar um d20. Em um resultado de 11 ou mais, elas perdem sua reação, incapazes de interromper seu alvo original.\nFalha Crítica: O mesmo que falha, mas em um resultado de 6 ou mais elas perdem sua reação, incapazes de interromper seu alvo original.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "corrupcao-audacia",
    nome: "Corrupção: Audácia",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando injetar um sentido de severidade em aliados, contra seus inimigos. Selecione uma criatura que você pode ver dentro do alcance, forçando-a a fazer um teste de resistência de Carisma.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: Criaturas que tentarem realizar um ataque de qualquer tipo contra uma criatura com quem você é aliado, a criatura afetada é mentalmente forçada a conter a força do ataque, reduzindo o dano causado por 1 dado de dano, com um mínimo de 1 dado de dano.\nFalha Crítica: O mesmo que falha, mas a redução no dado de dano é aumentada para 2.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3. Se este jutsu for conjurado no Rank B, aumente a redução do dado de dano em 1. Se este jutsu for conjurado no Rank S, aumente a redução do dado de dano em 2.",
  },
  {
    key: "corrupcao-desdem",
    nome: "Corrupção: Desdém",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando injetar um senso de impudência em seus inimigos. Selecione uma criatura que você pode ver dentro do alcance, forçando-a a fazer um teste de resistência de Carisma.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: Criaturas afetadas não podem aumentar o nível de seus jutsus durante a duração. Se tentarem fazê-lo, ainda gastam o chakra, mas os efeitos permanecem no nível base.\nFalha Crítica: O mesmo que falha, mas a criatura afetada deve tentar aumentar o nível de seus jutsus para o maior nível possível, gastando o chakra normalmente, mas os efeitos permanecem no nível base.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "corrupcao-inimizade",
    nome: "Corrupção: Inimizade",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Genjutsu", "Visual", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando injetar um senso de moral quebrada e desconfiança em seus inimigos. Selecione uma criatura que você pode ver dentro do alcance, forçando-a a fazer um teste de resistência de Carisma.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: Criaturas afetadas cujo aliado está conjurando um jutsu devem gastar sua reação para tentar interromper a conjuração de seus aliados. Uma vez que tentem interromper a conjuração, este jutsu termina.\nFalha Crítica: O mesmo que falha, mas a criatura afetada deve gastar sua reação para tentar interromper todas as conjurações de jutsu de seus aliados, se possível, pelo resto da duração.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    // Nota: o texto-fonte rotula este bloco "Em Níveis Mais Altos" (em vez de "Em Níveis Superiores", como no resto da série).
    key: "corrupcao-temeridade",
    nome: "Corrupção: Temeridade",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "Você coleta e constrói chakra ilusório, tentando suprimir a audácia deles em combate. Selecione uma criatura que você pode ver dentro do alcance, forçando-a a fazer um teste de resistência de Carisma.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a novas conjurações deste jutsu até o final do próximo turno do conjurador.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: A criatura afetada perde o benefício dos bônus baseados em jutsu de velocidade, tornando-se incapaz de se beneficiar deles durante a duração. A criatura afetada refaz seu teste de resistência no final de cada um de seus turnos.\nFalha Crítica: O mesmo que falha, mas isso também se estende às classes e características de classe.",
    emNiveisSuperiores: "Para cada nível que você conjura este jutsu acima do Nível D, aumente o custo deste jutsu em 3 e o número de criaturas que você pode afetar em +1.",
  },
  {
    key: "corrupcao-insolencia",
    nome: "Corrupção: Insolência",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando injetar uma sensação de aspereza em relação aos aliados, em seus inimigos. Selecione uma criatura que você possa ver dentro do alcance, forçando-a a fazer um teste de resistência de Carisma.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: Criaturas sob o efeito de um Genjutsu, que concede um bônus baseado em dados, têm este bônus reduzido pela metade.\nFalha Crítica: Criaturas sob o efeito de um Genjutsu, que concede um bônus baseado em dados, não podem se beneficiar deste bônus durante a duração.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "corrupcao-despejo",
    nome: "Corrupção: Despejo",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você coleta e constrói chakra ilusório, tentando desabilitar mentalmente as forças físicas de seus inimigos. Selecione uma criatura que você pode ver dentro do alcance, forçando-a a fazer um teste de resistência de Carisma.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: Criaturas afetadas sofrem uma penalidade de -2 em todos os ataques baseados em Força e rolagens de dano.\nFalha Crítica: O mesmo que falha, mas a penalidade é reduzida em mais -2.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e a penalidade em -1 adicional.",
  },
  {
    key: "detectar-ilusoes",
    nome: "Detectar Ilusões",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (Raio de 10 pés)",
    duracao: "10 minutos",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "Durante a duração, você pode sentir a presença de Genjutsu de Rank D ou inferior dentro de 10 pés de você. Se você detectar Genjutsu dessa forma, você pode usar sua ação para ver uma aura fraca ao redor de qualquer criatura ou objeto visível na área que esteja afetado por um Genjutsu.\n\nAlém disso, se um Genjutsu afetar uma área, a área afetada brilhará com esta aura em vez de quaisquer criaturas ou objetos individuais. Este jutsu não pode penetrar barreiras, paredes ou superfícies e não fornece informações sobre o Rank ou o número de Genjutsu afetando uma criatura.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e o rank de Genjutsu que você pode detectar.",
  },
  {
    key: "corrupcao-vil",
    nome: "Corrupção: Vil",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você coleta e constrói chakra ilusório, tentando desabilitar mentalmente a flexibilidade física de seus inimigos. Selecione uma criatura que você pode ver dentro do alcance, forçando-a a fazer um teste de resistência de Carisma.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: Criaturas afetadas sofrem uma penalidade de -2 em todos os ataques e rolagens de dano baseados em Destreza.\nFalha Crítica: O mesmo que falha, mas a penalidade é reduzida em mais -2.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e a penalidade em -1 adicional.",
  },
  {
    key: "detectar-o-mal",
    nome: "Detectar o Mal",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "10 minutos",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual", "Sensorial"],
    descricao: "Durante a duração, você sabe se há alguém dentro de 60 pés de você com intenção hostil. Você não sabe sua localização exata, apenas que estão dentro do alcance deste genjutsu.",
  },
  {
    key: "distorcao-de-valor",
    nome: "Distorção de Valor",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "10 Minutos",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Inconsciente"],
    descricao: "Ao lançar este Genjutsu, alvo um objeto com no máximo 1 pé de lado, dobrando o valor percebido do objeto adicionando um floreio ilusório ou reduzindo seu valor percebido pela metade com a ajuda de amassados ou arranhões ilusórios. Qualquer um que examine o objeto deve rolar uma investigação ou um teste de Ilusões contra o seu CD de resistência de Genjutsu para ver através deste Genjutsu.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e o tamanho do objeto em 5.",
  },
  {
    key: "detectar-intencao",
    nome: "Detectar Intenção",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Genjutsu", "Visual", "Sensorial"],
    descricao: "Selecione uma criatura que você pode ver dentro do alcance. Se o alvo não estiver ciente de sua presença, role sua perícia em Ilusão contra sua Enganação passiva. Em caso de sucesso, você sabe qual é a intenção imediata mais evidente da criatura.\n\nIsso não explica por que eles estão tentando fazer o que estão tentando fazer, apenas o que eles querem fazer. Se o alvo estiver ciente de sua presença, eles fazem um teste de resistência de Sabedoria. Em caso de falha, você obtém as mesmas informações que obteria se eles não estivessem cientes de sua presença. Em caso de sucesso, eles podem ocultar sua intenção, escondendo-a por trás de outra série de intenções.",
  },
  {
    key: "palavras-distantes",
    nome: "Palavras Distantes",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Minuto",
    alcance: "30 Pés",
    duracao: "Até ser dissipado",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você implanta uma mensagem dentro de um objeto no alcance, uma mensagem que é proferida quando uma condição desencadeante é atendida. Escolha um objeto que você possa ver e que não esteja sendo usado ou carregado por outra criatura. Em seguida, fale a mensagem, que deve ter 25 palavras ou menos, embora possa ser entregue ao longo de até 10 minutos. Finalmente, determine a circunstância que acionará o jutsu para entregar sua mensagem. Quando essa circunstância ocorre, uma voz desencarnada pode ser ouvida originando-se do objeto e recitando a mensagem em sua voz e no mesmo volume em que você falou.\n\nQuando você conjura este jutsu, você pode fazer com que ele termine após entregar sua mensagem, ou ele pode permanecer e repetir sua mensagem sempre que o gatilho ocorrer.\n\nA circunstância desencadeadora pode ser tão geral ou detalhada quanto você desejar, embora deva ser baseada em condições visuais ou auditivas que ocorrem dentro de 30 pés do objeto. Por exemplo, você poderia instruir a ilusão a falar quando qualquer criatura se mover dentro de 30 pés do objeto ou quando um sino de prata tocar dentro de 30 pés dele.",
  },
  {
    key: "dor-duplicada",
    nome: "Dor Duplicada",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação de Bônus",
    alcance: "60 Pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Tátil"],
    descricao: "Você mira em uma criatura e amplifica seu sistema nervoso, aumentando todas as instâncias de dor para um grau massivo. Selecione uma criatura alvo que você possa ver dentro do alcance. Durante a duração, sempre que você causar dano usando um Genjutsu, você causa dano psíquico adicional de 1d8.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3 e selecione uma criatura adicional para ser afetada.",
  },
  {
    key: "extra-sensorial",
    nome: "Extra Sensorial",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Visual", "Inalação", "Tátil"],
    descricao: "Você manifesta uma série de sensações supersensoriais destinadas a sobrecarregar os sentidos de uma criatura. Escolha uma criatura dentro do alcance. A criatura escolhida deve fazer um teste de resistência de Inteligência.\n\nSucesso Crítico: A criatura afetada consegue resistir aos efeitos deste jutsu.\nSucesso: A criatura afetada sofre uma penalidade de 1d4 no seu próximo teste de ataque.\nFalha: A criatura afetada recebe 2 níveis de Ofuscado.\nFalha Crítica: A criatura afetada recebe 2 níveis de Ofuscado e, no início do próximo turno dela, deve rolar um d10. Em um resultado de 1 ou 2, ela se retrai e perde sua Ação.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "afinidade-ambiental",
    nome: "Afinidade Ambiental",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal",
    duracao: "Especial",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "O ambiente parece se mover e girar ao seu redor. Durante a duração deste jutsu, criaturas que olham para você veem o terreno natural se movendo ao seu bel-prazer, fazendo-as hesitar.\n\nSe lançado enquanto você não está em combate, este jutsu dura 1 hora. Durante essa duração, você faz seu próximo teste de iniciativa com vantagem.\n\nSe lançado durante o combate, a duração deste jutsu se torna Concentração, até 1 minuto, e criaturas que te atacam com um ataque ou jutsu te tratam como se você estivesse em meia cobertura.\n\nSe o terreno não for natural e sim industrial, como um corredor de concreto, pisos de aço, ou algo semelhante, uma criatura faz um teste de Sabedoria (Ilusões) com vantagem contra seu CD de resistência de Genjutsu, ganhando imunidade a este jutsu durante a duração.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjura este jutsu, aumente o custo deste jutsu em 3. Quando lançado no Rank B, este jutsu não requer mais concentração.",
  },
  {
    key: "frenesi-azul",
    nome: "Frenesi: Azul",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "45 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando induzir um acesso de loucura depressiva que faz seus olhos brilharem de azul. Escolha uma criatura que você esteja ciente e que possa ouvi-lo dentro do alcance, forçando-a a fazer um teste de resistência de Sabedoria.\n\nSucesso Crítico: A criatura afetada consegue resistir ao efeito deste jutsu e se torna imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: Se a criatura afetada precisar fazer um teste de resistência durante a duração, em caso de falha, após sofrer os efeitos do jutsu desencadeador, ela cai prostrada e tem sua velocidade de movimento reduzida pela metade até o final do seu próximo turno. As criaturas refazem seu teste de resistência contra este jutsu no final de cada um de seus turnos.\nFalha Crítica: Semelhante à falha, mas a velocidade da criatura é reduzida a 0.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "frenesi-negro",
    nome: "Frenesi: Negro",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você coleta e constrói chakra ilusório, tentando apagar os pensamentos de seus alvos, tornando difícil para eles formar pensamentos coerentes ou administráveis. Escolha uma criatura que você esteja ciente e que possa ouvi-lo dentro do alcance, forçando-a a fazer um teste de resistência de Sabedoria.\n\nSucesso Crítico: A criatura afetada consegue resistir ao efeito deste jutsu e se torna imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada consegue resistir à maioria dos efeitos deste jutsu.\nFalha: A criatura afetada começa a sofrer apagões mentais. No início de cada um dos seus turnos, ela deve fazer uma verificação de habilidade de Sabedoria contra CD 13. Em uma verificação falha, todas as criaturas na iniciativa do turno são tratadas como hostis para ela, e ela não pode excluir criaturas na área de efeito de um jutsu ou efeitos de habilidades. No final de cada um dos seus turnos, ela refaz seu teste de resistência, encerrando o efeito deste jutsu sobre ela em caso de sucesso.\nFalha Crítica: Semelhante à falha, mas o CD da verificação de habilidade é aumentado para CD 16.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "frenesi-verde",
    nome: "Frenesi: Verde",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando infundir um alvo dentro do alcance com um aspecto da sua loucura, fazendo com que seus olhos brilhem de verde. Escolha uma criatura que você esteja ciente e que possa ouvi-lo dentro do alcance, forçando-a a fazer um teste de resistência de Sabedoria.\n\nSucesso Crítico: A criatura afetada consegue resistir ao efeito deste jutsu e se torna imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada consegue resistir à maioria dos efeitos deste jutsu, apenas sofrendo de concussão até o final do próximo turno.\nFalha: A criatura afetada sucumbe ao seu aspecto de loucura. Durante a duração, se ela tentar conjurar um Jutsu com tempo de conjuração como Ação Bônus, ela deve rolar um d4. Em um resultado de 1 ou 2, ela falha em conjurá-lo, perdendo o foco com murmúrios constantes. Em um resultado de 3 ou 4, ela conjura normalmente e refaz seu teste de resistência para encerrar os efeitos deste jutsu, permanecendo ainda inconsciente de estar sob o efeito deste Genjutsu.\nFalha Crítica: Semelhante à falha, mas agora ela deve rolar um d6 e só conseguirá conjurar normalmente com um resultado de 5 ou 6.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "frenesi-ciano",
    nome: "Frenesi: Ciano",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés (cubo de 20 pés)",
    duracao: "1 Rodada",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você coleta e constrói chakra ilusório, tentando induzir um acesso de loucura instável destinado a quebrar as mentes das criaturas na área afetada, enquanto seus olhos piscam com uma cor ciano. Escolha uma criatura que você esteja ciente e que possa ouvi-lo dentro do alcance, forçando-a a fazer um teste de resistência de Sabedoria.\n\nSucesso Crítico: A criatura afetada consegue resistir ao efeito deste jutsu e se torna imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: Se a criatura afetada tentar realizar uma ação ou ação bônus, ela deve fazer um teste de habilidade de Sabedoria contra CD 13. Em caso de falha, ela fica parada rindo maniacamente, desperdiçando a ação tentada. Em caso de sucesso, ela pode realizar suas ações normalmente. Este efeito termina ao final do turno da criatura afetada.\nFalha Crítica: Semelhante à falha, mas o CD do teste de habilidade é aumentado para 16.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3 e o tamanho do cubo em 5 pés.",
  },
  {
    key: "frenesi-laranja",
    nome: "Frenesi: Laranja",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você coleta e constrói chakra ilusório, tentando induzir um acesso de insanidade calma, fazendo com que os olhos da criatura pisquem na cor laranja. Escolha uma criatura que você esteja ciente e que possa ouvi-lo dentro do alcance, forçando-a a fazer um teste de resistência de Sabedoria.\n\nSucesso Crítico: A criatura afetada consegue resistir ao efeito deste jutsu e se torna imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada deve gastar sua ação bônus em cada um de seus turnos calmamente, mas de maneira prejudicial, arranhando seus braços e causando ferimentos, que infligem 1d8 + o modificador de Força do alvo de dano cortante. Em seguida, ela refaz seu teste de resistência contra este jutsu, encerrando-o em caso de sucesso no teste.\nFalha Crítica: Semelhante à falha, mas agora a criatura deve gastar sua ação principal, não a ação bônus, e causa 2d6 + o modificador de Força do alvo de dano cortante.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3, o número de criaturas que você pode alvejar em +1, e o dano crítico em 1d6.",
  },
  {
    key: "frenesi-magenta",
    nome: "Frenesi: Magenta",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando desencadear uma espiral de insanidade luxuriosa, fazendo com que os olhos da criatura brilhem com uma cor Magenta. Escolha uma criatura que você esteja ciente e que possa ouvi-lo dentro do alcance, forçando-a a fazer um teste de resistência de Sabedoria.\n\nSucesso Crítico: A criatura afetada consegue resistir ao efeito deste jutsu e se torna imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: Quando a criatura afetada tenta conjurar um jutsu ou realizar um ataque contra outra criatura, ela deve fazer um teste de habilidade de Sabedoria contra CD 13. Em caso de falha, ela ganha 3 níveis de Encanto contra aquela criatura durante a duração.\nFalha Crítica: Semelhante à falha, mas o CD do teste de habilidade é aumentado para 16.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "frenesi-vermelho",
    nome: "Frenesi: Vermelho",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando induzir um acesso de raiva e fúria em uma criatura, fazendo com que seus olhos brilhem de vermelho. Escolha uma criatura que você esteja ciente e que possa ouvi-lo dentro do alcance, forçando-a a fazer um teste de resistência de Sabedoria.\n\nSucesso Crítico: A criatura afetada consegue resistir ao efeito deste jutsu e se torna imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada consegue resistir à maioria dos efeitos deste jutsu.\nFalha: A criatura afetada ganha uma classificação de Berserk.\nFalha Crítica: A criatura afetada ganha uma classificação de Berserk que não é perdida no final do seu turno. Em vez disso, ela deve fazer um teste de resistência de sabedoria no final do seu turno, encerrando esta condição em um sucesso.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "frenesi-roxo",
    nome: "Frenesi: Roxo",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "45 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando tocar a loucura que se acumula profundamente na psique de seus inimigos, fazendo com que seus olhos brilhem de roxo. Escolha uma criatura que você esteja ciente e que possa ouvi-lo dentro do alcance, forçando-a a fazer um teste de resistência de Sabedoria.\n\nSucesso Crítico: A criatura afetada consegue resistir ao efeito deste jutsu e se torna imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada consegue resistir aos efeitos secundários deste jutsu.\nFalha: A criatura afetada cai em uma loucura momentânea. Na próxima vez que ela tentar conjurar um jutsu que cause dano, ela deve escolher uma criatura que considere aliada como alvo, antes do final do seu próximo turno.\nFalha Crítica: Semelhante à falha, mas também deve conjurar um jutsu de pelo menos Rank C em seu próximo turno, se tiver acesso a um jutsu desse nível. Se só tiver acesso a jutsus de Rank D, ela deve conjurar um desses.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o número de criaturas que você pode atingir em +1.",
  },
  {
    key: "frenesi-amarelo",
    nome: "Frenesi: Amarelo",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Inconsciente"],
    descricao: "Você coleta e constrói chakra ilusório, tentando induzir um acesso de insanidade enquanto os olhos da criatura piscam num amarelo dourado. Escolha uma criatura que você esteja ciente e que possa ouvi-lo dentro do alcance, forçando-a a fazer um teste de resistência de Sabedoria.\n\nSucesso Crítico: A criatura afetada consegue resistir ao efeito deste jutsu e se torna imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: Se a criatura afetada fizer um ataque em seu próximo turno, ela ganha uma ação adicional, que deve ser usada para fazer um ataque adicional usando a mesma habilidade, ação ou jutsu. Se o jutsu deveria terminar após o primeiro ataque original, ele não termina até que este ataque adicional seja feito. Este ataque adicional deve ser direcionado a um de seus aliados dentro do alcance do ataque, jutsu ou habilidade. Este efeito termina imediatamente se ela não fizer nenhum ataque no turno seguinte à conjuração deste jutsu.\nFalha Crítica: Semelhante à falha, mas ela deve realizar tanto o ataque original quanto o adicional, direcionando o ataque a uma criatura aliada.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "frenesi-prata",
    nome: "Frenesi: Prata",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você coleta e constrói chakra ilusório, tentando infligir um acesso de psicose distorcida, fazendo seus olhos brilharem prateados. Escolha uma criatura que você esteja ciente e que possa ouvi-lo dentro do alcance, forçando-a a fazer um teste de resistência de Sabedoria.\n\nSucesso Crítico: A criatura afetada consegue resistir ao efeito deste jutsu e se torna imune a novas conjurações deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada encontra difícil manter o foco em qualquer coisa se ela sofrer dano. Durante a duração, ela falha automaticamente em seu teste de concentração quando sofrer dano.\nFalha Crítica: Semelhante à falha, mas quando ela perder a concentração de um jutsu enquanto sob os efeitos deste jutsu, ela sofre 2d6 de dano psíquico para cada jutsu do qual perdeu a concentração.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3, o número de criaturas que você pode alvejar em +1, e o dano crítico em 1d6.",
  },
  {
    key: "hipnose",
    nome: "Hipnose",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Inconsciente"],
    descricao: "Você manifesta uma coleção de lã de carneiro na forma de pólen enquanto tenta induzir um sono profundo em uma criatura. Escolha uma criatura que você possa ver dentro do alcance. O alvo deve fazer um teste de resistência de Sabedoria. Uma criatura que está atualmente em combate é imune aos efeitos deste jutsu.\n\nSucesso Crítico: A criatura afetada consegue resistir aos efeitos deste jutsu.\nSucesso: A criatura afetada fica lenta até o final do próximo turno, pois está apenas um pouco sonolenta.\nFalha: A criatura afetada começa a sonhar acordada. Ela fica cega e surda para todos os eventos e acontecimentos que estão a mais de 10 pés de distância dela. Qualquer coisa que a afete ou a área dentro de 10 pés dela quebre esse estado de devaneio.\nFalha Crítica: A criatura afetada adormece, ficando inconsciente pelos próximos 10 minutos. Uma criatura que está adormecida dessa forma pode ser acordada por gritos, gritos, sons altos ou sendo fisicamente sacudida ou sofrendo qualquer tipo de dano.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "lingua-do-encantamento",
    nome: "Língua do Encantamento",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Concentração, até 10 minutos",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Uma criatura voluntária que você toca é aprimorada com um Genjutsu que faz com que as palavras que eles falam pareçam mais interessantes, atraentes ou convincentes. Durante a duração, a criatura afetada tem vantagem em todos os testes baseados em Carisma usando habilidades para conversar com outra criatura. Quando uma criatura que acha essa pessoa minimamente atraente ouve-a falar, ela deve fazer um teste de resistência de Carisma. Em caso de falha, a criatura ganha 1 nível de charme contra ela durante a duração.",
  },
  {
    key: "heroismo",
    nome: "Heroísmo",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Uma criatura voluntária que você toca é imbuída com bravura heroica. Até que o genjutsu termine, a criatura fica imune à condição de medo e ganha pontos de vida temporários iguais ao dobro do seu modificador de habilidade de Genjutsu no início de cada um de seus turnos. Quando o Genjutsu termina, o alvo perde quaisquer pontos de vida temporários restantes.",
    emNiveisSuperiores: "Para cada rank acima de Rank D com que você conjure este jutsu, aumente o custo em 3 e o número de criaturas afetadas por este jutsu em 1.",
  },
  {
    key: "silencio-imperfeito",
    nome: "Silêncio Imperfeito",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés (Esfera de 15 pés de raio)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Desapercebido"],
    descricao: "Selecione um espaço que você possa ver em um raio de 60 pés. Todas as criaturas dentro e tentando entrar em uma esfera de 30 pés centrada no seu espaço selecionado devem fazer um teste de resistência de Inteligência.\n\nSucesso: A criatura afetada é capaz de resistir ao efeito deste jutsu e pode ouvir outras criaturas dentro do raio da esfera.\nFalha: As criaturas afetadas ficam ensurdecidas e não podem ouvir outras criaturas que também estejam dentro do raio da esfera. Se uma criatura afetada sair do raio, este efeito do jutsu termina para ela.\nFalha Crítica: As criaturas afetadas ficam ensurdecidas pela duração. Uma criatura ensurdecida deve refazer seu teste de resistência de Inteligência no final de cada um de seus turnos para encerrar o efeito deste jutsu sobre si mesma.",
  },
  {
    key: "reforco-ilusorio",
    nome: "Reforço Ilusório",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando uma criatura aliada faz um teste de ataque ou resistência.",
    alcance: "30 Pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao: "Você manifesta um futuro possível e o mostra ao seu aliado, dando-lhes a chance de agarrar esse futuro pelos chifres. Quando uma criatura aliada faz um teste de ataque ou resistência, você também rola 1d20. A criatura aliada pode escolher usar o resultado do seu d20 ou o próprio.",
  },
  {
    key: "script-ilusorio",
    nome: "Script Ilusório",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Permanente",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 3,
    palavrasChave: ["Genjutsu", "Fuinjutsu", "Visual"],
    descricao: "Você pega um Selo de Chakra e escreve nele enquanto infunde seu chakra no pergaminho. Durante a duração, você e quaisquer criaturas que você designar no momento da conjuração do jutsu podem ver a escrita como deveria ser. Para todos os outros, a escrita aparece como se estivesse escrita em um script desconhecido ou estrangeiro que é incompreensível. Alternativamente, você pode fazer com que a escrita pareça ser uma mensagem completamente diferente, escrita em uma língua e em uma caligrafia diferentes, embora a língua deva ser uma que você conheça. Se o jutsu for dissipado, o script original e a ilusão desaparecem. Uma criatura com visão de chakra ou visão verdadeira pode ler a mensagem oculta.",
  },
  {
    key: "incompetencia",
    nome: "Incompetência",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil"],
    descricao: "Você distorce as mentes de uma criatura alvo tornando-as menos capazes do que eram antes. Selecione uma criatura que você possa ver dentro do alcance. O alvo deve fazer um teste de resistência de Carisma.\n\nSucesso: A criatura afetada é capaz de resistir ao efeito deste jutsu.\nFalha: A criatura afetada sofre uma penalidade de -1d6 em rolagens de ataque.\nFalha Crítica: A criatura afetada sofre uma penalidade de -1d8 em rolagens de ataque.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3. Se conjurado no Rank B, aumente a penalidade em 1 dado. Se conjurado no Rank S, aumente a penalidade em 2 dados.",
  },
  {
    key: "mentiras-perdidas",
    nome: "Mentiras Perdidas",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Cubo de 15 Pés",
    duracao: "10 Minutos",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Fuinjutsu", "Auditivo", "Desapercebido"],
    descricao: "Você vincula seu chakra a um Selo de Chakra e marca uma área. Seu chakra irradia em um cubo de 15 pés centrado no selo de chakra que você colocou. Durante a duração deste jutsu, criaturas que começarem seu turno ou entrarem na área do selo de chakra pela primeira vez devem fazer um teste de resistência de Carisma. Em uma falha no teste de resistência, a criatura não pode proferir uma mentira deliberada enquanto estiver no raio, sendo incapaz de falar quando tentar fazê-lo.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o dano em 1d12.",
  },
  {
    // Nota: a descrição da mecânica de dano (Sucesso/Falha/Falha Crítica) deste jutsu aparece de fato associada aos campos de "Mentiras Perdidas" no texto-fonte (colunas cruzadas); mantida junto a Mentiras Perdidas acima. Insinuação, abaixo, não possui blocos de Sucesso/Falha nem Em Níveis Superiores no texto-fonte.
    key: "insinuacao",
    nome: "Insinuação",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil"],
    descricao: "Você libera um turbilhão de desejos conflitantes na mente de uma criatura que você pode ver dentro do alcance, prejudicando sua capacidade de tomar decisões. O alvo deve fazer um teste de resistência de Inteligência.\n\nSucesso: A criatura afetada é capaz de resistir ao efeito deste jutsu, mas ainda sofre 1d12 de dano psíquico.\nFalha: A criatura afetada sofre 2d12 de dano psíquico e faz seu teste de controle de chakra para manter a concentração com desvantagem.\nFalha Crítica: A criatura afetada sofre 3d12 + modificador de habilidade de Genjutsu de dano psíquico e perde a concentração em um jutsu com o custo mais baixo em que estiver concentrando no momento.",
  },
  {
    key: "cegueira-leve",
    nome: "Cegueira Leve",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "Concentração, até 1 Minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "Você mira em uma criatura que pode ver dentro do alcance e tenta alterar sua percepção cerebral da luz. A criatura alvo deve fazer um teste de resistência de Inteligência. Se este jutsu for lançado em uma criatura que não está se beneficiando de Luz Brilhante antes do lançamento deste jutsu, este jutsu ganha a Palavra-chave Desapercebido durante a duração.\n\nSucesso: A criatura afetada é capaz de resistir ao efeito deste jutsu.\nFalha: A criatura afetada trata Luz Brilhante como Luz Fraca e Luz Fraca como escuridão total durante a duração.\nFalha Crítica: As criaturas afetadas tratam Luz Brilhante como escuridão total durante a duração.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de alvos em +1.",
  },
  {
    key: "lotus-petalas-amargas",
    nome: "Lótus: Pétalas Amargas",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés (raio de 5 pés)",
    duracao: "1 Minuto",
    componentes: ["SM", "MC", "FN (Kit de Veneno, 1 carga)"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Inalação", "Tátil", "Desapercebido"],
    descricao: "Você agarra um punhado de pétalas venenosas de Lótus, espalhando-as de maneira única. Selecione dois pontos que você possa ver dentro do alcance enquanto preenche dois raios de 5 pés com uma dança de pétalas de amargura. Uma criatura que tenha falhado no teste deste jutsu anteriormente não pode ser afetada novamente por 1 minuto.\n\nEnquanto elas flutuam, todas as criaturas dentro do alcance devem fazer um teste de resistência de Carisma, à medida que o pólen começa a afetar seu estado emocional.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a lançamentos futuros deste jutsu até o final do próximo turno do conjurador.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: A criatura afetada entra em um estado amargo de espírito, e durante a duração, se uma criatura aliada, dentro da sua faixa de velocidade de movimento, sofrer dano de um ataque, ela deve gastar sua reação para interpor-se no ataque, tornando-se o novo alvo. No final do turno da criatura afetada, refaça seu teste de resistência, encerrando este efeito em caso de sucesso.\nFalha Crítica: Igual a falha, mas o alvo ganha uma reação adicional que só pode ser usada para interpor-se em ataques direcionados aos seus aliados.",
  },
  {
    key: "lotus-petalas-ansiosas",
    nome: "Lótus: Pétalas Ansiosas",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés (cubo de 10 pés)",
    duracao: "1 Minuto",
    componentes: ["SM", "MC", "FN (Kit de Veneno, 1 carga)"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Inalação"],
    descricao: "Você agarra um punhado de pétalas venenosas de Lótus, espalhando-as de maneira única. Selecione um espaço que você possa ver dentro do alcance enquanto preenche um cubo de 10 pés com uma dança de pétalas de repulsa. Uma criatura que tenha falhado no teste deste jutsu anteriormente não pode ser afetada novamente por 1 minuto.\n\nEnquanto elas flutuam à sua frente, todas as criaturas dentro do alcance devem fazer um teste de resistência de Carisma, à medida que o pólen começa a afetar seu estado emocional.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a lançamentos futuros deste jutsu até o final do próximo turno do conjurador.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: A criatura afetada entra em estado de pânico. Durante a duração, a criatura deve gastar sua ação para realizar a ação de Correr (disparada). No final do turno da criatura afetada, refaça seu teste de resistência, encerrando este efeito em caso de sucesso. Se não puder se mover ou tiver velocidade de movimento igual a 0, este jutsu termina imediatamente.\nFalha Crítica: Igual a falha, mas o alvo também deve gastar sua ação bônus para fazer um teste de Atletismo contra CD 15, para ganhar +10 de velocidade de movimento adicional.",
  },
  {
    key: "lotus-petalas-dancantes",
    nome: "Lótus: Pétalas Dançantes",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (raio de 10 pés)",
    duracao: "1 Minuto",
    componentes: ["SM", "MC", "FN (Kit de Veneno, 1 carga)"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Inalação", "Tátil"],
    descricao: "Você agarra um punhado de pétalas venenosas de Lótus, espalhando-as ao redor de si em uma dança de desespero. Uma vez que este jutsu é lançado, você não pode lançá-lo novamente até o final do seu próximo turno. Enquanto elas flutuam ao seu redor, todas as criaturas dentro do alcance devem fazer um teste de resistência de Carisma para perceberem que devem segurar a respiração antes de inalarem o pólen venenoso.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a lançamentos futuros deste jutsu até o final do próximo turno do conjurador.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu, mas ainda sofre 2d6 de dano de veneno.\nFalha: A criatura afetada inala uma massa de pólen venenoso das pétalas, sofrendo 3d6 de dano de veneno e começando a tossir e vomitar na tentativa de remover o pólen das vias respiratórias. Criaturas que falharem neste teste de resistência perdem a concentração de qualquer Ninjutsu em que estiverem concentrando-se durante a duração. Como uma ação no turno de uma criatura afetada, ela pode fazer um teste de Constituição contra CD 13. Em caso de sucesso, os efeitos deste jutsu terminam.\nFalha Crítica: Igual a falha, mas a duração deste jutsu é aumentada para 10 minutos.",
  },
  {
    key: "lotus-petalas-calmantes",
    nome: "Lótus: Pétalas Calmantes",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (cubo de 20 pés)",
    duracao: "1 Minuto",
    componentes: ["SM", "MC", "FN (Kit de Veneno, 1 carga)"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Inalação", "Tátil"],
    descricao: "Você agarra um punhado de pétalas venenosas de Lótus, espalhando-as o suficiente para preencher um cubo de 20 pés que se origina de você em uma dança de serenidade. Uma criatura que tenha falhado no teste deste jutsu anteriormente não pode ser afetada novamente por 1 minuto. Enquanto elas flutuam à sua frente, todas as criaturas dentro do alcance devem fazer um teste de resistência de Carisma, à medida que o pólen começa a afetar seu estado emocional.\n\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a lançamentos futuros deste jutsu até o final do próximo turno do conjurador.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: A criatura afetada entra em um estado de calma e menos hostil, sem vontade de combate. Durante a duração, criaturas acalmadas não podem realizar ações hostis contra outras criaturas. Este jutsu termina imediatamente se outra criatura tentar realizar uma ação hostil contra uma criatura que a criatura afetada possa ver. Isso não impede que elas ajam em seu próprio interesse, mas apenas as impede de se envolver diretamente em ações hostis.\nFalha Crítica: Igual a falha, mas se o alvo tentar o teste de habilidade para encerrar seus efeitos, todas as criaturas que atualmente não estão afetadas por este jutsu, dentro de 10 pés do alvo que está tossindo, também devem fazer o teste de habilidade de Constituição CD 11. Em caso de falha, elas sofrem os efeitos da falha deste jutsu. Em caso de sucesso, elas não sofrem nenhum efeito.",
  },
];
