import type { JutsuDefinition } from "@/lib/jutsu/types";

/** Genjutsu, segunda metade do Rank D — Anotações do Jiraya, p.243-262. */
export const genjutsuPart2: JutsuDefinition[] = [
  {
    key: "lotus-petalas-sombrias",
    nome: "Lotus: Pétalas Sombrias",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (linha de 30 pés)",
    duracao: "1 Minuto",
    componentes: ["SM", "MC", "FN (Kit de Veneno, 1 carga)"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Inalação", "Tátil"],
    descricao:
      "Você agarra um punhado de pétalas venenosas de Lótus, lançando-as em linha reta em uma dança de tristeza. Uma criatura que tenha falhado no teste deste jutsu anteriormente não pode ser afetada novamente por 1 minuto. Enquanto elas flutuam à sua frente, todas as criaturas dentro do alcance devem fazer um teste de resistência de Carisma, à medida que o pólen começa a afetar seu estado emocional.\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a lançamentos futuros deste jutsu até o final do próximo turno do conjurador.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: A criatura afetada entra em um estado sombrio de espírito, e durante a duração, não pode lançar jutsus que concedam a outras criaturas que não ela própria um bônus em ataques, dano, velocidade, testes de habilidade ou habilidades. Se estiver concentrando-se em tal jutsu, perde a concentração sobre ele. As criaturas afetadas podem gastar sua Ação para fazer um teste de habilidade de Sabedoria CD 13 para encerrar os efeitos deste jutsu sobre elas.\nFalha Crítica: Igual a falha, mas a duração deste jutsu é aumentada para 10 minutos.",
  },
  {
    key: "lotus-petalas-furiosas",
    nome: "Lotus: Pétalas Furiosas",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (cone de 20 pés)",
    duracao: "1 Minuto",
    componentes: ["SM", "MC", "FN (Kit de Veneno, 1 carga)"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Inalação", "Tátil"],
    descricao:
      'Você agarra um punhado de pétalas venenosas de Lótus, espalhando-as em um cone amplo que se origina de você em uma dança de raiva. Uma vez que este jutsu é lançado, você não pode lançá-lo novamente até o final do seu próximo turno. Uma criatura que tenha falhado no teste deste jutsu anteriormente não pode ser afetada novamente por 1 minuto. Enquanto elas flutuam à sua frente, todas as criaturas dentro do alcance devem fazer um teste de resistência de Carisma, à medida que o pólen começa a afetar seu estado emocional.\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a lançamentos futuros deste jutsu até o final do próximo turno do conjurador.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: A criatura afetada entra em um estado de fúria, cheia de raiva e furor. Durante a duração, criaturas enfurecidas devem lançar todos os jutsus ao seu nível máximo possível. Se um jutsu lançado não tiver a linguagem "Em Níveis Superiores", elas devem aumentar o custo do jutsu lançado em +3. As criaturas afetadas podem gastar uma Ação em seu turno tentando se acalmar, fazendo um teste de habilidade de Carisma CD 13. Em caso de sucesso, este jutsu termina.\nFalha Crítica: Igual à falha, mas o CD para encerrar este efeito é aumentado para 16.',
  },
  {
    key: "lotus-petalas-em-panico",
    nome: "Lotus: Pétalas em Pânico",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você toma quando vê uma criatura hostil tentar interromper uma ação de criaturas aliadas.",
    alcance: "30 Pés",
    duracao: "1 Rodada",
    componentes: ["SM", "MC", "FN (Kit de Veneno, 1 carga)"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Inalação", "Tátil"],
    descricao:
      "Você agarra um punhado de pétalas venenosas de Lótus, lançando-as de maneira única contra uma criatura que você pode ver tentando interromper o lançamento de um jutsu de outra criatura aliada. O lançamento deste jutsu é tratado como uma tentativa de interromper um jutsu de criatura.\nEnquanto elas flutuam, a criatura selecionada dentro do alcance deve fazer um teste de resistência de Carisma à medida que o pólen começa a afetar seu estado emocional.\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a lançamentos futuros deste jutsu até o final do próximo turno do conjurador.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu, mas ainda assim aumenta o custo do jutsu que ela lançou em +3.\nFalha: A criatura afetada aumenta o custo do jutsu que ela lançou em +6.\nFalha Crítica: A criatura afetada aumenta o custo do jutsu que ela lançou em +9.",
    emNiveisSuperiores: "Para cada rank que você conjura este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o custo do jutsu da criatura afetada em +2.",
  },
  {
    key: "lotus-petalas-culpadas",
    nome: "Lotus: Pétalas Culpadas",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "30 Pés",
    duracao: "1 Rodada",
    componentes: ["SM", "MC", "FN (Kit de Veneno, 1 carga)"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Inalação", "Tátil", "Desapercebido"],
    descricao:
      "Você agarra um punhado de pétalas venenosas de Lótus, lançando-as de maneira única contra uma criatura que você pode ver dentro do alcance. Enquanto elas flutuam, a criatura alvo deve fazer um teste de resistência de Carisma à medida que o pólen começa a afetar seu estado emocional.\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a lançamentos futuros deste jutsu até o final do próximo turno do conjurador.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: A criatura afetada entra em um estado de culpa e autoaversão. Durante a duração, as criaturas não podem mentir e devem responder a qualquer pergunta tão verdadeiramente quanto possível. Se for feita uma pergunta, ela gasta sua Ação para responder à primeira pergunta feita. As criaturas só podem fazer perguntas em seu turno. Este jutsu então termina.\nFalha Crítica: Igual à falha, mas a criatura também deve gastar sua ação bônus para responder à segunda pergunta feita.",
  },
  {
    key: "lotus-petalas-vergonhosas",
    nome: "Lotus: Pétalas Vergonhosas",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés (Raio de 5 pés)",
    duracao: "1 Minuto",
    componentes: ["SM", "MC", "FN (Kit de Veneno, 1 carga)"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Inalação", "Tátil", "Desapercebido"],
    descricao:
      "Você agarra um punhado de pétalas venenosas de Lótus, espalhando-as de maneira única. Seleciona dois pontos dentro do alcance enquanto preenche dois raios de 5 pés com uma dança de amargura de pétalas. Uma criatura que falhou no teste de resistência deste jutsu anteriormente não pode ser afetada novamente por 1 minuto. Enquanto elas flutuam, todas as criaturas dentro do alcance devem fazer um teste de resistência de Carisma à medida que o pólen começa a afetar seu estado emocional.\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a lançamentos futuros deste jutsu até o final do próximo turno do conjurador.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: A criatura afetada entra em um estado de vergonha mental, sendo incapaz de obter o benefício de redução de dano baseado em jutsu. Uma criatura afetada refaz este teste de resistência no final de cada um de seus turnos, encerrando os efeitos deste jutsu em caso de sucesso.\nFalha Crítica: Igual à falha, mas a criatura também não pode obter o benefício de bônus na CA como resultado de jutsu.",
  },
  {
    key: "lotus-petalas-repugnantes",
    nome: "Lotus: Pétalas Repugnantes",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés (Cubo de 10 pés)",
    duracao: "1 Minuto",
    componentes: ["SM", "MC", "FN (Kit de Veneno, 1 carga)"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Inalação", "Tátil"],
    descricao:
      "Você agarra um punhado de pétalas venenosas de Lótus, espalhando-as de maneira única. Seleciona dois pontos dentro do alcance enquanto preenche ambos os cubos de 10 pés com uma dança de repugnância de pétalas. Uma criatura que falhou no teste de resistência deste jutsu anteriormente não pode ser afetada novamente por 1 minuto. Enquanto elas flutuam diante de você, todas as criaturas dentro do alcance devem fazer um teste de resistência de Carisma à medida que o pólen começa a afetar seu estado emocional.\nSucesso Crítico: A criatura afetada é capaz de resistir ao efeito deste jutsu, tornando-se imune a lançamentos futuros deste jutsu até o final do próximo turno do conjurador.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu.\nFalha: A criatura afetada entra em um estado de repulsa. Durante a duração, as criaturas afetadas recusam efeitos que concederiam pontos de vida temporários ou cura. As criaturas afetadas podem gastar sua ação para fazer um teste de Inteligência CD 13 para encerrar seus efeitos e ver através de seus próprios pensamentos.\nFalha Crítica: O mesmo que falha, mas o CD do teste de habilidade para encerrar este jutsu é aumentado para 16.",
  },
  {
    key: "ninjutsu-medico-pensamentos-curados",
    nome: "Ninjutsu Médico: Pensamentos Curados",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Médico"],
    descricao: "Você manifesta uma ilusão restauradora projetada para ajudar a aliviar as cicatrizes mentais da batalha. Selecione uma condição Mental ou Sensorial da qual uma criatura esteja sob efeito e reduza-a em 1 nível.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de condições com nomes diferentes que este jutsu pode selecionar em +1.",
  },
  {
    key: "noite-escuridao-amarga",
    nome: "Noite: Escuridão Amarga",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando uma criatura hostil conjura um jutsu que afeta uma área de qualquer formato.",
    alcance: "90 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao:
      "Você manifesta um poderoso sentido de solidão e isolamento na forma de chakra ilusório, e o impõe a uma criatura hostil que você pode ver dentro do alcance, que está conjurando um jutsu com alcance. A criatura alvo deve fazer um teste de resistência de Inteligência. Isso conta como uma Interrupção na conjuração deste jutsu.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune aos efeitos secundários deste jutsu até o final do seu próximo turno.\nSucesso: A criatura afetada é capaz de resistir aos efeitos negativos deste jutsu.\nFalha: O jutsu que a criatura afetada está conjurando tem seu tamanho de área reduzido por um tamanho específico. Esfera/Raio, Cubo, Cone, Linha: 10 pés, e Cilindro: 5 pés de largura, 10 pés de altura, até um mínimo de 5 pés para qualquer área de efeito.\nFalha Crítica: O mesmo que falha, mas o tamanho da área de efeito do jutsu alvo é reduzido em mais 10 pés.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e a redução do tamanho da área de efeito do jutsu em 5 pés.",
  },
  {
    key: "neblina-mental",
    nome: "Neblina Mental",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "FN (Kit de Veneno)"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Inalação", "Tátil"],
    descricao:
      "Você libera uma névoa formada de chakra ilusório enquanto suprime o potencial de combate mental do alvo. Uma criatura de sua escolha dentro do alcance deve realizar um teste de resistência de Sabedoria.\nSucesso: A criatura afetada é capaz de resistir aos efeitos deste jutsu.\nFalha: A criatura afetada fica envenenada e reduz o dano que causa em 1d6 durante a duração.\nFalha Crítica: A criatura afetada fica envenenada e reduz o dano que causa em 1d8 durante a duração.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e a redução de dano em 1d6 ou 1d8.",
  },
  {
    key: "noite-luz-amarga",
    nome: "Noite: Luz Amarga",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando uma criatura hostil conjura um jutsu que afeta um único alvo.",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao:
      "Você manifesta um poderoso sentimento de amizade ou camaradagem na forma de chakra ilusório, e o impõe a uma criatura hostil que você pode ver dentro do alcance, que está conjurando um jutsu com alcance. A criatura alvo deve fazer um teste de resistência de Inteligência. Isso conta como uma Interrupção na conjuração deste jutsu.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune aos efeitos secundários deste jutsu até o final do seu próximo turno.\nSucesso: A criatura afetada é capaz de resistir aos efeitos negativos deste jutsu.\nFalha: A criatura afetada deve selecionar um novo alvo, mesmo que isso signifique selecionar uma criatura aliada a ela. Ela não pode selecionar a mesma criatura que anteriormente para desencadear a reação deste jutsu.\nFalha Crítica: O mesmo que falha, o alvo deve agora selecionar uma criatura aliada a si mesma, mesmo que uma criatura hostil a ele também esteja dentro do alcance.",
  },
  {
    key: "noite-sentimentos-amargos",
    nome: "Noite: Sentimentos Amargos",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando uma criatura hostil ganha um rank de uma condição Mental ou Sensorial.",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao:
      "Você manifesta um poderoso sentimento de rancor ou ódio na forma de chakra ilusório, e o impõe a uma criatura hostil que você pode ver dentro do alcance, que acabou de ganhar um rank de uma condição Mental ou Sensorial que pode ter mais de 1 rank. A criatura alvo deve fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune aos efeitos secundários deste jutsu até o final do seu próximo turno.\nSucesso: A criatura afetada é capaz de resistir aos efeitos negativos deste jutsu.\nFalha: A criatura afetada ganha 1 rank adicional da mesma condição.\nFalha Crítica: O mesmo que falha, mas o alvo ganha 2 ranks adicionais da mesma condição.",
  },
  {
    key: "noite-dor-gelida",
    nome: "Noite: Dor Gélida",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "15 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil"],
    descricao:
      "Você manifesta uma lâmina de chakra ilusório gelado para atravessar os sentidos de um alvo, prejudicando-os temporariamente. Faça um ataque de Genjutsu corpo a corpo contra uma criatura que você possa ver dentro do alcance. Em caso de acerto, você causa 4d6 de dano psíquico e força a criatura a fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune aos efeitos secundários deste jutsu até o final do seu próximo turno.\nSucesso: A criatura afetada é capaz de resistir aos efeitos negativos deste jutsu.\nFalha: Os sentidos da criatura afetada são danificados. Ela ganha 1 nível de Atordoado.\nFalha Crítica: O mesmo que falha, mas ela ganha 2 níveis de Atordoado.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3, o dano em 1d6 e o número de alvos em +1.",
  },
  {
    key: "noite-reacoes-amargas",
    nome: "Noite: Reações Amargas",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando uma criatura hostil sofreria dano.",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao:
      "Você manifesta um poderoso sentimento de lentidão na forma de chakra ilusório, e o impõe a uma criatura alvo que você pode ver dentro do alcance, que sofreu dano. Os efeitos desta reação ocorrem antes dos efeitos baseados em reação da criatura alvo, se houver. A criatura alvo deve fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune aos efeitos deste jutsu até o final do seu próximo turno.\nSucesso: A criatura afetada é capaz de resistir aos efeitos negativos deste jutsu.\nFalha: A velocidade de pensamento da criatura afetada é reduzida. Ela fica incapaz de realizar reações até o final do turno atual.\nFalha Crítica: O mesmo que falha, mas ela não pode realizar reações até o início do próximo turno dela.",
  },
  {
    key: "noite-vinganca-amarga",
    nome: "Noite: Vingança Amarga",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando uma criatura aliada sofre dano.",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil"],
    descricao:
      "Você manifesta um poderoso sentimento de hiperagressividade na forma de chakra ilusório, e o impõe a uma criatura aliada que você pode ver dentro do alcance, que sofreu dano, exceto você. Eles ganham um impulso em sua agressividade, aumentando o bônus nos seus ataques e rolagens de dano em 1d6 até o final do próximo turno deles. Ao final do próximo turno deles, porém, eles sofrem um pouco de psicose, forçando-os a fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune aos efeitos secundários deste jutsu até o final do seu próximo turno.\nSucesso: A criatura afetada é capaz de resistir aos efeitos negativos deste jutsu.\nFalha: A criatura afetada sofre um pequeno feedback doloroso, sofrendo 2d6 de dano psíquico.\nFalha Crítica: O mesmo que falha, mas ela também sofre uma penalidade de 1d6 nas suas rolagens de ataque e dano até o final do próximo turno dela.",
  },
  {
    key: "noite-pensamentos-gelidos",
    nome: "Noite: Pensamentos Gélidos",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (cubo de 25 pés)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil"],
    descricao:
      "Você manifesta uma onda de choque de chakra ilusório gelado a partir de sua voz, influenciando os pensamentos das criaturas dentro do alcance afetando todas as criaturas de sua escolha em um cubo de 25 pés, originando-se de você dentro do alcance, forçando-as a fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune aos efeitos deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir aos efeitos negativos deste jutsu.\nFalha: A criatura afetada é sobrecarregada pelo chakra ilusório, encontrando dificuldade para pensar e, portanto, não consegue completar um pensamento completo sem ser atormentada por ideias lentas. Ela ganha 1 nível de Lento durante a duração.\nFalha Crítica: O mesmo que falha, mas ela também ganha 1 nível de Ofuscado durante a duração.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o tamanho do cubo em 5 pés.",
  },
  {
    key: "noite-visao-gelida",
    nome: "Noite: Visão Gélida",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (raio de 20 pés)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao:
      "Você manifesta uma aura de chakra ilusório gelado centrada em você, afetando todas as criaturas de sua escolha dentro do alcance, forçando-as a fazer um teste de resistência de Inteligência. Se o alvo possuir Visão de Chakra, ele não tem vantagem neste teste de resistência.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune aos efeitos deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir aos efeitos negativos deste jutsu.\nFalha: Se a criatura afetada possuir Visão de Chakra ou Visão no Escuro, ela ganha 2 níveis de Ofuscado enquanto estiver dentro do raio deste jutsu, desde que esteja recebendo os benefícios dessas visões especiais, pois o chakra ilusório sobrecarrega seus sentidos visuais.\nFalha Crítica: O mesmo que falha, mas as criaturas afetadas também perdem a Visão de Chakra ou Visão no Escuro durante a duração deste jutsu.",
  },
  {
    key: "noite-palavras-gelidas",
    nome: "Noite: Palavras Gélidas",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (cone de 20 pés)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao:
      "Você manifesta uma onda de chakra ilusório gelado apenas com suas palavras, afetando todas as criaturas de sua escolha dentro do alcance, forçando-as a fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune aos efeitos deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir aos efeitos negativos deste jutsu.\nFalha: A criatura afetada é sobrecarregada pelo chakra ilusório, encontrando dificuldade para ouvir e, portanto, fica surda para todos os sons que não se originam de você.\nFalha Crítica: O mesmo que falha, mas as criaturas afetadas também sofrem uma penalidade de 1d4 em todos os testes de resistência contra Genjutsu com a palavra-chave Auditivo durante a duração.",
  },
  {
    key: "noite-toque-gelido",
    nome: "Noite: Toque Gélido",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (linha de 30 pés e 5 pés de largura)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao:
      "Você manifesta um feixe de chakra ilusório gelado de dentro de si mesmo, afetando todas as criaturas de sua escolha em uma linha de 30 pés de comprimento e 5 pés de largura, originando-se de você dentro do alcance, forçando-as a fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune aos efeitos deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir aos efeitos negativos deste jutsu.\nFalha: A criatura afetada é sobrecarregada pelo chakra ilusório, encontrando dificuldade para sentir e, portanto, não consegue distinguir dor de cura. O próximo Genjutsu que a afetaria durante a duração ganha a palavra-chave Desprevenido, e então este jutsu termina.\nFalha Crítica: O mesmo que falha, mas ela também sofre 3d6 de dano psíquico no início de cada um de seus turnos durante a duração. Uma criatura que falhou criticamente no teste de resistência deste jutsu refaz seu teste no final de cada um de seus turnos, encerrando o dano crítico deste jutsu em caso de sucesso.",
  },
  {
    key: "visao-dolorosa",
    nome: "Visão Dolorosa",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao:
      "Você seleciona uma criatura que pode ver dentro do alcance, intensificando sua sensibilidade à luz. A criatura alvo deve fazer um teste de resistência de Sabedoria.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu, mas ganha sensibilidade à luz solar, sofrendo uma penalidade de -2 em rolagens de ataque enquanto estiver em luz brilhante até o final de seu próximo turno.\nFalha: No início do turno de uma criatura afetada, ela sofre 2d8 + o modificador de habilidade de Genjutsu em dano psíquico. Se estiver em luz fraca, ela sofre 2d6 + o modificador de habilidade de Genjutsu em dano psíquico. No final de cada turno da criatura afetada, ela refaz o teste de resistência, encerrando este jutsu com um sucesso.\nFalha Crítica: No início do turno de uma criatura afetada, ela sofre 3d8 + o modificador de habilidade de Genjutsu em dano psíquico. Se estiver em luz fraca, ela sofre 3d6 + o modificador de habilidade de Genjutsu em dano psíquico. No final de cada turno da criatura afetada, ela refaz o teste de resistência, encerrando este jutsu com um sucesso. Se estiver em luz brilhante, ela refaz seu teste de resistência com desvantagem.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3, o dano em 1d8 ou 1d6, e o número de criaturas que você pode afetar em +1.",
  },
  {
    key: "mordiscar-nos-calcanhares",
    nome: "Mordiscar nos Calcanhares",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "90 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Desprevenido"],
    descricao:
      "Você bate suas mãos no chão criando uma nuvem de fumaça ilusória enquanto um bando de cães selvagens que parecem agressivos correm e mordiscam uma criatura que você pode ver dentro do alcance, que deve fazer um teste de resistência de Inteligência. Um alvo que esteja pelo menos a 10 pés do chão (em uma árvore, voando, etc.) ou que tenha sentidos, características ou jutsus ativos que lhe concedam vantagem em sua Sabedoria (Percepção), tem vantagem no teste de resistência.\nSucesso: A criatura afetada é capaz de resistir aos efeitos deste jutsu.\nFalha: A criatura afetada tem desvantagem em rolagens de ataque e testes de habilidade contra outra criatura de sua escolha, pois fica distraída pelos cães atacantes. No final de cada um de seus turnos, o alvo refaz seu teste de resistência, encerrando o efeito sobre si mesmo com um sucesso no teste.\nFalha Crítica: O mesmo que falha, e a(s) criatura(s) afetada(s) que lançaria(m) um jutsu com os componentes Sinal Manual (SM) ou Mobilidade (M) sofrem 2d8 de dano psíquico enquanto os cães mordem nelas.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o número de criaturas que você pode afetar em +1.",
  },
  {
    key: "psionicos-garantia",
    nome: "Psiônicos: Garantia!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando vê uma criatura hostil sofrer dano",
    alcance: "60 pés",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Tátil"],
    descricao:
      "Você vê uma criatura sofrer dano e pode ver o impacto que ele causa. Você aproveita essa oportunidade para garantir que o dano infligido permaneça. A criatura que provocou o gatilho deve fazer um teste de resistência de Inteligência.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu, sofrendo 2d6 de dano psíquico.\nFalha: A criatura afetada sofre uma quantidade de dano psíquico igual a Xd6, onde X é igual ao seu modificador de habilidade de Genjutsu.\nFalha Crítica: A criatura afetada sofre os efeitos de uma falha e fica Sobrecarregada até o final do próximo turno dela.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3, o dano em 1d6 ou 1d8 e o alcance em 5 pés.",
  },
  {
    key: "voz-dolorosa",
    nome: "Voz Dolorosa",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (Cone de 30 pés)",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil"],
    descricao:
      "Você cobre suas mãos e grita através da abertura na outra extremidade. Todas as criaturas que podem ouvi-lo em um cone de 30 pés, originando-se de você, devem fazer um teste de resistência de Sabedoria.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu.\nSucesso: A criatura afetada é capaz de resistir à maioria dos efeitos deste jutsu, mas fica surda até o final do próximo turno dela.\nFalha: A criatura afetada sofre 4d6 de dano psíquico.\nFalha Crítica: A criatura afetada sofre 4d8 + modificador de habilidade de Genjutsu de dano psíquico.",
  },
  {
    key: "luz-fantasma",
    nome: "Luz Fantasma",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "1 hora",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao:
      "Você toca um único objeto que mede menos de 10 pés em todas as dimensões. Até o fim deste Jutsu, você e até 3 outras criaturas podem ver uma luz brilhante originando-se desse objeto em um raio de 20 pés, e luz fraca por mais 20 pés. A luz pode ser colorida como você preferir. Apenas você e as criaturas selecionadas podem se beneficiar dessa fonte de luz artificial. Você pode usar sua ação bônus para dissipar este jutsu.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o número de objetos que você pode afetar com este jutsu em +1.",
  },
  {
    key: "psionicos-bloqueio-mental",
    nome: "Psiônicos: Bloqueio Mental",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao:
      "Você tenta bloquear os pensamentos de um alvo em um ciclo infinito de pensamento circular, sempre terminando na sua resposta anterior. Selecione uma criatura hostil que você possa ver e alcançar dentro do alcance, forçando-a a fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune a lançamentos futuros deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir aos efeitos deste jutsu.\nFalha: A criatura afetada deve gastar sua ação, em cada um dos seus turnos subsequentes, relançando o mesmo jutsu (de sua escolha) que lançou em seu turno anterior. Se o alvo não lançou um jutsu em seu último turno, este jutsu termina imediatamente. A criatura refaz seu teste de resistência no final de cada um de seus turnos, encerrando este jutsu em caso de sucesso.\nFalha Crítica: O mesmo que falha, mas a criatura também recebe uma penalidade de 1d4 em seu primeiro teste de resistência para encerrar os efeitos deste jutsu sobre ela.",
  },
  {
    key: "psionicos-atraso",
    nome: "Psiônicos: Atraso!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você manifesta um som atrasado que continua a ecoar por alguns momentos antes de desaparecer. Em seguida, selecione uma criatura que você possa ver dentro do alcance. No final do seu próximo turno, este jutsu entra em efeito. Se a criatura alvo lançar qualquer jutsu em seu próximo turno, ela sofrerá 3d12 de dano psíquico.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o dano em 1d12.",
  },
  {
    key: "psionicos-confusao",
    nome: "Psiônicos: Confusão!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao:
      "Você tenta despedaçar o fio de pensamento de uma criatura, instilando uma confusão severa e causando-lhes dor mental através da inconsistência. Selecione um alvo dentro do alcance. Ele deve fazer um teste de resistência de Sabedoria.\nSucesso: A criatura afetada é capaz de resistir aos efeitos deste jutsu.\nFalha: A criatura afetada ganha 1 nível de Confusão.\nFalha Crítica: A criatura afetada ganha 1 nível de Confusão, e o primeiro teste feito para encerrar a condição é aumentado em 2.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de criaturas que você pode afetar em +1.",
  },
  {
    key: "psionicos-dreno",
    nome: "Psiônicos: Dreno!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "1 Minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil", "Desapercebido"],
    descricao:
      "Você tenta drenar o poder mental de uma criatura hostil que você pode ver, tornando mais difícil para ela pensar claramente no momento. Selecione uma criatura hostil que você possa ver dentro do alcance, forçando-a a fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune a lançamentos futuros deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir aos efeitos deste jutsu.\nFalha: A criatura hostil sofre 3d6 de dano psíquico e sofre uma penalidade de 1d4 em todos os testes de ataque baseados em Inteligência e testes de habilidade pelos próximos minutos.\nFalha Crítica: O mesmo que Falha, mas o dano é aumentado para 5d8.",
  },
  {
    key: "psionicos-corte",
    nome: "Psiônicos: Corte!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao: "Você manifesta lâminas formadas de chakra ilusório que rasgam as defesas mentais de uma criatura. Faça um ataque de Genjutsu à distância causando 4d8 de dano psíquico. Se este jutsu for lançado estando a até 10 pés da criatura alvo, aumente a ameaça crítica deste ataque em +1.",
    // NOTE: fonte tem dois blocos "Em Ranks Superiores" seguidos, sem novo título entre eles — provável artefato de duplicação/rascunho no PDF de origem. Concatenados aqui.
    emNiveisSuperiores:
      "Para cada rank acima de D, aumente o custo deste jutsu em 3, o dano em 1d8. Se este jutsu for lançado no Rank B, aumente a ameaça crítica em +1. Se este jutsu for lançado no Rank S, aumente a ameaça crítica em +2. [Texto duplicado na fonte:] Para cada rank acima de D, aumente o custo deste jutsu em 3 e o dano em 1d6 e 1d8, respectivamente.",
  },
  {
    key: "psionicos-fortaleza",
    nome: "Psiônicos: Fortaleza",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao:
      "Você conjura uma armadura ilusória. Esta armadura concede um bônus de +1 na sua CA. Se você seria alvo de um ataque de Genjutsu, você trata este bônus como +2. Se uma criatura conseguir acertar você com um ataque corpo a corpo ou taijutsu, você a força a fazer um teste de resistência de Inteligência enquanto envia um feedback psíquico de volta.\nSucesso: A criatura afetada é capaz de resistir aos efeitos deste jutsu.\nFalha: A criatura afetada imediatamente começa a se mover de maneiras desajeitadas e desajeitadas. Os ataques que visam a criatura ganham um bônus de +1d4 para acertar, uma vez por turno, por criatura.\nFalha Crítica: O mesmo que falha, mas a velocidade de movimento da criatura também é reduzida a 0 até o final do próximo turno dela.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de criaturas que você pode afetar em +1.",
  },
  {
    key: "psionicos-exposicao-da-fraqueza",
    nome: "Psiônicos: Exposição da Fraqueza",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil", "Desapercebido"],
    descricao:
      "Você tenta expor a fraqueza de seus inimigos fazendo-os inconscientemente se exporem. Selecione uma criatura que você possa ver dentro do alcance, forçando-a a fazer um teste de resistência de Inteligência.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada imediatamente cai prostrada e larga sua arma, se tiver alguma. Isso não impede o dano. Este jutsu então termina.\nFalha Crítica: O mesmo que falha, mas a criatura também reduz sua CA em 1, durante a duração.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3. Se este jutsu for lançado no rank B, você ganha Redução de Dano Psíquico de 5 para a duração deste jutsu. Se este jutsu for lançado no rank S, você ganha Redução de Dano Psíquico de 10 para a duração deste jutsu.",
  },
  {
    key: "psionicos-futuro-falso",
    nome: "Psiônicos: Futuro Falso",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Desapercebido"],
    descricao:
      "Você tenta forçar uma visão de um falso futuro em um alvo, fazendo com que ele tome uma decisão mal informada. Selecione uma criatura hostil que você possa ver dentro do alcance, forçando-a a fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada é capaz de resistir aos efeitos deste jutsu, tornando-se imune a lançamentos futuros deste jutsu pelos próximos 10 minutos.\nSucesso: A criatura afetada é capaz de resistir aos efeitos deste jutsu.\nFalha: A criatura hostil deve gastar sua reação para se mover pelo menos 30 pés, se puder, para um espaço onde se moveria se fosse seu turno agora.\nFalha Crítica: O mesmo que falha, mas a velocidade de movimento da criatura é reduzida pela metade após seu movimento, até o final de seu próximo turno.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de criaturas que isso pode afetar em +1.",
  },
  {
    key: "psionicos-enxaqueca",
    nome: "Psiônicos: Enxaqueca!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao:
      "Você estende sua mão e seleciona um alvo dentro do alcance. A criatura alvo deve fazer um teste de resistência de Inteligência. Se o valor de habilidade de Inteligência deles for 12 ou menos, eles fazem este teste com desvantagem.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada vê seu corpo inchar e experimenta uma quantidade extraordinária de dor, sentindo como se sua cabeça fosse explodir. Ela sofre 4d4 de dano psíquico e até o final do próximo turno dela, ela sofre uma penalidade de -10 na sua velocidade.\nFalha Crítica: A criatura afetada vê seu corpo inchar e experimenta uma quantidade extraordinária de dor, sentindo como se sua cabeça fosse explodir. Ela sofre 6d4 de dano psíquico e até o final do próximo turno dela, ela sofre uma penalidade de -20 na sua velocidade e o próximo jutsu que ela lançar e o custo de concentração são dobrados antes do final do próximo turno dela.",
    // NOTE: fonte literalmente diz "Para cada rank acima de C" (não "D" como as entradas irmãs) — mantido como está.
    emNiveisSuperiores: "Para cada rank acima de C, aumente o custo deste jutsu em 3, o dano em 1d4 e o número de criaturas que podem ser alvo em +1.",
  },
  {
    key: "psionicos-transferencia-hostil",
    nome: "Psiônicos: Transferência Hostil",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil"],
    descricao:
      "Você tenta transferir as condições mentais negativas de uma criatura aliada para uma hostil. Selecione uma criatura aliada que você possa ver dentro do alcance e que tenha condições mentais. Quando o fizer, selecione uma criatura hostil que você possa ver dentro do alcance, forçando-a a fazer um teste de resistência de Inteligência.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura hostil adquire uma das condições mentais que a criatura aliada possui (sua escolha).\nFalha Crítica: A criatura hostil adquire todas as condições mentais que a criatura aliada possui, e a criatura aliada perde cada condição mental que a criatura hostil adquire.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de criaturas hostis que você pode afetar em +1.",
  },
  {
    key: "psionicos-meditacao",
    nome: "Psiônicos: Meditação!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Pessoal",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Genjutsu", "Tátil"],
    descricao: "Você estabiliza seus pensamentos, encontrando equilíbrio e paz interior no momento da batalha. Durante a duração, você ganha um bônus de 1d4 nos ataques de Genjutsu e causa um dano adicional de 1d6 psíquico com Genjutsu que você lançar.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3. Se este jutsu for lançado no rank B, aumente o bônus para acertar e o dano em 1 passo de dado (1d6, 1d8). Se este jutsu for lançado no rank S, aumente o bônus para acertar e o dano em 1 passo de dado (1d8, 1d10).",
  },
  {
    key: "psionicos-pulso",
    nome: "Psiônicos: Pulso!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (20 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil"],
    descricao:
      "Você manifesta um pulso de pensamento, destinado a infligir dor e desorientar todos próximos a você. Todas as criaturas de sua escolha dentro do alcance devem fazer um teste de resistência de Inteligência.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada sofre 3d4 de dano psíquico e é forçada a recuar 10 pés de você.\nFalha Crítica: A criatura afetada sofre 5d4 de dano psíquico e é forçada a recuar 25 pés de você.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3, o dano em 1d4 e o raio em 5 pés.",
  },
  {
    key: "psionicos-branqueamento-mental",
    nome: "Psiônicos: Branqueamento Mental!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil", "Desapercebido"],
    descricao:
      "Você tece um som gutural e visceral que ecoa para fora, projetado para criar espaços vazios nas mentes dos ouvintes. Selecione uma criatura que possa ouvir você dentro do alcance. O alvo deve fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada consegue resistir aos efeitos deste Genjutsu.\nSucesso: O próximo jutsu lançado pela criatura afetada aumenta seu custo em +4.\nFalha: A criatura afetada se torna incapaz de lançar um jutsu que tenha lançado em seu turno anterior. Se ela tentar lançar tal jutsu, ele falha.\nFalha Crítica: A criatura afetada se torna incapaz de lançar um jutsu que tenha lançado em seu turno anterior. Se ela tentar lançar tal jutsu, ele falha, e ela sofre uma enxaqueca intensa, sofrendo 5d6 de dano psíquico.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3, o número de criaturas que você pode afetar em +1 e o dano em 1d6.",
  },
  {
    key: "psionicos-paralisia-de-alcance",
    nome: "Psiônicos: Paralisia de Alcance!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao:
      "Você tenta reduzir o alcance eficaz de um criatura ao nublar sua visão e impor limitações visuais sobre ela. Selecione uma criatura hostil que você possa ver dentro do alcance, forçando-a a fazer um teste de resistência de Inteligência.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada ganha 2 ranks de Atordoado durante a duração. Os ranks de Atordoado infligidos por este jutsu não desaparecem no final dos turnos da criatura afetada, mas apenas quando este jutsu termina.\nFalha Crítica: O mesmo que falha, mas também se a criatura tentar lançar um jutsu ou realizar um ataque com alcance maior que 15 pés, o alcance do jutsu ou ataque é reduzido em 10 pés.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3, o número de criaturas que podem ser alvo em +1 e a redução de alcance em caso de falha crítica em 5 pés.",
  },
  {
    key: "psionicos-onda-psicotica",
    nome: "Psiônicos: Onda Psicótica!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (cone de 15 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "Você manifesta um pulso ilusório, que bate nos padrões de pensamento de uma criatura, deixando-a mentalmente drenada. Todas as criaturas dentro de um cone de 15 pés originado de você devem fazer um teste de resistência de Sabedoria.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada fica Atordoada e Confusa.\nFalha Crítica: A criatura afetada fica Atordoada, Confusa e Concussa.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o tamanho do cone em 5 pés.",
  },
  {
    key: "psionicos-choque",
    nome: "Psiônicos: Choque!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao:
      "Você libera uma poderosa descarga de chakra psíquico destinada a sobrecarregar os receptores sensoriais de uma criatura. Uma criatura de sua escolha dentro do alcance deve fazer um teste de resistência de Inteligência.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada sofre 6d4 de dano psíquico. Este dano ignora resistência e trata imunidade como resistência.\nFalha Crítica: A criatura afetada sofre 6d6 de dano psíquico e fica Atordoada. Este dano ignora redução de dano e ignora resistência e trata imunidade como resistência.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o dano em 1d4 ou 1d6, ou o número de criaturas que podem ser alvo em +1.",
  },
  {
    key: "psionicos-pensamentos-compartilhados",
    nome: "Psiônicos: Pensamentos Compartilhados!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    // NOTE: fonte literalmente lê "Genjutsu, Auditivo, Desconhecido" — "Desconhecido" não é uma palavra-chave padrão usada em outras entradas (normalmente "Desapercebido"); mantido como está, provável artefato de OCR.
    palavrasChave: ["Genjutsu", "Auditivo", "Desconhecido"],
    descricao:
      'Você tenta ver e compartilhar os pensamentos de uma criatura que você pode ver, descobrindo o que ela está pensando ou planejando. Selecione uma criatura que você possa ver dentro do alcance, forçando-a a fazer um teste de resistência de Inteligência.\nSucesso Crítico: A criatura afetada consegue resistir aos efeitos deste jutsu, tornando-se imune a novos lançamentos deste jutsu pelos próximos 10 minutos. Além disso, ela fica ciente de que alguém tentou penetrar em sua mente.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura hostil começa a compartilhar inconscientemente seus pensamentos com você. No início de cada um de seus turnos, o Mestre informa a você sobre o jutsu que estão lançando, ações que estão realizando ou pensamentos que têm durante seu turno apenas. Se o alvo lançar um jutsu ou realizar um ataque, você obtém o benefício da reação "Ler o Inimigo" com sucesso. No final de cada turno do alvo, ele refaz seu teste de resistência, ainda sem saber que está compartilhando pensamentos com você.\nFalha Crítica: O mesmo que falha, mas o alvo não refaz seus testes até que perceba que está sob os efeitos deste Genjutsu.',
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de criaturas que podem ser alvo em +1.",
  },
  {
    key: "psionicos-golpe",
    nome: "Psiônicos: Golpe!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao: "Você reveste as mãos e os pés de uma criatura que toca com energia psíquica, fazendo com que cada golpe prejudique tanto o corpo quanto a mente simultaneamente. Quando ela causar dano com um ataque desarmado, ela causa um dano psíquico adicional de 1d10, uma vez por turno. Se ela causar um acerto crítico enquanto obtém os benefícios deste jutsu, você pode optar por converter todo o dano causado com o ataque em dano psíquico.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o dano em 1d10.",
  },
  {
    key: "santuario",
    nome: "Santuário",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "30 pés",
    duracao: "1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual", "Desapercebido"],
    descricao:
      "Você tece chakra criando uma barreira nebulosa de ilusões protegendo uma criatura dentro do alcance contra ataques. Até este jutsu acabar, qualquer criatura que alvejar a criatura protegida com um ataque ou um jutsu deve primeiro ter sucesso em um teste de resistência de Sabedoria. Em caso de falha no teste, a criatura deve escolher um novo alvo ou perder o ataque ou jutsu. Esta barreira não protege contra efeitos de área, como um Jutsu Estilo Fogo: Bola de Fogo ou qualquer jutsu similar. Se a criatura protegida realizar um ataque ou conjurar um jutsu que afete outra criatura, este jutsu termina.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de criaturas que você pode alvejar com este jutsu em +1.",
  },
  {
    key: "psionicos-suprimir-foco",
    nome: "Psiônicos: Suprimir Foco!",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao:
      "Você tenta forçar uma criatura que está se beneficiando de um aumento de qualquer tipo a não mais se beneficiar desse aumento. Selecione uma criatura hostil que você possa ver dentro do alcance, forçando-a a fazer um teste de resistência de Inteligência.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: Se o alvo estiver sob os efeitos de um jutsu que lhe concede um bônus a ataques, dano, CA, testes de habilidade ou testes de habilidade, selecione uma das estatísticas mencionadas. O alvo tem os benefícios escolhidos suprimidos, incapaz de obter aquele aumento na estatística escolhida pela duração.\nFalha Crítica: O mesmo que falha, mas em vez de uma estatística, ele não pode obter um bônus baseado em jutsu para qualquer uma das estatísticas listadas pela duração.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de criaturas que podem ser alvo em +1.",
  },
  {
    key: "arte-de-selamento-delirios",
    nome: "Arte de Selamento: Delírios",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Fuinjutsu"],
    descricao:
      "Você infunde chakra em selos de chakra enquanto tenta marcar uma criatura que você pode ver no alcance com o selo dos desejos. A criatura alvo deve realizar um teste de resistência de Carisma. Em caso de falha no teste, o alvo é marcado com o selo dos desejos, começando a ver flashes e visões das coisas que mais deseja na vida, fazendo-a congelar no lugar, focando nas coisas à sua frente. Durante a duração, uma criatura marcada com este selo, no início de cada um de seus turnos, refaz o teste de resistência, ficando atordoada até o final de seu turno em caso de falha. Em caso de sucesso no teste, ela resiste aos efeitos do selo, terminando este jutsu. Se a criatura alvo sofrer dano, ela repete o teste de resistência para terminar este jutsu.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o número de criaturas que você pode alvejar com este jutsu em +1.",
  },
  {
    key: "fantoches-da-escuridao",
    nome: "Fantoches da Escuridão",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao:
      'Você tece chakra criando ilusões animadas da sombra de uma criatura dentro do alcance, fazendo com que ela ataque. Como uma ação bônus, quando você conjura este jutsu ou como uma ação bônus em turnos subsequentes, enquanto mantiver a concentração, comande a sombra para atacar. Faça um ataque Genjutsu corpo-a-corpo contra uma criatura alvo. Em um acerto, você causa 2d10 de dano psíquico e ela deve fazer um teste de resistência de Inteligência, ficando atordoada até o início do seu próximo turno em caso de falha. Outra criatura que possa tocar o alvo afetado pode tentar uma jogada de Sabedoria (Ilusões) contra o seu CD de resistência de Genjutsu para encerrar este jutsu à força neles.',
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3. Se lançado como um jutsu de Rank B, aumente o número de criaturas que você pode alvejar com este jutsu para 2. Se lançado como um jutsu de Rank S, aumente o número de criaturas que você pode alvejar com este jutsu para 3.",
  },
  {
    key: "mordida-da-sombra",
    nome: "Mordida da Sombra",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao: "Você cria momentaneamente uma agulha de escuridão que irrompe da sombra de uma criatura que você pode ver dentro do alcance. Faça um ataque de Genjutsu à distância. Em um acerto, você causa dano psíquico igual a 4d6 + seu modificador de habilidade de Genjutsu e reduz a velocidade da criatura em 10 até o início do seu próximo turno. Uma criatura cuja velocidade é reduzida dessa forma não pode se beneficiar de velocidade adicional durante a duração da redução de sua velocidade.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de D, aumente o custo em 3, o número de criaturas que você pode alvejar em +1, o dano em 1d6 e a redução de velocidade em -5.",
  },
  {
    key: "arte-do-selamento-sonhos-doces",
    nome: "Arte do Selamento: Sonhos Doces",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual", "Fuinjutsu"],
    descricao: "Você infunde chakra em selos de chakra enquanto tenta marcar uma criatura disposta que você possa ver dentro do alcance com o selo do descanso. Durante a duração, como uma ação bônus, você pode forçar a criatura a experimentar um padrão de sono hiperacelerado. A criatura alvo ganha alguns dos benefícios de um descanso curto, permitindo que ela gaste dados de vida para recuperar pontos de vida. A criatura afetada não recupera quaisquer características ou recursos que seriam restaurados ou recuperados durante um descanso curto.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de D, aumente o custo em 3 e o número de criaturas que você pode alvejar com este jutsu em +1.",
  },
  {
    key: "imagem-silenciosa",
    nome: "Imagem Silenciosa",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 10 minutos",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual", "Desprevenido"],
    descricao: "Você cria a imagem de um objeto, uma criatura ou outro fenômeno visível que não seja maior que um cubo de 15 pés. A imagem aparece em um ponto dentro do alcance e dura pela duração. A imagem é puramente visual; não é acompanhada por som, cheiro ou outros efeitos sensoriais. Você pode usar sua ação para fazer a imagem se mover para qualquer ponto dentro do alcance. Conforme a imagem muda de localização, você pode alterar sua aparência para que seus movimentos pareçam naturais para a imagem. Por exemplo, se você criar a imagem de uma criatura e movê-la, pode alterar a imagem para que pareça estar caminhando. A interação física com a imagem revela que é uma ilusão, pois objetos podem passar através dela, fazendo com que o Genjutsu termine imediatamente.",
  },
  {
    key: "sombra-do-temor",
    nome: "Sombra do Temor",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (raio de 20 pés)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "Você transforma sua aparência em um monstro sem rosto conhecido como Nyarlathotep. Esta figura pode ser de sua própria descrição, já que esse monstro não possui uma descrição singular conhecida. Durante a duração, qualquer criatura dentro de 20 pés de você se torna incapaz de se mover voluntariamente mais perto de você, a menos que faça um teste de resistência de Sabedoria bem-sucedido no início de seu turno. Construtos e mortos-vivos são imunes a este efeito. Além disso, você tem vantagem em testes de resistência para resistir à condição de medo.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de D, aumente o custo em 3 e o raio em 5 pés.",
  },
  {
    key: "cancao-dos-antigos",
    nome: "Canção dos Antigos",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "próprio (raio de 20 pés)",
    duracao: "Concentração, até 10 minutos",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo", "Tátil"],
    descricao:
      "Você começa a cantarolar ou cantar uma melodia errática em uma língua incompreensível projetada para levar aqueles que a ouvem a um curto surto de loucura. Quando faz isso, todas as criaturas dentro de um raio de 20 pés de você começam a experimentar surtos de loucura. Durante a duração, você não gasta chakra para manter este jutsu; em vez disso, deve gastar uma ação bônus nos turnos subsequentes para mantê-lo. Criaturas que começam seus turnos dentro do alcance devem fazer um teste de resistência de inteligência.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada adquire a condição de loucura até o final de seu próximo turno.\nFalha Crítica: A criatura afetada adquire a condição de loucura por 1d4 de seus turnos.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de D, aumente o custo deste jutsu em 3 e o raio em 5 pés.",
  },
  {
    key: "silhueta",
    nome: "Silhueta",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "100 pés",
    duracao: "Concentração, até 10 minutos",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Genjutsu", "Visual", "Desprevenido"],
    descricao: "Você cria uma peça de sombras contra uma tela ou parede. A superfície pode abranger até 100 pés quadrados e não tem um ponto de origem singular, em vez disso, aproveita todas as sombras que objetos e estruturas mundanas emitem. O número de criaturas que podem ver o espetáculo de sombras é igual ao seu modificador de habilidade de Genjutsu. As figuras sombrias não fazem som, mas podem dançar, correr, mover-se, beijar, lutar, etc. A maioria das figuras que você pode criar é baseada em criaturas que você pode ter visto antes.",
  },
  {
    key: "cancao-suave",
    nome: "Canção Suave",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Concentração, até 10 minutos",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Auditivo"],
    descricao: "Você começa a cantarolar uma melodia ou falar uma frase de sua escolha. Quando faz isso, todas as criaturas dispostas dentro de 30 pés de você começam a se sentir revitalizadas pela sua melodia. Durante a duração, você não gasta chakra para manter este jutsu; em vez disso, deve gastar uma ação bônus nos turnos subsequentes para mantê-lo. Criaturas que começam seus turnos dentro do alcance ganham vantagem em testes de resistência contra Genjutsus com a palavra-chave Auditivo, independentemente de quaisquer outras palavras-chave que o Jutsu possa ter. Adicionalmente, Genjutsus com as palavras-chave Auditivo e Desprevenido perdem a palavra-chave Desprevenido ao afetar criaturas beneficiadas por este jutsu.",
  },
  {
    key: "eco-estrondoso-e-silencioso",
    nome: "Eco Estrondoso e Silencioso",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "próprio (cone de 30 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Visual", "Desprevenido"],
    // NOTE: fonte só mostra os tiers "Sucesso Crítico" e "Falha Crítica" para esta entrada (sem linhas
    // simples "Sucesso"/"Falha") — mantido como está, não inventado.
    descricao:
      "Você grita em um rugido silencioso e enganador, então cobre as mãos ao redor da boca enquanto grita. Todas as criaturas de sua escolha em um cone de 30 pés à sua frente devem fazer um teste de resistência de Sabedoria.\nSucesso Crítico: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha Crítica: A criatura afetada fica cega em uma falha de resistência. No final de cada um de seus turnos, o alvo pode fazer outro teste de resistência para encerrar este efeito. Além disso, a criatura sofre 4d6 de dano psíquico no turno em que falhou o teste e 4d6 de dano psíquico no início do próximo turno do conjurador.",
  },
  {
    key: "rejeicao-de-pensamento",
    nome: "Rejeição de Pensamento",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando sofreria dano.",
    alcance: "90 pés (raio de 10 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao:
      "Você captura um instantâneo da dor que sente e tenta injetá-la na mente de uma criatura dentro do alcance. Selecione um ponto que você possa ver dentro do alcance, onde você envia sua projeção psíquica, que então explode afetando todas as criaturas dentro de 10 pés do ponto escolhido. Todas as criaturas afetadas devem fazer um teste de resistência de Sabedoria.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada sofre 4d6 de dano psíquico.\nFalha Crítica: A criatura afetada ganha 1 condição de Deslumbrado e sofre 4d6 de dano psíquico.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de D, aumente o custo deste jutsu em 3 e o dano em 1d6.",
  },
  {
    key: "sobressalto",
    nome: "Sobressalto",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "90 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao:
      "Você tece uma imagem projetada para assustar e assombrar uma criatura por um momento. Selecione uma criatura que você possa ver dentro do alcance; ela deve fazer um teste de resistência de Carisma. Uma criatura imune a ficar amedrontada é imune aos efeitos deste jutsu.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada é assustada e encerra a concentração em um jutsu no qual está concentrada, com o custo base mais alto.\nFalha Crítica: A criatura afetada é assustada e encerra a concentração em todos os jutsus nos quais está concentrada.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de D, aumente o custo deste jutsu em 3 e o número de criaturas que você pode alvejar em +1.",
  },
  {
    key: "risada-descontrolada",
    nome: "Risada Descontrolada",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "FN (Pó de Riso)"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Auditivo", "Inalação"],
    descricao:
      "Uma criatura de sua escolha que você possa ver dentro do alcance percebe tudo como extremamente engraçado e entra em uma crise de riso se este jutsu a afetar. O alvo deve fazer um teste de resistência de Sabedoria. Se a criatura for danificada, o jutsu termina imediatamente. Uma criatura com um escore de Inteligência de 4 ou menos não é afetada. Uma criatura com um escore de Sabedoria de 15 ou mais faz seu teste com vantagem.\nSucesso Crítico: A criatura afetada consegue resistir aos efeitos deste jutsu.\nSucesso: A criatura afetada consegue resistir à maior parte dos efeitos deste jutsu, mas fica incapaz de realizar reações até o início de seu próximo turno.\nFalha: A criatura afetada sucumbe a uma crise de riso, caindo prostrada e sendo incapaz de realizar reações. Uma criatura rindo refaz seu teste de resistência ao final de cada um de seus turnos para encerrar os efeitos deste jutsu.\nFalha Crítica: A criatura afetada cai em uma crise de riso, ficando prostrada e incapacitada. Uma criatura rindo refaz seu teste de resistência ao final de cada um de seus turnos para encerrar os efeitos deste jutsu.",
  },
  {
    key: "filme-de-pensamento",
    nome: "Filme de Pensamento",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você toma quando sofre dano psíquico.",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Genjutsu", "Tátil"],
    descricao: "Você manifesta uma barreira psíquica projetada para proteger sua mente do dano que outra criatura causaria a ela. Quando você sofreria dano psíquico, você reduz o dano recebido em 3d6. Além disso, você ganha um bônus de 1d4 em testes de resistência feitos para resistir aos efeitos de um Genjutsu, se houver.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de D, aumente o custo deste jutsu em 3 e a redução de dano em 1d6.",
  },
  {
    key: "rosto-desinteressante",
    nome: "Rosto Desinteressante",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "10 minutos",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual"],
    descricao: "Uma criatura disposta que você tocar tem seu rosto distorcido até se tornar o mais mundano possível. Tanto que eles se tornam absolutamente únicos e incapazes de se destacar. Durante a duração, eles se tornam irreconhecíveis e não podem ser identificados em meio a uma multidão. Uma criatura que tente ver através desta ilusão deve fazer um teste de Sabedoria (Intuição) ou Sabedoria (Ilusões) contra o seu CD de resistência de Genjutsu. Em caso de sucesso, ela se torna imune aos efeitos deste genjutsu pelas próximas horas.",
  },
  {
    key: "armas-das-trevas",
    nome: "Armas das Trevas",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Auto",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Tátil"],
    descricao: "Você conjura adagas feitas de escuridão e medo. Quando elas atingem uma criatura alvo, elas instilam um terrível senso de terror nela. A lâmina é semelhante em tamanho e forma a um Kunai, e dura pela duração. Essas adagas são apenas ilusões, mas parecem extremamente reais ao atingir uma criatura. Você pode lançá-las até 60 pés antes de se dissiparem. Você pode gastar sua ação para fazer um ataque de Genjutsu corpo a corpo ou à distância contra uma criatura alvo dentro do alcance. Em caso de acerto, a criatura alvo sofre 5d4 de dano psíquico. Se você lançar a adaga ilusória, ela se dissolve e se reforma em sua mão após colidir com uma criatura ou superfície.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de D, aumente o custo deste jutsu em 3. Se este jutsu for conjurado como Rank C ou superior, aumente o dano em 1d4. Se este jutsu for conjurado como Rank B, você pode fazer dois ataques em vez de um. Se este jutsu for conjurado como Rank A ou superior, você pode adicionar seu modificador de habilidade de Genjutsu ao dano causado. Se este jutsu for conjurado como Rank S, você pode fazer três ataques em vez de um.",
  },
  {
    key: "agarrar-das-viboras",
    nome: "Agarrar das Víboras",
    tipo: "genjutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (raio de 30 pés)",
    duracao: "1 minuto",
    componentes: ["SM", "MC", "FN (Kit de Veneno)"],
    custoChakra: 5,
    palavrasChave: ["Genjutsu", "Visual", "Inalação", "Desprevenido"],
    // NOTE: o texto de Falha Crítica é cortado exatamente na fronteira das páginas 262/263 da fonte
    // ("...com desvantagem" — a frase continua na página 263, onde "Rank C" começa, fora do escopo desta extração).
    descricao:
      "Você libera um veneno inodoro no ar, usando 1 carga do seu Kit de Veneno, afetando criaturas dentro de 30 pés que o inalam. Criaturas dentro do alcance devem fazer um teste de resistência de Sabedoria. Se uma criatura envenenada for curada da condição de envenenamento causada por este jutsu, ele termina imediatamente.\nSucesso Crítico: A criatura afetada consegue resistir aos efeitos deste jutsu e se torna imune a ele pelas próximas 24 horas.\nSucesso: A criatura afetada consegue resistir aos efeitos deste jutsu.\nFalha: A criatura afetada fica envenenada pelo próximo minuto e começa a ver vislumbres de cobras e outras bestas répteis convergindo para ela. No início do turno de uma criatura envenenada, ela deve fazer um teste de Sabedoria (Acrobacia) contra o seu CD de resistência de Genjutsu. Em caso de falha no teste, ela fica restrita pelas serpentes até o início do próximo turno.\nFalha Crítica: A criatura afetada fica envenenada pelo próximo minuto e começa a ver vislumbres de cobras e outras bestas répteis convergindo para ela. No início do turno de uma criatura envenenada, ela deve fazer um teste de Sabedoria (Acrobacia) com desvantagem [TEXTO TRUNCADO NA FONTE — continua na página 263, fora do escopo desta extração].",
  },
];
