import type { JutsuDefinition } from "@/lib/jutsu/types";

export const medicoJutsu: JutsuDefinition[] = [
  {
    key: "ninjutsu-medico-virtude",
    nome: "Ninjutsu Médico: Virtude",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "1 Turno",
    componentes: ["SM", "MC"],
    custoChakra: 1,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você toca uma criatura que permita seu toque, a enchendo de vitalidade. Se a criatura tiver pelo menos 1 Ponto de Vida, a criatura ganha uma quantidade de Pontos de Vida Temporários igual a 1d4 + seu Modificador de Habilidade com Ninjutsu. Os Pontos de Vida Temporários são perdidos no final do próximo turno da criatura.",
  },
  {
    // NOTE: esta é a primeira das duas impressões de "Arma Sinistra" encontradas nas páginas 49-50 (a segunda, marcada [NOVO], aparece logo a seguir como "ninjutsu-medico-arma-sinistra-novo"). Textos e valores muito semelhantes (tema "Ceifeiro" com dano necrótico 1d6/1d12); mantidas ambas por não ser possível determinar qual é a versão vigente.
    key: "ninjutsu-medico-arma-sinistra",
    nome: "Ninjutsu Médico: Arma Sinistra",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Toque",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC", "A (Qualquer)"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Fuinjutsu", "Medicinal"],
    descricao: "Você realiza rapidamente selos de mão, invocando seu chakra medicinal e o fundindo a sua arma com uma coloração escura, melhorando sua arma. Você não perde a concentração nesse Jutsu por receber dano. Pela duração, a arma afetada por esse Jutsu fica encantada com chakra necrótico. Armas encantadas por esse Jutsu concedem 1d6 de dano Necrótico adicional a seus ataques com a arma, até o máximo de 2 vezes por turno. Se a criatura atingida tiver recuperado Pontos de Vida antes da rolagem de iniciativa, o dano aumenta para 1d12. Uma vez por Rodada, criaturas atingidas pela arma recebem efeitos de cura reduzidos pela metade.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3. Se for conjurado Rank-B ou acima, aumente o dano desse Jutsu em 1 dado. Se for conjurado Rank-S ou acima, criaturas atingidas por essa arma ficam impossibilitadas de ganhar Pontos de Vida pela duração desse Jutsu.",
  },
  {
    key: "ninjutsu-medico-armadura-acida",
    nome: "Ninjutsu Médico: Armadura Ácida",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "10 Minutos",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você manifesta chakra ácido na forma de uma aura altamente perigosa ao que reage golpes seus ou feitos por inimigos. Você ganha 14 de Vida Temporária. Criaturas que forem o atacar corpo a corpo recebem 6 de dano Ácido para cada vez que eles forem causar dano, enquanto você possuir sua Vida Temporária garantida por esse Jutsu. Criaturas que o atacarem com armas ou punhos cujo o rank seja igual ou menor a esse jutsu recebem -1 de penalidade ao dano até serem reparadas por Reparo ou Jutsus com a palavra-chave medicinal. Uma arma ou parte do corpo que chegar a -5 de penalidade é completamente devorada pelo ácido.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3, a Vida Temporária em 7 e o dano ácido em 3.",
  },
  {
    // NOTE: segunda impressão de "Arma Sinistra" (marcada "[NOVO]" no livro), na coluna direita da pág. 50 — texto quase idêntico ao da entrada "ninjutsu-medico-arma-sinistra" (tema idêntico de arma amaldiçoada pelo Ceifeiro). A tag "[NOVO]" ficou posicionada de forma ambígua entre as duas colunas no OCR; presumida como pertencente a esta versão revisada por estar mais próxima do título.
    key: "ninjutsu-medico-arma-sinistra-novo",
    nome: "Ninjutsu Médico: Arma Sinistra (Novo)",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Toque",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "A (Qualquer)"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Médico", "Fuinjutsu"],
    descricao: "Você entrelaça selos de invocação, infundindo-os em sua arma e o chakra de liberação médica que se manifesta como um eco de chakra negro do ceifador aprimora a arma que você toca. Você não pode perder a concentração deste jutsu como resultado de dano. Durante a duração, a arma afetada por este jutsu é aprimorada pelo chakra necrótico negro do ceifador. Armas aprimoradas causam 1d6 de dano necrótico adicional duas vezes por turno. Se a criatura afetada tiver recuperado pontos de vida antes desta jogada de iniciativa, este dano é aumentado para 1d12. Uma vez por rodada, criaturas que recebem dano necrótico desta arma aprimorada reduzem o número de pontos de vida que recuperam pela metade.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3. Se este jutsu for conjurado no Rank B ou superior, aumente o dano que este jutsu causa em 1d6 ou 1d12 respectivamente. Se este jutsu for conjurado no Rank S, criaturas que receberem dano necrótico desta arma aprimorada não poderão recuperar pontos de vida durante a duração deste jutsu.",
  },
  {
    key: "ninjutsu-medico-aura-restaurativa",
    nome: "Ninjutsu Médico: Aura Restaurativa",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "20 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você molda seu chakra em uma teia e a atira em múltiplas criaturas, as curando. Escolha até no máximo de 3 criaturas em seu alcance. Você as cura por 2d4. Esse Jutsu não terá efeito em zumbis ou construções.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o número de criaturas que você pode afetar em 1. Se for conjurado Rank-B ou acima, troque o dado de cura para d6. Se conjurado Rank-S ou acima, troque o dado para d8.",
  },
  {
    key: "ninjutsu-medico-cauda-acida",
    nome: "Ninjutsu Médico: Cauda Ácida",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Cone de 15 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você manifesta seu chakra ácido na forma de uma cauda, seja se um grande dragão ou de um leão. Realize um Ataque Corpo-a-Corpo de Ninjutsu contra todas criaturas no alcance. Para cada alvo atingido, você causa 2d6 + 1d6 de dano Ácido para cada criatura atingida após a primeira. Adicionalmente, todas as criaturas atingidas devem fazer uma Salvaguarda de Força, ganhando 1 rank de Corroído em um teste falho.",
  },
  {
    // NOTE: entrada atípica no livro — usa "Nível" no lugar de "Rank" e tem Tempo de Conjuração/Alcance "Especial" (definidos por qual das 3 variações de ação é escolhida ao conjurar); as três variações foram preservadas dentro do texto de descrição por não haver campo próprio na interface.
    key: "ninjutsu-medico-adepto-da-cura",
    nome: "Ninjutsu Médico: Adepto da Cura",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "Especial",
    alcance: "Especial",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Médico"],
    descricao: "Você cobre suas mãos com chakra que brilha com um tom verde quente, reativando o processo reprodutivo das células de uma criatura, fechando suas feridas. Este jutsu é único por si só, pois pode ser lançado em uma das três variações, cada uma levando mais tempo para ser lançada do que a anterior. Este jutsu não tem efeito em mortos-vivos ou constructos. 1 Ação: Quando conjurado, o alcance deste jutsu se torna Toque e uma criatura afetada recupera um número de pontos de vida igual a 3d8. 1 Ação Bônus: Quando conjurado, o alcance deste jutsu se torna Próprio (raio de 15 pés) e todas as criaturas de sua escolha no alcance recuperam 8 pontos de vida. 1 Ação de Turno Completo: Quando conjurado, o alcance deste jutsu se torna Próprio (raio de 30 pés) e todas as criaturas de sua escolha no alcance recuperam 3d8+5 pontos de vida.",
    emNiveisSuperiores: "Para cada nível que você conjurar este jutsu acima do Nível D, aumente o custo deste jutsu em 3 e a cura em +1 dado. Se você não rolar dados para cura ao conjurar este jutsu, você aumenta a cura em +4.",
  },
  {
    key: "ninjutsu-medico-chicote-acido",
    nome: "Ninjutsu Médico: Chicote Ácido",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você manifesta chakra ácido na forma de dois chicotes ácidos para segurar e corroer seus inimigos. Realize dois Ataques a Distância de Ninjutsu, em um acerto, cause 2d6 de dano ácido. Adicionalmente, em um acerto, a criatura acertada deve realizar uma Salvaguarda de Força. Caso falhe o teste, a criatura fica Agarrada pelos seus chicotes. Uma criatura Agarrada por esse Jutsu recebe 1d6 de dano ácido no início de seu turno.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o número de ataques em 1.",
  },
  {
    key: "ninjutsu-medico-bom-fruto",
    nome: "Ninjutsu Médico: Bom Fruto",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["SM", "M"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Toque até um total de 5 frutas ou nozes as infundindo com seu chakra medicinal pela duração. Uma criatura pode se utilizar de sua ação para comer uma dessas 5 frutas. Comer uma fruta infundida por esse Jutsu cura a criatura em 1 de Ponto de Vida e a deixa satisfeita e nutrida por 1 dia. Uma criatura não pode se beneficiar desse Jutsu mais de 2 vezes por Descanso Longo. A fruta perde seus benefícios após 24 horas se não for consumida a partir do conjuramento desse Jutsu.",
  },
  {
    key: "ninjutsu-medico-corda-acidas",
    nome: "Ninjutsu Médico: Corda Ácidas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Cubo de 20 pés)",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você manifesta chakra ácido na forma de arame farpado, o suficiente para encher um cubo de 20 pés originário de você. Durante a duração, criaturas, excluindo você, que começariam seu turno ou entrariam pela primeira vez em seu turno, na área afetada, elas recebem 7 de dano ácido e mais 7 de dano ácido para cada 5 pés que elas se movessem pela área afetada. Uma criatura não pode receber dano do mesmo quadrado de 5 por 5 pés mais de uma vez por rodada.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o tamanho da área em 5 pés.",
  },
  {
    key: "ninjutsu-medico-deteccao-de-venenos-e-doencas",
    nome: "Ninjutsu Médico: Detecção de Venenos e Doenças",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "10 Minutos",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal", "Sensorial"],
    descricao: "Pela duração desse Jutsu, você pode sentir a presença e localização de venenos, doenças e criaturas venenosas a 30 pés de você. Esse jutsu pode penetrar barreiras contanto que sejam até 1 pé de espessura, 1 polegada de metal comum, um tecido de couro ou 3 pés de lã ou terra.",
  },
  {
    key: "ninjutsu-medico-corrupcao",
    nome: "Ninjutsu Médico: Corrupção",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Medicinal", "Fuinjutsu"],
    descricao: "Você utiliza seu chakra médico de forma contorcida para controlar e espalhar uma maldição em uma área. Selecione um espaço que você possa ver dentro de seu alcance. Você manifesta a partir desse ponto uma nuvem corrupta de 5 pés onde, no começo de seu turno pela duração desse jutsu, essa nuvem cresce em 5 pés. Toda criatura que adentrar a área corrompida deve realizar uma Salvaguarda de Carisma. Em um teste falho, as mesmas recebem 3d12 de dano Necrótico. Em um sucesso, criaturas não recebem dano.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em 1d12.",
  },
  {
    key: "ninjutsu-medico-elixir-de-cura",
    nome: "Ninjutsu Médico: Elixir de Cura",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Minuto",
    alcance: "Toque",
    duracao: "1 Hora",
    componentes: ["SM", "MC", "FN (1 Carga de um Kit Médico)"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você utiliza seu kit médico para criar um elixir de cura que é colocado dentro de um frasco que aparece em sua mão. O elixir mantém a potência de cura pelo tempo de duração desse Jutsu ou até ser consumido. Como uma ação, uma criatura pode beber do elixir ou dar de beber a outra. A criatura que beber o elixir recupera 4d6+6 de Pontos de Vida e remove imediatamente 2 ranks de Sangramento ou Envenenado.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3. Se conjurado Rank-B ou acima, a criatura que beber regenera 4d8+12 de Pontos de Vida e cura imediatamente das condições de Envenenado, Atordoado ou Fraqueio ou remove 5 ranks de Sangramento. Se conjurado Rank-S ou acima, a criatura que beber regenera 4d12+24 e cura imediatamente quaisquer efeitos que não sejam Exaustão, Propenso ou Invisível.",
  },
  {
    key: "ninjutsu-medico-feixe-acido",
    nome: "Ninjutsu Médico: Feixe Ácido",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Linha de 60 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você manifesta chakra ácido na forma de um feixe poderoso capaz de derreter tudo que esteja em seu caminho. Todas as criaturas em uma linha de 60 pés originando de você devem fazer uma Salvaguarda de Destreza. Em um teste falho, as mesmas recebem 3d6 de dano ácido e, no começo do turno da criatura, recebem 3d4 de dano ácido. Construções e estruturas feitas de terra, metal ou madeira recebem o dobro de dano enquanto o ácido corrói o material.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em +1 dado para os dois danos.",
  },
  {
    key: "ninjutsu-medico-estouro-venenoso",
    nome: "Ninjutsu Médico: Estouro Venenoso",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal", "Conflito"],
    descricao: "Você molda seu chakra médico dentro de seu estômago que começa a aquecer como uma liberação do estilo fogo, lançando uma gosta verde / roxo escuro de sua boca ou mãos. Todas as criaturas dentro de um raio de 10 pés centralizadas em um ponto que você pode ver dentro de seu alcance devem realizar uma Salvaguarda de Destreza. Criaturas que falharem o teste sofrem 2d8 de dano Venenoso e recebem 1 rank de Envenenado. Em um sucesso, criaturas só recebem metade do dano e nenhum efeito adicional.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3, o dano em 1d8 e o raio da esfera em 5 pés.",
  },
  {
    key: "ninjutsu-medico-feridas",
    nome: "Ninjutsu Médico: Feridas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você manifesta seu chakra medicinal de uma forma contorcida com o objetivo de abrir feridas e alcançar a carne. Faça um Ataque a Distância de Ninjutsu contra uma criatura que esteja em alcance e que você possa ver. Em um acerto, você causa 3d10 de dano Necrótico. Criaturas que têm ranks de Sangramento transformam um dos ranks em 1 rank de Lacerado.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em +1 dado.",
  },
  {
    key: "ninjutsu-medico-extracao-toxica",
    nome: "Ninjutsu Médico: Extração Tóxica",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Toque",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você consegue manipular quaisquer substâncias que estejam corrompidas por material tóxico ou venenoso, como se fosse um mestre do estilo água. Como uma ação em seu turno, uma criatura que você tocar pode ter quaisquer efeitos de venenos ou toxinas retirados de seu corpo pela pele. A substância sai em forma de uma água escura que você pode colocar dentro de um frasco, podendo usar mais tarde, ou apenas despejando no chão. O veneno extraído continua em sua potência pelos próximos 10 minutos e pode ser despejado em uma arma ou utilizado como componente para outro Jutsu que demanda um Kit de Veneno.",
  },
  {
    key: "ninjutsu-medico-golpe-ensinado",
    nome: "Ninjutsu Médico: Golpe Ensinado",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "1 Rodada",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você injeta sua mão nos músculos do inimigo tentando prejudicar seu movimento. Pela próxima vez que você atingir uma criatura com um Ataque Corpo-a-Corpo ou a Distância com ou sem arma antes desse Jutsu acabar, seu inimigo adicionalmente deve realizar uma Salvaguarda de Força. Em um teste falho, a criatura fica Restrita até o final de seu próximo turno. Uma criatura Grande ou maior tem vantagem na Salvaguarda. Enquanto restrita por esse Jutsu, o alvo recebe 1d8 de dano Venenoso no começo de seu turno. Jutsus ou efeitos que podem remover condições de Envenenado podem também remover o efeito causado por esse Jutsu.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em +1 dado.",
  },
  {
    key: "ninjutsu-medico-fragmentos-venenosos",
    nome: "Ninjutsu Médico: Fragmentos Venenosos",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Cubo de 15 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você molda seu chakra medicinal em suas mãos para imitar uma substância e estrutura imitando uma liberação de terra, a liberando em um cristal verde / roxo escuro e gosmento que sai do próprio chão. Todas as criaturas em um cubo de 15 pés originado de você devem fazer uma Salvaguarda de Constituição. Em um teste falho, criaturas recebem 2d12 de dano Venenoso e têm seu movimento reduzido em 10 pés pelo próximo minuto. Caso obtenha sucesso no teste, criaturas recebem metade do dano e nenhum efeito adicional. Jutsus ou efeitos que podem remover condições de Envenenado podem também remover o efeito causado por esse Jutsu.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3, o dano em +1 dado e o tamanho do cubo em +5 pés. Caso conjurado Rank-B ou acima, criaturas que falharem o teste também recebem 1 rank de Envenenado. Caso conjurado Rank-A ou acima, criaturas que falharem o teste também tratam a área afetada como terreno difícil.",
  },
  {
    // NOTE: campo Duração impresso como "Especial" — o próprio texto descreve a duração real (a esfera flutua por 1 minuto ou até ser utilizada).
    key: "ninjutsu-medico-limpeza-acida",
    nome: "Ninjutsu Médico: Limpeza Ácida",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (15 pés)",
    duracao: "Especial",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Esse Jutsu lhe capacita a controlar ácido a sua vontade. Criaturas a 15 pés de distância de você que contenham o efeito Corroído se liberam desse efeito enquanto você tira os resquícios ácidos em uma esfera acima de sua cabeça. A esfera flutua por 1 minuto ou até ser utilizada. A próxima vez que você conjurar um Jutsu que dê dano Ácido, você pode usar a sua esfera, conjurando o Jutsu 1 rank acima sem custo adicional e ignorando limitações de maior conjuração.",
  },
  {
    key: "ninjutsu-medico-murchar-e-florescer",
    nome: "Ninjutsu Médico: Murchar e Florescer",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés (Círculo de 10 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você conduz seu chakra medicinal o moldando para invocar a vida e a morte. Todas as criaturas da sua escolha em um círculo de 10 pés centralizado no ponto que você pode ver dentro de seu alcance devem realizar uma Salvaguarda de Constituição. Em um teste falho as criaturas recebem 3d6 de dano Necrótico. Adicionalmente, uma criatura da sua escolha que esteja dentro da área cura por 3d6 de Pontos de Vida.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3, o dano em 1d6 e a cura em 1d6.",
  },
  {
    // NOTE: Custo impresso como "5 Chakra e 1 Dado de Vida" — custoChakra reflete apenas a parcela em chakra; há um custo adicional de 1 Dado de Vida não representado pela interface.
    key: "ninjutsu-medico-mascara-sinistra",
    nome: "Ninjutsu Médico: Máscara Sinistra",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal", "Fuinjutsu"],
    descricao: "Você conjura dois selos e os funde junto ao seu chakra medicinal, manifestando a máscara do Ceifeiro da Morte. A máscara colhe parte de sua força vital ao ser vestida, porém garante a você um grande poder em troca. Você não perde concentração nesse jutsu ao tomar dano. Seus ataques ganham 1d4 de dano Necrótico adicional pela duração. Se um ataque ou Jutsu que você conjurar já der dano Necrótico, o dano adicional se torna 1d8. Adicionalmente, em ataques críticos ou ataques que derem o máximo de dano possível na rolagem de dado, caso o personagem que você esteja atingindo seja classificado como um jogador, o jogador perde 1 Dado de Vida. Caso seja classificado um Adversário, o adversário perde 1 Dado de Tenacidade.",
  },
  {
    key: "ninjutsu-medico-necrose",
    nome: "Ninjutsu Médico: Necrose",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você funde seu chakra medicinal em suas mãos na tentativa de corroer seu alvo. Realize um Ataque Corpo-a-Corpo contra uma criatura que você possa tocar. Em um acerto, o alvo recebe 2d12 de dano Necrótico. Plantas recebem o dobro de dano. Adicionalmente, criaturas atingidas devem realizar uma Salvaguarda de Constituição. Em um teste falho, elas recebem 1 rank de Envenenamento enquanto o corpo da criatura começa a abrir feridas cicatrizadas.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em 1d12.",
  },
  {
    key: "ninjutsu-medico-misseis-corruptos",
    nome: "Ninjutsu Médico: Mísseis Corruptos",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você conjura seu chakra medicinal em formato de uma bala ou esfera feita para ser atirada como um míssil. Realize um Ataque a Distância de Ninjutsu contra uma criatura dentro de seu alcance que você possa ver. Em um acerto, cause 2d8 + Seu Modificador de Ninjutsu em dano Necrótico. Adicionalmente, a próxima vez que a criatura afetada for ganhar chakra pelo próximo minuto, a criatura receberá apenas metade do valor.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em 1d8.",
  },
  {
    key: "ninjutsu-medico-saude-inversa",
    nome: "Ninjutsu Médico: Saúde Inversa",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Reação, que você pode usar ao ver uma criatura recuperando Pontos de Vida",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você utiliza seu chakra medicinal de forma inversa para inverter efeitos de cura. Quando você vir uma criatura sendo curada, seja por ela ou por outra criatura, você pode interferir nessa cura. Role 4d6, reduzindo a quantidade de cura recebida pela criatura pelo resultado da rolagem.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3, o número de alvos em +1 e a quantidade de redução na cura em 1d6.",
  },
  {
    key: "ninjutsu-medico-picada-de-abelha",
    nome: "Ninjutsu Médico: Picada de Abelha",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "A (Quaisquer com propriedade de Arremesso)"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você funde seu chakra medicinal a uma arma de arremesso a encantando. Realize um Ataque a Distância de Ninjutsu contra uma criatura que você possa ver dentro de seu alcance. Em um acerto, cause o dano de sua arma + 2d6 de dano Venenoso e a criatura deve realizar uma Salvaguarda de Constituição. Em um teste falho, a criatura fica Envenenada por 1 minuto.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em 1d6.",
  },
  {
    key: "ninjutsu-medico-presas-toxicas",
    nome: "Ninjutsu Médico: Presas Tóxicas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC", "FN (1 Carga de um Kit Venenoso)"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você cobre suas mãos em um líquido venenoso e usa seu chakra médico para manter sua letalidade e viscosidade. Pela duração desse Jutsu, suas mãos, pés ou dentes são completamente cobertos por essa substância tóxica, prontas para serem usadas como armas letais. Pela duração, você pode utilizar-se de sua ação para fazer um Ataque Corpo a Corpo de Ninjutsu. Em um acerto, o alvo recebe 3d4 de dano Venenoso e, uma vez por turno, você pode forçar a criatura a fazer uma Salvaguarda de Constituição. Em um teste falho, o alvo recebe 1 rank de Envenenamento.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em 1d4. Caso seja conjurado Rank-B ou acima, você pode realizar 2 ataques com 1 ação ao invés de apenas 1 ataque. Caso conjurado Rank-S, você pode realizar até 3 ataques.",
  },
  {
    key: "ninjutsu-medico-choque-venenoso",
    nome: "Ninjutsu Médico: Choque Venenoso",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você conjura seu chakra medicinal imitando correntes elétricas violentas. Selecione uma criatura que você possa ver em seu alcance. A criatura deve realizar uma Salvaguarda de Constituição. Em um teste falho, a criatura recebe 3d8 de dano Venenoso e ganha 1 rank de Envenenado; caso suceda, apenas recebe metade do dano e nenhum efeito adicional. Criaturas que forem envenenadas por esse Jutsu sofrem -1 de penalidade para Salvaguardas de Força para cada rank que tiverem.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em 1d8.",
  },
  {
    key: "ninjutsu-medico-tecnica-de-abelha-mel",
    nome: "Ninjutsu Médico: Técnica de Abelha Mel",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal"],
    descricao: "Você invoca um enxame de abelhas feitas pelo seu chakra medicinal que atacam uma criatura que você vê em seu alcance. Realize um Ataque a Distância de Ninjutsu. Em um acerto, cause 2d6 de dano Venenoso e o alvo deve fazer uma Salvaguarda de Constituição. Em um teste falho, o alvo sente seu corpo reagir às picadas de abelha, com seus músculos ficando inflamados pelo próximo minuto. No começo do turno da criatura atingida, ela faz uma rolagem de 1d12. Caso o resultado seja 1 ou 2, a dor começa a ficar insuportável, recebendo a condição de Inconsciente até o final de seu turno. Criaturas no final de seu turno podem refazer a Salvaguarda de Constituição, encerrando a inflamação em um sucesso. Outra criatura da sua escolha que esteja a 20 pés do alvo recupera Pontos de Vida igual ao dano causado. Jutsus que retiram a condição de Envenenado também retiram o efeito desse Jutsu.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em 1d8.",
  },
  {
    // NOTE: Custo impresso como "5 Chakra e 1 Dado de Vida" — custoChakra reflete apenas a parcela em chakra; há um custo adicional de 1 Dado de Vida não representado pela interface.
    key: "ninjutsu-medico-sifao-sinistro",
    nome: "Ninjutsu Médico: Sifão Sinistro",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Medicinal", "Fuinjutsu"],
    descricao: "Você conjura dois selos e os funde junto ao seu chakra, manifestando a mão do Ceifeiro da Morte. Sua foice colhe parte de sua força vital para invocá-la, porém garante em troca um grande poder. Selecione uma criatura que você pode ver em seu alcance; essa criatura deve realizar uma Salvaguarda de Carisma. Em um teste falho, a mesma recebe 2d8 + Seu Modificador de Ninjutsu em dano Necrótico e, dependendo da classificação de seu alvo, aplique um dos efeitos abaixo: Se a criatura for um jogador, o jogador atingido perde 1 Dado de Vida ou metade do dano em um teste bem-sucedido (nenhuma perda). Se a criatura for um Adversário, você rouba 1 Dado de Tenacidade que pode ser usado como bônus para um Teste de Perícia, Teste de Habilidade ou Salvaguarda em um teste falho.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3, o dano em 1d6 e o número de alvos em +1.",
  },
  {
    key: "ninjutsu-medico-tiro-venenoso",
    nome: "Ninjutsu Médico: Tiro Venenoso",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "medico",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Medicinal", "Conflito"],
    descricao: "Você inala ar, acumulando saliva misturada com seu chakra medicinal antes de cuspir essa saliva. Realize um Ataque a Distância de Ninjutsu; em um acerto, cause 3d6 de dano Venenoso e criaturas atingidas sofrem uma penalidade de 1d4 à sua próxima rolagem de ataque ou teste de perícia até o final do turno dessa criatura. A penalidade não acumula.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3. Se conjurado Rank-B ou acima, aumente o número de ataques em +1. Se conjurado Rank-S ou acima, aumente o número de ataques em +2.",
  },
];
