import type { JutsuDefinition } from "@/lib/jutsu/types";

/** Ninjutsu Não Elemental, Rank E e D — Anotações do Jiraya, p.5-19. */
export const naoElementalJutsu: JutsuDefinition[] = [
  // Rank E
  {
    key: "arte-de-elemento-formacao-de-capa-da-invisibilidade",
    nome: "Arte de Elemento: Formação de Capa da Invisibilidade",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["FN"],
    custoChakra: 1,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você rapidamente se cobre com uma capa estilo camaleão enquanto estiver encostado em uma parede ou outra superfície. Role um Teste de Furtividade e adicione 1d4+1 como bônus para o Teste. Se alguma criatura for realizar um Teste de Percepção para tentar lhe encontrar, eles fazem esse teste com 1d4+1 de penalidade. Essa penalidade dura até você se mover a mais de 10 pés (3 metros) de sua localização atual.",
  },
  {
    key: "cordas-de-luz",
    nome: "Cordas de Luz",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés (9 metros)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 2,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você utiliza o seu Chakra para criar uma linha de selamento partindo do seus pés e se estendendo a um alvo que você possa ver em seu alcance. Criaturas atingidas devem realizar uma salvaguarda de Carisma, reduzindo a velocidade de deslocamento para 0 de ambos, tanto a sua quanto a de seu alvo, em uma tentativa falha. Isso pode ser usado com outros alvejando a mesma criatura, aumentando a dificuldade do teste em +1 para cada uso adicional na mesma criatura. As criaturas refazem a salvaguarda no fim de cada um de seus turnos.",
  },
  {
    key: "deesa-aprimorada",
    nome: "Deesa Aprimorada",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM"],
    custoChakra: 2,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você foca o seu chakra na última camada de sua pele, fornecendo a você resistência a dano Contundente, Cortante e Perfurante até o começo de seu próximo turno.",
  },
  {
    key: "brilhos-de-fogos-de-artificio",
    nome: "Brilhos de Fogos de Artifício",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["FN"],
    custoChakra: 2,
    palavrasChave: ["Ninjutsu", "Bukijutsu"],
    descricao:
      "Você utiliza um pacote de fogos de artifício e utiliza seu chakra para acender os pavios de cada um antes de jogar eles em um arco na sua frente. Criaturas em frente a você em um espaço de 15 pés (4,5 metros) devem realizar uma salvaguarda de Sabedoria, garantindo uma vantagem a você no seu próximo ataque contra as criaturas e desvantagem no ataque das criaturas contra você em um teste de resistência falho.",
  },
  {
    key: "maos-de-chakra",
    nome: "Mãos de Chakra",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés (9 metros)",
    duracao: "1 Minuto",
    componentes: ["MC"],
    custoChakra: 1,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Uma mão flutuante, espectral surge em um ponto que você determinou dentro do alcance. Essa mão permanece ativa pela duração ou até ser dissipada com uma Ação. A mão sumirá caso esteja a mais de 30 pés (9 metros) de distância de você ou caso você dissipe o Jutsu. Você pode utilizar a sua Ação para controlar a mão. Você pode usar a mão para manipular objetos, abrir uma porta ou baú destrancado, colocar ou retirar um item de um recipiente aberto, ou despejar conteúdos dentro de um frasco. Você pode mover a mão até 30 pés (9 metros) toda vez que você usar sua Ação para isso. A mão não pode atacar, ativar itens de chakra ou carregar mais do que 10 libras (0,5 kg).",
  },
  {
    key: "golpe-de-chakra",
    nome: "Golpe de Chakra",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Alcance da Arma",
    duracao: "1 Rodada",
    componentes: ["SM", "MC", "A (Qualquer)"],
    custoChakra: 2,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você deve realizar um ataque com uma arma contra uma criatura no alcance da arma para utilizar esse Jutsu, caso contrário o Jutsu falhará. Você imbui sua arma com uma linha fina de chakra permitindo que o golpe seja mais forte que o normal. Em um acerto, o alvo recebe 1d6 de dano extra.",
    emNiveisSuperiores: "Esse Jutsu aumenta sua efetividade em 1d6 com base em seu nível. (Nível 5 = 2d6, Nível 11 = 3d6, Nível 17 = 4d6).",
  },
  {
    key: "luz",
    nome: "Luz",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "1 Hora",
    componentes: ["MC"],
    custoChakra: 1,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você toca um objeto que não seja maior que 10 pés (3 metros) em qualquer direção. Até esse jutsu acabar, o objeto brilha em Luz Forte em um círculo de 10 pés (3 metros) de diâmetro e Luz Fraca por um adicional de 10 pés (3 metros) tendo um tom azulado. Cobrir totalmente o objeto com algo opaco também bloqueia a luz. O Jutsu acaba se você conjurar novamente a habilidade ou dissipar como sua ação. Se você tocar um objeto que esteja sendo segurado ou vestido por uma criatura hostil, a criatura pode realizar uma salvaguarda de Destreza para evitar o Jutsu.",
  },
  {
    key: "movimento-por-chakra",
    nome: "Movimento por Chakra",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM"],
    custoChakra: 1,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você transfere seu chakra para a sola de seus pés criando uma força sob o chão, que aumenta a sua velocidade de deslocamento momentaneamente. Aumente o seu deslocamento máximo em 10 pés (3 metros) até o final do seu próximo turno.",
    emNiveisSuperiores: "Esse Jutsu aumenta o deslocamento bônus em 5 pés (1.5 m) com base em seu nível. (Nível 5 = 15 pés, Nível 11 = 20 pés, Nível 17 = 25 pés).",
  },
  {
    key: "resistencia-aprimorada",
    nome: "Resistência Aprimorada",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Reação, que você pode usar ao falhar uma salvaguarda.",
    alcance: "Próprio",
    duracao: "1 Rodada",
    componentes: ["SM"],
    custoChakra: 2,
    palavrasChave: ["Ninjutsu"],
    descricao: "Você foca o seu chakra em seu corpo, o reforçando para aguentar os ataques. Você ganha um bônus de +1 para a próxima salvaguarda que fizer.",
    emNiveisSuperiores: "Esse jutsu aumenta a resistência em +1 baseado em seu nível. (Nível 5 = +2, Nível 11 = +3, Nível 17 = +4).",
  },
  {
    key: "pericia-aprimorada",
    nome: "Perícia Aprimorada",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Reação, que você pode usar ao falhar um Teste de Perícia",
    alcance: "Próprio",
    duracao: "1 Rodada",
    componentes: ["SM"],
    custoChakra: 2,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você foca o seu chakra em diferentes partes de seu corpo para aprimorar sua habilidade em completar uma tarefa. Quando você falhar em um Teste de Perícia que utiliza Força Física e que tenha como atributo (Força, Destreza ou Constituição), você pode adicionar +2 de bônus para o teste que você falhou. Ao utilizar esse jutsu, você só poderá usar o mesmo novamente após 10 minutos.",
    emNiveisSuperiores: "Esse jutsu aumenta o bônus em +2 baseado em seu nível. (Nível 5 = +4, Nível 11 = +6, Nível 17 = +8).",
  },
  {
    key: "selo-gravado-com-o-dedo",
    nome: "Selo Gravado com o Dedo",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Permanente",
    componentes: ["MC", "SC"],
    custoChakra: 1,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você foca seu chakra na ponta de seus dedos e utiliza o calor e energia aplicado em seus dedos para escrever palavras, desenhar ou fazer letras da sua escolha, com um limite de 20 palavras para cada ação utilizada. Essas palavras podem ser aplicadas a estruturas e construções e não causam dano. Essas palavras também podem ser aplicadas a criaturas dispostas, deixando tatuado permanentemente em sua pele.",
  },
  {
    key: "pulso-de-chakra",
    nome: "Pulso de Chakra",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés (1.5 metros)",
    duracao: "Instantâneo",
    componentes: ["SM"],
    custoChakra: 2,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Uma forte corrente de chakra é formada e explode de seu corpo. Cada criatura que esteja a 5 pés (1.5 m) de distância de você, que não seja você, deve realizar uma salvaguarda de Força ou receberá 2d4 de dano de Força e caem (condição: Caído).",
    emNiveisSuperiores: "Esse Jutsu aumenta a efetividade do jutsu em 2d4 com base em seu nível. (Nível 5 = 4d4, Nível 11 = 6d4, Nível 17 = 8d4).",
  },
  {
    key: "tecnica-de-fuga",
    nome: "Técnica de Fuga",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM"],
    custoChakra: 2,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você utiliza o seu chakra para soltar os nós em cordas, correntes e outras ferramentas utilizadas para lhe imobilizar. Isso lhe ajuda a entender qual o melhor plano para escapar enquanto estiver preso. Enquanto estiver Restringido ou Contido, você pode rolar Prestidigitação ao invés do teste ou salvaguarda necessários, com vantagem. Em caso de sucesso, você consegue se soltar da condição imposta.",
  },
  {
    key: "reparo",
    nome: "Reparo",
    tipo: "ninjutsu",
    rank: "E",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Minuto",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["MC"],
    custoChakra: 1,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Esse jutsu repara apenas uma pequena parte quebrada dentre duas peças, como cordas, correntes, dois pedaços de chave, uma capa rasgada ou um vazamento em um balde. Contanto que o dano não seja maior do que 1 pés (0.3m), você repara o objeto, sem deixar marcas.",
  },

  // Rank D
  {
    key: "arte-de-selamento-fraturar",
    nome: "Arte de Selamento: Fraturar",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés (18 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você infunde o seu chakra em um selo para tentar marcar uma criatura com o selo de descendência e então o quebra causando uma fratura no equilíbrio Yin e Yang de seu alvo. A criatura que você pode ver e esteja no alcance do jutsu deve realizar uma Salvaguarda de Carisma. E em uma tentativa falha, a criatura recebe 3d8 de Dano de Força e ganha 1 rank de Selado. Uma criatura com 3 ou mais ranks de Selado realiza a Salvaguarda com desvantagem.",
    emNiveisSuperiores:
      "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em 1d8. Se o Jutsu for conjurado no Rank-B ou maior, aumente a quantidade do rank de Selado aplicado para 2.",
  },
  {
    key: "100-palmas-de-buda",
    nome: "100 Palmas de Buda",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "10 pés (3 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você foca o seu chakra ao redor de seu corpo, formando a imagem de um Buda dourado ao seu redor e realizando múltiplos golpes com seus 100 braços. Realize um Ataque de Ninjutsu Corpo-a-Corpo, em um acerto, o alvo recebe 4d6 de Dano Contundente.",
    emNiveisSuperiores: "Para cada Rank que você conjurar esse jutsu acima do Rank-D, aumente o custo de chakra em 3 e o dano em 1d6.",
  },
  {
    key: "arte-de-selamento-bloquear",
    nome: "Arte de Selamento: Bloquear",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao:
      "1 Reação, que você pode realizar quando você ou um aliado que possa ver forem o alvo de um ataque ou forem realizar uma salvaguarda de um jutsu que tenha Fuinjutsu como Palavra-Chave.",
    alcance: "60 pés (18 metros)",
    duracao: "1 Rodada",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você funde o seu chakra em um selo para tentar manifestar o selo de proteção. Quando você ou um aliado for o alvo de um ataque ou forem realizar uma Salvaguarda ou um Teste de Perícia contra quaisquer Jutsu com a Palavra-Chave Fuinjutsu você invoca um totem de defesa para lhe fornecer proteção até o começo de seu próximo turno. Você ou o seu Aliado ganham +2 de bônus na sua CA e Salvaguardas contra Fuinjutsus e quando forem realizar um Teste de Perícia contra um Fuinjutsu, vocês ganham +2 de bônus na Perícia Ninshou.",
    emNiveisSuperiores:
      "Para cada Rank que você conjurar esse Jutsu acima de Rank-D, aumente o custo de chakra em 3. Se esse Jutsu for conjurado no Rank-B ou maior, aumente os bônus de CA e Salvaguarda para +3. Se esse Jutsu for conjurado no Rank-S ou maior, aumente o bônus de CA e Salvaguarda para +4.",
  },
  {
    key: "arte-de-selamento-reverberar",
    nome: "Arte de Selamento: Reverberar",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC", "SC", "A (Qualquer)"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você funde seu chakra em um selo, marcando uma arma que você tocou com o selo de veneração. Pela duração, o Dado de Dano da Arma é aumentado em +1. Se a arma já rola mais de 1 dado de dano aumente o tipo de dado em 1 estágio (d4 > d6 > d8 > d10 > d12). A arma fundida não pode receber efeitos que mudariam o tipo de dano, dado, aumento de dano ou aumento de status por qualquer Jutsu ou Traço durante esse Jutsu. Caso receba, a arma se quebra em pedaços. Se essa arma critar o dado, o selo se rompe e você pode rolar quaisquer dados iguais a 1, usando o segundo resultado. Após isso, o Jutsu acaba imediatamente.",
  },
  {
    key: "aura-opressiva",
    nome: "Aura Opressiva",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "10 pés (3 metros)",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você molda seu chakra em uma aura que começa a se formar ao seu redor, com intensidade o suficiente para ser vista a olho nu e essa aura move objetos pequenos e soltos como poeira, folhas e gotas d'água. Criaturas que estejam a 10 pés (3 metros) de você quando esse jutsu é ativado devem realizar uma Salvaguarda de Força para resistirem a cair de joelhos e ficarem Caídos pela duração, ficando impossibilitados de se levantarem enquanto estiverem dentro da aura. Criaturas que ficarem Caídas por esse Jutsu podem refazer a Salvaguarda no começo de seu turno para cessar o efeito. Se você ou uma criatura afetada se mover para fora da área os efeitos desse jutsu se encerram imediatamente. Uma criatura que foi afetada por esse jutsu e escapou dos efeitos não pode ser afetada novamente até o final do seu turno.",
  },
  {
    key: "arte-de-selamento-trancar",
    nome: "Arte de Selamento: Trancar",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés (18 metros)",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 3,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você funde seu chakra em um selo, na tentativa de marcar um objeto com o selo de proteção. Selecione um objeto que não esteja sendo segurado ou vestido ou uma criatura que você possa ver que esteja segurando um objeto. Se o objeto estiver parado em uma superfície ele fica preso a superfície. Caso uma criatura esteja segurando o objeto a mesma deve realizar uma Salvaguarda de Força. Em uma tentativa falha, o objeto é selado a superfície mais próxima ficando preso, seja a um piso, parede ou teto. Pela duração desse jutsu, o objeto fica preso aquela superfície e não pode ser movido ou arrastado. Uma criatura a 5 pés (1.5 metros) do objeto selado pode tentar remover o selo realizando um Teste de Perícia (Ninshou) contra sua CD. Caso a criatura seja bem sucedida, ela quebra o selo liberando o objeto.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o alcance em 30 pés (9 metros).",
  },
  {
    key: "berro-do-trovao",
    nome: "Berro do Trovão",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Cone de 15 pés/4.5 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você cria um berro de alta tonalidade que afeta criaturas que estejam no caminho das ondas sonoras. Criaturas dentro da área devem realizar uma Salvaguarda de Constituição. Em uma falha, seus corpos sofrem um choque sonoro, recebendo 1 rank de Concussão e perdendo a concentração em qualquer Jutsu de rank igual ou menor a esse. Caso seja bem sucedida, a criatura resiste ao berro não sofrendo nenhum efeito.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o tamanho do cone em 5 pés (1.5 metros).",
  },
  {
    key: "arte-de-selamento-vincular",
    nome: "Arte de Selamento: Vincular",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés (18 metros)",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você funde seu chakra em um selo, na tentativa de marcar uma criatura com o selo de vinculação. Uma criatura alvo no alcance deve realizar uma Salvaguarda de Carisma. Em uma falha, a criatura fica Contida pela duração desse Jutsu e ganha 1 rank de Selado. Uma criatura Contida por esse jutsu pode refazer a Salvaguarda no final de cada um de seus turnos.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o número de alvos em +1.",
  },
  {
    key: "cintilacao-corporal",
    nome: "Cintilação Corporal",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Pessoal",
    duracao: "1 Rodada",
    componentes: ["SM", "M"],
    custoChakra: 3,
    palavrasChave: ["Ninjutsu"],
    descricao: "Você ganha maestria de movimento, permitindo que você cubra uma distância muito maior em um período de tempo menor. Até o final do seu próximo turno, aumente sua velocidade em 30 pés.",
  },
  {
    key: "desenho-de-imitacao-da-besta-cobras",
    nome: "Desenho de Imitação da Besta: Cobras",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés (18 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "SC", "FN (Pergaminho em Branco)"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Ao conjurar esse Jutsu você desenha a imagem de duas cobras dentro de seu pergaminho, fundindo seu chakra com o papel e o trazendo a vida. Você comanda um par de cobras para atacar e enrolar inimigos. Escolha até 2 criaturas no alcance. Cada criatura deve realizar um teste de Salvaguarda de Força. Se as criaturas estiverem a 5 pés (1.5 metros) de distância uma da outra eles realizam a Salvaguarda com desvantagem. Em uma tentativa falha, as criaturas ficam sob o efeito de Restringido. Criaturas restritas por esse Jutsu podem utilizar sua ação principal para refazer a Salvaguarda. Caso suceda, a mesma e todas as criaturas em 5 pés de distância são libertadas.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e aumente o número de alvos em 1.",
  },
  {
    key: "clone-de-tinta",
    nome: "Clone de Tinta",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "90 pés (27 metros)",
    duracao: "1 Minuto",
    componentes: ["SM", "MC", "SC", "FN (Frasco de Tinta)"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você funde seu chakra dentro da tinta realizando um selo. Você então conjura um clone de você mesmo feito de tinta. Esse clone se parece com você, soa como você e age como você do jeito que você descrever. O custo de chakra desses clones não podem ser reduzidos para menos da metade. O Clone de Tinta tem 1 Ponto de Vida e não pode ir mais longe do que 90 pés (27 metros) de você. O clone pode andar, falar e interagir com o ambiente porém ele não pode atacar por si próprio. O clone age sempre no final de seu turno. Como uma Ação Bônus você pode comandar o clone para atacar. Quando isso acontece, o clone finge fazer selos de mão para conjurar um Jutsu atacando uma criatura a até 60 pés (18 metros) do clone. A criatura atingida deve realizar um Teste de Intuição contra sua CD de Salvaguarda de Ninjutsu. Em uma falha, a criatura fica distraída pelo clone. A criatura distraída por esse Jutsu garante que o próximo ataque a essa criatura seja feito com vantagem como se estivessem surpresas.",
  },
  {
    key: "desenho-de-imitacao-da-besta-falcao-de-recuperacao",
    nome: "Desenho de Imitação da Besta: Falcão de Recuperação",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "120 pés (36 metros)",
    duracao: "Concentração, até o máximo de 1 minuto",
    componentes: ["SM", "MC", "SC", "FN (Pergaminho Branco)"],
    custoChakra: 3,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você rapidamente desenha um falcão para coletar algo para você. O falcão salta de seu pergaminho e tenta lhe trazer um objeto que não pese mais que 10 libras (4.5 kg) e traz para seu destino de escolha dentro do alcance. A movimentação aérea do falcão é de 45 pés, ele tem uma CA de 15 e 1 Ponto de Vida. O falcão deve permanecer dentro do alcance desse Jutsu partindo de seu conjurador e não precisa ser comandado com uma ação para andar ou voar. O destino do falcão pode ser alterado usando uma ação bônus no turno do conjurador.",
    emNiveisSuperiores:
      "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3, o movimento do falcão em 10 pés (3 metros), o limite de peso em 10 libras e o alcance do Jutsu em 30 pés (9 metros).",
  },
  {
    key: "desenho-de-imitacao-da-besta-pombas",
    nome: "Desenho de Imitação da Besta: Pombas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "Até 10 Minutos",
    alcance: "Próprio",
    duracao: "24 Horas",
    componentes: ["SM", "MC", "SC", "FN (Pergaminho em Branco)"],
    custoChakra: 3,
    palavrasChave: ["Ninjutsu", "Fuinjutsu", "Constructo"],
    descricao:
      "Você escreve em seu pergaminho uma mensagem de qualquer tamanho que você possa concebivelmente escrever em um intervalo de tempo de 10 minutos ou menos. Uma vez concluído, os escritos se manifestam na forma de um pássaro de sua descrição e agora carregam eles mesmos a mensagem. Você também pode conjurar este jutsu mirando em uma mensagem já escrita de 25 palavras ou menos. O pássaro que você cria tem 1 PV e uma CA de 15. Você então específica um local que você visitou anteriormente e um destinatário que corresponde a uma descrição geral. Você pode também dar ao pássaro uma carta, pergaminho, etiqueta para ser entregue. O constructo viaja durante a duração do jutsu em direção ao local. Quando o pássaro chega, ele se transforma novamente e entrega a mensagem, pergaminho ou quaisquer pacotes para a criatura que você descreveu. O pássaro irá liberar o objeto somente para a criatura que você especificou ou se for morto.",
    emNiveisSuperiores:
      "Para cada rank acima do D, aumenta o custo deste jutsu em 3 e a duração em 24 horas. Ao conjurar na Classificação B ou Superior, o pássaro se torna grande em tamanho e é capaz de carregar duas criaturas de tamanho médio em suas costas.",
  },
  {
    key: "desenho-de-imitacao-da-besta-lagarto",
    nome: "Desenho de Imitação da Besta: Lagarto",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés (9 metros)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "SC", "FN (Pergaminho em Branco)"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Fuinjutsu", "Constructo"],
    descricao:
      "Você invoca um lagarto de tinta em um espaço que você pode ver dentro do alcance e que possa mantê-lo lá. O lagarto é um construto com as seguintes estatísticas: CA 12, 5d6 (20) pontos de vida. O lagarto imediatamente após ser invocado, grita um som ameaçador para aqueles ao redor. Todas as criaturas que começarem seu turno a 10 pés (3 metros) do lagarto, excluindo você, devem fazer uma salvaguarda de Sabedoria. Em uma falha, eles ganham 1 nível de Medo. Enquanto uma criatura tiver níveis de Medo ganhos como resultado deste jutsu eles não podem se aproximar voluntariamente do Lagarto.",
    emNiveisSuperiores: "Para cada nível que você conjurar este jutsu acima do Rank-D, aumente o custo deste jutsu em 3 e o alcance do grito do lagarto em 5 pés (1,5 m).",
  },
  {
    key: "desenho-de-imitacao-da-besta-morcegos",
    nome: "Desenho de Imitação da Besta: Morcegos",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés (9 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "SC", "FN (Pergaminho em Branco)"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você desenha a imagem de um morcego dentro de um pergaminho em branco para cegar seu inimigos. Realize um Ataque de Ninjutsu a Distância contra uma criatura de tamanho Médio ou menor. Em um acerto, a criatura fica Cega. Como uma ação em seu turno, a mesma pode tentar tirar os morcegos de sua face realizando uma Salvaguarda de Força, a retirando da condição Cega caso seja bem sucedida.",
    emNiveisSuperiores:
      "Para cada nível que você conjurar este jutsu acima do Nível D, aumente o custo deste jutsu em 3 e este número de ataques que este jutsu pode fazer em +1. No entanto, cada ataque adicional deve ter como alvo uma criatura diferente.",
  },
  {
    key: "desenho-de-imitacao-da-besta-veados",
    nome: "Desenho de Imitação da Besta: Veados",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés (9 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "SC", "FN (Pergaminho em Branco)"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você desenha uma imagem de uma manada de veados que avançam do seu pergaminho em direção ao alvo escolhido. Faça um ataque de Ninjutsu à distância. Em caso de sucesso, o alvo sofre 2d8 de dano de Concussão e deve fazer um teste de resistência de Força, ou estará Caída em uma falha. Se este jutsu for lançado visando uma Criatura Caída, você não rola com desvantagem, em vez disso rola com vantagem e causa 2d6 a mais de dano de concussão.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o dano em 1d8.",
  },
  {
    key: "desenho-de-imitacao-da-besta-ratos",
    nome: "Desenho de Imitação da Besta: Ratos",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Minuto",
    alcance: "Raio de 1 Milha",
    duracao: "10 Minutos",
    componentes: ["SM", "MC", "SC", "FN (Pergaminho em Branco)"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Fuinjutsu", "Sensorial"],
    descricao:
      "Você desenha uma horda de ratos dentro de um pergaminho em branco. Após 1 minuto a imagem fica pronta e os ratos surgem a vida. Depois de um tempo de espera de 10 minutos, realize um Teste de Ninshou. Baseado no resultado, você fica ciente de certas coisas em um raio de 1 milha:\nCD 10: Você fica ciente das estruturas que não estão escondidas dentro do alcance. Isso não informa a sua localização exata ou tamanho da construção, apenas a direção geral.\nCD 15: Você fica ciente de criaturas não escondidas dentro do alcance. Isso não informa a localização dessas criaturas ou o tamanho delas, apenas a direção geral.\nCD 20: Você fica ciente de lugares escondidos.\nCD 25: Você fica ciente de tamanho dos lugares e tipos de criaturas.\nCD 30: Você fica ciente de criaturas escondidas.",
    emNiveisSuperiores:
      "Para cada Rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3. Caso conjurado no Rank-B ou acima, aumente o alcance desse Jutsu para 2 milhas. Caso conjurado no Rank-S ou acima, Aumente o alcance para 3 milhas.",
  },
  {
    key: "escudo-de-chakra",
    nome: "Escudo de Chakra",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Reação, que você pode usar quando receber dano",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Conflito"],
    descricao:
      "Você manifesta uma barreira giratória de chakra ao seu redor, protegendo-o do ataque desencadeador. Você ganha 12 pontos de vida temporários. Se você tiver uma liberação da natureza, este jutsu ganha uma única palavra-chave de liberação da natureza que você pode conjurar, e efeitos adicionais com base na liberação da natureza. Seu escudo ganha um dos seguintes benefícios com base na liberação da natureza escolhida. Se você não tiver uma liberação da natureza, este escudo tem 16 pontos de vida temporários.\nTerra: Seu escudo tem resistência a dano de Frio, vulnerabilidade a Dano de Raio e, uma vez conjurado, deixa para trás uma construção de Terra.\nVento: Seu escudo tem resistência a Dano de Raio, vulnerabilidade a Dano de Fogo e, uma vez conjurado, todas as criaturas de sua escolha a até 5 pés de você ganham 1 nível de sangramento.\nFogo: Seu escudo tem resistência a Dano de Vento, Vulnerabilidade a Dano de Frio e todas as criaturas a até 10 pés de você recebem dano de fogo igual ao seu modificador de habilidade Ninjutsu.\nÁgua: Seu escudo tem resistência a dano de fogo, vulnerabilidade a dano de terra e se este jutsu for lançado perto de uma fonte suficiente de água, reduza o custo deste jutsu em -2.\nRelâmpago: Seu escudo tem resistência a dano de terra, vulnerabilidade a dano de vento e você ganha +2 em testes de resistência de Destreza até o início do seu próximo turno.",
    emNiveisSuperiores: "Para cada nível que você lançar este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e a redução de dano em 2d4.",
  },
  {
    key: "disparo-de-chakra",
    nome: "Disparo de Chakra",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés (18 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Conflito"],
    descricao:
      "Você atira uma esfera de 4 polegadas feita de chakra puro em uma criatura em seu alcance. Realize um Ataque de Ninjutsu à Distância. Em um acerto, o alvo recebe 3d6 de dano. O tipo de dano desse Jutsu depende de sua liberação elemental. Caso você não tenha uma liberação elemental, esse Jutsu causa dano de Força. Caso você tenha mais de uma, escolha dentre elas para o tipo de dano e efeito.\nEstilo Terra: O alvo deve também realizar uma Salvaguarda de Força, recebendo 1 rank de Machucado em um teste falho.\nEstilo Vento: O alvo deve também realizar uma Salvaguarda de Força, sendo empurrado para trás 15 pés (4.5 m) e ficará Caído em um teste falho.\nEstilo Fogo: Cada criatura dentro de uma esfera de 5 pés (1.5 m) do alvo principal deve realizar uma Salvaguarda de Destreza, recebendo 1 rank de Queimado em um teste falho.\nEstilo Água: Cada criatura dentro de uma esfera de 5 pés (1.5 m) do alvo principal deve realizar uma Salvaguarda de Constituição, recebendo 1 rank de Refrigerado em um teste falho.\nEstilo Raio: O alvo deve também realizar uma Salvaguarda de Constituição, recebendo 1 rank de Chocado em um teste falho.\nSem Elemento: Troque o dado para d8. O alvo deve também realizar uma Salvaguarda de Destreza, ficando Atordoado em um teste falho.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo do de chakra em 3 e o dano em +1 dado.",
  },
  {
    key: "estrelas-vazias",
    nome: "Estrelas Vazias",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "120 pés (36 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você força as palmas das mãos antes de apontá-las para o céu, disparando quatro rajadas de chakra que tomam a forma de pequenas estrelas antes de cair no chão em quatro espaços diferentes de sua escolha dentro do alcance, causando dano a objetos, criaturas e estruturas que ocupam o espaço. Objetos, criaturas e estruturas nos espaços selecionados recebem 1d4+1 de dano cada. Uma criatura, objeto ou estrutura na área de mais de uma estrela recebe o dano de cada uma dessas estrelas. Se você tiver uma liberação de natureza, este jutsu ganha uma única palavra-chave de liberação de natureza que você pode conjurar e seu tipo de dano se torna o tipo de dano de liberação de natureza correspondente (Água = Frio). Se você não tiver uma liberação de natureza, este jutsu causa Dano de Força. Uma criatura só pode ser afetada pelos seguintes efeitos duas vezes por conjuração.\nEstilo Terra: Adicionalmente a estrela deixa uma cratera na área de 10 pés (3 metros) do local atingido, deixando esse terreno como terreno difícil até ser concertado.\nEstilo Vento: Criaturas a 5 pés (1.5 metros) de distância do espaço onde a estrela caiu deve realizar uma Salvaguarda de Força. Em um teste falho, a criatura é empurrada 5 pés para trás do local atingido e estão Caídas.\nEstilo Fogo: Criaturas a 5 pés (1.5 metros) de distância do espaço onde a estrela caiu deve realizar uma Salvaguarda de Destreza. Em um teste falho, a criatura recebe a mesma quantia de dano do que o alvo original.\nEstilo Água: Criaturas a 5 pés (1.5 metros) de distância do espaço onde a estrela caiu devem realizar uma Salvaguarda de Constituição. Em um teste falho, a criatura recebe 1 rank de Refrigerado.\nEstilo Raio: Se o alvo de 2 ou mais estrelas estiverem 15 pés (4.5 metros) de distância uma da outra, um arco de relâmpago se formam dentre as estrelas em uma linha contanto que não haja obstáculos. Criaturas dentro dessa linha devem realizar uma Salvaguarda de Constituição. Em um teste falho, criaturas sofrem 1 rank de Chocado.\nSem Liberação Elemental: Troque o dado para d8. Criaturas ocupando o espaço recebem 1 rank de Machucado.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o número de estrelas em 1.",
  },
  {
    key: "marca-de-chakra",
    nome: "Marca de Chakra",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "Especial",
    alcance: "Toque",
    duracao: "10 Minutos",
    componentes: ["SC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Fuinjutsu", "Sensorial"],
    descricao:
      "Você cria um selo de chakra e tenta colocar em uma criatura, estrutura ou construção que você pode tocar. Ao acertar um Ataque Corpo a Corpo ou a Distância, você marca a criatura. Isso não funciona caso outra criatura, construção ou estrutura intercepte o dano do ataque. Enquanto marcado por esse Jutsu mesmo se a criatura, estrutura ou construção estiver a 1 milha de você fica ciente da existência desse selo mesmo sem saber exatamente a localização exata. Você ganha um bônus de +4 para quaisquer testes na tentativa de achar, caçar ou procurar a criatura marcada. Adicionalmente, se você possuir algo que lhe permita teletransportar, você pode se teletransportar para essa marca se a criatura, estrutura ou construção marcada estiver dentro de 1 milha de distância. Se você se teletransportar, a marca é consumida e desaparece, encerrando esse Jutsu.",
    emNiveisSuperiores:
      "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3. Caso conjurado como Rank-C ou acima, aumente a duração para 1 hora. Caso conjurado como Rank-B ou acima, aumente a duração para 8 horas. Caso conjurado como Rank-A ou acima, aumente a duração para 24 horas. Caso conjurado como Rank-S, aumenta a duração para Permanente.",
  },
  {
    key: "reacoes-aprimoradas",
    nome: "Reações Aprimoradas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "8 Horas",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Ninjutsu", "Sensorial"],
    descricao: "Você concentra chakra na sua visão e se prepara para se movimentar rapidamente a qualquer momento. Quando rolar iniciativa pela primeira vez pela duração desse Jutsu, você pode adicionar 1d4 + 1 a sua rolagem. Ao ser utilizado, esse Jutsu se encerra.",
  },
  {
    key: "mordida-da-serpente-das-sombras",
    nome: "Mordida da Serpente das Sombras",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "15 pés (4.5 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "SC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você invoca uma cobra formada de chakra que se origina de um local do seu corpo, que se estende e ataca a criatura alvo dentro do alcance. Faça um ataque de Ninjutsu. A criatura alvo sofre 2d8 de dano de Veneno e deve fazer um teste de resistência de Força em um Acerto. Em um teste de resistência de Força falho, a criatura alvo é contida pela cobra. Como uma ação no turno de uma criatura contida, ela pode tentar outro teste de resistência de Força para encerrar esta condição em si mesma.",
    emNiveisSuperiores: "Para cada nível que você conjura este jutsu acima do Nível D, aumente o custo deste jutsu em 3 e o número de alvos que este jutsu afeta em +1.",
  },
  {
    key: "salto-de-chakra",
    nome: "Salto de Chakra",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM", "M"],
    custoChakra: 3,
    palavrasChave: ["Ninjutsu"],
    descricao: "Você concentra seu chakra em suas pernas, aumentando sua capacidade de pulo astronomicamente. Até o final de seu turno, dobre sua altura de pulo.",
    emNiveisSuperiores:
      "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3. Se conjurado como Rank-B ou acima, a duração desse jutsu se estende para 1 minuto. Caso seja conjurado como um jutsu Rank-S, a duração se estende para 1 hora.",
  },
  {
    key: "pele-de-chakra",
    nome: "Pele de Chakra",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "8 Horas",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Este jutsu só pode ser usado quando você não estiver usando armadura. Você se reveste de uma aura protetora de chakra, protegendo-o de danos. Sua CA se torna 13 + Modificador de Destreza ou Inteligência (Escolha um) + Metade do seu Bônus de proficiência. Este jutsu termina se você usar armadura ou dispensar o jutsu como uma ação Bônus.",
    emNiveisSuperiores:
      "Para cada nível que você conjurar este jutsu acima do Nível D, aumente o custo deste jutsu em 3. Se este jutsu for conjurado no Nível C ou superior, você ganha pontos de vida temporários iguais ao seu modificador de habilidade de Ninjutsu. Como uma ação bônus no seu turno, você pode repor esses pontos de vida temporários por 5 Chakra. Se este jutsu for conjurado no Nível B ou superior, aumente a CA que este Jutsu concede em +1. Se este jutsu for conjurado no Nível A ou superior, os pontos de vida temporários ganhos são, em vez disso, iguais à metade do valor de habilidade de Ninjutsu do conjurador. Se este jutsu for conjurado no Nível S ou superior, aumente a CA que este Jutsu concede em +2, em vez de +1.",
  },
  {
    key: "camuflagem",
    nome: "Camuflagem",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "1 Minuto",
    componentes: ["SM"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu"],
    descricao: "Você cobre seu corpo em chakra e imita a cor e textura da área ao seu redor como um camaleão. Pela duração desse Jutsu, role seus testes de Furtividade com +4 de Bônus.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e você pode escolher +1 criatura para receber esse bônus.",
  },
  {
    key: "alarme",
    nome: "Alarme",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Cubo de 30 pés (9 metros)",
    duracao: "8 Horas",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Fuinjutsu", "Sensorial"],
    descricao:
      "Você aplica um selo de chakra que se expande 30 pés (9 metros) pelo chão ou superfície e se espalha em uma fina e indetectável aura de chakra formando um Cubo de 30 pés (9 metros). Até o final desse Jutsu, você é alertado de todas as criaturas que entrarem em contato com o selo ou adentrarem a área designada. Você pode designar criaturas que não acionam o alarme. Você também pode decidir se esse alarme é audível ou mental.",
  },
  {
    key: "chamada-das-lagrimas",
    nome: "Chamada das Lágrimas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (Cone de 30 pés/9 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você manifesta chakra ao redor de sua língua e garganta e o utiliza para vibrar um ultra grito capaz de incapacitar criaturas ao seu redor. Todas as criaturas em um cone de 30 pés devem realizar uma Salvaguarda de Sabedoria, ficando Surdas e Atordoadas até o final do turno da criatura em um teste falho. Adicionalmente, quaisquer armadilhas como explosivos, armadilhas de porta ou placas de pressão que estejam dentro do alcance são ativadas instantaneamente.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D, aumente o custo de chakra em 3 e o alcance em 5 pés.",
  },
  {
    key: "catapulta",
    nome: "Catapulta",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "90 pés (27 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Escolha um objeto que pese no máximo 1 volume dentro do alcance, que não esteja sendo usado ou carregado. O objeto voa em linha reta até 90 pés em uma direção que você escolher antes de cair no chão, parando mais cedo se atingir uma superfície sólida. Se o objeto atingir uma criatura, essa criatura deve fazer um teste de resistência de Destreza. Em uma falha, o objeto atinge o alvo e para de se mover. Em ambos os casos, tanto o objeto quanto a criatura ou superfície sólida sofrem 3d8 de dano contundente.",
    emNiveisSuperiores:
      "Para cada nível que você conjura este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o volume máximo dos objetos que este jutsu pode usar aumenta em 1 volume, e a distância máxima em 10 pés. O dano deste jutsu também muda dependendo do volume do objeto afetado: 1 volume ou menos: 3d8. 2 volume: 4d8. 3 volume: 5d8. 4 volume: 6d8. 5 volume: 7d8.",
  },
  {
    key: "invocacao",
    nome: "Invocação",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "Turno Completo",
    alcance: "10 pés (3 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "SC"],
    // Fonte lista "Custo: Especial (Baseado na Invocação mencionada no capítulo de Invocações)" — não é um valor fixo.
    custoChakra: 0,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você deve ter formado um Contrato de Sangue com uma Tribo Sábia, como um encontrado na seção Jutsu de Invocação encontrado no final do capítulo Ninjutsu para conjurar este jutsu com sucesso. Se uma criatura se recusar ou não puder ser invocada, você gasta chakra de acordo com a classificação deste jutsu (custo Especial, baseado na invocação — ver capítulo de Invocações). A Invocação aparece onde for designada para aparecer e pode agir como uma Ação Bônus dentro do turno do conjurador. Você pode se comunicar com a criatura e a mesma vai lhe escutar e apenas lhe escutar durante o combate. Você pode acionar sua invocação para performar as seguintes ações: Atacar (Corpo-a-Corpo, com Armas ou Jutsus), Desengajar ou Ajudar. A invocação pode performar uma ação e um movimento. A invocação tem que ficar dentro de um alcance de 120 pés do invocador. Todas as criaturas sábias sabem falar a língua comum.",
    emNiveisSuperiores: "Para cada rank que você conjurar esse Jutsu acima do Rank-D você invoca a criatura correspondente em nível e Rank mencionados de sua criatura na ativação.",
  },
  {
    key: "deslocamento-instantaneo",
    nome: "Deslocamento Instantâneo",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "1 Turno",
    componentes: ["SM", "M"],
    custoChakra: 3,
    palavrasChave: ["Ninjutsu"],
    descricao: "Você masteriza o seu deslocamento, permitindo a você cobrir uma distância maior em um menor tempo. Até o final do seu próximo turno, aumente sua velocidade de Deslocamento em 30 pés.",
  },
  {
    key: "sensorial",
    nome: "Sensorial",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "Especial",
    alcance: "Próprio",
    duracao: "10 Minutos",
    componentes: ["SM"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Sensorial"],
    descricao:
      "Você espalha seu chakra de forma que você consegue sentir a assinatura de chakra de outras criaturas claramente. Você só pode usar esse jutsu em seu turno, e conjurar esse jutsu não custa sua ação. Quando o jutsu for conjurado, pela duração você ganha acesso a uma ação especial chamada de Identificar Chakra. Essa ação pode ser usada em combinação com outros efeitos. Essa ação especial conta como uma Ação de Perícia de Constituição e Sabedoria.\nIdentificar Chakra: Como uma ação bônus, você pode realizar um Teste de Percepção utilizando Constituição ou Sabedoria contra o Controle de Chakra básico de quaisquer criaturas dentro de um raio de 30 pés (9 metros) de você. Caso obtenha sucesso, você ganha o benefício de Sentir Chakra contra as criaturas pela duração ou até as mesmas ficarem com 0 de chakra ou eles tentem com sucesso a ação de Suprimir Chakra.",
    emNiveisSuperiores: "Para cada Rank que você conjurar esse Jutsu acima de Rank-D, aumente o custo de chakra em 3 e o alcance de Identificar Chakra em 30 pés.",
  },
  {
    key: "substituicao",
    nome: "Substituição",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Reação que pode ser utilizada quando você for receber dano.",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM", "M"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Você rapidamente se movimenta utilizando a Técnica de Substituição, escapando com uma pequena margem. Quando você for receber dano de um ataque, aumente sua CA em +3 contra este ataque e todos os subsequentes até o começo de seu próximo turno. Se esse bônus for o que fez o ataque falhar, você pode se movimentar até metade de seu deslocamento. Caso esse Jutsu seja acionado para sair de uma Salvaguarda, você ainda realiza a Salvaguarda mesmo que seu movimento o tire da zona afetada.",
  },
  {
    key: "transformacao-avancada",
    nome: "Transformação Avançada",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Concentração, até o máximo de 10 minutos",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Ninjutsu"],
    descricao:
      "Uma forma avançada de Transformação. Quando você conjura esse Jutsu, você transforma o seu corpo em um objeto físico como uma arma ou objeto menor que um tamanho Médio. Enquanto transformado em um objeto, você recebe as características físicas e funcionalidades desse objeto. Se for transformado em uma arma, você também ganha as propriedades da arma. Outros podem o carregar e usar como se fosse uma arma contanto que você mantenha a concentração nesse Jutsu. Você não pode se transformar em um objeto que se divide em múltiplas peças, se desconectar de sua base ou tenha muitas partes mecânicas, como um ventilador ou um cofre. Caso você se transforme em um desses objetos, os mesmos não conseguem utilizar essa funcionalidade e não podem se mover de jeito nenhum (O ventilador não gira, o cofre não abre, etc…). Enquanto transformado, você não pode se mover, falar ou atuar. Você continua ciente de seus arredores e pode escutar normalmente, porém não pode conjurar Jutsus ou realizar quaisquer tipos de ataque enquanto transformado.",
    emNiveisSuperiores: "Para cada Rank que você conjurar esse Jutsu acima de Rank-D, aumente o custo de chakra em 3. Quando esse Jutsu for conjurado em Rank-B você pode se transformar em objetos de tamanho Grande ou Minúsculo.",
  },
  {
    key: "visao-noturna",
    nome: "Visão Noturna",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "10 Minutos",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Sensorial"],
    descricao: "Você toca uma criatura que esteja disposta a receber a habilidade de enxergar no escuro. Pela duração desse Jutsu, a criatura ganha visão noturna dentro de um alcance de 60 pés (18 m).",
    emNiveisSuperiores: "Para cada Rank que você conjurar esse Jutsu acima de Rank-D, aumente o custo de chakra em 3 e o numero de criaturas que você pode afetar em +1.",
  },
  {
    key: "travar-destravar",
    nome: "Travar / Destravar",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "nao-elemental",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Até ser desconjurada",
    componentes: ["SM", "SC"],
    custoChakra: 3,
    palavrasChave: ["Ninjutsu", "Fuinjutsu"],
    descricao:
      "Você coloca um selo em uma porta, janela, baú ou outro objeto que pode abrir e fechar e caso ele já esteja fechado ele ficará trancado pela duração. Somente você e criaturas que você designou ao conjurar esse Jutsu podem abrir o objeto normalmente. Você pode também colocar uma senha que quando falada dentro de 5 pés (1.5 m) de distância do objeto o permite ser aberto por 1 minuto. Esse Jutsu também pode ser utilizado de maneira inversa para uma tentativa de abrir uma porta trancada utilizando seu chakra. Realize um Teste de Controle de Chakra (Inteligência) contra o CD da Fechadura como se você estive-se destravando uma porta com um Kit de Segurança. Criaturas devem fazer um teste de Atletismo contra seu CD de Salvaguarda de Ninjutsu para tentar arrombar um objeto que você trancou.",
  },
];
