import type { JutsuDefinition } from "@/lib/jutsu/types";

export const relampagoJutsu: JutsuDefinition[] = [
  {
    key: "disjuntor-de-circuito",
    nome: "Disjuntor de Circuito",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você coloca sua palma no chão e conduz uma descarga de relâmpago que percorre até um alvo criatura dentro do alcance. Este jutsu ignora linha de visão e pode contornar cantos. A criatura alvo deve fazer um teste de constituição, sofrendo 3d6 de Dano de Relâmpago e ganhando 1 nível de estado chocado em caso de falha no teste, ou metade do dano em caso de sucesso.\n\nSobrecarga: Quando você conjura este jutsu no tempo de conjuração listado, você pode escolher gastar sua Ação Bônus ou Reação para sobrecarregar seus efeitos. Quando o faz, uma criatura que falhe em seu teste de resistência também fica lenta pelo mesmo tempo que estiver chocada.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjura este jutsu, aumente o custo em 3 e o dano em 1d6, além de aumentar em +1 o número de criaturas que você pode alvejar.",
  },
  {
    key: "banquete-relampago",
    nome: "Banquete Relâmpago",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "90 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você conjura seu chakra do Estilo relâmpago para gerar uma descarga elétrica na tentativa de chocar uma criatura dentro do alcance. Faça um Ataque de Ninjutsu à Distância, e em caso de acerto, cause 1d6 de Dano de Relâmpago. Se a criatura alvo estiver concentrada em um Jutsu, ela faz seu teste com desvantagem. Se o alvo tiver um jutsu ativo que não exija concentração e não estiver concentrado em um jutsu, ele perde os benefícios desse jutsu até o final de seu próximo turno.\n\nSobrecarga: Quando você conjura este jutsu no tempo de conjuração listado, você pode escolher gastar sua Ação Bônus ou Reação para sobrecarregar seus efeitos. Quando o faz, aumente o dano causado em 2 etapas e adicione seu modificador de habilidade de Ninjutsu.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjura este jutsu, aumente o custo em 3 e o número de ataques que você faz em +1.",
  },
  {
    key: "campo-eletromagnetico",
    nome: "Campo Eletromagnético",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (cubo de 20 pés)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você conjura seu chakra do Estilo relâmpago para gerar uma aura de eletricidade. Cada criatura de sua escolha dentro de um cubo de 20 pés ao redor de você quando este jutsu é conjurado, e aquelas que começam seus turnos dentro do alcance deste jutsu, devem fazer um teste de resistência de Constituição. Em caso de falha no teste, cada vez que elas sofreriam Dano de Relâmpago, o dado de dano do relâmpago aumenta em 1 etapa (D4 > D6 > D8 > D10 > D12).",
  },
  {
    key: "impulso-carregado",
    nome: "Impulso Carregado",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Até 8 Horas",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você toca uma criatura disposta. Durante a duração, o alvo pode adicionar 1d8 ao seu primeiro teste de iniciativa feito durante a duração. Durante o próximo minuto após rolar iniciativa, o alvo pode, como uma ação bônus em cada um de seus turnos, tomar a ação de deslocamento. O jutsu então termina.",
  },
  {
    key: "irritacao-eletromagnetica",
    nome: "Irritação Eletromagnética",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (cubo de 20 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você conjura seu chakra do Estilo relâmpago para gerar uma onda de eletricidade. Cada criatura em um cubo de 20 pés ao redor de você deve fazer um teste de resistência de Constituição. Em caso de falha, eles ganham 1 nível de estado chocado. Se uma criatura já estiver chocada, ela faz este teste com desvantagem.\n\nSobrecarga: Quando você conjura este jutsu no tempo de conjuração listado, você pode escolher gastar sua Ação Bônus ou Reação para sobrecarregar seus efeitos. Quando o faz, todas as criaturas que falharem no teste de resistência têm sua velocidade reduzida em 10 para cada nível de estado chocado que possuírem.",
    emNiveisSuperiores: "Para cada classificação que você lançar este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o cubo em 5 pés.",
  },
  {
    key: "repulsao-relampago",
    nome: "Repulsão Relâmpago",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Reação ao ser alvo de um ataque ou jutsu.",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você cria um campo de força magnética ao seu redor, desviando os ataques para longe de você. Os ataques têm desvantagem ao alvejá-lo até o início do seu próximo turno.",
  },
  {
    key: "reflexo-relampago",
    nome: "Reflexo Relâmpago",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Reação que você toma quando é obrigado a fazer um teste de resistência de Destreza.",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Seu corpo se carrega com chakra do Estilo relâmpago, aumentando seus reflexos a grandes alturas. Quando você faz um teste de resistência de Destreza, você pode rolar com vantagem.",
  },
  {
    // NOTE: heading OCR'd as "ESTILO RELAMPAGO: BOLTE GUIA" (single line, unlike the usual 2-line
    // wrapped headings in this chapter). "Bolte" is not a Portuguese word; given the description
    // (a lightning bolt that grants advantage on the next attack against the target), the intended
    // name is very likely "Raio Guia" (a "Guiding Bolt" analogue). Kept as printed; name uncertain.
    key: "bolte-guia",
    nome: "Bolte Guia",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "90 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu", "Confronto"],
    descricao: "Um flash de relâmpago irrompe de suas mãos em direção a uma criatura de sua escolha dentro do alcance. Faça um ataque de ninjutsu à distância contra o alvo. Em caso de acerto, o alvo sofre 3d8 de dano de relâmpago, e o próximo rolagem de ataque feita contra o alvo antes do final do seu próximo turno tem vantagem, graças à corrente de eletricidade que guia o próximo ataque ao alvo.\n\nSobrecarga: Quando você conjura este jutsu no tempo de conjuração listado, você pode escolher gastar sua Ação Bônus ou Reação para sobrecarregar seus efeitos. Quando o faz, este jutsu se transforma em uma linha de 60 pés de comprimento e 5 pés de largura. Todas as criaturas dentro do alcance devem fazer um teste de resistência de Destreza, sofrendo 3d8 de dano de relâmpago em caso de falha no teste, ou metade desse dano em caso de sucesso. Independentemente de passar ou falhar, a próxima rolagem de ataque feita contra as criaturas afetadas antes do final do seu próximo turno tem vantagem.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjura este jutsu, aumente o custo em 3 e o dano em 1d8.",
  },
  {
    key: "habilidade-aprimorada",
    nome: "Habilidade Aprimorada",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "1 Minuto",
    componentes: ["SM", "MC", "M"],
    custoChakra: 5,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você toca uma criatura disposta e concede um vasto aumento em uma de suas habilidades físicas. Escolha um dos seguintes efeitos; o alvo ganha o efeito até o fim do jutsu. Você só pode ter este jutsu ativo em uma criatura por vez.\n\nAgilidade. O alvo tem vantagem em testes de resistência de Destreza. Além disso, ele não sofre dano de quedas de 20 pés ou menos, se não estiver incapacitado.\n\nResistência. O alvo tem vantagem em testes de resistência de Constituição. Além disso, ele ganha 10 pontos de vida temporários, que são perdidos quando o jutsu termina.\n\nForça. O alvo tem vantagem em testes de resistência de Força. Além disso, ele aumenta o dano causado com rolagens de ataque que usam sua força em +2.\n\nSobrecarga: Quando você conjura este jutsu no tempo de conjuração listado, você pode escolher gastar sua Ação Bônus ou Reação para sobrecarregar seus efeitos. Quando o faz, os seguintes efeitos são aprimorados das seguintes maneiras;\n\nAgilidade. O alvo pode realizar a ação de deslocamento como uma ação bônus durante a duração.\n\nResistência. O alvo ganha 15 pontos de vida temporários adicionais.\n\nForça. O alvo se torna imune à condição Enfraquecido pelo próximo minuto.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjura este jutsu, aumente o custo em 3 e o número de criaturas nas quais você pode ter este jutsu ativo ao mesmo tempo aumenta em +1.",
  },
  {
    key: "bola-de-relampago",
    nome: "Bola de Relâmpago",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você gera múltiplas pequenas esferas flutuantes de chakra relâmpago. Você dispara todas elas rapidamente em um único alvo. Faça um ataque de ninjutsu à distância. Se a criatura alvo estiver empunhando uma arma metálica, você realiza este ataque com vantagem. Em caso de acerto, a criatura alvo sofre 6d4 de Dano de Relâmpago e a criatura deve fazer um teste de resistência de constituição. Em caso de falha no teste, ela ganha 1 nível de estado chocado.\n\nSobrecarga: Quando você conjura este jutsu no tempo de conjuração listado, você pode escolher gastar sua Ação Bônus ou Reação para sobrecarregar seus efeitos. Quando o faz, você cria um segundo conjunto de esferas de relâmpago e deve selecionar uma segunda criatura para alvejar com este jutsu.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjura este jutsu, aumente o custo em 3 e aumente o número de ataques que você pode fazer em +1.",
  },
  {
    key: "passo-celestial",
    nome: "Passo Celestial",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "90 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você conjura seu chakra do Estilo relâmpago para gerar uma partícula de eletricidade. Selecione um espaço que outra criatura não esteja ocupando que você possa ver dentro do alcance onde você lança sua partícula. Este espaço pode estar no ar, mas não pode passar por paredes ou água, parando em vez disso na primeira superfície semissólida que encontrar.\n\nVocê pode optar por mirar uma criatura com esta partícula em vez de um espaço vazio. Faça um ataque de ninjutsu à distância. Em caso de sucesso, você causa 1d8 de dano de relâmpago e o alvo deve fazer um teste de resistência de Constituição, ganhando 1 nível de estado chocado em caso de falha no teste. A partícula então ocupa o espaço aberto mais próximo como a criatura alvo.\n\nComo uma reação, você pode detonar a partícula. Todas as criaturas dentro de 5 pés da partícula devem fazer um teste de resistência de Destreza. Em caso de falha no teste, elas sofrem 2d6 de dano de relâmpago e ganham 1 nível de estado chocado. Se uma criatura que passar neste teste já estiver chocada, ela faz seu teste de resistência com uma penalidade de -2. Quando você faz isso, o jutsu termina imediatamente.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjura este jutsu, aumente o custo em 3, o dano em 1d8 e o dano adicional em 1d6, respectivamente.",
  },
  {
    key: "punho-relampago",
    nome: "Punho Relâmpago",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "M"],
    custoChakra: 3,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu", "Taijutsu"],
    descricao: "Você cobre seu punho em eletricidade pulsante, utilizando-o para golpear à frente com um soco eletricamente carregado. Realize um ataque de ninjutsu corpo a corpo (ou Taijutsu) contra uma criatura dentro do alcance. Em caso de acerto, você causa seu [Dano Desarmado] + 2d6 de dano de relâmpago e a criatura deve fazer um teste de resistência de constituição, ganhando 1 nível de estado chocado em caso de falha no teste.\n\nSobrecarga: Quando você conjura este jutsu no tempo de conjuração listado, você pode escolher gastar sua Ação Bônus ou Reação para sobrecarregar seus efeitos. Quando o faz, este jutsu ganha um bônus de +1 na faixa de ameaça crítica.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjura este jutsu, aumente o custo em 3 e aumente o número de ataques que você pode fazer em +1. Você só pode alvejar uma criatura até duas vezes com ataques feitos como resultado deste jutsu.",
  },
  {
    key: "escudo-de-relampago",
    nome: "Escudo de Relâmpago",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu", "Fuinjutsu"],
    descricao: "Você conjura seu chakra do Estilo relâmpago e o molda em torno de um selo de chakra até formar um escudo feito de Relâmpago. Durante a duração, este jutsu não pode ser encerrado como resultado de uma falha em um teste de concentração.\n\nO escudo de relâmpago que você manifesta repousa em seu braço e tem um design à sua escolha. Durante a duração, quando você sofreria dano de um ataque corpo a corpo, você pode, como uma reação, tentar desviar o ataque. Quando o faz, reduza o dano sofrido em 2d6 + seu modificador de habilidade de Ninjutsu. Se o dano for reduzido a 0, a criatura que desencadeou o ataque ganha 1 nível de estado chocado.\n\nSe o tipo de dano desencadeador for de Vento, você rola 2d4 + seu modificador de habilidade de Ninjutsu em vez disso.\n\nPara cada nível de estado chocado que uma criatura possui, aumente a redução de dano deste jutsu em +1 dado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjura este jutsu, aumente o custo em 3 e aumente a redução de dano em +2 dados.",
  },
  {
    key: "velocidade-relampago",
    nome: "Velocidade Relâmpago",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você reveste seu corpo com um filme de relâmpago enquanto se teletransporta até sua velocidade de movimento para um espaço desocupado que você pode ver, aparecendo como um clarão de relâmpago quando encerra seu movimento.",
  },
  {
    key: "garra-de-pantera",
    nome: "Garra de Pantera",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "10 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você conjura seu chakra do Estilo relâmpago e o molda ao redor de seus braços até conjurar uma construção de sua descrição.\n\nRealize um ataque de ninjutsu corpo a corpo. Em caso de acerto, você causa 2d10 de Dano de Relâmpago.\n\nSe o alvo tiver pelo menos 1 nível de estado chocado, seu dado de dano se torna d12.\nSe o alvo tiver pelo menos 2 níveis de estado chocado, você também aumenta sua faixa crítica para 19-20.\nSe o alvo tiver pelo menos 3 níveis de estado chocado, você também adiciona seu modificador de habilidade de Ninjutsu ao dano causado.\nSe o alvo tiver pelo menos 5 níveis de estado chocado, você realiza um ataque adicional de ninjutsu corpo a corpo.\n\nSobrecarga: Quando você conjura este jutsu no tempo de conjuração listado, você pode escolher gastar sua Ação Bônus ou Reação para sobrecarregar seus efeitos. Quando o faz, você pode adicionar seu modificador de habilidade de Ninjutsu ao dano causado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjura este jutsu, aumente o custo em 3 e o dano em 1d10.",
  },
  {
    key: "marca-de-choques",
    nome: "Marca de Choques",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu", "Fuinjutsu"],
    descricao: "Você conjura seu chakra do Estilo relâmpago e o molda em torno de um selo de chakra até formar um Kanji de sua própria descrição e com seu próprio significado. Este Kanji flutua em um espaço dentro de 5 pés de você e pode ser movido até 20 pés em qualquer direção de sua escolha como uma ação bônus. Escolha um dos seguintes efeitos:\n\nChoques: Todas as criaturas, exceto você, dentro de uma esfera de raio de 10 pés centrada no seu Kanji, sofrem dano de relâmpago igual a 1d6 + seu modificador de habilidade de Ninjutsu no final de cada um de seus turnos.\n\nImpactos: Todas as criaturas, exceto você, dentro de uma esfera de raio de 10 pés centrada no seu Kanji que sofrerem dano de relâmpago devem fazer um teste de resistência de constituição e ganham 1 nível de estado chocado em caso de falha no teste. Uma vez que este efeito tenha sido acionado e infligido a condição chocada 3 vezes, este jutsu termina imediatamente.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjura este jutsu, aumente o custo em 3 e o dano em 1d6 ou o número de gatilhos em +1.",
  },
  {
    key: "raio-destruidor",
    nome: "Raio Destruidor",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Um feixe de relâmpago azul crepitante se lança em direção a uma criatura dentro do alcance, formando um arco de relâmpago sustentado entre você e o alvo. Realize um ataque de ninjutsu à distância contra essa criatura. Em um acerto, o alvo sofre 2d12 de dano de relâmpago e ganha 1 nível de chocado. Uma vez em cada um de seus turnos durante a duração, você pode usar sua ação para causar 2d12 de dano de relâmpago e infligir automaticamente 1 nível de chocado.\n\nO jutsu termina se você usar sua ação para qualquer outra coisa. O jutsu também termina se o alvo deixar o alcance deste jutsu ou se estiver totalmente coberto por você. Quando este jutsu termina, o alvo original perde todos os níveis de chocado que ganhou deste jutsu.\n\nSuper recarga: Quando você conjura este jutsu com seu tempo de conjuração listado, você pode optar por gastar sua Ação Bônus ou Reação para supercarregar seus efeitos. Quando o fizer, o primeiro alvo ganha 2 níveis de chocado no primeiro acerto feito com este jutsu.",
    emNiveisSuperiores: "Para cada rank que você conjura este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o dano em 1d12.",
  },
  {
    // NOTE: heading OCR'd as a single word "ESTILO RELAMPAGO: RETRIBUICÃO" (no second wrapped line,
    // unlike most headings in this chapter). Content and fields are unambiguous; only the possibility
    // that the printed name is abbreviated/truncated is flagged.
    key: "retribuicao",
    nome: "Retribuição",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Reação, que você realiza quando sofre dano.",
    alcance: "Pessoal (Esfera de Raio de 15 pés)",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você conjura seu chakra do Estilo relâmpago e molda-o para formar um instrumento defensivo à sua escolha; pode ser uma grande espada, escudo, parede ou uma versão construída de relâmpago de você mesmo. Este jutsu não pode ser ativado contra redução psíquica ou de chakra.\n\nQuando você sofre dano, você ganha pontos de vida temporários iguais à metade do seu CD de Salvaguarda de Ninjutsu (arredondado para baixo). Enquanto tiver pontos de vida temporários ganhos por este jutsu, você tem resistência a dano de terra e vulnerabilidade a dano de vento.\n\nCada vez que você sofre dano até o final do turno atual, você acumula chakra do Estilo relâmpago. Você deve acompanhar todo o dano sofrido até o final do turno atual. Se seus pontos de vida forem reduzidos a 0 enquanto este jutsu estiver ativo, ele termina imediatamente.\n\nAo final do turno atual, você libera todo o chakra acumulado do Estilo relâmpago. Todas as criaturas dentro de uma esfera de raio de 15 pés devem realizar um teste de resistência de Destreza, sofrendo dano de relâmpago igual ao dano que você sofreu + 3d6 em uma falha ou metade desse valor em um sucesso. Se uma criatura estiver chocada, ela faz seu teste de resistência com desvantagem.",
    emNiveisSuperiores: "Para cada rank que você conjura este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o dano em 1d6.",
  },
  {
    // NOTE: heading OCR'd as "ESTILO RELAMPAGO: SEFNIDO ESTATICO". "Sefnido" is not a Portuguese
    // word; given the description (passively seeing electrical signals at range, "Sensorial" keyword),
    // the intended name is almost certainly "Sentido Estático" (Static Sense). Kept as printed.
    key: "sefnido-estatico",
    nome: "Sefnido Estático",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal",
    duracao: "1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu", "Sensorial"],
    descricao: "Você ganha a habilidade de ver sinais elétricos ocorrendo em criaturas ou objetos a até 300 pés de distância. Isso penetra até 5 pés de superfícies não metálicas.\n\nVocê pode detectar quando um objeto que funciona com eletricidade, como sistemas de comunicação não baseados em jutsu, câmeras, computadores e outros dispositivos tecnológicos estão em uso ativo, se movendo, e sua forma geral.\n\nVocê pode detectar quando criaturas podem gerar eletricidade, como estilo relâmpago ou como um fenômeno natural (enguia, ímãs, baterias, etc.).",
  },
  {
    key: "chicote-de-choque",
    nome: "Chicote de Choque",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você cria um chicote de relâmpago e o lança em uma criatura alvo dentro do alcance. O alvo deve realizar um teste de resistência de Força, sofrendo 2d10 de dano de relâmpago e sendo puxado ou empurrado 10 pés em uma falha no teste, ou metade do dano em um sucesso.\n\nSuperrecarga: Quando você conjura este jutsu com seu tempo de conjuração listado, você pode optar por gastar sua Ação Bônus ou Reação para supercarregar seus efeitos. Quando o faz, uma criatura que falha em seu teste de resistência ganha 1 nível de chocado.",
    emNiveisSuperiores: "Para cada rank que você conjura este jutsu acima do Rank D, aumente o custo deste jutsu em 3, aumente o dano em 1d10 e o alcance em 5 pés.",
  },
  {
    // NOTE: this page interleaves two entries ("Faísca" and "Marca de Thor") whose field blocks and
    // descriptions are heavily cross-cut in the OCR stream. Assignment below was resolved via content
    // matching: this entry's description text ("gerar uma faísca de força de vontade de dentro de
    // uma criatura") matches the touch/instant/Médico field set, not the ranged/concentration set.
    key: "faisca-relampago",
    nome: "Faísca",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu", "Médico"],
    descricao: "Você conjura seu chakra do Estilo relâmpago para gerar uma faísca de força de vontade de dentro de uma criatura. Uma criatura que você toca ganha 1 ponto de vida e um número de pontos de vida temporários igual a 2d6 + seu Modificador de Habilidade em Ninjutsu. Esses pontos de vida temporários duram por 1 minuto. Além disso, a criatura ganha resistência a dano de relâmpago enquanto tiver pontos de vida temporários concedidos por este jutsu.\n\nSuperrecarga: Quando você conjura este jutsu com seu tempo de conjuração listado, você pode optar por gastar sua Ação Bônus ou Reação para supercarregar seus efeitos. Quando o faz, na primeira vez que você sofreria dano de relâmpago enquanto se beneficia de pontos de vida temporários (PVs) como resultado deste jutsu, você ganha PVs temporários adicionais iguais à metade do dano causado.",
    emNiveisSuperiores: "Para cada rank que você conjura este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e os pontos de vida temporários em 1d6.",
  },
  {
    // NOTE: see "Faísca" above — this entry's description ("envia uma faísca... para se fixar em uma
    // criatura alvo... marcando-a") matches the 90 pés / Concentração / Fuinjutsu-less ranged mark
    // field set (resolved via content matching against the interleaved OCR columns).
    key: "marca-de-thor",
    nome: "Marca de Thor",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "90 pés",
    duracao: "Concentração, até 1 hora",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você envia uma faísca carregada negativamente de chakra do Estilo relâmpago para se fixar em uma criatura alvo que você pode ver dentro do alcance, marcando-a. Você não precisa gastar chakra para manter a concentração neste jutsu. Até o fim do jutsu, você causa um dado adicional de dano ao alvo sempre que o acertar com Ninjutsu que tenha a Palavra-chave de Estilo Relâmpago. Além disso, você tem vantagem em testes de Sabedoria (Percepção) ou (Sobrevivência) que fizer para rastrear ou encontrar o alvo. Se uma criatura marcada com este jutsu alcançar 0 pontos de vida, você pode mover a marca para outra criatura como uma ação bônus.",
    emNiveisSuperiores: "Para cada rank que você conjura este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e aumente o dano em 1d10.",
  },
  {
    key: "tormenta-de-trovao",
    nome: "Tormenta de Trovão",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "Cone de 25 pés",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Uma onda de força elétrica varre a partir de você. Cada criatura em um cone de 25 pés originado de você deve realizar um teste de resistência de Força. Em um falha no teste, a criatura sofre 4d4 de dano de relâmpago, é empurrada 10 pés para trás e fica chocada. Em um sucesso no teste, a criatura sofre metade desse dano e não é empurrada.\n\nSuperrecarga: Quando você conjura este jutsu com seu tempo de conjuração listado, você pode optar por gastar sua Ação Bônus ou Reação para supercarregar seus efeitos. Quando o faz, uma criatura que falhe em seu teste de resistência tem sua ordem de iniciativa reduzida em 1d4, caindo na ordem de iniciativa conforme o resultado. Uma criatura só pode ter sua iniciativa alterada duas vezes por causa deste efeito.",
    emNiveisSuperiores: "Para cada rank que você conjura este jutsu acima do Rank D, aumente o custo deste jutsu em 3, aumente o dano em 2d4 e a distância do empurrão em 5 pés.",
  },
  {
    key: "garra-de-trovao",
    nome: "Garra de Trovão",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você conjura seu chakra do Estilo relâmpago para gerar garras de relâmpago ao redor de suas mãos. Durante a duração, você pode realizar um ataque de ninjutsu corpo a corpo como uma ação. Em um acerto, você causa 2d6 + seu modificador de habilidade de ninjutsu em dano de relâmpago. Se um alvo estiver chocado, aumente o dado de dano para um d8.\n\nSuperrecarga: Quando você conjura este jutsu com seu tempo de conjuração listado, você pode optar por gastar sua Ação Bônus ou Reação para supercarregar seus efeitos. Quando o faz, a primeira vez a cada turno que você causa dano com este jutsu, se uma criatura tiver qualquer número de ranks de chocado, aumente a faixa de ameaça crítica deste jutsu em +1.",
    emNiveisSuperiores: "Para cada rank que você conjura este jutsu acima do Rank D, aumente o custo deste jutsu em 3. Se conjurado no Rank B ou superior, aumente o número de ataques em +1. Se conjurado no Rank S, aumente o número de ataques em +1.",
  },
  {
    key: "raio",
    nome: "Raio",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "relampago",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio (esfera de raio de 15 pés)",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Relâmpago", "Ninjutsu"],
    descricao: "Você gera 2 esferas de relâmpago em cada mão, descarregando-as em uma esfera de raio de 15 pés originada de você. Todas as criaturas de sua escolha na área alvo devem realizar um teste de resistência de Destreza, sofrendo 2d10 de dano de relâmpago e ficando chocadas em caso de falha no teste, ou metade desse dano em caso de sucesso.\n\nSuperrecarga: Quando você conjura este jutsu com seu tempo de conjuração listado, você pode optar por gastar sua Ação Bônus ou Reação para supercarregar seus efeitos. Quando o faz, aumente o raio deste jutsu em 10 pés.",
  },
];
