import type { JutsuDefinition } from "@/lib/jutsu/types";

export const taijutsuJutsu: JutsuDefinition[] = [
  {
    key: "chute-da-furia-bestial",
    nome: "Chute da Fúria Bestial",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Finalizador"],
    descricao: "Execute um devastador chute circular com força suficiente para afetar criaturas a até 10 pés de distância. Realize um ataque de taijutsu corpo a corpo mirando um alvo dentro do alcance. Em caso de acerto, você causa seu dano de ataque desarmado + 2d4 e o alvo deve realizar um teste de resistência de Força, sendo empurrado 10 pés para trás em caso de falha. Efeito de Finalizador: Se esta técnica for usada como um Finalizador, todas as criaturas em um cone de 15 pés diretamente à sua frente devem realizar um teste de resistência de Força. Em caso de falha, elas sofrem seu dano de ataque desarmado + 2d6, são empurradas 10 pés para trás e caem prostradas. Em caso de sucesso, elas sofrem metade do dano e não são empurradas nem derrubadas.",
    emNiveisSuperiores: "Aumente o custo desta técnica em 3 e aumente o dano em 1d4 ou 1d6 para cada rank acima de Rank D.",
  },
  {
    key: "mil-anos-de-morte",
    nome: "Mil Anos de Morte",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu"],
    descricao: "Você deve estar oculto do alvo para executar esta técnica. Movimente-se rapidamente atrás do alvo e golpeie-o com os dedos estendidos na tentativa de humilhá-lo. Realize um ataque de taijutsu corpo a corpo. Em um acerto, o alvo deve realizar um teste de resistência de Carisma. Em caso de falha, ele recua e é empurrado 15 pés em linha reta, tomado pelo constrangimento. Até o final do próximo turno do alvo, o próximo ataque corpo a corpo contra ele tem vantagem.",
  },
  {
    key: "danca-da-avalanche",
    nome: "Dança da Avalanche",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combinação"],
    descricao: "Golpeie as articulações do seu oponente para fazê-lo desmoronar sob o próprio peso. Realize um ataque de Taijutsu, causando seu dano de ataque desarmado + 1d6. O alvo deve realizar um teste de resistência de Força, ganhando 1 nível de Ferido em caso de falha. Até o final do seu turno, você pode escolher um dos alvos afetados para receber um Finalizador de Taijutsu, independentemente da distância, uma vez por turno, usando uma Ação ou Ação Bônus, ignorando o tempo de conjuração listado.",
    emNiveisSuperiores: "Aumente o custo desta técnica em 3 e o dano em +1d6 para cada rank acima de Rank D. Se conjurado em Rank B ou superior, aumente o número de ataques que você pode realizar em +1. Em Rank S, aumente o dado de dano desta técnica para d8.",
  },
  {
    key: "chute-borboleta",
    nome: "Chute Borboleta",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Golpe Final"],
    descricao: "Você salta e realiza uma série de chutes que mantêm você suspenso no ar. Enquanto realiza esses chutes, você cria uma imagem das asas de uma borboleta. Realize um ataque de taijutsu corpo a corpo contra todas as criaturas de sua escolha adjacentes a você, comparando sua determinação contra a CA delas. Em um acerto, você causa seu [Dano Desarmado] + 2d4 e força todas as criaturas atingidas a fazer um teste de resistência de Força, ganhando 1 grau de atordoamento em um fracasso. Se este jutsu for usado como um Golpe Final, todas as criaturas em um cubo de 15 pés com origem em você devem fazer um teste de resistência de Força. Em uma falha, elas sofrem seu [Dano Desarmado] + 2d8, ganham 1 grau de atordoamento e são derrubadas. Em um sucesso, sofrem metade do dano e nenhum efeito adicional. Após os alvos fazerem seus testes de resistência, escolha um espaço desocupado até 15 pés de distância onde você possa se posicionar sem provocar ataques de oportunidade.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3. Se este jutsu for conjurado no Rank C ou superior, aumente o dano causado em 2d4 ou 1d8. Se este jutsu for conjurado no Rank B ou superior, aumente o número de ataques ou graus de atordoamento em +1. Se este jutsu for conjurado no Rank A ou superior, aumente o dano causado em 2d4 ou 1d8. Se este jutsu for conjurado no Rank S, as criaturas não podem se beneficiar de bônus de jutsu em sua CA ou teste de resistência de Força.",
  },
  {
    key: "flor-de-parafusos",
    nome: "Flor de Parafusos",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 Pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você tenta desferir uma série de golpes diretos. Realize dois ataques de taijutsu, cada um causando 3d6 de dano contundente. Se acertar ambos os ataques no mesmo alvo, ele é derrubado. Até o final de seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, utilizando uma Ação ou Ação Bônus, ignorando seu tempo de conjuração listado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o dado de dano em um passo (D6 > D8 > D10 > D12). Se este jutsu for conjurado no Rank B ou superior, aumente o número de ataques em +1. Se este jutsu for conjurado no Rank S, adicione seu modificador de habilidade de Taijutsu aos rolos de dano.",
  },
  {
    key: "bracadeira",
    nome: "Braçadeira",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando é obrigado a fazer um teste de resistência de Força ou Constituição",
    alcance: "Pessoal",
    duracao: "1 rodada",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu"],
    descricao: "Você se prepara para o impacto de um efeito que sabe que não pode evitar. Você ganha um bônus de +2 ao fazer um teste de resistência de Força ou Constituição.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3. Se este jutsu for conjurado no Rank B, aumente sua jogada de resistência em +4. Se este jutsu for conjurado no Rank S, aumente sua jogada de resistência em +6.",
  },
  {
    key: "ataque-cerberus",
    nome: "Ataque Cerberus",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você golpeia rapidamente diferentes alvos que pode ver dentro do alcance. Selecione até três alvos dentro do alcance e realize um ataque de taijutsu corpo a corpo, comparando o resultado com a CA de cada um. Em um acerto, você causa seu [Dano Desarmado] + 1d8, eles não podem realizar ataques de oportunidade até o início do próximo turno deles e o próximo ataque corpo a corpo que visar qualquer criatura afetada ganha um bônus de +2 no rolagem de ataque antes do final do seu próximo turno. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, utilizando uma Ação ou Ação Bônus, ignorando seu tempo de conjuração listado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o dano em 1d10.",
  },
  {
    key: "formacao-de-asa-de-guindaste",
    nome: "Formação de Asa de Guindaste",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu"],
    descricao: "Você salta e realiza um ataque giratório que cria a imagem de uma Garça antes de tentar contornar uma criatura alvo dentro do alcance, forçando-a ao chão com este agarramento avançado. Realize um ataque de taijutsu contra o alvo, derrubando-o e agarrando-o em um acerto. Você pode agarrar um número de criaturas igual ao número de mãos que você possua. A criatura agarrada com este taijutsu pode usar sua ação no próprio turno para fazer um teste de resistência de Força para escapar do agarramento e não pode escapar do agarramento seguindo as regras normais de agarramento. Em uma falha de salvamento, você pode realizar um ataque desarmado contra o alvo causando o dobro do seu [Dano Desarmado] em um acerto.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3. Se este jutsu for conjurado no Rank C ou superior, você pode selecionar uma criatura adicional como alvo com este jutsu.",
  },
  {
    // NOTE: name/text reads "ARRASANDO PRENA RÁPIDA" in the source; "Prena" looks like a possible OCR
    // artifact (perhaps "Plena"), kept verbatim. Its "Em Níveis Superiores" text is physically printed
    // at the top of the following page, ahead of even its own heading, due to two-column layout;
    // attribution here is inferred from strong thematic match (alcance + movement distance scale together).
    key: "arrasando-prena-rapida",
    nome: "Arrasando Prena Rápida",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "15 Pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você avança rapidamente em direção a uma criatura dentro do alcance e desfere um poderoso ataque varrendo. Movimente-se até 15 pés em direção a uma criatura hostil, terminando seu movimento em um espaço adjacente a ela. Quando o fizer, realize um ataque de taijutsu corpo a corpo causando seu [Dano Desarmado] + 1d10. Se obtiver um acerto crítico, se você conjurar um Taijutsu com a palavra-chave Golpe Final de igual rank a este jutsu quando conjurado, antes do final do turno atual, seu custo é reduzido pela metade. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, utilizando uma Ação ou Ação Bônus, ignorando seu tempo de conjuração listado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o alcance deste Taijutsu e quantos pés você pode mover ao conjurar em +5 pés. Se este jutsu for conjurado no Rank B ou superior, aumente o dano em 1d10. Se este jutsu for conjurado no Rank S ou superior, aumente o dano em 1d10.",
  },
  {
    key: "mergulho-profundo",
    nome: "Mergulho Profundo",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 5,
    palavrasChave: ["Taijutsu"],
    descricao: "Você tenta arremessar uma criatura contra a superfície mais distante de você. Realize um teste de agarrar contra uma criatura que você possa alcançar. Em caso de sucesso, você imediatamente avança com ela até seu movimento completo em direção à superfície mais distante que você possa alcançar (como uma parede). Se não houver outras superfícies próximas a você, você a arremessa no chão. Independentemente de onde você a arremessar, ela sofre dano contundente igual ao seu dano desarmado. Se você e a criatura alvo estiverem em pé sobre água ou completamente submersos quando este jutsu for conjurado, você realiza seu teste de agarrar com vantagem. Em caso de sucesso, você mergulha diretamente para baixo com uma velocidade de movimento de até duas vezes a sua velocidade de movimento até o fundo do corpo de água, arremessando-os no fundo do corpo de água causando dano contundente igual ao dobro do seu dano desarmado. Este jutsu pode ser usado se você já estiver agarrando uma criatura, tentando arremessá-la imediatamente sem quaisquer verificações adicionais. Quando você arremessa com sucesso uma criatura usando este jutsu, seu agarrar termina.",
  },
  {
    key: "surto-do-ciclone",
    nome: "Surto do Ciclone",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (5 pés)",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você salta no ar, realizando um golpe giratório, atingindo e lançando todas as criaturas para o ar com você. Você salta 15 pés no ar atingindo todas as criaturas dentro do alcance. Realize um ataque de taijutsu corpo a corpo, comparando o resultado com a CA de todas as criaturas de sua escolha dentro do alcance. Em um acerto, você causa seu [Dano Desarmado] + 2d4 e é lançado 15 pés no ar, ficando no ar até o final do turno atual. Uma criatura no ar não pode conjurar jutsus com a palavra-chave Mobilidade (M) até pousar e não sofre dano por queda como resultado deste jutsu. Até o final do seu turno, você ou uma criatura aliada pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, utilizando uma Ação, Ação Bônus ou Reação, ignorando seu tempo de conjuração listado.",
  },
  {
    key: "punho-do-demonio",
    nome: "Punho do Demônio",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combo", "Confronto"],
    descricao: "Realize um poderoso uppercut com força suficiente para gerar uma onda de choque que percorre o solo, capaz de causar dano concussivo. Realize um ataque de taijutsu à distância contra uma criatura que você possa ver dentro do alcance e que esteja atualmente sobre a mesma superfície que você. Em um acerto, você causa 3d6 de dano contundente. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, utilizando uma Ação ou Ação Bônus, ignorando seu tempo de conjuração listado.",
  },
  {
    key: "dempsey-roll",
    nome: "Dempsey Roll",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você toma quando sofre dano de um ataque corpo a corpo ou quando uma criatura erra um ataque corpo a corpo contra você.",
    alcance: "5 Pés",
    duracao: "1 Rodada",
    componentes: ["M"],
    // NOTE: source lists "Custo: Especial" (variable, spent as part of the reaction's effect); no fixed
    // integer is given, so 0 is used as a placeholder — see descricao/emNiveisSuperiores for the real cost.
    custoChakra: 0,
    palavrasChave: ["Taijutsu"],
    descricao: "Você adota uma postura de boxeador quando é confrontado por um ataque corpo a corpo de uma criatura dentro de 5 pés de você. Até o início do seu próximo turno, cada ataque corpo a corpo que mirar em você, você pode gastar 4 chakra. Quando o fizer, você tenta esquivar-se e tecer, concedendo a si mesmo um bônus de +2 na CA contra a criatura que provocou o ataque e imediatamente realiza um ataque desarmado em resposta ao ataque corpo a corpo que provocou esta reação. Este bônus na CA pode acumular até duas vezes.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo de ativação em 3. Se este jutsu for conjurado no Rank B, aumente o bônus na CA em +1.",
  },
  {
    key: "ataque-da-palma-do-dragao",
    nome: "Ataque da Palma do Dragão",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 Pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 5,
    palavrasChave: ["Taijutsu", "Golpe Final", "Confronto"],
    descricao: "Como requisito para ativar este jutsu, você deve estar atualmente na Postura do Punho do Dragão. Você realiza uma miríade de movimentos distrativos antes de reunir seu chakra na palma da mão para um único golpe poderoso, atingindo o núcleo da criatura e a lançando para longe. Realize um ataque de taijutsu corpo a corpo contra uma criatura que você possa ver dentro do alcance. Em um acerto, você causa seu [Dano Desarmado] + 2d4 e empurra o alvo 10 pés para trás. Se este jutsu for usado como um Golpe Final, você causa [Dano Desarmado] + 2d12 de dano e o alvo é empurrado 10 pés a mais. Se o alvo atingir uma superfície sólida como resultado deste empurrão, ele sofre 1d6 de dano contundente para cada 10 pés que não pôde ser movido.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo de ativação em 3, o dano em 1d4 ou 1d12 e a distância do empurrão em 5 pés.",
  },
  {
    key: "arrastando-rotacao-completa",
    nome: "Arrastando Rotação Completa",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você toma quando uma criatura erra um ataque corpo a corpo contra você.",
    alcance: "5 Pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu"],
    descricao: "Quando uma criatura dentro de 5 pés de você erra um ataque corpo a corpo, você rapidamente a agarra antes que ela possa fazer qualquer outra ação, usando seu próprio momentum contra ela, arrastando-a 10 pés com você em qualquer direção de sua escolha, antes de lançá-la uma quantidade de pés igual a 5 vezes o seu modificador de Força (mínimo 1). Uma criatura cujo movimento é interrompido por uma superfície sólida (como uma árvore ou parede) sofre dano contundente igual a 1d6 para cada 10 pés que você a teria lançado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo deste jutsu em 3 e a distância que você lança uma criatura afetada em 10 pés.",
  },
  {
    key: "empate",
    nome: "Empate!",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando sofre dano de um ataque.",
    alcance: "Pessoal",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu"],
    descricao: "Você se esquiva rapidamente para trás, criando distância entre você e outra criatura. Como uma reação quando você sofreria dano de um ataque, você pode se esquivar para trás, movendo-se até 10 pés de distância do alvo que provocou o ataque na tentativa de escapar do alcance do ataque. Quando o faz, faça um teste contestado de resistência de Destreza contra o resultado do ataque. Em caso de sucesso, o ataque provocador erra você. Então, imediatamente mova-se até 20 pés em direção à criatura provocadora, realizando um ataque desarmado. Em caso de acerto, você causa seu [Dano Desarmado] + 2 [dado de dano desarmado].",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo de ativação em 3 e o dano em +1 [dado de dano desarmado].",
  },
  {
    key: "entrada-dinamica",
    nome: "Entrada Dinâmica",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Confronto"],
    descricao: "Você realiza um chute de salto alto que o propelirá em direção a uma criatura alvo que você possa ver dentro do alcance. Realize um Ataque de Taijutsu. Em um acerto, a criatura alvo sofre 3d10 de dano contundente. Independentemente se você acertar ou errar, você se move até 30 pés, terminando seu movimento a até 5 pés do alvo original.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo de ativação em 3 e o dano em 1d10.",
  },
  {
    key: "queda-do-dragao",
    nome: "Queda do Dragão",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 5,
    palavrasChave: ["Taijutsu", "Golpe Final"],
    descricao: "Como parte da ativação deste jutsu, a criatura alvo deve estar no ar ou caindo. Você salta para cima seguindo um alvo no ar ou caindo. Você se enrola em uma bola enquanto gira mais e mais rápido até ficar acima do alvo. Você se desenrola enquanto realiza um chute giratório, fazendo a criatura alvo cair violentamente no chão. Realize um ataque de taijutsu corpo a corpo contra a criatura no ar ou caindo. Em um acerto, você causa seu [Dano Desarmado] + 3d6, fazendo-os cair no chão e ficar de bruços. Se este jutsu for usado como um Golpe Final, você causa [Dano Desarmado] + 3d6 de dano contundente. Em seguida, você cai rapidamente atrás deles, fazendo um segundo ataque de taijutsu corpo a corpo, batendo os dois pés na criatura de bruços. Em um acerto, você causa 3d6 de dano contundente.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo de ativação em 3 e o dano em 1d6.",
  },
  {
    key: "combo-erratico",
    nome: "Combo Errático",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 Pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Como requisito para ativar este jutsu, você deve estar atualmente na Postura do Punho Bêbado. Você oscila dentro e fora do combate, dançando ao redor de seu oponente em um estupor alcoólico para confundi-lo. Realize dois ataques de taijutsu corpo a corpo contra uma única criatura ao seu alcance. Em um acerto, você causa 2d6 de dano contundente. Cada vez que você acerta uma criatura usando este jutsu, você aumenta sua CA em +1 até o início do seu próximo turno. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, utilizando uma Ação ou Ação Bônus, ignorando seu tempo de conjuração listado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo de ativação em 3 e o dano em 1d6.",
  },
  {
    key: "exorcismo",
    nome: "Exorcismo",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 Pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você realiza uma combinação de múltiplos ataques com toda a sua força e peso corporal. Realize três ataques de taijutsu corpo a corpo. Em um acerto, você causa 1d12 de dano contundente e empurra o alvo 5 pés em qualquer direção de sua escolha. Se você acertar pelo menos um ataque em uma criatura, ela deve fazer um teste de resistência de Constituição. Em caso de falha no teste, ela ganha +1 de classificação de Ferido. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, utilizando uma Ação ou Ação Bônus, ignorando seu tempo de conjuração listado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo de ativação em 3. Se este jutsu for conjurado no Rank B ou superior, aumente o dano em +1d12. Se este jutsu for conjurado no Rank S, aumente o dano em +1d12.",
  },
  {
    key: "touro-forte",
    nome: "Touro Forte",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SC", "M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu"],
    descricao: "Você concentra chakra por todo o seu corpo, aumentando sua força física e resistência. Pela duração, seus pontos de habilidade de Força e Constituição se tornam 16 se forem menores que 16. Você ganha 15 pontos temporários de vida que duram pela duração. Quando você conjurar um Taijutsu com a palavra-chave Golpe Final, em um acerto bem-sucedido ou se um alvo falhar na sua jogada de resistência, ele ganha +1 nível de concussão.",
  },
  {
    key: "combo-de-penas",
    nome: "Combo de Penas",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação ou 1 Reação, que você toma quando está caindo ou no ar.",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Como parte da ativação deste jutsu, você deve estar no ar, caindo ou mirando uma criatura no ar ou caindo. Você realiza um combo aéreo, atacando uma criatura dentro do alcance. Realize dois ataques de taijutsu corpo a corpo. Em um acerto, você causa seu [Dano Desarmado]. Se acertar a mesma criatura duas vezes, use o momento do segundo golpe para se impulsionar até 20 pés em qualquer direção de sua escolha e pousar em um espaço que possa suportá-lo sem sofrer dano por queda. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, utilizando uma Ação ou Ação Bônus, ignorando seu tempo de conjuração listado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo de ativação em 3 e o dano em +1d6.",
  },
  {
    key: "gato-gracioso",
    nome: "Gato Gracioso",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Próprio",
    duracao: "Concentração, até 1 minuto",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu"],
    descricao: "Você concentra chakra por todo o seu corpo, aumentando sua Destreza física e Astúcia. Pela duração, seus pontos de habilidade de Destreza e Sabedoria se tornam 16 se forem menores que 16. Você não sofre dano por queda de alturas menores que 30 pés. Sua velocidade de movimento aumenta em +20 pés e você ganha +2 na sua percepção passiva. Quando você conjurar um Taijutsu com a palavra-chave Combo, você ganha +10 de bônus na sua velocidade de movimento até o final do turno que você o conjurou.",
  },
  {
    key: "primeira-respiracao-celestial-inspire",
    nome: "Primeira Respiração Celestial: Inspire",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Concentração, até 10 Minutos",
    componentes: ["MC"],
    custoChakra: 5,
    palavrasChave: ["Taijutsu"],
    descricao: "Você aumenta a capacidade de seus pulmões em dobro. Isso aumenta sua ingestão de oxigênio e sua força física de forma semelhante. Você não pode perder a concentração deste jutsu como resultado de dano e não pode manter a concentração em Ninjutsu ou Genjutsu durante a duração. Aumente seu bônus de ataque de Taijutsu em +1, o dano de Taijutsu em 1d8 duas vezes por turno e a Velocidade em +10.",
  },
  {
    key: "aquecer",
    nome: "Aquecer",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "1 Rodada",
    componentes: ["MC", "M"],
    custoChakra: 5,
    palavrasChave: ["Taijutsu"],
    descricao: "Você libera uma onda de chakra por todo o seu corpo, ativando a produção de adrenalina e acelerando por um único e rápido momento enquanto também aumenta a sensibilidade do seu corpo à dor. Você não pode reduzir o custo deste jutsu de forma alguma. O próximo taijutsu que você conjurar, que requer um teste de ataque, aumenta seu dado de dano em 1 passo até o final do seu turno (D4 > D6 > D8 > D10 > D12). Além disso, até o início do seu próximo turno, você ganha vulnerabilidade ao próximo dano contundente, perfurante ou cortante causado por uma criatura hostil.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3. Se este jutsu for conjurado em Rank C ou superior, você relança todos os resultados de 1, 2 e 3, usando o segundo resultado. Se este jutsu for conjurado em Rank B ou superior, aumente os dados de dano em 1 passo adicional. Se este jutsu for conjurado em Rank A ou superior, o próximo taijutsu que você conjurar que requer um teste de ataque ignora resistência e imunidade. Se este jutsu for conjurado em Rank S, a duração deste jutsu se torna 1 minuto, causando o seguinte: aumente os dados de dano do Taijutsu em 2 passos adicionais durante a duração e você ganha vulnerabilidade a dano contundente, perfurante ou cortante, à sua escolha quando conjurado, durante a duração.",
  },
  {
    key: "martelo",
    nome: "Martelo",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 5,
    palavrasChave: ["Taijutsu", "Golpe Final"],
    descricao: "Como parte da ativação deste jutsu, você deve estar mirando uma criatura que possa ser alvo de um taijutsu com a palavra-chave Golpe Final, independentemente da distância. Você junta suas mãos, entrelaçando seus dedos até que suas mãos se assemelhem a um único dispositivo contundente. Faça um ataque de taijutsu corpo a corpo causando seu [Dano Desarmado] + 3d8 de dano contundente e o alvo deve realizar uma jogada de resistência de Força. Em caso de falha, eles ganham +1 nível de concussão e Tonto.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo de ativação em 3 e o dano em 1d8.",
  },
  {
    key: "monge-alto",
    nome: "Monge Alto",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Golpe Final"],
    descricao: "Você realiza uma série de chutes altos. Faça dois ataques de Taijutsu, causando seu [Dano Desarmado] + 1d6. Se este jutsu for usado como um Golpe Final, você em vez disso causa seu [Dano Desarmado] + 2d6, saltando 15 pés para trás sem provocar ataques de oportunidade.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e a distância do salto para trás em 5 pés. Se este jutsu for conjurado em Rank B, aumente o dano causado em 1d6. Se este jutsu for conjurado em Rank S, aumente o dano causado em 2d6.",
  },
  {
    key: "junta-uiva",
    nome: "Junta Uiva",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Próprio",
    duracao: "Concentração, Até 1 Minuto",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu"],
    descricao: "Como requisito para ativar este jutsu, você deve estar atualmente na postura do Punho do Lobo. Você não gasta chakra para manter a concentração deste jutsu. Você começa a exibir o poder feroz dos lobos ao se tornar um bando de um só lobo. Durante a duração, você pode executar o Punho da Presa de Lobo como uma Ação Bônus. Você pode fazer isso uma vez por turno.",
  },
  {
    key: "rajada-da-folhas",
    nome: "Rajada da Folhas",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você realiza um chute giratório baixo que desequilibra seu alvo. Uma criatura alvo dentro do alcance deve fazer um teste de resistência de Destreza. Em caso de falha no teste, eles são derrubados (caídos) e devem gastar uma Ação para se levantar até o final do próximo turno deles. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, usando uma Ação ou Ação Bônus, ignorando o tempo de conjuração listado.",
  },
  {
    key: "junta-de-ferro",
    nome: "Junta de Ferro",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Golpe Final"],
    descricao: "Como requisito para ativar este jutsu, você deve estar atualmente na postura do Punho de Ferro. Você executa um único golpe de alta potência com total intenção de causar dano. Faça um ataque de taijutsu. Em caso de acerto, você causa seu [Dano Desarmado] + 2d6 e força o alvo a fazer um teste de resistência de Força. Em caso de falha no teste, você o empurra para trás um número de pés igual a 5 vezes o modificador de Força. Se este jutsu for usado como um Golpe Final, você em vez disso causa seu [Dano Desarmado] + 4d6 e, em caso de falha no teste, eles são empurrados para trás um número de pés igual a 10 vezes o modificador de Força e, se eles atingirem uma superfície sólida com menos de 5 pés de espessura, eles a atravessam se tiverem mais de 10 pés restantes para serem empurrados para trás, sofrendo 3d6 de dano contundente.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o dano em 1d6.",
  },
  {
    key: "chute-da-folhas",
    nome: "Chute da Folhas",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Golpe Final"],
    descricao: "Você desfere um único chute descendente, forte o suficiente para fazer o ambiente desmoronar ao seu redor. Faça um ataque de Taijutsu corpo-a-corpo contra uma criatura dentro do alcance. Em caso de acerto, você causa seu dano desarmado + 1d12 e o alvo deve fazer um teste de resistência de Força. Em caso de falha no teste, eles ganham 1 nível de Velocidade Reduzida até o final do próximo turno deles. Se este jutsu for usado como um Golpe Final, você em vez disso causa seu [Dano Desarmado] + 3d12 e, em caso de falha no teste, o alvo cai prostrado enquanto você os força contra o chão, fazendo com que a área em um cubo de 10 pés ao redor de você seja considerada terreno difícil.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o dano em 1d12.",
  },
  {
    key: "greve-de-ferro",
    nome: "Greve de Ferro",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Golpe Final"],
    descricao: "Você soca com tanta força que é capaz de perfurar qualquer defesa que seu inimigo possa ter. Faça um ataque de taijutsu. Em caso de acerto, eles sofrem seu [Dano Desarmado] + 2d6. Se o alvo tentar lançar um Jutsu como uma Reação ao dano que você causar, o custo do jutsu deles é aumentado em +4 devido ao esforço necessário para acompanhar seu golpe. Se o jutsu deles não custar chakra, eles devem gastar 10 chakra para realizar a reação. Se este jutsu for usado como um Golpe Final, você em vez disso causa seu [Dano Desarmado] + 4d6 e o aumento no custo dos jutsus de Reação lançados contra você é aumentado em +8.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3, o dano em 1d8 e o aumento no custo dos jutsus de Reação em +4.",
  },
  {
    key: "blitz-miragem",
    nome: "Blitz Miragem",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando iria receber dano de um ataque corpo-a-corpo.",
    alcance: "Auto",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu"],
    descricao: "Você realiza uma esquiva giratória especial projetada para lhe dar uma pequena vantagem no seu próximo ataque. Quando você iria receber dano de um ataque corpo-a-corpo, você ganha um bônus de +3 na sua CA, potencialmente transformando um acerto em um erro enquanto você salta para trás e reage com um único golpe. Realize um ataque de taijutsu corpo-a-corpo contra a criatura que desencadeou o ataque. Em caso de acerto, você causa o dobro do seu [Dano Desarmado], empurrando o alvo 15 pés para trás e o alvo deve fazer um teste de resistência de Força, sendo derrubado em caso de falha no teste.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o dano em 1d6.",
  },
  {
    key: "uppercut-da-folhas",
    nome: "Uppercut da Folhas",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 Pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você executa um único chute de cambalhota para trás ou um uppercut ascendente com força suficiente para rachar o chão debaixo de você. Faça um único ataque de Taijutsu corpo-a-corpo. Em caso de acerto, você lança a criatura a 30 pés no ar, causando 3d6 de dano contundente. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, usando uma Ação ou Ação Bônus, ignorando o tempo de conjuração listado. Se o Golpe Final de Taijutsu tiver o prefixo Folha, ele aumenta seu dano em +1 dado de dano.",
  },
  {
    key: "ataque-salto",
    nome: "Ataque Salto",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Reação, que você realiza quando uma criatura aliada declara que vai realizar um ataque corpo-a-corpo.",
    alcance: "15 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu"],
    descricao: "Como requisito para ativar este jutsu, você deve estar atualmente na postura Punho de Sapo. Você assume uma postura de salto preparada para apoiar sua equipe. Quando uma criatura aliada dentro do alcance declara que vai realizar um ataque corpo-a-corpo contra uma criatura dentro de 30 pés delas, você bate no chão, lançando-os ao ar enquanto salta e estende seus pés, lançando-os em alta velocidade em direção ao alvo deles. A criatura aliada é movida até 30 pés em linha reta em direção ao alvo deles, terminando em um espaço adjacente de sua escolha, onde então eles devem realizar seu ataque corpo-a-corpo. Ao fazê-lo, eles podem usar seu bônus de ataque de Taijutsu ou seu bônus normal de ataque. Independentemente disso, em caso de sucesso, eles causam dano adicional igual ao seu [Dano Desarmado].",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o bônus de dano em +1 dado de [Dano Desarmado].",
  },
  {
    key: "alta-lua",
    nome: "Alta Lua",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Como parte da ativação deste jutsu, você também deve ter se movido pelo menos 15 pés em direção ao alvo. Você realiza um chute giratório duplo de salto. Realize dois ataques de taijutsu corpo-a-corpo. Em caso de acerto, você causa seu [Dano Desarmado] + 1d6. Se ambos os ataques forem bem-sucedidos, o alvo é empurrado 20 pés para trás e deve fazer um teste de resistência de Constituição. Em caso de falha no teste, eles ganham 1 nível de confusão. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, usando uma Ação ou Ação Bônus, ignorando o tempo de conjuração listado.",
  },
  {
    key: "redemoinho-de-avestruz",
    nome: "Redemoinho de Avestruz",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Golpe Final"],
    descricao: "Como parte da ativação deste jutsu, você só pode usar este taijutsu contra um alvo caído que pode ser alvo de um Golpe Final. Você realiza uma exibição acrobática de habilidade. Ao chutar uma criatura caída, você se impulsiona para trás enquanto realiza um segundo chute em movimento. Realize dois ataques de taijutsu corpo-a-corpo, em caso de acerto você causa seu [Dano Desarmado] + 2d10. Em seguida, escolha um espaço que você possa ver dentro de 20 pés, saltando para esse local, sem provocar ataques de oportunidade.",
  },
  {
    key: "golpe-na-nuca",
    nome: "Golpe na Nuca",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você tenta atingir um ponto de pressão vital na nuca de um alvo humanoide. Realize um ataque corpo-a-corpo de taijutsu. Em caso de acerto, cause seu [Dano Desarmado] + 1d6 e o alvo deve realizar um teste de resistência de Constituição. Em caso de falha no teste, eles ficam Atordoados. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, usando uma Ação ou Ação Bônus, ignorando o tempo de conjuração listado.",
  },
  {
    key: "golpe-de-reza",
    nome: "Golpe de Reza",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você realiza um golpe poderoso no núcleo do seu oponente, enviando ondas de choque pelo corpo deles que quebrariam um oponente menor e atordoariam os maiores. Realize um ataque corpo-a-corpo de taijutsu. Em caso de acerto, você causa dano contundente de 1d4 e força o alvo a realizar um teste de resistência de Constituição. Em caso de falha no teste, eles ficam Atordoados até o final do turno atual. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, usando uma Ação ou Ação Bônus, ignorando o tempo de conjuração listado.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o número de ataques em +1.",
  },
  {
    key: "impacto-nobre",
    nome: "Impacto Nobre",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu"],
    descricao: "Você se movimenta para golpear seu oponente realizando uma série regal de ataques. Realize quatro ataques de taijutsu contra uma única criatura dentro do alcance. Em caso de acerto, você causa dano contundente de 1d6. Se você acertar pelo menos 2 ataques em uma única criatura, ela não pode conjurar um Jutsu que requer Mobilidade (M) como Ação ou Ação Bônus até o final do próximo turno dela.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o dano em 1d4. Se este jutsu for conjurado no Rank B ou superior, aumente o dano causado pelo seu [Dano Desarmado].",
  },
  {
    key: "furia-do-coelho",
    nome: "Fúria do Coelho",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "Velocidade de Movimento",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Como requisito para ativar este jutsu, você deve estar atualmente na Postura do Punho de Coelho. Você entra em uma postura de ataque, sobrecarregando seus inimigos com velocidade e agilidade. Realize dois ataques de taijutsu corpo-a-corpo. Em caso de acerto, você causa seu [Dano Desarmado] + 1d6. Se seus alvos possuem níveis de Medo, aumente o dado de dano deste jutsu em 1 etapa. Se este jutsu for usado como um Golpe Final, você causa seu [Dano Desarmado] + 1d10 e se acertar dois golpes no alvo, ele deve realizar um teste de resistência de Sabedoria, ganhando +1 nível de Medo em caso de falha.",
    emNiveisSuperiores: "Para cada rank acima de Rank D que você conjurar este jutsu, aumente o custo em 3 e o dano em 1d6 ou 1d10. Se este jutsu for conjurado no Rank A ou superior, você pode aumentar o número de ataques em +1.",
  },
  {
    key: "assalto-orgulhoso",
    nome: "Assalto Orgulhoso",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 Ação",
    alcance: "5 Pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Golpe Final"],
    descricao: "Como requisito para ativar este jutsu, você deve estar atualmente na postura do Punho do Leão. Você assume uma postura orgulhosa mostrando sua superioridade e poder avassaladores. Mova-se em uma linha reta até sua velocidade de movimento, terminando em um espaço de sua escolha movendo-se através de espaços de criaturas hostis terminando seu movimento em um espaço de sua escolha que pode prendê-lo. Faça dois ataques de taijutsu comparando o resultado com todas as criaturas hostis de sua escolha CA, cujo espaço você passa, causando seu [Dano Desarmado] + 1d4. Se você atingir uma criatura com dois ou mais ataques, ela deve fazer um Teste de Resistência de Destreza. Em uma falha, ela é derrubada Prostrado. Se você se mover através de um Grande, ou espaço de criatura maior, para cada espaço dela que você se mover após o primeiro, você faz um ataque adicional contra ela. Até o final do seu turno, você pode mirar em uma criatura afetada com um Finalizador de Taijutsu independentemente do alcance, uma vez por turno, usando uma Ação ou ação Bônus, ignorando seu tempo de conjuração listado.",
  },
  {
    key: "dragao-ascendente",
    nome: "Dragão Ascendente",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 ação bônus",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você se move para golpear um alvo por baixo, levantando-o do chão. Faça um ataque de taijutsu, causando seu [Dano Desarmado] + 1d8. O alvo é lançado a 30 pés de altura até o final do seu turno atual, aterrissando em pé sem sofrer dano de queda ao final do turno atual, a menos que especificado de outra forma. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, usando uma Ação ou Ação Bônus, ignorando o tempo de conjuração listado.",
  },
  {
    key: "segunda-respiracao-celestial-ofegante",
    nome: "Segunda Respiração Celestial: Ofegante",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 reação, que você realiza quando sofre dano",
    alcance: "Próprio",
    duracao: "Especial",
    componentes: ["MC"],
    custoChakra: 5,
    palavrasChave: ["Taijutsu"],
    descricao: "Como requisito para ativar este jutsu, você deve ter a Primeira Respiração Celestial: Inalar ativa no momento. Você encerra sua concentração naquele jutsu e este assume seu lugar, mantendo as mesmas limitações de duração e restrições de conjuração de jutsu. Você mantém todos os efeitos e duração daquele jutsu, empilhando-os com os efeitos deste jutsu. Você aumenta a capacidade dos seus pulmões quatro vezes. Isso aumenta ainda mais a sua entrada de oxigênio à medida que seu corpo se expande e seus músculos se tornam mais proeminentes. Aumente seu bônus de ataque de taijutsu em +1, o dano extra de taijutsu em 1d8 duas vezes por turno, e você ganha 10 pontos de vida temporários.",
  },
  {
    key: "guarda-real",
    nome: "Guarda Real",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 ação",
    alcance: "Próprio",
    duracao: "1 rodada",
    componentes: ["MC", "M"],
    // NOTE: source lists "Custo: Especial" (you spend chakra equal to damage negated, per descricao); no
    // fixed integer is given, so 0 is used as a placeholder.
    custoChakra: 0,
    palavrasChave: ["Taijutsu"],
    descricao: "Você molda rapidamente seu chakra, criando múltiplas camadas de armadura a partir dele e levantando sua guarda para anular um ataque no exato momento em que ele o atingiria. Quando você receberia dano, você anula o impacto ao encontrá-lo com uma quantidade igual de chakra. Até o início do seu próximo turno, cada vez que você receberia dano, você pode gastar chakra igual ao dano recebido, ganhando Imunidade ao ataque ou dano e efeitos do jutsu até o final do turno atual. Se um efeito não causar dano ou custar chakra, este jutsu não previne seus efeitos. Você pode ativar os efeitos deste Jutsu um número de vezes igual ao seu modificador de habilidade Taijutsu, por conjuração.",
  },
  {
    key: "punhalada-da-serpente-dupla",
    nome: "Punhalada da Serpente Dupla",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Golpe Final"],
    descricao: "Como requisito para ativar este jutsu, você deve estar atualmente na postura do Punho da Serpente. Você assume uma postura de ataque baixo, mostrando sua concentração e precisão avassaladoras ao desabilitar seu oponente com precisão cirúrgica. Faça dois ataques de taijutsu corpo a corpo causando seu [Dano Desarmado] + 1d8. Uma criatura que seja atingida por pelo menos um desses ataques deve fazer um teste de resistência de Constituição. Em caso de falha, ela ganha +1 nível de Debilitado. Se este jutsu for usado como um Golpe Final, você causa seu [Dano Desarmado] + 1d12 e se acertar dois golpes no alvo, ele deve fazer um teste de resistência de Constituição, ganhando +2 níveis de Debilitado em caso de falha.",
    emNiveisSuperiores: "Para cada nível acima de D, aumente o custo deste jutsu em 3 e o dano em 1d8 ou 1d12.",
  },
  {
    key: "leao-em-furia",
    nome: "Leão em Fúria",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 ação",
    alcance: "Próprio",
    duracao: "Concentração, até 1 minuto",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu"],
    descricao: "Você concentra chakra por todo o seu corpo, aumentando sua Força Física e Destreza. Durante a duração, seus scores de habilidade de Força e Destreza se tornam 16 se forem menores que 16. Sua altura de salto é dobrada e você não pode realizar testes de Força ou Destreza com desvantagem. Quando você conjurar um Taijutsu que afeta uma área e força um teste de resistência, aumente o tamanho da área em +5 pés.",
  },
  {
    key: "impacto-reto",
    nome: "Impacto Reto",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 ação",
    alcance: "Toque",
    duracao: "Especial",
    componentes: ["M"],
    // NOTE: source lists "Custo: Especial" (variable, scales with how many steps you amplify the jutsu,
    // per descricao); no fixed integer is given, so 0 is used as a placeholder.
    custoChakra: 0,
    palavrasChave: ["Taijutsu", "Golpe Final"],
    descricao: "Você assume uma postura preparada, preparando seu punho ou pé para um único golpe poderoso. Ao ativar este jutsu, você pode gastar 5 chakras para revestir seu punho com esse chakra. Você aprende a ser capaz de cometer ações adicionais para tornar esse ataque mais forte. Você pode gastar sua ação bônus e mais 5 chakras adicionais para ampliar este jutsu em 1 passo. Você pode gastar sua reação e mais 5 chakras adicionais para ampliar este jutsu em 1 passo. Você pode infligir a condição de atordoamento em si mesmo até o final do seu turno até o início do próximo turno para ampliar este jutsu em 1 passo. Realize um único ataque de taijutsu flamejante. Em um acerto, você causa seu dano desarmado + 2d4 de dano. Para cada passo que você ampliar este jutsu, aumente o dano bônus em 2d4. Se este jutsu for usado como um Golpe Final, para cada passo que você ampliar este jutsu, aumente o dano bônus em 4d4.",
    emNiveisSuperiores: "Para cada nível acima de D, aumente o chakra gasto ao ativar este jutsu inicial e o efeito adicional em 3. Se este jutsu for conjurado no Rank B, aumente o dado de dano deste jutsu em 1 passo (D4 > D6). Se este jutsu for conjurado no Rank S, aumente o dado de dano deste jutsu em 1 passo (D6 > D8).",
  },
  {
    key: "movimento-silencioso",
    nome: "Movimento Silencioso",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 ação",
    alcance: "Próprio",
    duracao: "Concentração, até 1 minuto",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu"],
    descricao: "Como requisito para ativar este jutsu, você deve estar atualmente na postura do Punho Silencioso. Você assume uma postura neutra, projetada para exemplificar o silêncio e o vazio, dificultando a capacidade de prever suas ações para a maioria das criaturas. Você não gasta chakra para manter a concentração neste jutsu. Durante a duração, as criaturas não podem fazer reações contra um dos seguintes. Escolha um (isso não pode ser alterado a menos que este jutsu seja conjurado novamente): Seu Movimento. Ações Bônus que você realiza. Reações que você realiza.",
  },
  {
    key: "agarre-constrictor-da-cobra",
    nome: "Agarre Constrictor da Cobra",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "Especial",
    alcance: "5 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu"],
    descricao: "Quando você causa [Dano Desarmado] a uma criatura como resultado de um ataque desarmado, você pode conjurar este jutsu como parte desse mesmo ataque. Quando o fizer, o alvo deve realizar um teste de resistência de Força, sendo restrito em caso de falha. Como uma ação no turno da criatura alvo, ela pode tentar um teste de resistência de Força para escapar do seu agarre.",
  },
  {
    key: "danca-selvagem",
    nome: "Dança Selvagem",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 3,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você primeiro ataca seu oponente com um chute, seguido imediatamente por um soco e outro chute, atingindo-os em três ângulos diferentes. Realize três ataques de taijutsu corpo a corpo. Em um acerto, cada ataque causa 1d8 de dano contundente e empurra o alvo 5 pés em qualquer direção de sua escolha. Se o alvo não puder ser empurrado por causa de uma estrutura ou construção, como uma parede ou árvore, você o golpeia contra ela, causando um dano adicional de +1d6. Até o final do seu turno, você pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, usando uma Ação ou Ação Bônus, ignorando seu tempo de conjuração listado.",
    emNiveisSuperiores: "Para cada nível acima de D, aumente o custo deste jutsu em 3 e o dano em 1d8.",
  },
  {
    key: "danca-da-andorinha",
    nome: "Dança da Andorinha",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 ação",
    alcance: "Próprio (Cone de 10 pés)",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 5,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você executa um poderoso chute redondo de varredura ampla, levantando tanto você quanto todas as criaturas atingidas. Todas as criaturas em um cone de 10 pés originado de você devem realizar um teste de resistência de Destreza. Em caso de falha, elas recebem seu dano desarmado + 1d8 e são lançadas a 15 pés no ar até o final do turno atual, caindo prostradas.",
    emNiveisSuperiores: "Para cada nível que você conjura este jutsu acima do Rank D, aumente o custo deste jutsu em 3 e o dano em 1d8. Se você conjurar este jutsu no Rank B ou superior, aumente o dano que o alvo recebe ao bater em uma parede em 1d6. Se este jutsu for conjurado no Rank S, aumente o dano que o alvo recebe ao bater em uma parede em 1d6.",
  },
  {
    key: "chute-de-troca",
    nome: "Chute de Troca",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu", "Combo"],
    descricao: "Você salta e executa um duplo chute rápido na tentativa de apoiar sua equipe ao preparar um poderoso golpe final. Como parte da conjuração deste jutsu, você deve ter uma Ação Bônus ou reação disponível. Realize dois ataques de taijutsu contra uma criatura dentro do alcance, causando seu [Dano Desarmado] em um acerto. Se você acertar pelo menos um ataque com este jutsu, você deve gastar sua Ação Bônus ou reação. Ao fazer isso, você concede a um aliado uma reação adicional que eles só podem usar para conjurar um Taijutsu com a Palavra-chave Golpe Final que tenha um tempo de conjuração de 1 ação. Até o final do seu turno, você ou uma criatura aliada pode escolher uma criatura afetada para ser alvo de um Golpe Final de Taijutsu, independentemente da distância, uma vez por turno, usando uma Ação, Ação Bônus ou reação, ignorando seu tempo de conjuração listado.",
  },
  {
    key: "tartaruga-sabia",
    nome: "Tartaruga Sábia",
    tipo: "taijutsu",
    rank: "D",
    tempoConjuracao: "1 ação",
    alcance: "Próprio",
    duracao: "Concentração, até 1 minuto",
    componentes: ["M"],
    custoChakra: 4,
    palavrasChave: ["Taijutsu"],
    descricao: "Você concentra chakra por todo o seu corpo, aumentando sua Força física e Astúcia. Pela duração, seus atributos de Força e Sabedoria se tornam 16 se forem menores que 16. Sua força de levantamento é dobrada e você ganha +2 na sua Percepção passiva. Quando você conjurar um Taijutsu com alcance maior que 5 pés, aumente seu dano em +1 dado de dano.",
  },
];
