import type { JutsuDefinition } from "@/lib/jutsu/types";

/** Estilo Terra, Rank D — Anotações do Jiraya, p.82-89. */
export const terraJutsu: JutsuDefinition[] = [
  {
    key: "estilo-terra-espinho-agonizante",
    nome: "Estilo Terra: Espinho Agonizante",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Estilo Terra"],
    descricao:
      "Você gera fragmentos de terra e os lança contra uma criatura ou objeto dentro do alcance. Realize um Ataque de Ninjutsu à Distância contra o alvo. Em caso de acerto, o alvo sofre 3d8 de dano da Terra e deve realizar um teste de resistência de Força, sofrendo 1 grau de contusão em caso de falha no teste.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3 e o dano em 1d8.",
  },
  {
    key: "estilo-terra-caixao-de-rocha",
    nome: "Estilo Terra: Caixão de Rocha",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Estilo Terra"],
    descricao:
      "Você manipula e molda a terra sob seus inimigos para envolvê-los em um caixão de pedra. A criatura alvo realiza um teste de resistência de Destreza. Em caso de falha no teste, eles são capturados dentro do caixão e são considerados restritos e agarrados. Em caso de sucesso, eles escapam do caminho da forma desmoronante dos caixões. Em cada um de seus turnos subsequentes, eles podem realizar um teste de resistência de Força para se libertar. Se uma criatura tentar atacar o caixão para quebrá-lo, o caixão é uma Construção Terrestre, com uma CA igual ao seu CD de Salvaguarda de Ninjutsu, 25 pontos de Vida, resistência a dano de Frio e vulnerabilidade a dano de Raios.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3, o número de criaturas que você pode alvejar em +1 e os pontos de vida do caixão em 10.",
  },
  {
    // NOME INCERTO: o texto original lê "ESTILO TERRA: CALCITE: PODER" (provável erro de OCR/diagramação); melhor leitura assumida: "Cálice de Poder"
    key: "estilo-terra-calice-de-poder",
    nome: "Estilo Terra: Cálice de Poder",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Estilo Terra", "Médico"],
    descricao:
      "Você cria uma onda de Chakra do Estilo Terra e a utiliza para amplificar uma criatura disposta que você possa ver dentro do alcance. Uma vez conjurado com sucesso, você não precisa mais ver onde está o alvo, mas deve permanecer dentro de 120 pés dele. A Força da criatura alvo se torna 18 durante a duração, se ainda não for. Seus ataques desarmados, com armas e Taijutsu causam um dano adicional de 1d6 de dano da Terra, e você sempre sabe quando eles sofrem dano e sua condição atual, mesmo que não possa vê-los durante a duração.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3 e o número de criaturas afetadas em +1.",
  },
  {
    key: "estilo-terra-pele-de-rocha",
    nome: "Estilo Terra: Pele de Rocha",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Reação, que você realiza quando sofre dano.",
    alcance: "Pessoal",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Estilo Terra"],
    descricao: "O jutsu endurece a pele em resposta ao dano recebido. Reduza o dano que você sofre até o início do seu próximo turno em 1d6+4 (exceto dano psíquico ou de Raios).",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3 e a redução de dano em +4.",
  },
  {
    // NOME INCERTO: o texto original lê "ESTILO TERRA: ESTANDARTE / DOMINOUS" — grafia mantida literalmente por falta de leitura melhor.
    key: "estilo-terra-estandarte-dominous",
    nome: "Estilo Terra: Estandarte Dominous",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Pessoal (raio de 10 pés)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "A (Qualquer)"],
    custoChakra: 5,
    palavrasChave: ["Estilo Terra", "Ninjutsu"],
    descricao:
      "Você reveste sua arma com chakra terrestre, erguendo-a acima de você e liberando seu chakra dourado na forma de um estandarte, enquanto um pulso de chakra dourado aprimora as armas de seus aliados, convertendo sua defesa em ofensiva. Você não pode perder a concentração deste jutsu como resultado de dano. Durante a duração, uma arma que você e cada criatura aliada afetada por este jutsu estejam empunhando é aprimorada pelo seu chakra terrestre dourado. As armas aprimoradas causam um dano adicional de 1d4 de dano da Terra duas vezes por turno e concedem ao seu portador +3 de redução de dano contra todas as fontes (exceto Raios e psíquico). Se você ou as criaturas aliadas afetadas soltarem a arma ou ela for retirada de seu portador original, o chakra dourado se dispersa.",
    emNiveisSuperiores:
      "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3. Se este jutsu for conjurado no Rank B ou superior, aumente o dano bônus para 2d4 e a redução de dano para +6. Se este jutsu for conjurado no Rank S, aumente o dano bônus para 3d4 e a redução de dano para +9.",
  },
  {
    key: "estilo-terra-rio-do-fluxo-da-terra",
    nome: "Estilo Terra: Rio do Fluxo da Terra",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal (cone de 30 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Terra", "Ninjutsu"],
    descricao:
      "Você transforma a superfície à sua frente em um rio de lama. O rio criado é um cone de 30 pés que varre as criaturas de seus pés e as carrega até o final do cone, mais distante do conjurador. Criaturas no caminho do deslizamento de lama devem realizar um teste de resistência de Força. Em caso de falha no teste, elas são arrastadas e movidas até o final do fluxo, caem prostradas, são desarmadas de quaisquer armas ou itens que estejam segurando e têm sua velocidade reduzida em 10 pés até o final do próximo turno delas. Em caso de sucesso no teste, nenhum efeito ocorre.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3, o tamanho do cone em 5 pés e a velocidade que elas são reduzidas em 5 pés.",
  },
  {
    key: "estilo-terra-agarrar-terrestre",
    nome: "Estilo Terra: Agarrar Terrestre",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Terra", "Ninjutsu"],
    descricao:
      "Você seleciona um quadrado de 5 pés de espaço desocupado no chão que você pode ver dentro do alcance. Uma mão de tamanho médio feita de terra, solo e poeira se forma e alcança uma criatura que você pode ver a 10 pés dela. O alvo deve fazer um teste de resistência de Força. Em uma falha, o alvo sofre 2d6 de dano de terra e é agarrado e contido pela duração do Jutsu. Uma criatura agarrada dessa forma tem uma de suas mãos amarrada e é incapaz de formar Selos de Mão ou usar Selos de Chakra com ela. Como uma ação bônus, você pode fazer a mão esmagar o alvo contido, causando 2d6 de dano de terra. Como uma ação em seu turno, o alvo contido pode refazer o teste de resistência. Em um sucesso, o alvo escapa e não é mais contido pela mão. Como uma ação, você pode fazer a mão alcançar uma criatura diferente ou se mover até 30 pés para um espaço desocupado diferente que você pode ver. Este movimento deve ser ao longo da mesma superfície ou superfície conectada à qual a mão está presa. A mão libera um alvo contido se você fizer qualquer uma das duas coisas. Esta mão conta como um Fragmento de terremoto.",
    emNiveisSuperiores: "Para cada rank que você conjura este jutsu acima do Rank D, aumente o custo deste jutsu em 3, o número de mãos de barro que podem alvejar outras criaturas em +1 e aumente o dano em 1d6.",
  },
  {
    key: "estilo-terra-rancor-da-espinha-de-terra",
    nome: "Estilo Terra: Rancor da Espinha de Terra",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal",
    duracao: "1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Ninjutsu", "Estilo Terra"],
    descricao:
      "Você gera fragmentos de terra e os levita ao seu redor, criando um campo de detritos de pedra para protegê-lo. Durante a duração deste jutsu, ataques à distância são realizados como se você estivesse sob meia cobertura, com a terra flutuante ao seu redor. Além disso, criaturas de sua escolha consideram todos os espaços dentro de 10 pés de você como terreno difícil. Esta terra flutuante conta como uma única construção terrestre enquanto estiver ativa.",
  },
  {
    key: "estilo-terra-entroncamento-terrestre",
    nome: "Estilo Terra: Entroncamento Terrestre",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Estilo Terra"],
    descricao:
      "Arcos de pedra gancho e segurando brotam do chão em um cubo de 20 pés a partir de um ponto dentro do alcance. Durante a duração, esses arcos terrestres transformam o solo em terreno difícil. Criaturas não podem realizar a ação de Correr ou Esquivar-se enquanto estiverem dentro desta área de terreno difícil. Criatura(s) de sua escolha na área quando você conjurar o ninjutsu devem realizar um teste de resistência de Força ou ficarão restritas pelos arcos de pedra entrecruzados até o final do jutsu. Uma criatura restrita pela terra pode usar sua ação para fazer um teste de resistência de Força contra o seu CD de Salvaguarda de Ninjutsu. Em caso de sucesso, ela se liberta. Quando você conjura este jutsu, o terreno difícil permanece mesmo após você encerrar a concentração deste jutsu. O terreno difícil pode ser removido com 10 minutos de trabalho tentando fazê-lo. Enquanto o terreno difícil permanecer, ele conta como uma única construção terrestre.",
  },
  {
    key: "estilo-terra-genese-geologica",
    nome: "Estilo Terra: Gênese Geológica",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "30 Pés",
    duracao: "Especial",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Estilo Terra"],
    descricao:
      "Você cria um fragmento de terra cintilante, feito de chakra do Estilo Terra. Este fragmento pode ter qualquer forma que você escolher e pode cintilar em qualquer cor que você goste. Em seguida, você seleciona um espaço que você pode ver dentro do alcance e lança o fragmento cintilante para o espaço escolhido. Como ação bônus em seu turno, você pode ativar o fragmento fazendo-o explodir em uma cabeça de flor florescente feita de terra. Todas as criaturas dentro de 10 pés do fragmento devem realizar um teste de resistência de Força. Em caso de falha no teste, você causa 2d6 + o modificador de habilidade de Ninjutsu de dano da Terra e 1 nível de contusão; ou metade dessa quantidade em dano e nenhum efeito adicional em um teste bem-sucedido. Uma vez que a flor floresce, ela permanece imóvel no chão e conta como uma construção terrestre. Até 3 criaturas de tamanho médio podem ficar seguramente na flor de terra. Como reação ou ação bônus, você pode fazer com que a flor se eleve a 60 pés no ar, levando qualquer criatura em pé com ela. A flor se dissolve ao final do seu próximo turno.",
  },
  {
    key: "estilo-terra-tremor-terrestre",
    nome: "Estilo Terra: Tremor Terrestre",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés (cubo de 20 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Terra", "Ninjutsu"],
    descricao:
      "Você causa um tremor no chão em um cubo de 20 pés centrado em um ponto que você pode ver dentro do alcance. Cada criatura que não seja você naquela área deve realizar um teste de resistência de Destreza. Em caso de falha no teste, a criatura sofre 2d8 de dano da Terra e é derrubada no chão. Se o solo naquela área for terra solta ou pedra, ele se torna terreno difícil até ser limpo, o que requer aproximadamente 10 minutos de trabalho.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3, o dano em 1d8 e o raio em 5 pés.",
  },
  {
    key: "estilo-terra-couraca-geologica",
    nome: "Estilo Terra: Couraça Geológica",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal",
    duracao: "1 Hora",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Estilo Terra"],
    descricao:
      "Você cria uma aura de chakra do Estilo Terra que permeia seu corpo pela duração. Este chakra age como uma couraça de material semelhante ao aço. Durante a duração, seu CA é calculado como 13 + seu modificador de Inteligência (ou Constituição, à sua escolha) + metade do seu bônus de proficiência. Enquanto você estiver obtendo o benefício deste cálculo de armadura, você ganha +3 de redução de dano contra todas as fontes (exceto dano psíquico ou de Raios). Este jutsu termina se você usar armadura, dispensar o jutsu como uma ação bônus ou se você alterar o cálculo de armadura como resultado de uma característica de clã ou classe.",
    emNiveisSuperiores:
      "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3. Se este jutsu for conjurado no Rank B, aumente a redução de dano que este jutsu proporciona para +6. Se este jutsu for conjurado no Rank S, aumente a redução de dano que este jutsu proporciona para +9.",
  },
  {
    key: "estilo-terra-geolocalizacao-geologica",
    nome: "Estilo Terra: Geolocalização Geológica",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "Auto",
    duracao: "10 minutos",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Terra", "Ninjutsu", "Sensorial"],
    descricao:
      "Você estende seu chakra por toda a terra ao seu redor, até uma distância de 30 pés de você. Durante a duração, você ganha sentido de tremores. Criaturas que se movem sob a superfície na qual você está em pé são percebidas por você com seu sentido de tremores.",
    emNiveisSuperiores:
      "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3. Se conjurado no Rank C, aumente a duração para 1 hora. Se conjurado no Rank B, a duração é de 8 horas. Se conjurado no Rank A, a duração é de 24 horas.",
  },
  {
    key: "estilo-terra-isotoma-geologica",
    nome: "Estilo Terra: Isotoma Geológica",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "90 Pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Estilo Terra"],
    descricao:
      "Você amplifica construtos feitos de terra fazendo-os manifestar uma aura de chakra do Estilo Terra. Selecione um Construto de Terra de sua criação dentro do alcance. Todas as criaturas de sua escolha dentro de 60 pés do construto escolhido ganham um bônus de +1 em sua CA, enquanto você diminui o peso das criaturas escolhidas permitindo que elas se movam mais rapidamente e com menos resistência. Uma criatura pode ser afetada por no máximo 2 auras criadas por este jutsu.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3. Se conjurado no Rank B, aumente o bônus na CA para +2. Se conjurado no Rank S, aumente o bônus na CA para +3.",
  },
  {
    key: "estilo-terra-gemas-douradas",
    nome: "Estilo Terra: Gemas Douradas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "Auto",
    duracao: "1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Estilo Terra"],
    descricao:
      "Você solidifica seu chakra do Estilo Terra em 2 pequenas gemas cristalinas brilhantes. As gemas podem ser de qualquer cor que você escolher e flutuam ao seu redor durante a duração. Você pode gastar suas gemas para aprimorar outros jutsus do Estilo Terra. Ao gastar 1 Gema Dourada, quando você conjura um Ninjutsu com a palavra-chave Estilo Terra, você pode aprimorá-lo de uma das seguintes maneiras: Reforçar: Se o jutsu invocado invoca um construto ou estrutura que intercepta dano, aumente seus pontos de vida em 1d10. Você pode gastar até 5 gemas desta forma. Endurecer: Se o jutsu invocado concederia pontos de vida temporários a uma criatura, aumente a quantidade ganha em 1 dado. Solidificar: Se o jutsu invocado causaria dano, aumente o dano causado em 1 dado de dano.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3 e você gera 1 gema adicional.",
  },
  {
    key: "estilo-terra-ressonancia-geologica",
    nome: "Estilo Terra: Ressonância Geológica",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "90 Pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Estilo Terra"],
    descricao:
      "Você amplifica construtos feitos de terra fazendo-os manifestar uma aura de chakra do Estilo Terra. Selecione um Construto de Terra de sua criação dentro do alcance. Todas as criaturas de sua escolha dentro de 60 pés do construto escolhido devem realizar um teste de resistência de Força a cada turno que começam na aura de um Construto. Se uma criatura estiver dentro de 2 auras diferentes criadas por este jutsu, ela faz um único teste de resistência. Em caso de falha no teste, a CA da criatura é reduzida em 1 até o início do próximo turno dela, enquanto você aumenta o peso das criaturas escolhidas forçando-as a se mover mais lentamente. Uma criatura pode ser afetada por no máximo 2 auras criadas por este jutsu.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3. Se conjurado no Rank B, aumente a penalidade na CA para -2. Se conjurado no Rank S, aumente a penalidade na CA para -3.",
  },
  {
    key: "estilo-terra-devocao-de-jade",
    nome: "Estilo Terra: Devoção de Jade",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (esfera de 10 pés)",
    duracao: "1 Minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Ninjutsu", "Estilo Terra"],
    descricao:
      "Você libera uma onda de chakra do Estilo terra que permeia você e seus aliados. Todas as criaturas dispostas de sua escolha dentro de uma esfera de 10 pés centrada em você ganham 4d6 pontos de vida temporários e resistência a dano contundente, perfurante e cortante enquanto tiverem pontos de vida temporários concedidos por este jutsu. Criaturas que têm pontos de vida temporários concedidos por este jutsu são contadas como Construtos da Terra criados por você.",
    emNiveisSuperiores: "Para cada rank acima do Rank D que você conjurar este jutsu, aumente o custo em 3 e os pontos de vida temporários em 1d6.",
  },
  {
    key: "estilo-terra-tecnica-do-cacador-de-cabecas",
    nome: "Estilo Terra: Técnica do Caçador de Cabeças",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Terra", "Ninjutsu"],
    descricao:
      "Enquanto estiver escavando sob um alvo, você pode tentar arrastá-lo para baixo, deixando-o submerso na terra com apenas a cabeça exposta. A criatura alvo deve fazer um teste de resistência de Destreza para evitar ser arrastada para dentro da terra e ficar restrita. Se você estiver oculto do alvo e ele não estiver ciente de sua presença, ele faz essa salvaguarda com desvantagem. Criaturas que estão restritas por este jutsu podem fazer um teste de Força (Atletismo) contra seu valor de CD de salvaguarda de Ninjutsu como uma ação em seu turno para escapar do solo, encerrando a condição restrita.",
  },
  {
    key: "estilo-terra-chuva-de-jade",
    nome: "Estilo Terra: Chuva de Jade",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "90 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "SC"],
    // Fonte lista "Custo: Especial (28 Chakra)" — custo fixo de jutsu de Combinação, não o valor normal por rank.
    custoChakra: 28,
    palavrasChave: ["Ninjutsu", "Estilo Terra", "Fuinjutsu", "Combinação"],
    descricao:
      "Ao tecer selos de mão juntos, você cria um selo feito completamente de chakra do Estilo Terra brilhante no ar acima de você. Este selo então altera seu ângulo antes de você liberar um enxame de fragmentos brilhantes de pedras afiadas. Todas as criaturas em uma linha de 15 pés de largura e 90 pés de comprimento originando-se de você devem fazer um teste de resistência de Destreza, sofrendo 6d6 de dano de terra em uma falha ou metade desse dano em um sucesso. Combinação: Se este jutsu for conjurado como um jutsu de Combinação com 2 ou mais usuários, você aumenta o dado de dano em 3. Qualquer criatura que ajude na conjuração deste jutsu como um jutsu de combinação aumenta o dano deste jutsu em um passo com base no modificador de Carisma mais alto dentro do grupo de conjuradores. (+0-1: Sem Mudança, +2: D8, +3-4: D10, +5: D12).",
  },
  {
    // Reconstrução de coluna incerta para este par (Tela de Jade / Movimento de Toupeira): os campos Alcance/Custo/Componentes/Palavras-chave
    // seguem a posição estrutural das colunas do PDF; verificar contra o livro original se possível.
    key: "estilo-terra-tela-de-jade",
    nome: "Estilo Terra: Tela de Jade",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "Auto",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Terra", "Ninjutsu"],
    descricao:
      "Você convoca dois pilares de terra, cada um com 15 pés de altura e 5 pés de espessura. Eles ocupam um espaço que pode contê-los e devem estar a até 25 pés um do outro, sem outras estruturas diretamente entre eles. Esses pilares são estruturas de seu design e não podem ser movidos uma vez conjurados. Uma linha de chakra do Estilo terra é criado entre os dois pilares em linha reta. Este filme e os pilares compartilham um número de pontos de vida igual ao dobro do seu valor de CD de Proteção de Ninjutsu e têm resistência a dano contundente, perfurante e cortante. Todos os ataques ou jutsus de um lado de sua escolha, que passariam por este filme, em vez disso o atingem, reduzindo seus pontos de vida como se fosse o alvo original. Quando os pontos de vida da estrutura e do filme alcançam 0, este jutsu termina imediatamente, pois a estrutura desmorona. Todos os ataques à distância que passariam pelo filme do outro lado passam sem causar danos e ataques de Ninjutsu e Taijutsu de sua escolha aumentam seu alcance em 10 pés, e o dano em 1 dado de dano. Este jutsu pode causar dano adicional dessa forma não mais do que 3 vezes por conjuração.",
  },
  {
    // Reconstrução de coluna incerta (ver comentário em Tela de Jade). Alcance "30 pés" e Custo Especial/Fuinjutsu/Combinação
    // seguem a posição estrutural da coluna deste jutsu no PDF, mas a descrição sugere um efeito de auto-enterramento.
    key: "estilo-terra-movimento-de-toupeira",
    nome: "Estilo Terra: Movimento de Toupeira",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC", "SC"],
    custoChakra: 28,
    palavrasChave: ["Ninjutsu", "Estilo Terra", "Fuinjutsu", "Combinação"],
    descricao:
      "Você começa a afundar no chão depois de converter a terra sob seus pés em uma substância semelhante a areia macia. Você ganha uma velocidade de escavação de 30 pés. Você pode escavar tanto terra quanto areia. Se ficar sem chakra enquanto estiver subterrâneo, você emerge diretamente de onde está. Você deixa um único túnel grande o suficiente para que uma pessoa passe de cada vez. Você tem conhecimento de quantas pessoas estão na superfície diretamente acima de você em uma esfera de raio 10 pés centrada em você.",
  },
  {
    key: "estilo-terra-onda-de-lama",
    nome: "Estilo Terra: Onda de Lama",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (cone de 20 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Terra", "Ninjutsu"],
    descricao:
      "Você revolve a terra à sua frente e a lança para frente em um cone de 20 pés. Criaturas no cone devem fazer um teste de resistência de Força, sofrendo 3d6 de dano de terra e ficando machucadas em caso de falha no teste, e metade desse dano sem nenhum efeito adicional em caso de sucesso. Combinação: Se este jutsu for conjurado como um jutsu de Combinação com 2 ou mais usuários, nenhum dos conjuradores precisa gastar chakra para manter a concentração neste jutsu. Qualquer criatura que ajudar na conjuração deste jutsu como um jutsu de combinação aumenta o dano baseado no modificador de Carisma mais alto dentro do grupo de conjuradores. (+0-1: Sem Mudança, +2: +2 dados de dano adicionais, +3: +3 dados de dano adicionais, +4: +4 dados de dano adicionais, +5: +5 dados de dano adicionais).",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo em 3, o dano em 1d6 e o tamanho do cone em 5 pés.",
  },
  {
    key: "estilo-terra-punho-de-pedra",
    nome: "Estilo Terra: Punho de Pedra",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "Auto",
    duracao: "1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Terra", "Ninjutsu", "Choque"],
    descricao:
      "Você envolve um único braço em rocha, permitindo-se golpear com socos endurecidos, enquanto também se protege do contato direto. Durante a duração deste jutsu, quando você realiza a ação de ataque, você causa seu Dano Desarmado +2d6 de dano de terra. Os benefícios deste jutsu não podem ser aplicados a qualquer Taijutsu ou Bukijutsu, sob quaisquer circunstâncias. Durante a duração deste jutsu, uma de suas mãos está ocupada e não pode ser usada para fazer Sinais Manuais (SM) ou usar Selos de Chakra (SC). Além disso, quando você golpeia uma criatura com o braço envolto, isso não conta como contato direto com ela.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo em 3. Quando este jutsu é conjurado no Rank B, aumente o dano em 1d6. Quando este jutsu é conjurado no Rank S, aumente o dano em 1d6.",
  },
  {
    key: "estilo-terra-tecnica-da-rocha-em-ascensao",
    nome: "Estilo Terra: Técnica da Rocha em Ascensão",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Terra", "Ninjutsu", "Choque"],
    descricao:
      "Você arranca dois grandes pedaços de pedras do chão usando apenas a força de seu chakra, lançando-os em um único alvo. Realize dois ataques de ninjutsu à distância contra o alvo, causando 2d8 de dano de terra em um acerto. Os dois grandes pedaços de pedra permanecem após serem lançados, sendo contados como construtos terrestres, ocupando dois espaços de sua escolha dentro de 5 pés do alvo original. Selecione dois espaços dentro de 5 pés de você ao conjurar este jutsu. Esses dois espaços de onde você retirou as pedras contam como terreno difícil até serem limpos, o que leva pelo menos 10 minutos de trabalho.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo em 3. Quando este jutsu é conjurado no Rank B, aumente o número de ataques em +1. Quando este jutsu é conjurado no Rank S, aumente o número de ataques em +1.",
  },
  {
    key: "estilo-terra-shuriken-de-pedra",
    nome: "Estilo Terra: Shuriken de Pedra",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "terra",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Terra", "Ninjutsu"],
    descricao: "Você molda pequenas pedras em forma de shuriken. Quando faz isso, você as dispara autonomamente, uma após a outra, como balas que rasgam e atravessam os inimigos. Realize um ataque de ninjutsu à distância. Em um acerto, você causa 4d6 de dano de terra e inflige 1 machucado.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo em 3 e o dano em 1d6.",
  },
];
