import type { JutsuDefinition } from "@/lib/jutsu/types";

/** Estilo Vento, Rank D — Anotações do Jiraya, p.109-115. */
export const ventoJutsu: JutsuDefinition[] = [
  {
    key: "estilo-vento-bala-de-ar",
    nome: "Estilo Vento: Bala de Ar",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você cria uma pequena esfera de ar comprimido na palma da sua mão antes de lançá-la contra uma criatura alvo que você possa ver dentro do alcance. Você dispara duas balas de ar. Você pode direcionar as balas para o mesmo alvo ou alvos diferentes. Realize dois ataques de ninjutsu à distância, causando 2d8 de dano de vento.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de Rank-D, aumente o custo deste jutsu em 3 e o número de ataques em +1.",
  },
  {
    key: "estilo-vento-danca-da-corrente-de-ar",
    nome: "Estilo Vento: Dança da Corrente de Ar",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "Ação Bônus",
    alcance: "Pessoal (esfera de raio de 10 pés)",
    duracao: "1 Minuto",
    componentes: ["SM", "MC"],
    custoChakra: 3,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você agita correntes de ar ao redor de suas mãos e gera uma nuvem de poeira que envolve você e qualquer pessoa dentro do raio deste jutsu em uma densa nuvem de poeira e detritos. Todas as criaturas são tratadas como se tivessem cobertura total enquanto estiverem dentro da nuvem, em relação às criaturas fora da nuvem e vice-versa. Esta cobertura total não impede que ataques ou jutsus entrem ou saiam da nuvem. Criaturas que não sejam você têm desvantagem em testes de percepção para ver através da nuvem se possuírem visão especial como Visão de Chakra. Além disso, a visão de criaturas que não sejam você é tratada como se estivesse em luz fraca enquanto estiverem dentro da nuvem.",
  },
  {
    key: "estilo-vento-folego-coletivo",
    nome: "Estilo Vento: Fôlego Coletivo",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "15 Pés",
    duracao: "1 Minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Vento", "Ninjutsu", "Médico"],
    descricao:
      "Você coleta chakra do Estilo vento e o infunde em sua técnica do Estilo Médico. Uma criatura disposta dentro do alcance respira este vento infundido medicamente. Durante a duração, uma criatura que tenha respirado este vento não precisa respirar, ignora os efeitos de 2 níveis de Exaustão e, quando recuperar pontos de vida como resultado de um ninjutsu com a Palavra-chave Médico, recupera um adicional de 1d4 pontos de vida.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de Rank-D, aumente o custo deste jutsu em 3 e ignora os efeitos de até 2 níveis adicional de Exaustão.",
  },
  {
    key: "estilo-vento-vento-distorcido",
    nome: "Estilo Vento: Vento Distorcido",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Reação, que você realiza quando receberia dano",
    alcance: "Pessoal",
    duracao: "1 Rodada",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Seu corpo se torna borrado, oscilando e tremeluzindo para todos que podem vê-lo. Quando conjurado, o ataque que desencadeou esta reação rola um d20 adicional, considerando o resultado mais baixo. Durante a duração, até o início do seu próximo turno, criaturas hostis têm desvantagem em ataques contra você. Um atacante é imune a este efeito se não depender de visão, como com Visão Cega, ou puder ver através de ilusões, como com Visão Verdadeira.",
  },
  {
    key: "estilo-vento-ondas-de-ar-bufante",
    nome: "Estilo Vento: Ondas de Ar Bufante",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "60 Pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você cria correntes de ar extremamente fortes e comprimidas, capazes de rachar pedra e desviar cachoeiras. Realize um ataque de ninjutsu à distância. Em caso de acerto, a criatura alvo sofre 4d4 de dano de vento e deve realizar um teste de Força. Em caso de falha no teste, ela é empurrada 20 pés para trás, derrubada no chão e ganha 1 nível de sangramento. Remoinho. Criaturas que falhariam no teste de resistência delas espalham todas as condições elementares afetando-as no momento para todas as criaturas, exceto o conjurador, dentro de 5 pés delas. Criaturas hostis dentro de 5 pés da que falhou no teste ganham 1 nível de todas as condições elementares afetando-a no momento.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de Rank-D, aumente o custo deste jutsu em 3, o dano em 1d4 e os níveis de sangramento em +1.",
  },
  {
    key: "estilo-vento-contra-brisa",
    nome: "Estilo Vento: Contra-Brisa",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Reação, que você realiza quando receberia dano de um Ninjutsu ou Taijutsu",
    alcance: "Pessoal",
    duracao: "1 Rodada",
    componentes: ["SM", "MC", "M"],
    custoChakra: 5,
    palavrasChave: ["Estilo Vento", "Ninjutsu", "Confronto"],
    descricao:
      "Você cria uma bolha condensada de ar super denso ao seu redor na tentativa de desviar ataques entrantes. Role 2d10 + Modificador de Habilidade de Ninjutsu. O resultado do lançamento é a quantidade de dano que sua bolha de ar pode prevenir antes de estourar. Isso dura até o início do seu próximo turno. Dano de Raios causa metade do dano à sua bolha de ar e Dano de Fogo causa o dobro de dano.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de Rank-D, aumente o custo deste jutsu em 3 e role um adicional de 1d10.",
  },
  {
    key: "estilo-vento-palma-de-vendaval",
    nome: "Estilo Vento: Palma de Vendaval",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "5 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "M"],
    custoChakra: 4,
    palavrasChave: ["Estilo Vento", "Ninjutsu", "Confronto"],
    descricao:
      "Você une suas mãos cobrindo suas palmas abertas em um vendaval poderoso. Você realiza um ataque de ninjutsu corpo a corpo em uma criatura ou objeto alvo. Em caso de acerto, a criatura sofre 3d6 de dano de vento e deve realizar um teste de resistência de Força para resistir ao empurrão de 20 pés para trás. Em caso de sucesso no teste de Força, ela não sofre efeitos adicionais.",
  },
  {
    key: "estilo-vento-vento-de-poeira",
    nome: "Estilo Vento: Vento de Poeira",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (Cone de 15 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você gera um vento forte dos seus pulmões com um único sopro. Ao exalar, você levanta uma nuvem de poeira, sujeira e outros detritos soltos no raio alvo. Criaturas que estiverem na área afetada devem realizar um teste de Resistência de Sabedoria. Em caso de falha, as criaturas afetadas são consideradas cegas até o final do próximo turno delas. Em caso de sucesso no teste, nenhum efeito adicional é aplicado. Redemoinho. Criaturas que falhariam no teste de resistência delas espalham todas as condições elementares afetando-as no momento para todas as criaturas, exceto o conjurador, dentro de 5 pés delas. Criaturas hostis dentro de 5 pés daquela que falhou no teste ganham 1 nível de todas as condições elementares afetando-as no momento.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de Rank-D, aumente o custo deste jutsu em 3 e o tamanho do cone em 10 pés.",
  },
  {
    key: "estilo-vento-rugido-de-leoes",
    nome: "Estilo Vento: Rugido de Leões",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "Pessoal",
    duracao: "Concentração, até 1 Minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você entrelaça chakra do Estilo vento, criando um véu fino de chakra em forma de leão ao seu redor. Este chakra então colapsa sobre você concedendo benefícios conforme listado abaixo: Aumenta sua Velocidade de Movimento em 15 pés. Você ganha um bônus de +2 nas jogadas de ataque de ninjutsu. Ninjutsu que você conjura com a Palavra-chave de Estilo Vento que tenha alcance de pelo menos 5 pés aumenta seu alcance em 10 pés.",
  },
  {
    key: "estilo-vento-queda-de-penas",
    nome: "Estilo Vento: Queda de Penas",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Reação, que você realiza quando começa a cair.",
    alcance: "Pessoal",
    duracao: "1 Minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao: "Você cria um único fluxo de ar de alta pressão a partir das suas mãos ou pés, reduzindo sua descida enquanto cai em 60 pés por rodada até o fim do jutsu. Se você pousar antes do fim do ninjutsu, não sofrerá dano de queda, pousando de pé, e o jutsu termina.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de Rank-D, aumente o custo deste jutsu em 3 e selecione 1 alvo adicional para os benefícios deste jutsu dentro de 30 pés de você.",
  },
  {
    key: "estilo-vento-vortice-de-palma",
    nome: "Estilo Vento: Vórtice de Palma",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (cone de 3 metros)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você cria um vórtice localizado de vento cortante. Todas as criaturas dentro do alcance devem realizar um teste de resistência de Destreza para evitar serem terrivelmente cortadas. Em uma falha no teste, as criaturas sofrem 3d6 de dano de vento e são puxadas 1,5 metros na sua direção. Em um sucesso no teste, elas sofrem metade do dano e não sofrem efeitos adicionais. Se uma criatura estiver atualmente sob efeito de qualquer condição elemental, você ativa as energias residuais elementais, inflamando-as novamente. Uma criatura sob efeito de uma condição elemental faz seu teste de resistência com desvantagem. Em uma falha no teste, tal criatura sofre 3d8 + o modificador de habilidade de seu Ninjutsu de dano do tipo da sua condição selecionada.",
    emNiveisSuperiores: "Para cada rank acima de Rank-D que você conjure este jutsu, aumente o custo em 3, o dano em 1d6 ou 1d8.",
  },
  {
    key: "estilo-vento-bater-de-asa-de-griffin",
    nome: "Estilo Vento: Bater de Asa de Griffin",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (raio de 20 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você cria duas asas feitas de chakra do Estilo vento que batem com força suficiente para parecer que um tornado está passando. Todas as criaturas dentro do alcance devem realizar um teste de resistência de Força para resistir a serem machucadas e derrubadas. Uma criatura que estiver machucada achará difícil manter a concentração em múltiplos jutsus. Se uma criatura estiver concentrando em mais de 1 jutsu, ela deve perder a concentração em todos, exceto 1. Redemoinho. Criaturas que falhariam no teste de resistência delas espalham todas as condições elementares afetando-as no momento para todas as criaturas, exceto o conjurador, dentro de 5 pés delas. Criaturas hostis dentro de 5 pés daquela que falhou no teste ganham 1 nível de todas as condições elementares afetando-as no momento.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de Rank-D, aumente o custo deste jutsu em 3 e o alcance em 10 pés.",
  },
  {
    key: "estilo-vento-tifao-passante",
    nome: "Estilo Vento: Tifão Passante",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "Auto (esfera de raio de 15 pés)",
    duracao: "Concentração, até 1 Minuto",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você cria uma corrente poderosa de ventos fortes em uma esfera de raio de 15 pés, centrada em você. Este campo de vento também o segue. Durante a duração, enquanto estiver dentro da área deste jutsu, ele ensurdece outras criaturas, extingue chamas desprotegidas, torna-se terreno difícil para criaturas que não sejam você e dispersa vapores, gases e névoas que podem ser dispersados por ventos fortes. Além disso, ataques à distância têm desvantagem se passarem para dentro ou para fora da área deste jutsu.",
  },
  {
    key: "estilo-vento-vento-furioso",
    nome: "Estilo Vento: Vento Furioso",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "60 pés (raio de 15 pés)",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você manifesta um poderoso turbilhão de vento, forte o suficiente para levantar e lançar a maioria das criaturas. Seleciona um espaço que você pode ver dentro do alcance. Um turbilhão espiral de vento irrompe para cima. Todas as criaturas dentro de 15 pés do espaço escolhido devem realizar um teste de resistência de Força. Em uma falha no teste, elas são lançadas 30 pés para cima, ficam atordoadas, sofrem dano de queda e caem prostradas. Redemoinho. Criaturas que falhariam no teste de resistência espalham todas as condições elementais atualmente afetando-as para todas as criaturas, excluindo o conjurador dentro de 5 pés delas. Criaturas hostis dentro de 5 pés da criatura que falhar no teste ganham 1 nível de todas as condições elementais atualmente afetando-a.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo em 3 e a altura que elas são lançadas para cima em 15 pés.",
  },
  {
    key: "estilo-vento-redemoinho-de-pavao",
    nome: "Estilo Vento: Redemoinho de Pavão",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 4,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você gera um vento forte ao varrer um de seus membros. Uma rajada de vento é gerada em uma linha reta de 30 pés de comprimento por 5 pés de largura, originando-se de você. Criaturas na linha devem realizar um teste de resistência de Força, sofrendo 2d6 de dano de vento, sendo derrubadas e ganhando 1 nível de sangramento em caso de falha no teste, e apenas metade do dano e nenhum efeito adicional em caso de sucesso no teste. Redemoinho. Criaturas que falhariam no teste de resistência delas espalham todas as condições elementares afetando-as no momento para todas as criaturas, exceto o conjurador, dentro de 5 pés delas. Criaturas hostis dentro de 5 pés daquela que falhou no teste ganham 1 nível de todas as condições elementares afetando-as no momento.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima de Rank-D, aumente o custo deste jutsu em 3, o dano em 1d6 e os níveis de sangramento em +1.",
  },
  {
    key: "estilo-vento-vortice-furioso",
    nome: "Estilo Vento: Vórtice Furioso",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "Toque",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você envolve uma criatura disposta com poderosa Chakra de Estilo Vento. Durante a duração, você amplia as capacidades físicas do alvo. A criatura alvo adiciona 1d4 a todos os testes de habilidade e salvaguardas de Força e Destreza. A velocidade de movimento deles é aumentada em 15 pés, e ataques corpo a corpo que eles realizarem que causam dano infligem um dano adicional de 1d6 de Vento.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo em 3 e o número de alvos que você pode afetar em +1.",
  },
  {
    key: "estilo-vento-segundo-vento",
    nome: "Estilo Vento: Segundo Vento",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação Bônus",
    alcance: "Auto",
    duracao: "Instantâneo",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao: "Você respira profundamente, enchendo seus pulmões e sangue com oxigênio de chakra filtrado, acelerando o fluxo sanguíneo e rejuvenescendo levemente. Você recupera 2d6 + o modificador de habilidade de Ninjutsu pontos de vida.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo em 3 e role um adicional de 1d6.",
  },
  {
    key: "estilo-vento-vendaval-de-apoio",
    nome: "Estilo Vento: Vendaval de Apoio",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Reação para realizar um teste de resistência de Força, Destreza ou Constituição",
    alcance: "Pessoal",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você lança suas mãos para a frente criando uma explosão comprimida de ar que o ajuda em várias tarefas físicas; desde escapar, repelir um ataque, ou dispersar um gás perigoso. Como uma reação, quando você for obrigado a realizar um teste de resistência de Força, Destreza ou Constituição contra um Ninjutsu ou Taijutsu, você usa o modificador de habilidade de Ninjutsu no lugar de sua Força, Destreza ou Constituição para o teste que provocou essa reação.",
    emNiveisSuperiores:
      "Para cada rank acima de D, aumente o custo deste jutsu em 3. Se lançado no rank C, você adiciona seu bônus de proficiência ao teste se ainda não for proficiente. Se lançado no rank B, você pode selecionar outra criatura a até 20 pés de você para receber os benefícios deste jutsu, usando seu modificador de habilidade e bônus de proficiência. Se lançado no rank A, as criaturas que se beneficiam deste jutsu têm vantagem no teste. Se lançado no rank S, todas as criaturas de sua escolha a até 30 pés de você podem receber os benefícios deste jutsu.",
  },
  {
    key: "estilo-vento-ondas-cortantes",
    nome: "Estilo Vento: Ondas Cortantes",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "30 pés",
    duracao: "Instantâneo",
    componentes: ["SM", "MC", "M"],
    custoChakra: 4,
    palavrasChave: ["Estilo Vento", "Ninjutsu", "Confronto"],
    descricao: "Você cria uma corrente poderosa de ventos extremamente fortes e finos. Você move sua mão em direção ao seu alvo. Realize um ataque de Ninjutsu à distância. Criaturas atingidas sofrem 3d8 de dano de vento e ganham 1 nível de sangramento em um acerto.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo em 3, o dano em 1d8 e os níveis de sangramento em +1.",
  },
  {
    key: "estilo-vento-vento-dividido",
    nome: "Estilo Vento: Vento Dividido",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "90 pés",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você cria um campo de vento opressivo e potente que corta e golpeia qualquer instância de sinais de mão (SM). Selecione um espaço que você pode ver dentro do alcance, todas as criaturas dentro de 20 pés do espaço escolhido que tentarem conjurar um jutsu com o componente de sinais de mão (SM) imediatamente sofrem 2d6 de dano de vento e devem realizar um teste de resistência de Constituição, ganhando a condição de sangramento em uma falha no teste. Como ação bônus em seu turno, você pode mover o campo até 30 pés em qualquer direção para um espaço que você pode ver dentro do alcance.",
    emNiveisSuperiores: "Para cada rank que você conjurar este jutsu acima do Rank D, aumente o custo em 3, o tamanho da área afetada em 5 pés, e o dano em 1d6.",
  },
  {
    key: "estilo-vento-chuva-de-vacuo",
    nome: "Estilo Vento: Chuva de Vácuo",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "1 Ação",
    alcance: "90 pés (cilindro de 20 pés de diâmetro)",
    duracao: "Concentração, até 1 minuto",
    componentes: ["SM", "MC"],
    custoChakra: 28,
    palavrasChave: ["Estilo Vento", "Ninjutsu", "Combinação"],
    descricao:
      "Você cria uma poderosa corrente ascendente que suga o oxigênio e o ar para cima, privando criaturas da capacidade de respirar dentro do alcance. Todos os lançadores deste jutsu criam um cilindro de 20 pés de largura por 60 pés de altura, removendo todo o ar de seu interior e substituindo-o por lâminas furiosamente rotativas de Chakra de Estilo Vento, centrado em um ponto de sua escolha dentro do alcance. Todas as criaturas dentro do cilindro devem realizar um teste de resistência de Destreza e Constituição. Em uma falha no teste de Destreza, elas são cortadas repetidamente pelo chakra do vento, sofrendo 2d6 de Dano Cortante e 2d6 de Dano de Vento, ou metade disso em caso de sucesso. A criatura realiza este teste de resistência no início de cada turno que começar dentro do cilindro. Em uma falha no teste de Constituição, elas são privadas do ar nos pulmões e começam a sufocar. Uma criatura sufocante só pode sobreviver por um número de rodadas igual ao seu modificador de Constituição antes de desmaiar e perder a consciência devido à falta de ar. A criatura realiza este teste de resistência no início de cada turno que começar dentro do cilindro. Uma criatura inconsciente pode recuperar a consciência quando outra criatura gasta uma ação para acordá-la. As criaturas dentro do cilindro não podem obter os benefícios de um aumento na velocidade de movimento e são tratadas como se estivessem em terreno difícil. Combinação: Se este jutsu for lançado como um jutsu de Combinação com 2 ou mais lançadores, aumente o dano em 2d6 para cada tipo de dano. Qualquer criatura que auxiliar no lançamento deste jutsu como um jutsu de Combinação aumenta o tamanho da área de efeito deste Jutsu com base no modificador de Carisma mais alto dentro do grupo de lançadores. (+0-1: Sem mudança, +2: Aumente a altura em +10 pés e o raio para 30 pés, +3: Aumente a altura em +20 pés e o raio para 40 pés, +4: Aumente a altura em +30 pés e o raio para 50 pés, +5: Aumente a altura em +40 pés e o raio para 60 pés).",
  },
  {
    key: "estilo-vento-bomba-de-vacuo",
    nome: "Estilo Vento: Bomba de Vácuo",
    tipo: "ninjutsu",
    rank: "D",
    natureza: "vento",
    tempoConjuracao: "Especial",
    alcance: "60 pés",
    duracao: "Instantânea",
    componentes: ["SM", "MC"],
    custoChakra: 5,
    palavrasChave: ["Estilo Vento", "Ninjutsu"],
    descricao:
      "Você cria um único ponto de alta pressão de ar usando seu Chakra de Estilo Vento antes de expandi-lo e criar uma série de reações. Todas as criaturas atualmente afetadas por uma condição elemental que teriam um jutsu lançado sobre elas que provoca o efeito de redemoinho, potencialmente passam todas essas condições para outras criaturas próximas a elas em um espaço expandido com mais volatilidade. Quando uma criatura teria o efeito de redemoinho acionado sobre ela, você pode lançar este jutsu como parte da mesma ação. Todas as criaturas a até 20 pés da criatura que provocou o gatilho e falhou em seu teste ganham dois níveis de todas as condições elementais que a criatura que provocou o gatilho tinha.",
    emNiveisSuperiores: "Para cada rank acima de D, aumente o custo deste jutsu em 3 e o tamanho da área afetada em 5 pés.",
  },
];
