import type { ClassProgressionDefinition } from "@/lib/classProgression/types";

/**
 * Progressão completa do Ninja Batedor (Scout-Nin) — "Observações do
 * Orochimaru" (compêndio de Classes), p.360-410. Complementa o resumo em
 * catalog/classes.ts com a tabela nível-a-nível (1-20), as características
 * por extenso e as 9 subclasses de "Técnica de Reconhecimento" (escolhida
 * no 3º nível, com recursos no 3º, 6º, 9º, 14º, 17º e 20º).
 *
 * Cada subclasse usa um recurso de "Manobras" alimentado por Dados de
 * Superioridade (como um sistema de mestre de batalha), com um catálogo de
 * opções sem nível fixo. A fonte extraída capturou esses catálogos de
 * forma desigual:
 * - Árbitro, Assalto, Clonagem, Barreira, Elemental e Desbravador tiveram
 *   seus catálogos de manobras capturados com texto completo — incluídos
 *   abaixo como características de catálogo.
 * - Fantasma, Tático e Trapaceiro tiveram apenas os NOMES das manobras
 *   identificados, sem texto — sinalizado como lacuna em cada subclasse,
 *   sem inventar conteúdo.
 *
 * Outras notas sobre a fonte:
 * - O grupo de subclasses aparece na tabela como "Técnica de Escotismo" e
 *   no corpo do texto como "Técnica de Reconhecimento" — mantido o nome
 *   do corpo do texto.
 * - A linha do 18º nível veio corrompida na fonte; os valores de Jutsu
 *   Conhecidos/Rank foram interpolados a partir das linhas vizinhas.
 * - A subclasse "Escoteiro de Clonagem" foi remontada juntando dois
 *   trechos da fonte (3º nível em um, 6º-20º e o catálogo de manobras em
 *   outro); a tabela de Dados de Superioridade/Manobras Conhecidas também
 *   foi remontada juntando as duas metades (níveis 3-11 e 12-20).
 * - A subclasse "Escoteiro Desbravador" teve sua manobra "Pontos de Troca"
 *   remontada juntando dois trechos da fonte.
 */
export const progressaoNinjaBatedor: ClassProgressionDefinition = {
  classeKey: "ninja-batedor",
  nomeGrupoSubclasse: "Técnica de Reconhecimento",
  nivelEscolhaSubclasse: 3,

  levels: [
    { nivel: 1, bonusProficiencia: 3, caracteristicas: "Postura de Luta, Explorador Hábil",
      colunasExtras: { "Jutsu Conhecidos": "6", "Rank Mais Alto do Jutsu": "Rank-D" } },
    { nivel: 2, bonusProficiencia: 3, caracteristicas: "Adepto Shinobi",
      colunasExtras: { "Jutsu Conhecidos": "7", "Rank Mais Alto do Jutsu": "Rank-D" } },
    { nivel: 3, bonusProficiencia: 3, caracteristicas: "Técnica de Reconhecimento",
      colunasExtras: { "Jutsu Conhecidos": "8", "Rank Mais Alto do Jutsu": "Rank-D" } },
    { nivel: 4, bonusProficiencia: 4, caracteristicas: "Melhoria/talento na pontuação de habilidade",
      colunasExtras: { "Jutsu Conhecidos": "8", "Rank Mais Alto do Jutsu": "Rank-D" } },
    { nivel: 5, bonusProficiencia: 4, caracteristicas: "Ataque Extra, Jack de Todos os Ofícios, Mestre de Nenhum",
      colunasExtras: { "Jutsu Conhecidos": "9", "Rank Mais Alto do Jutsu": "Rank-C" } },
    { nivel: 6, bonusProficiencia: 4, caracteristicas: "Técnica de Reconhecimento (2), Explorador Hábil (Mobilidade)",
      colunasExtras: { "Jutsu Conhecidos": "10", "Rank Mais Alto do Jutsu": "Rank-C" } },
    { nivel: 7, bonusProficiencia: 5, caracteristicas: "Jutsu de Assinatura",
      colunasExtras: { "Jutsu Conhecidos": "11", "Rank Mais Alto do Jutsu": "Rank-C" } },
    { nivel: 8, bonusProficiencia: 5, caracteristicas: "Melhoria/talento na pontuação de habilidade",
      colunasExtras: { "Jutsu Conhecidos": "11", "Rank Mais Alto do Jutsu": "Rank-C" } },
    { nivel: 9, bonusProficiencia: 5, caracteristicas: "Técnica de Reconhecimento (3)",
      colunasExtras: { "Jutsu Conhecidos": "12", "Rank Mais Alto do Jutsu": "Rank-B" } },
    { nivel: 10, bonusProficiencia: 6, caracteristicas: "Técnica de Assinatura",
      colunasExtras: { "Jutsu Conhecidos": "13", "Rank Mais Alto do Jutsu": "Rank-B" } },
    { nivel: 11, bonusProficiencia: 6, caracteristicas: "Explorador Hábil (Incansável)",
      colunasExtras: { "Jutsu Conhecidos": "14", "Rank Mais Alto do Jutsu": "Rank-B" } },
    { nivel: 12, bonusProficiencia: 6, caracteristicas: "Melhoria/talento na pontuação de habilidade",
      colunasExtras: { "Jutsu Conhecidos": "14", "Rank Mais Alto do Jutsu": "Rank-B" } },
    { nivel: 13, bonusProficiencia: 7, caracteristicas: "Adepto Shinobi (2)",
      colunasExtras: { "Jutsu Conhecidos": "15", "Rank Mais Alto do Jutsu": "Rank-A" } },
    { nivel: 14, bonusProficiencia: 7, caracteristicas: "Técnica de Reconhecimento (4)",
      colunasExtras: { "Jutsu Conhecidos": "16", "Rank Mais Alto do Jutsu": "Rank-A" } },
    { nivel: 15, bonusProficiencia: 7, caracteristicas: "Jutsu de Assinatura (2)",
      colunasExtras: { "Jutsu Conhecidos": "17", "Rank Mais Alto do Jutsu": "Rank-A" } },
    { nivel: 16, bonusProficiencia: 8, caracteristicas: "Melhoria/talento na pontuação de habilidade",
      colunasExtras: { "Jutsu Conhecidos": "17", "Rank Mais Alto do Jutsu": "Rank-A" } },
    { nivel: 17, bonusProficiencia: 8, caracteristicas: "Técnica de Reconhecimento (5)",
      colunasExtras: { "Jutsu Conhecidos": "18", "Rank Mais Alto do Jutsu": "Rank-S" } },
    { nivel: 18, bonusProficiencia: 8, caracteristicas: "-",
      colunasExtras: { "Jutsu Conhecidos": "19", "Rank Mais Alto do Jutsu": "Rank-S" } },
    { nivel: 19, bonusProficiencia: 9, caracteristicas: "Melhoria/talento na pontuação de habilidade",
      colunasExtras: { "Jutsu Conhecidos": "20", "Rank Mais Alto do Jutsu": "Rank-S" } },
    { nivel: 20, bonusProficiencia: 9, caracteristicas: "Técnica de Reconhecimento (6)",
      colunasExtras: { "Jutsu Conhecidos": "20", "Rank Mais Alto do Jutsu": "Rank-S" } },
  ],

  features: [
    {
      nivel: 1,
      nome: "Fundição de Jutsu",
      descricao: "CD de resistência do Ninjutsu = 8 + bônus de proficiência + modificador de Inteligência; modificador de ataque de Ninjutsu = bônus de proficiência + modificador de Inteligência. CD de resistência de Genjutsu = 8 + bônus de proficiência + modificador de Sabedoria; modificador de ataque de Genjutsu = bônus de proficiência + modificador de Sabedoria. CD de resistência de Taijutsu = 8 + bônus de proficiência + modificador de Força; modificador de ataque de Taijutsu = bônus de proficiência + modificador de Força.",
    },
    {
      nivel: 1,
      nome: "Postura de Luta",
      descricao: "A partir do 1º nível, você adota um estilo particular de luta como sua especialidade. Escolha uma Postura de Combate do Capítulo 13: Opções de Personalização, entre Postura de Taijutsu e Postura de Arma. Não pode escolher a mesma postura mais de uma vez, mesmo que possa trocar de escolha mais tarde.",
    },
    {
      nivel: 1,
      nome: "Explorador Hábil",
      descricao: "A partir do 1º nível, você é um generalista insuperável na maioria dos ambientes.\n\nAstúcia (1º nível): escolha uma perícia qualquer e ganhe proficiência nela; se já for proficiente, ganha experiência (dobra o bônus de proficiência) nela.\n\nMobilidade (6º nível): sua velocidade ao escalar paredes e se mover sobre a água passa a ser igual à sua velocidade de caminhada; ganha velocidade de natação e escalada iguais à de caminhada.\n\nIncansável (11º nível): precisa de menos tempo para descansar e se recuperar. Uma vez por descanso longo, pode gastar um turno inteiro de sua ação para descansar, recuperando todos os dados de vida gastos que normalmente recuperaria em um descanso curto.",
    },
    {
      nivel: 2,
      nome: "Adepto Shinobi",
      descricao: "A partir do 2º nível, sua habilidade como shinobi floresceu, concedendo-lhe uma variedade de caminhos opcionais. Escolha dois dos recursos a seguir (mais dois a partir do 13º nível, que você ainda não tenha escolhido):\n\n- Treinamento de Shinobi: cria, aprende e personaliza qualquer jutsu Rank D ou inferior na metade do tempo normal (não acumula com outros recursos que reduzam o tempo de aprendizado; a partir do 13º nível, também vale para jutsu Rank C).\n- Táticas de Shinobi: criaturas que tentam procurá-lo sofrem -1d4 no teste, se você estiver escondido ou fora de visão.\n- Alfabetização Geral do Shinobi: pode contar suas pontuações de habilidade como 16 para fins de aprender/obter jutsu de Rank B ou superior por restrições de pontuação de habilidade (não acumula com outros traços de alfabetização).\n- Competência em Ferramentas de Shinobi: pode usar bombas de pimenta, bombas de papel, Flash Tags ou Bombas de Fumaça como ação bônus em vez de ação.\n- Precisão do Shinobi: selecione uma palavra-chave (Ninjutsu, Taijutsu, Bukijutsu ou Genjutsu); o jutsu que lançar com essa palavra-chave e que exija rolagem de ataque reduz a RD do alvo em 5, uma vez por conjuração.\n- Borda do Shinobi: reduz em 1 (mínimo 1) o custo para manter concentração em um jutsu.",
    },
    {
      nivel: 4,
      nome: "Melhoria/Talento de Pontuação de Habilidade",
      descricao: "Ao atingir o 4º nível, e novamente no 8º, 12º, 16º e 19º, você pode aumentar uma pontuação de habilidade em +1 e um Talento de sua escolha para o qual se qualifique. Não é possível aumentar uma pontuação de habilidade acima de 20 usando este recurso.",
    },
    {
      nivel: 5,
      nome: "Ataque Extra",
      descricao: "A partir do 5º nível, você pode atacar duas vezes, em vez de uma, sempre que realizar a ação de Ataque em seu turno.",
    },
    {
      nivel: 5,
      nome: "Jack de Todos os Ofícios, Mestre de Nenhum",
      descricao: "A partir do 5º nível, você exemplifica o ideal do combate generalizado. Selecione uma generalização, obtendo seus benefícios. Pode trocá-la ao completar um descanso, ou gastar um dado de Superioridade da sua subclasse para trocá-la, uma vez por descanso curto.\n\n- Combate: +1 (+2 no 11º nível) em ataque e dano com Ninjutsu, Taijutsu, Genjutsu e Bukijutsu; ao usar a ação de Ataque, pode fazer um ataque com arma como ação bônus, uma vez por turno.\n- Controle: +1 (+2 no 11º) na CD de jutsu/manobras que infligem condição ou penalidade; enquanto beneficiado, +1d4 em verificações de confronto.\n- Mobilidade: +3 metros (+4,5 no 11º) de velocidade e +1 (+2 no 11º) em lances de defesa contra efeitos hostis; ao usar perícia não-proficiente para encerrar condição/efeito hostil em um lance de defesa, +1d4.\n- Habilidade: +2 (+3 no 11º) em verificações de perícia e habilidade; ações baseadas em habilidade que exigem ação podem ser feitas como ação bônus.\n- Apoio: pode usar Ajudar e Procurar como ação bônus; pode gastar reação para interpor um ataque, redirecionando um ataque hostil de um aliado para você; alcance de Ajudar de 9 metros (13,5 no 11º); criaturas no alcance que ataquem/lancem jutsu contra um aliado provocam ataque de oportunidade seu.",
    },
    {
      nivel: 7,
      nome: "Jutsu de Assinatura",
      descricao: "A partir do 7º nível, você encontrou um jutsu no qual se especializa. Selecione um jutsu conhecido Rank B ou inferior; ganha um dos benefícios abaixo ao usá-lo (pode trocar o jutsu afetado ao aprender um novo jutsu ao subir de nível; a partir do 15º nível, pode selecionar um segundo efeito para obter os benefícios de ambos):\n\n- Poder de Assinatura: causa dano adicional igual ao seu modificador de habilidade do jutsu; ignora resistência ao tipo de dano escolhido; não pode ser negado/dissipado no turno em que é lançado.\n- Aumento de Assinatura: se o jutsu adiciona um dado extra por grau de upcast, adiciona um dado adicional, uma vez por conjuração; caso contrário, aumenta a CD em +1 a cada dois níveis de upcast.\n- Controle de Assinatura: reduz o custo do jutsu em 2 (mínimo 1); se exigir concentração, reduz o custo de manutenção em até metade.",
    },
    {
      nivel: 10,
      nome: "Técnica de Assinatura",
      descricao: "A partir do 10º nível, você se compromete temporariamente com uma técnica. Ao completar um descanso, selecione uma opção (a partir do 18º nível, pode se beneficiar de duas simultaneamente):\n\n- Técnica Oculta: como ação, estando ao menos levemente obscurecido, você e aliados em raio de 1,5 metro ficam invisíveis (com equipamento); quem tentar localizá-los sofre -10, e se ninguém se mover não podem ser detectados por sentido de Tremor, jutsu Sensorial ou visão de chakra; se você ou um aliado atacar enquanto beneficiado, o ataque é crítico automático se o resultado for 5 ou mais acima da CA do alvo (uma vez, até um descanso longo).\n- Técnica Agressiva: como ação bônus, gaste 2 Dados de Vida para recuperar 1d10 + seu nível de Batedor em PV; ou gaste 2 de chakra para recuperar 1d10 + metade do seu nível de Batedor em chakra.\n- Técnica Tática: criaturas não podem fazer ataques de oportunidade contra você ou aliados em raio de 3 metros; você e aliados que iniciem o turno a até 3 metros podem usar Disparada como ação bônus.",
    },
  ],

  subclasses: [
    {
      key: "escoteiro-arbitro",
      nome: "Escoteiro Árbitro",
      classeKey: "ninja-batedor",
      descricaoIntro: "Os Scout-Nin que escolhem se tornar Árbitros se concentram em aprimorar seus aliados, utilizando suas habilidades além do que a maioria dos shinobi só poderia sonhar em fazer, permitindo que sua equipe realize feitos de proezas incríveis com apenas um pouco de arbitragem.",
      features: [
        { nivel: 3, nome: "Arbitragem Superior", descricao: "A partir do 3º nível, você aprende manobras alimentadas por um Dado de Superioridade (d8). Aprende três manobras à escolha (catálogo abaixo), ganhando mais com o nível (Manobras Conhecidas: 3º-4 níveis seguintes: 3; 8º-12º: 4; 13º-17º: 5; 18º-20º: 6). Dados de Superioridade: 3 no 3º nível, 4 no 6º, 5 no 9º, 6 no 12º, 7 no 15º, 8 no 18º. Só pode usar uma manobra por ataque ou criatura aliada por turno. Ao tirar um descanso longo, pode trocar uma manobra conhecida por outra para a qual se qualifique. Um dado é gasto quando usado; todos os gastos são recuperados ao terminar um descanso curto ou longo." },
        { nivel: 3, nome: "Mestre da Arbitragem", descricao: "A partir do 3º nível, você aprende a impor sua presença em qualquer discussão ou briga. Ganha proficiência em Enganação, Intimidação e Persuasão. Pode gastar um dado de Superioridade ao fazer qualquer verificação de habilidade baseada em Carisma, somando o resultado à verificação. A partir do 6º nível, sempre que for bem-sucedido em uma verificação baseada em Carisma contra uma criatura hostil ou não aliada, recupera 1 dado de Superioridade dessa forma, uma vez por criatura, por descanso." },
        { nivel: 3, nome: "Julgamento no Campo de Batalha", descricao: "Também no 3º nível, você se torna o líder que sua equipe precisa. Uma vez por turno, ao fazer a ação de Ataque, no lugar de um de seus ataques, pode ordenar que um aliado que o veja/ouça lance um jutsu que exija rolagem de ataque, faça um ataque com arma, realize uma ação de habilidade, se esquive ou se desvencilhe (movendo-se até metade do deslocamento). Pode comandar uma criatura assim duas vezes por rolagem de iniciativa. Além disso, quando um aliado faz uma rolagem de ataque, pode gastar um dado de Superioridade para somar o resultado a ela." },
        { nivel: 6, nome: "Autoridade Absoluta", descricao: "A partir do 6º nível, você e aliados em raio de 9 metros podem somar metade do seu modificador de Carisma (arredondado para baixo) à CA, desde que não estejam usando armadura pesada." },
        { nivel: 9, nome: "Presença Imponente", descricao: "A partir do 9º nível, quando se beneficiar de Mestre da Arbitragem, a criatura-alvo sofre -1d6 em verificações de Carisma contra você. Além disso, aliados sob Genjutsu que iniciem o turno a até 3 metros de você refazem o lance de defesa para encerrar o efeito (uma vez por descanso curto, por criatura). Você e aliados em raio de 3 metros que façam lances de defesa contra Genjutsu ganham bônus igual à metade do seu modificador de Carisma." },
        { nivel: 14, nome: "Presença do Paragão", descricao: "A partir do 14º nível, todos os aliados em raio de 9 metros são imunes às condições Berserk, Encantado ou Temido (você escolhe qual ao final de um descanso curto)." },
        { nivel: 17, nome: "Comando Incansável", descricao: "A partir do 17º nível, você pode rolar 1d4 em vez de gastar um Dado de Superioridade para Mestre da Arbitragem, Julgamento no Campo de Batalha ou Presença de Comando." },
        { nivel: 20, nome: "Quem Decidiu Isso?", descricao: "A partir do 20º nível, quando falhar em um lance de defesa, pode ter sucesso em vez disso, sem sofrer efeitos adicionais (duas vezes por descanso curto). Além disso, quando outra criatura em raio de 9 metros falhar em um lance de defesa, pode gastar um dado de Superioridade para que ela tenha sucesso. Uma criatura só pode se beneficiar assim uma vez por descanso longo." },
        { nivel: 3, nome: "Catálogo de Manobras do Árbitro", descricao: `Lista de manobras disponíveis para o recurso Arbitragem Superior (3º nível).

- Precisão Assistida: gaste um dado de Superioridade visando um aliado em raio de 9 metros. No próximo ataque dele, soma metade do resultado do dado à rolagem de ataque. Em acerto, se você fizer o mesmo tipo de ataque contra a mesma criatura no seu próximo turno, soma o mesmo dado à sua rolagem.
- Controle Assistido: gaste um dado de Superioridade visando um aliado em raio de 9 metros. Na próxima vez que ele forçar um hostil a um lance de defesa via jutsu, soma metade do resultado do dado à CD (mín. 1). Se o hostil falhar e você o atacar no próximo turno, soma o mesmo dado ao dano.
- Exemplo de Líderes: ao atingir uma criatura com ataque corpo a corpo, gaste um dado de Superioridade somando o resultado à sua rolagem de ataque. Em acerto, selecione um aliado em raio de 9 metros; se ele fizer o mesmo tipo de ataque contra a mesma criatura no turno seguinte, soma o mesmo resultado à rolagem dele.
- Autoridade dos Líderes: ao atingir uma criatura com um ataque, gaste um dado de Superioridade. Todos os hostis em raio de 4,5 metros fazem lance de defesa de Sabedoria contra sua CD (ou CD de Taijutsu, se arma/desarmado), ganhando 1 grau de Medo em falha.
- Presença de Líderes: ao atingir uma criatura com um ataque, gaste um dado de Superioridade. Todos os aliados em raio de 4,5 metros encerram automaticamente uma condição mental ou sensorial, à sua escolha.
- Vontade dos Líderes: ao atingir uma criatura com um ataque, gaste um dado de Superioridade. Se estiver sob efeito/condição que exigiu um lance de defesa que falhou, refaça-o imediatamente, somando o dado ao resultado.
- Arbitragem de Líderes: como ação, gaste um dado de Superioridade visando criaturas à sua escolha em raio de 18 metros. Elas fazem lance de defesa de Sabedoria ou Inteligência contra sua CD de Ninjutsu/Genjutsu, ou tornam-se incapazes de mentir, enganar ou agir com hostilidade contra você/aliados, preferindo um meio-termo benéfico a ambos.` },
      ],
    },
    {
      key: "escoteiro-de-assalto",
      nome: "Escoteiro de Assalto",
      classeKey: "ninja-batedor",
      descricaoIntro: "Os Scout-Nin que optam por se tornar especialistas em Assalto concentram-se no desenvolvimento da força física bruta aprimorada até a perfeição mortal, combinando treinamento rigoroso com excelência física para desferir golpes devastadores.",
      features: [
        { nivel: 3, nome: "Assalto Superior", descricao: "A partir do 3º nível, você aprende manobras alimentadas por um Dado de Superioridade (d4). Aprende três manobras à escolha (catálogo abaixo), ganhando mais com o nível (Dados de Superioridade: 3 do 3º ao 6º nível, 4 do 7º ao 10º, 5 do 11º ao 14º, 6 do 15º ao 18º, 7 do 19º ao 20º; Manobras Conhecidas segue a mesma progressão). Só pode usar uma manobra por ataque. Ao tirar descanso longo, pode trocar uma manobra conhecida. Um dado é gasto quando usado; todos os gastos são recuperados ao terminar um descanso curto ou longo." },
        { nivel: 3, nome: "Ataque Brutal", descricao: "Também no 3º nível, sempre que acertar um ataque corpo a corpo ou à distância e causar dano, causa dano adicional igual ao resultado do seu dado de Superioridade." },
        { nivel: 3, nome: "Durabilidade Brutal", descricao: "Também no 3º nível, uma vez por descanso curto, ao fazer um lance de defesa, pode somar um dado de Superioridade ao resultado sem gastá-lo. Se usar novamente antes de um descanso curto, pode gastar um dado para ativá-la mais uma vez. Se esse bônus levar um lance de defesa contra a morte a 20 ou mais, ganha os benefícios de um 20 natural." },
        { nivel: 6, nome: "Potencial Inexplorado", descricao: "A partir do 6º nível, seu dado de Superioridade cresce um passo (d6), repetindo no 9º (d8), 14º (d10) e 17º (d12). Além disso, uma vez por turno, ao obter acerto crítico ou tirar 20 natural em um lance de defesa, recupera 1 dado de Superioridade." },
        { nivel: 9, nome: "Atleta Notável", descricao: "A partir do 9º nível, pode gastar um dado de Superioridade somando o resultado a qualquer verificação de Força, Destreza ou Constituição." },
        { nivel: 14, nome: "Crítico Devastador", descricao: "A partir do 14º nível, ao obter acerto crítico com ataque corpo a corpo, ganha bônus de dano igual ao seu nível de Scout-Nin; com ataque à distância, ganha bônus igual à metade do seu nível." },
        { nivel: 17, nome: "Sobrevivente", descricao: "A partir do 17º nível, no início de cada um dos seus turnos, se estiver com menos da metade dos PV (e não em 0), recupera PV iguais a 5 + seu modificador de Constituição." },
        { nivel: 20, nome: "Ataque Implacável", descricao: "A partir do 20º nível, ao declarar um ataque/jutsu contra um hostil, pode selecionar um efeito defensivo dele (PV temporários, resistência, imunidade ou redução de dano) e ignorá-lo ao causar dano. Deve decidir ao declarar o ataque e não pode alterar até o início do próximo turno." },
        { nivel: 3, nome: "Catálogo de Manobras de Assalto", descricao: `Lista de manobras disponíveis para o recurso Assalto Superior (3º nível).

- Força Amplificada: ao lançar um jutsu que exija lance de defesa, gaste até 3 dados de Superioridade, aumentando a CD em +1 por dado e somando o total à rolagem de dano. Se a(s) criatura(s) falhar(em) por 5 ou mais, recebem o dobro do dano e o dobro de graus da condição.
- Incapacitante Amplificado: ao atingir uma criatura, gaste um dado de Superioridade somando o dobro do resultado ao dano. Ela faz lance de defesa de Força (ou CD de Taijutsu) ou tem a velocidade reduzida à metade; pode gastar uma ação de Atletismo contra a mesma CD para recuperar a velocidade total.
- Crítico Amplificado: ao declarar um ataque, gaste até 3 dados de Superioridade, aumentando a margem de crítico em +1 por dado. Em um crítico, soma o dobro do número de dados gastos ao dano.
- Nocaute Amplificado: ao atingir uma criatura, gaste um dado de Superioridade somando o dobro do resultado ao dano; o alvo é empurrado 1,5 metro por ponto do dado e cai de bruços. Se colidir com superfície sólida, recebe o dobro de dano de queda a cada 3 metros que seria arremessado.
- Golpes Amplificados: ao atacar com arma/desarmado ou lançar jutsu de ataque, gaste um dado de Superioridade e selecione criaturas em raio de 1,5 metro do alvo original. Soma o dado à primeira rolagem de ataque; em acerto, o alvo original e os selecionados sofrem o mesmo dano (sem outros efeitos do jutsu).
- Ataque Ameaçador: gaste um dado de Superioridade; no próximo ataque, soma o dobro do resultado ao dano, e todas as criaturas em raio de 6 metros à sua escolha fazem lance de defesa de Sabedoria (ou CD de Taijutsu) ou ganham 1 grau de Medo. Causar dano a você encerra o medo da criatura.
- Precisão Ameaçadora: ao fazer uma rolagem de ataque, gaste um dado de Superioridade para somar o resultado (antes ou depois de rolar, mas antes dos efeitos). Em acerto, ganha metade do resultado original para o próximo ataque antes do fim do próximo turno; em um segundo acerto, ganha metade novamente para o ataque seguinte.
- Finta Ameaçadora: ao errar um ataque, gaste um dado de Superioridade; no próximo ataque contra a mesma criatura antes do fim do turno, soma o dobro do resultado ao dano. Em acerto, ganha os benefícios de Desvencilhar-se.
- Retaliação Ameaçadora: ao sofrer dano de um ataque dentro do alcance de um de seus ataques, gaste um dado de Superioridade e sua reação para atacar (desarmado, com arma, ou jutsu de rolagem única), somando o dobro do resultado do dado ao dano causado.` },
      ],
    },
    {
      key: "escoteiro-de-clonagem",
      nome: "Escoteiro de Clonagem",
      classeKey: "ninja-batedor",
      descricaoIntro: "Os Scout-Nin que optam por se tornar especialistas em clonagem empregam números superiores como seu principal método de combate. Aprimoram essa habilidade por meio do uso repetido de seus clones em diferentes situações, tornando-se mestres do combate duplicado — nem todo scout usa clones da mesma forma, o que fica evidente em suas táticas e habilidades disponíveis.",
      features: [
        { nivel: 3, nome: "Táticas de Clonagem", descricao: "A partir do 3º nível, você aprende manobras alimentadas por um Dado de Superioridade (d8). Aprende três manobras à escolha (catálogo abaixo), ganhando mais com o nível (Dados de Superioridade / Manobras Conhecidas: 3º-5º: 3/3; 6º-7º: 4/3; 8º: 4/4; 9º-11º: 5/4; 12º: 6/4; 13º-14º: 6/5; 15º-17º: 7/5; 18º-20º: 8/6). A maioria das manobras aprimora você ou seus clones; só pode usar uma por ataque. Ao tirar descanso longo, pode trocar uma manobra conhecida. Um dado é gasto quando usado; todos os gastos são recuperados ao terminar um descanso curto ou longo." },
        { nivel: 3, nome: "Tajū Kage Bunshin", descricao: "A partir do 3º nível, você adiciona a Técnica de Clone das Sombras à sua lista de jutsu conhecidos e pode aprender qualquer Ninjutsu com palavra-chave Clone, exceto os com palavra-chave Hijutsu. Ao invocar um Clone das Sombras, criaturas hostis não conseguem distingui-lo dos demais clones — você fica oculto até que façam a ação Procurar (com desvantagem) para discerni-lo. Aumenta em +1 o número máximo de clones invocáveis via Ninjutsu com palavra-chave Clone (e o jutsu que podem lançar); +2 no 9º nível, +3 no 14º. Esses clones duram 10 minutos, podem ficar a até 36 metros de você, podem ser comandados a se separar em até dois grupos, ganham suas proficiências de perícia e uma ação bônus para ações de habilidade ou a ação Ajudar (uma ação de habilidade por convocação, por clone)." },
        { nivel: 3, nome: "Técnica do Clone", descricao: "Também a partir do 3º nível, os clones invocados deixam de ter restrições de palavra-chave e podem lançar qualquer jutsu que você conheça como se fossem um Clone das Sombras. Pode gastar 1 dado de Superioridade ou de chakra para invocar um clone como se lançasse qualquer Ninjutsu que conheça e que invoque clones, sem gastar chakra, tratando-o como invocado no rank mais alto disponível. A partir do 6º nível, uma vez por turno, sempre que um clone invocado obtiver acerto crítico ou tirar 20 em ataque, verificação de habilidade ou lance de defesa, você recupera 1 dado de Superioridade." },
        { nivel: 6, nome: "Clones em Toda Parte", descricao: "No 6º nível, ao invocar clones via Ninjutsu com palavra-chave Clone, invoca 1 clone adicional sem custo (não funciona se o clone for convocado por Técnica do Clone). Quando um clone causar dano, aumenta o dado de dano em 1 passo (mais 1 passo adicional no 14º e no 17º). Quando dois ou mais Clones das Sombras seus lançarem um jutsu ou atacarem visando a mesma criatura, ganham +1d6 nas rolagens de dano para cada clone adicional que estiver auxiliando o principal." },
        { nivel: 9, nome: "Clones Superiores", descricao: "A partir do 9º nível, seus clones podem usar manobras que você conhece, gastando seu dado de Superioridade. A velocidade deles aumenta para igualar a sua em até 18 metros, ganham proficiência em seus lances de defesa e podem manter concentração no jutsu que lançam por +1 dos seus turnos. Clones cujo dano seria reduzido por serem clones reduzem a penalidade em 1 (2 no 17º nível). Além disso, ao aprender, modificar ou criar jutsu, seus clones ajudam a reduzir o custo do tempo de inatividade em valor igual ao rank do jutsu (D:1, C:2, B:3, A:4, S:5)." },
        { nivel: 14, nome: "Táticas de Clone", descricao: "A partir do 14º nível, ao receber dano de um ataque ou falhar em um lance de defesa de um jutsu que causa dano, como reação, pode gastar 1 dado de Superioridade, registrando o resultado: lança um Ninjutsu com palavra-chave Clone à sua escolha e invoca um número de clones igual ao resultado, ignorando o máximo normal. Alternativamente, quando um clone seu morrer, pode gastar a reação para usar Técnica do Clone, invocando um clone adicional do mesmo tipo (sem gastar dado de Superioridade). Só pode invocar clones por qualquer um desses métodos duas vezes por descanso; usos adicionais custam 1 dado de Superioridade ou de chakra." },
        { nivel: 17, nome: "Mestre dos Clones", descricao: "A partir do 17º nível, pode lançar a Técnica do Clone das Sombras como ação bônus, podendo comandar seus clones como parte da mesma ação." },
        { nivel: 20, nome: "Clones Supremos", descricao: "A partir do 20º nível, selecione uma manobra de clone. Seus clones podem realizá-la sem gastar um dado de Superioridade, uma vez por turno." },
        { nivel: 3, nome: "Catálogo de Manobras de Clonagem", descricao: `Lista de manobras disponíveis para o recurso Táticas de Clonagem (3º nível).

- Agilidade dos Clones: ao usar ação bônus para comandar um clone, gaste um dado de Superioridade para que um número de clones igual à metade do resultado façam um movimento adicional com velocidade dobrada até o fim do turno, sem provocar ataques de oportunidade.
- Clone Frenético: tendo um ou mais clones ativos, gaste um dado de Superioridade. Na próxima vez que ordenar seus clones a atacar, eles somam o resultado às rolagens de ataque e dano. Clones que normalmente causariam metade do dano passam a causar o dano total.
- Troca de Clones: quando você ou um aliado receberia dano, como reação, gaste um dado de Superioridade para que um clone em raio de 9 metros troque de lugar com você/o aliado, recebendo o dano e os efeitos associados.
- Combinação de Clones: ao usar um ataque corpo a corpo ou à distância, tendo pelo menos um clone ativo, gaste um dado de Superioridade para que os clones ataquem com você, dispensando qualquer número deles. Para cada clone dispensado, ganha +1 dado de Superioridade de dano, ou +1 na CD de defesa a cada dois clones dispensados.
- Defesa do Clone: quando um aliado for atingido por um ataque a até 4,5 metros de seu clone, como reação, gaste um dado de Superioridade para que você ou o clone interponha o ataque, recebendo o dano/efeito. O aliado protegido ganha bônus na CA ou em lances de defesa igual à metade do resultado do dado, até o início do seu próximo turno.
- Resistência do Clone: ao invocar pelo menos um clone, gaste um dado de Superioridade: um dos clones pode lançar um número de jutsu adicional igual à metade do resultado; se tiver chakra, ganha chakra igual ao dobro do resultado.
- Enxame de Clones: como ação bônus, gaste um dado de Superioridade para comandar seus clones a atacar um alvo em raio de 18 metros, enquanto um número de clones à sua escolha corre em direção a ele, terminando a até 4,5 metros. Role o dado gasto: na próxima rolagem de d20 do alvo, ele sofre penalidade igual ao resultado.
- Apoio dos Clones: como reação, ao fazer um lance de defesa de qualquer tipo, gaste um dado de Superioridade e dispense um clone ativo: ganha bônus no lance igual ao resultado do dado.
- Clone Preparado: quando você ou um clone receberia dano de um ataque, gaste sua reação: todos os clones ativos lançam um jutsu visando a criatura desencadeadora e depois são dispensados.
- Clone Durável: ao comandar seus clones a realizar qualquer ação, ou quando eles receberiam dano, gaste um dado de Superioridade: ganham PV temporários iguais a cinco vezes o resultado até o fim do turno.
- Clone de Elite: ao invocar mais de um clone via jutsu, gaste um dado de Superioridade como parte do lançamento: invoca apenas um clone, mas com os PV e chakra combinados de um número de clones igual ao dado gasto (e limitação de jutsu aumentada na mesma proporção); esse clone soma o dobro do dado gasto a todo dano que causar, uma vez por turno, pela sua existência. Só pode ter um clone criado assim ativo por vez.
- Técnica de Clonagem: selecione pelo menos um clone ativo; gaste um dado de Superioridade para que ele obtenha os benefícios de todas as suas características de classe e de clã até o fim do seu próximo turno.` },
      ],
    },
    {
      key: "escoteiro-de-barreira",
      nome: "Escoteiro de Barreira",
      classeKey: "ninja-batedor",
      descricaoIntro: "Os Escoteiros Ninja que optam por se tornar Escoteiros de Barreira (Defensive Scouts) treinam para fortalecer as pessoas ao seu redor. Eles podem inspirar seus aliados com vigor renovado, elevando-os a novos patamares e, ao mesmo tempo, protegê-los de danos.",
      features: [
        { nivel: 3, nome: "Defesa Superior", descricao: "A partir do 3º nível, você aprende manobras alimentadas por um Dado de Superioridade (d8). Aprende três manobras à escolha (catálogo abaixo), ganhando mais com o nível (Dados de Superioridade / Manobras Conhecidas: 3º-5º: 3/3; 6º-7º: 3/4; 8º: 4/4; 9º-11º: 4/5; 12º: 4/6; 13º-14º: 5/6; 15º-17º: 5/7; 18º-20º: 6/8). Muitas manobras melhoram seus aliados. Só pode usar uma manobra por ataque ou por aliado, por turno. Ao tirar descanso longo, pode trocar uma manobra conhecida. Um dado é gasto quando usado; todos os gastos são recuperados ao terminar um descanso curto ou longo." },
        { nivel: 3, nome: "Barreira de Chakra", descricao: "Além disso, no 3º nível, você aprende a manifestar uma Barreira de Chakra. Sempre que completa um descanso curto ou longo, cria uma Barreira para si ou para um aliado que complete o descanso com você; ela permanece presa ao alvo até você completar outro descanso. Tem PV iguais ao dobro do seu nível de personagem, tratados como PV temporários que não podem ser ignorados, removidos ou dissipados por efeitos hostis (exceto dano).\n\nQuando a criatura beneficiada recebe dano, a barreira o intercepta; se isso a reduzir a 0, a criatura recebe o dano restante e a barreira não absorve mais dano até se recuperar: ao ganhar PV temporários, a barreira recupera PV iguais à quantidade (se já no máximo, você ganha os PVT normalmente); ao ganhar Redução de Dano de um jutsu, recupera PV iguais ao dobro da RD; ao ganhar bônus de CA, recupera PV iguais a três vezes o bônus.\n\nEnquanto sua barreira tiver PV, você ganha +1d4 em verificações para manter concentração em jutsu. A partir do 6º nível, uma vez por turno, ao reduzir para metade ou menos o dano que você ou um aliado sofreria por uma característica de classe ou jutsu, recupera 1 dado de Superioridade." },
        { nivel: 3, nome: "Barreira Projetada", descricao: "A partir do 3º nível, você sabe manipular sua barreira de duas formas, usáveis um número de vezes igual ao seu bônus de proficiência por descanso longo (usos extras custam 1 dado de Superioridade ou de chakra):\n\nEsfera de Chakra: como reação, expande a Barreira em raio de 3 metros centrado em você até o início do seu próximo turno; aliados à sua escolha dentro dela reduzem em um dado de dano o dano que sofreriam (dois no 9º nível, três no 17º).\n\nExplosão de Repelência: como ação, expande a barreira instantaneamente, criando uma explosão em raio de 3 metros centrado em você; cada criatura à sua escolha no alcance faz lance de defesa de Força ou Destreza (escolha) contra sua CD de Ninjutsu; falha: Xd6 de dano de força (X = bônus de proficiência), empurrada 3 metros e cai de bruços; sucesso: metade do dano, sem outro efeito." },
        { nivel: 6, nome: "Escudo Resistente", descricao: "A partir do 6º nível, você converte passivamente seu chakra em pontos de vida de suas barreiras com mais eficiência. No início de cada um dos seus turnos em combate, enquanto tiver sua Barreira de Chakra, ela recupera PV iguais ao seu bônus de proficiência." },
        { nivel: 9, nome: "Barreira de Mobilização", descricao: "A partir do 9º nível, você aprende a reforçar seus aliados para que continuem lutando apesar dos ferimentos. Como ação bônus, selecione até 3 aliados em raio de 9 metros (excluindo você): ganham PV temporários iguais ao resultado do seu Dado de Superioridade + seu nível de personagem, por 10 minutos (acumulável com outras fontes de PVT). Duas vezes por descanso." },
        { nivel: 14, nome: "Barreira Dominada", descricao: "A partir do 14º nível, você domina a habilidade de dobrar, manipular e reforçar sua Barreira de Chakra, ganhando uma variação de Barreira Projetada chamada Guarda Pesada: gastando 1 Dado de Chakra, coloca sua barreira sobre um número de aliados em raio de 9 metros igual ao seu bônus de proficiência; as criaturas cobertas ganham resistência a todo dano até o fim do turno." },
        { nivel: 17, nome: "Blindagem Adaptativa", descricao: "No 17º nível, quando sua Barreira de Chakra recebe dano, pode fazer com que ela ganhe resistência a danos subsequentes desse tipo até o início do seu próximo turno (sem ação necessária). Se receber dano de mais de um tipo simultaneamente, escolhe a qual ganha resistência. Sua barreira só pode ter resistência a um tipo por vez." },
        { nivel: 20, nome: "Blindagem Superior", descricao: "A partir do 20º nível, você aprende a aplicar sua Barreira de Chakra a todos os aliados. Como ação, selecione até 3 criaturas visíveis e aliadas em raio de 18 metros: cada uma ganha uma Barreira de Chakra com PV iguais ao seu nível de Scout-Nin. Cada uma tem sua própria barreira, mas pode usar Barreira Projetada (cada habilidade utilizável uma vez por descanso). A barreira dos aliados não pode ser reabastecida como a sua; ao chegar a 0 PV, é perdida até você fornecê-la novamente. Duas vezes por descanso longo." },
        { nivel: 3, nome: "Catálogo de Manobras de Barreira", descricao: `Lista de manobras disponíveis para o recurso Defesa Superior (3º nível).

- Aprimoramento Defensivo: gaste um dado de Superioridade para aumentar as defesas de um aliado visível (que não seja você), registrando o resultado. Ele ganha bônus no próximo lance de defesa igual à metade do resultado; em falha, ganha PV temporários iguais a três vezes o resultado.
- Aumento da Defesa: ao lançar um jutsu que concederia PV temporários só a você, gaste um dado de Superioridade para que todos os aliados em raio de 3 metros ganhem o benefício do jutsu até o fim do turno, independentemente da duração original. Ao rolar os PVT, adicione o dobro do resultado do dado.
- Incitamento Defensivo: ao causar dano a uma criatura, gaste um dado de Superioridade para persuadi-la a atacá-lo, somando o dado à rolagem de dano; o alvo fica em desvantagem em ataques contra qualquer um que não seja você até o fim do seu próximo turno.
- Segurança Defensiva: gaste um dado de Superioridade e chame uma criatura em raio de 18 metros que possa vê-lo/ouvi-lo, que faça lance de defesa de Destreza ou Inteligência: ela soma metade do valor rolado à sua defesa. Se ela tiver sucesso, você ganha +1d4 no seu próximo lance de defesa de Destreza ou Inteligência no minuto seguinte.
- Recuperação Defensiva: como ação bônus, selecione um aliado em raio de 9 metros que tenha sofrido dano nesta iniciativa; gaste um dado de Superioridade para inspirá-lo — ele pode opcionalmente gastar um de seus próprios Dados de Vida. Recupera PV iguais ao dobro do seu dado de Superioridade mais o dado de acerto gasto, se houver.
- Repreensão Defensiva: ao lançar um jutsu que concederia Redução de Dano só a você, gaste um dado de Superioridade para que todos os aliados em raio de 3 metros ganhem o benefício até o fim do turno. Ao rolar a RD, some seu dado de Superioridade ao resultado.
- Regressão Defensiva: quando uma criatura em raio de 18 metros sofrer um acerto crítico, gaste 1 dado de Superioridade, registrando o resultado, e reduza o número de dados de dano que o alvo rola de acordo com o resultado (se reduzir a 0 dados, o dano é reduzido a 0).
- Guarda da Vingança: ao lançar um jutsu que lhe conceda redução de dano ou PVT, gaste um dado de Superioridade: a primeira instância de dano com a qual essa redução/PVT interagiria no turno é ecoada, afetando todos os hostis em raio de 3 metros, que fazem lance de defesa de Destreza contra a CD original (ou CD de Taijutsu, se arma/desarmado); falha: recebem o mesmo dano + duas vezes o resultado do dado; sucesso: metade do dano.
- Guarda da Equipe: a menos de 3 metros de um aliado, gaste um dado de Superioridade: todos os aliados no alcance (incluindo você) ganham +2 de CA e em todos os lances de defesa até o fim do seu próximo turno, enquanto permanecerem a até 3 metros de você. Se qualquer um receber dano, você reduz o dano sofrido pelo resultado do dado.
- Escudo em Camadas: ao receber dano enquanto sua Barreira de Chakra tiver 0 PV, gaste qualquer número de dados de Superioridade: ela ganha PV iguais a 5 vezes o resultado, até o fim do turno, a partir de 0.` },
      ],
    },
    {
      key: "batedor-elemental",
      nome: "Batedor Elemental",
      classeKey: "ninja-batedor",
      descricaoIntro: "Os Scout-Nin que escolhem se tornar Elementalistas aprendem a manejar uma Liberação da Natureza e a mantê-la fluindo constantemente em suas bobinas de chakra, logo abaixo da superfície, tornando seu elemento mais forte e a si próprios mais resistentes contra ele.",
      features: [
        { nivel: 3, nome: "Elementos Superiores", descricao: "A partir do 3º nível, você aprende manobras alimentadas por um Dado de Superioridade (d6). Aprende três manobras à escolha (catálogo abaixo), ganhando mais com o nível (Dados de Superioridade / Manobras Conhecidas: 3º-5º: 3/3; 6º-7º: 3/4; 8º: 4/4; 9º-11º: 4/5; 12º: 4/6; 13º-14º: 5/6; 15º-17º: 5/7; 18º-20º: 6/8). Só pode usar uma manobra por ataque. Ao tirar descanso longo, pode trocar uma manobra conhecida. Um dado é gasto quando usado; todos os gastos são recuperados ao terminar um descanso curto ou longo." },
        { nivel: 3, nome: "Conhecimento Elemental", descricao: "A partir do 3º nível, você concentrou esforços em aproveitar sua Liberação de Natureza inata. Selecione uma Liberação (Terra, Vento, Fogo, Água ou Relâmpago); ganha a habilidade de lançar jutsu com essa palavra-chave (se já pudesse, aprende um jutsu adicional dela). Além disso, quando você ou um aliado em raio de 9 metros lançaria um Ninjutsu sem a palavra-chave da natureza escolhida, pode gastar um dado de Superioridade para dar a ele essa palavra-chave e somar o dado gasto ao dano. A partir do 6º nível, uma vez por turno, ao obter acerto crítico com ataque baseado em jutsu ou quando um hostil falhar por 5+ em defesa contra um jutsu seu, recupera 1 dado de Superioridade." },
        { nivel: 3, nome: "Ataque Elemental", descricao: "Além disso, no 3º nível, ao lançar um jutsu com sua natureza escolhida, pode reter parte dessa energia: pelo minuto seguinte, seus ataques desarmados/com arma causam +1d6 do tipo de dano da natureza escolhida. A partir do 9º nível, ao obter acerto crítico ou quando um hostil falhar por 5+ contra um Ninjutsu lançado com essa natureza enquanto aumentado, inflige um grau da condição associada (Catálogo de Condições Elementais)." },
        { nivel: 6, nome: "Resistência Elemental", descricao: "A partir do 6º nível, você ganha resistência ao dano da sua Liberação de Natureza escolhida. Quando você ou um aliado em raio de 6 metros faz um lance de defesa contra um jutsu com a palavra-chave dessa liberação, soma metade do seu modificador de Inteligência ao resultado." },
        { nivel: 9, nome: "Poder Elemental", descricao: "A partir do 9º nível, ao causar dano com um jutsu (sem a palavra-chave Combinação) da sua natureza escolhida, pode gastar 2 dados de Superioridade para que o jutsu cause dano máximo (não pode obter acerto crítico dessa forma). Se exigir rolagem de ataque, apenas a primeira que acertar ganha o efeito." },
        { nivel: 14, nome: "Ataque Primordial", descricao: "A partir do 14º nível, o chakra elemental residual de seu jutsu se fortaleceu: ao se beneficiar de Ataque Elemental, causa +2d6 de dano adicional. Além disso, o dano da sua natureza escolhida ignora resistência e trata imunidade como resistência." },
        { nivel: 17, nome: "Superioridade Elemental", descricao: "A partir do 17º nível, seu corpo produz constantemente chakra da natureza escolhida. Ao usar uma manobra, pode tratar o resultado como o dobro do valor rolado. Além disso, pode gastar um dado de Superioridade no seu turno para ganhar imunidade ao dano da sua natureza e resistência à natureza associada até o início do próximo turno: Terra → imune a Terra, resistente a Raio; Vento → imune a Vento, resistente a Fogo; Fogo → imune a Fogo, resistente a Frio/Água; Água → imune a Frio/Água, resistente a Terra; Relâmpago → imune a Raio, resistente a Vento." },
        { nivel: 20, nome: "Tempestade Primordial", descricao: "A partir do 20º nível, ao causar dano a uma criatura com um jutsu da natureza escolhida ou ataque com arma, gastando um dado de Superioridade ou usando uma manobra como parte do ataque/lançamento, causa dano adicional igual a três vezes o resultado do dado." },
        { nivel: 3, nome: "Catálogo de Manobras Elementais", descricao: `Lista de manobras disponíveis para o recurso Elementos Superiores (3º nível), e tabela de Condições Elementais referenciada por Ataque Elemental (9º nível).

- Perturbação Elemental: ao atingir uma criatura com ataque de arma ou jutsu, gaste um dado de Superioridade: até o início do seu próximo turno, o próximo jutsu que ela lançar tem o custo aumentado em valor igual ao dobro do resultado.
- Ser Elemental: como reação a ser alvo de um ataque, transforme-se em seu elemento; gaste um dado de Superioridade para aumentar sua CA em metade do resultado até o fim do turno. Se a criatura estiver a menos de 1,5 metro e o ataque falhar, ela recebe dano igual a três vezes o resultado, do tipo do elemento escolhido.
- Doença Elemental: ao lançar um jutsu de liberação de natureza que causa dano, gaste um dado de Superioridade e some-o ao dano (ou metade à CD); se o jutsu infligir condição, soma um grau extra; se não infligir, as criaturas atingidas fazem resistência de Constituição ou recebem uma Condição Elemental até o fim do próximo turno delas.
- Jutsu Intensificado: ao lançar um jutsu com a palavra-chave da natureza escolhida, gaste um dado de Superioridade e some o triplo do resultado ao dano.
- Jutsu Natural: ao lançar Genjutsu, Taijutsu ou Bukijutsu, gaste um dado de Superioridade e some-o ao dano, ou aumente a CD em +1; o jutsu ganha a palavra-chave da natureza escolhida e seu dano passa a ser dessa natureza.
- Ataque Mágico Elemental: como ação bônus, selecione um Ninjutsu de rolagem de ataque, tempo de lançamento de 1 ação/ação bônus, alvo único e da natureza escolhida; gastando 1 dado de Superioridade e o custo do jutsu, infunda-o em sua arma/golpes. No primeiro acerto com arma/desarmado antes do fim do próximo turno, causa dano da arma + dano do jutsu + dado de Superioridade. Se o jutsu exigir defesa, o alvo recebe metade do dano de imediato e faz o lance; falha: metade restante + efeitos; sucesso: sem dano adicional.
- Recuperação Primordial: gaste um dado de Superioridade para recuperar chakra igual ao resultado + modificador de Constituição, recuperando também a capacidade de moldar chakra se perdida. Máximo duas vezes por rolagem de iniciativa.
- Poder Primordial: gaste um dado de Superioridade para somar cinco vezes o resultado ao dano do próximo ataque, reduzindo sua rolagem de ataque pelo mesmo resultado.
- Aprimoramento Primordial: ao lançar um jutsu que reduz dano ou concede PVT a si mesmo com a palavra-chave da natureza escolhida, gaste um dado de Superioridade: aumenta o dado usado em um passo e soma o dobro do resultado do dado de Superioridade ao total.
- Bully Primal: quando uma criatura seria afligida por uma condição de um jutsu seu, gaste um dado de Superioridade para infligir, em vez disso, a condição da sua natureza (tabela abaixo).

Catálogo de Condições Elementais: Liberação de Fogo → 1 grau de Queimado; Liberação de Água → 1 grau de Resfriado; Liberação de Vento → 1 grau de Sangramento; Liberação de Terra → 1 grau de Contusão; Liberação de Relâmpago → 1 grau de Choque.` },
      ],
    },
    {
      key: "escoteiro-desbravador",
      nome: "Escoteiro Desbravador",
      classeKey: "ninja-batedor",
      descricaoIntro: "Os Scout-Nin que optam por se tornar Escoteiros Desbravadores usam velocidade extrema para quase se teletransportar pelo campo de batalha. Eles usam sua velocidade extrema para proteger seus aliados e manobrá-los de forma mais eficaz durante a batalha.",
      features: [
        { nivel: 3, nome: "Movimento Superior", descricao: "A partir do 3º nível, você aprende manobras alimentadas por um Dado de Superioridade (d6). Aprende três manobras à escolha (catálogo abaixo), ganhando mais com o nível (Dados de Superioridade / Manobras Conhecidas: 3º-6º: 3/3; 7º-10º: 4/4; 11º-14º: 5/5; 15º-18º: 6/6; 19º-20º: 7/7). Só pode usar uma manobra por ataque. Ao tirar descanso longo, pode trocar uma manobra conhecida. Um dado é gasto quando usado; todos os gastos são recuperados ao terminar um descanso curto ou longo." },
        { nivel: 3, nome: "Salvador Móvel", descricao: "A partir do 3º nível, você aprende o Ninjutsu Movimento do Chakra (não conta no limite de jutsu conhecido); seu tempo de lançamento passa a ser Especial (quando você se moveria pelo menos 3 metros). Também escolhe entre Liberação de Vento: Zephyr Strike, Liberação de Relâmpago: Velocidade do Relâmpago, Gato Gracioso ou Fuga das Pétalas de Flores — aprendendo o jutsu selecionado (também fora do limite conhecido), lançável gastando 1 dado de Superioridade em vez de chakra (se exigir concentração, mantida sem custo adicional). Aprende outro jutsu dessa lista no 6º, 9º e 14º nível, todos lançáveis com um dado de Superioridade." },
        { nivel: 3, nome: "Explosão de Velocidade", descricao: "Além disso, no 3º nível, você pode se lançar como ação bônus. Alternativamente, uma vez por turno, pode gastar metade do movimento para se teletransportar, rolando o dado de Superioridade: teletransporta-se um número de metros igual a 3x o resultado. Esse movimento conta como jutsu de teletransporte/aumento de velocidade. Ao lançar tal jutsu, ganha aumento na rolagem de dano do próximo ataque igual a 2d6 (4d6 no 9º nível, 6d6 no 17º). Além disso, ignora restrições de liberação de natureza/habilidade ao aprender ou usar Ninjutsu, Genjutsu ou Taijutsu de teletransporte/bônus de velocidade. A partir do 6º nível, uma vez por turno, ao rolar 1 ou 6 no dado de Superioridade, ele não é gasto." },
        { nivel: 6, nome: "Passageiro Adicional", descricao: "A partir do 6º nível, ao se mover por um jutsu de teletransporte ou sob efeito de aumento de velocidade, uma criatura disposta do seu tamanho ou menor que possa tocá-lo também pode se mover da mesma forma, ganhando o benefício de Explosão de Velocidade (uma vez por turno, para criaturas que não sejam você)." },
        { nivel: 9, nome: "Velocidade Superior", descricao: "A partir do 9º nível, pode se concentrar em até 3 jutsu que permitam teletransporte ou concedam bônus de velocidade de movimento. Além disso, o jutsu lançado com esses efeitos tem o custo reduzido em valor igual ao rank (D:-1, C:-2, B:-3, A:-4, S:-5)." },
        { nivel: 14, nome: "Defesa Transversal", descricao: "A partir do 14º nível, ao sofrer dano de um ataque ou jutsu, pode usar a reação para se tornar resistente ao dano desse ataque/jutsu nesse turno." },
        { nivel: 17, nome: "Transposição Natural", descricao: "A partir do 17º nível, como ação bônus, pode se teletransportar até 13,5 metros para um espaço desocupado visível. Pode usar as manobras Choque Elétrico e Passo Blitz para modificar esta característica." },
        { nivel: 20, nome: "Transposição Superior", descricao: "A partir do 20º nível, selecione um espaço visível em raio de 36 metros; como ação livre, manifesta uma esfera de 9 metros de raio centrada nesse ponto, sob seu controle (você e criaturas/objetos soltos dentro dela). Como ação, ação bônus ou reação, gastando um dado de Superioridade, selecione uma criatura ou objeto visível e tente movê-lo para outro espaço no raio; faz lance de defesa de Carisma contra sua CD de Ninjutsu (ou Genjutsu); falha: é movido ao ponto escolhido, sem poder usar reações a esse movimento forçado." },
        { nivel: 3, nome: "Catálogo de Manobras do Desbravador", descricao: `Lista de manobras disponíveis para o recurso Movimento Superior (3º nível).

- Ataque Rápido: sob efeito de jutsu que aumente velocidade, ou tendo se teletransportado imediatamente antes de atacar, gaste um dado de Superioridade na ação de Ataque para fazer um número de ataques adicionais igual ao resultado, sem somar modificador de habilidade ou bônus de dano além do dado de arma/desarmado não modificado.
- Passo Blitz: ao lançar ou usar um jutsu de teletransporte/aumento de velocidade, gaste um dado de Superioridade para aumentar a distância do teleporte ou o bônus de velocidade em metros iguais a 1,5x o resultado, até o fim do turno.
- Choque Elétrico: imediatamente após lançar/usar um jutsu de teletransporte, gaste um dado de Superioridade: cada criatura em raio de 1,5 metro recebe dano de Força igual a três vezes o resultado.
- Guarda Blitz: sob efeito de jutsu que aumenta velocidade, ao receber dano, gaste um dado de Superioridade e uma reação: reduz sua velocidade atual pela metade até o fim do próximo turno e reduz o dano em 5 para cada 3 metros de velocidade reduzida, até o máximo de 10 vezes o resultado do dado.
- Recuperação Rápida: sob efeito de condição/jutsu/característica que reduza velocidade ou impeça reações, gaste um dado de Superioridade para um lance de defesa/verificação adicional contra a CD original, somando o resultado do dado (sem CD definida, usa 10 + rank: D:5, C:7, B:9, A:11, S:13).
- Porta do Interruptor: ao lançar um jutsu que só a você teletransporte ou dê bônus de velocidade, gaste um dado de Superioridade e alveje um aliado em raio de 3 metros: se for teletransporte, o aliado se teletransporta no seu lugar e pode somar o dado à próxima rolagem de ataque antes do fim do seu próximo turno; se for bônus de velocidade, o aliado recebe o efeito em seu lugar pela duração listada (se exigir concentração, decide-se quem a mantém, decisão final).
- Pontos de Troca: ao lançar ou usar um jutsu que lhe permite se teletransportar, gaste um dado de Superioridade e escolha uma criatura dentro do alcance do teleporte. Você troca de lugar com ela; se for um aliado disposto, soma o resultado do dado à CA dele contra o próximo ataque que o tiver como alvo. Se não estiver disposta, ela deve ser bem-sucedida em um lance de defesa de Carisma contra sua CD de Ninjutsu (ou Taijutsu); em falha, troca de lugar com você; uma criatura relutante tem a CA reduzida em valor igual à metade do resultado do dado.
- Troca de Blitz: como reação, quando um aliado em raio de 18 metros for alvo de um ataque ou forçado a um lance de defesa, gaste um dado de Superioridade para trocar de lugar com ele, tornando-se o novo alvo do ataque ou do lance de defesa. Soma metade do resultado do dado como bônus à CA e aos lances de defesa de você e dos aliados contra o efeito desencadeante, até o fim do turno.` },
      ],
    },
    {
      key: "escoteiro-fantasma",
      nome: "Escoteiro Fantasma",
      classeKey: "ninja-batedor",
      descricaoIntro: "O Scout-Nin que escolhe se tornar um Phantom torna-se um fantasma que desaparece e some de vista, agindo como um espectro praticamente impossível de ser tocado ou encontrado. Mestre da furtividade e especialista em assassinatos, usa seu Ninjutsu e Genjutsu fantasmagóricos para executar seus objetivos com pouca ou nenhuma oposição.",
      features: [
        { nivel: 3, nome: "Fantasma Superior", descricao: "A partir do 3º nível, você aprende manobras alimentadas por um Dado de Superioridade (d6). Aprende três manobras à escolha (catálogo do recurso não capturado na fonte extraída — ver nota abaixo), ganhando mais com o nível (Dados de Superioridade / Manobras Conhecidas: 3º-5º: 3/3; 6º-7º: 3/4; 8º: 4/4; 9º-11º: 4/5; 12º: 4/6; 13º-14º: 5/6; 15º-17º: 5/7; 18º-20º: 6/8). Muitas manobras aprimoram um ataque. Só pode usar uma manobra por ataque. Ao tirar descanso longo, pode trocar uma manobra conhecida. Um dado é gasto quando usado; todos os gastos são recuperados ao terminar um descanso curto ou longo.\n\nAs Manobras Fantasmagóricas referenciadas aqui não tiveram seu texto completo localizado na fonte extraída — apenas os nomes: Golpe Medonho, Visagem Horripilante, Lamento Medonho, Evasão Fantasma, Garra Fantasma, Arrebatamento de Sombras, Assombração Fantasma, Drenagem da Sombra, Movimento Fantasma." },
        { nivel: 3, nome: "Conhecimento do Fantasma", descricao: "A partir do 3º nível, você começa a se familiarizar com seu jutsu horripilante e como ele interage com o mundo ao seu redor. Ganha proficiência em Ilusões, Percepção e Furtividade, caso ainda não tenha. Ao fazer uma verificação de Furtividade, pode usar Sabedoria em vez de Destreza. Além disso, ao fazer uma verificação de Furtividade usando Destreza ou Sabedoria, pode gastar um dado de Superioridade, somando-o ao resultado." },
        { nivel: 3, nome: "Poder do Fantasma", descricao: "Também no 3º nível, você aprende a comprimir seu chakra fantasmagórico em rajadas de poder medonho — seu Poder Fantasmático, representado como 1d8 (aumenta para 2d8 no 6º, 3d8 no 9º, 4d8 no 14º, 5d8 no 17º, 6d8 no 20º). Quando uma característica subsequente exigir seu Poder Fantasmático, role o dado correspondente, além de quaisquer outros efeitos; só pode usá-lo uma vez por turno. Você começa podendo usá-lo para aumentar a força de seus golpes: uma vez por turno, ao atingir uma criatura com um ataque em que tenha vantagem, causa dano necrótico adicional igual ao seu Poder Fantasmático. A partir do 6º nível, uma vez por rodada, ao rolar seu Poder Fantasmático, se 2 ou mais dados tiverem o mesmo número, recupera 1 dado de Superioridade." },
        { nivel: 6, nome: "Domínio do Fantasma", descricao: "A partir do 6º nível, você aprende a tornar partes do corpo e armas etéreas para cortar as manifestações metafísicas de outra pessoa. Ao causar dano com um ataque, pode gastar 1 dado de Superioridade para atravessar a essência espiritual da criatura, forçando um lance de defesa de Sabedoria contra sua CD de Taijutsu (ou Genjutsu, à escolha). Em falha, o alvo sofre um dos efeitos: (1) dano psíquico igual à metade do seu Poder Fantasmático e 2 graus de Concussão; (2) dano necrótico igual ao seu Poder Fantasmático e 1 grau de Medo até o fim do próximo turno; (3) dano de chakra igual ao dobro do seu Poder Fantasmático e fica incapaz de moldar chakra até o fim do próximo turno." },
        { nivel: 9, nome: "Caminhada Fantasma", descricao: "A partir do 9º nível, você aprendeu a tornar todo o corpo etéreo, capaz de atravessar matéria sólida, como um fantasma. Como ação bônus, assume forma espectral: velocidade de voo igual à metade da de movimento, pode pairar, e rolagens de ataque contra você têm desvantagem. Pode se mover através de criaturas, objetos e paredes como terreno difícil, recebendo 1d10 de dano de força se terminar o turno dentro de uma criatura/objeto (não vale para superfícies reforçadas com chakra ou criadas por jutsu). Pode permanecer na forma por 10 minutos ou encerrar como ação bônus; depois de usada, só novamente após um descanso longo, a menos que gaste um dado de Superioridade para reusar." },
        { nivel: 14, nome: "Sanguessuga Horripilante", descricao: "A partir do 14º nível, ao usar seu Poder Fantasmático, pode selecionar um dos dados rolados, recuperando PV ou chakra iguais à rolagem. Usável um número de vezes igual ao seu bônus de proficiência, por descanso longo." },
        { nivel: 17, nome: "Estalo Etéreo", descricao: "A partir do 17º nível, você ganha um uso adicional do Poder Fantasmático: Estalo Etéreo. Enquanto se beneficia de Caminhada Fantasma, ao acertar um ataque corpo a corpo, pode alcançar o corpo do inimigo e passar de incorpóreo para corpóreo forçosamente. A criatura faz lance de defesa de Carisma contra sua CD de Taijutsu (ou Genjutsu); em falha, recebe chakra e dano necrótico iguais ao dobro do seu Poder Fantasmático e ganha 3 graus de Concussão. Duas vezes por descanso longo (uma criatura que resista não gasta um uso)." },
        { nivel: 20, nome: "Poltergeist", descricao: "A partir do 20º nível, você se torna uma figura sinistra de terror completo: (1) pode usar seu Poder Fantasmático duas vezes por turno; (2) pode usar Caminhada Fantasma duas vezes por descanso curto; (3) Sanguessuga Horripilante agora permite selecionar 3 dados em vez de 1." },
      ],
    },
    {
      key: "escoteiro-tatico",
      nome: "Escoteiro Tático",
      classeKey: "ninja-batedor",
      descricaoIntro: "Os Scout-Nin que optam por se tornar Especialistas Táticos empregam técnicas marciais passadas por gerações. Para um especialista tático, o combate é um campo acadêmico, às vezes incluindo assuntos além da batalha, como armeiro ou confecção de armaduras. Nem todo batedor absorve as lições de história, teoria e arte que se refletem na especialidade tática, mas aqueles que o fazem são lutadores bem preparados, com grande habilidade e conhecimento.",
      features: [
        { nivel: 3, nome: "Táticas Superiores", descricao: "A partir do 3º nível, você aprende manobras alimentadas por um Dado de Superioridade (d10). Aprende três manobras à escolha (catálogo do recurso não capturado na fonte extraída — ver nota abaixo), ganhando mais com o nível (Dados de Superioridade / Manobras Conhecidas: 3º-5º: 3/3; 6º-8º: 4/4; 9º-11º: 5/5; 12º-13º: 6/6; 14º-15º: 7/7; 16º-17º: 8/8; 18º-19º: 9/9; 20º: 10/10). Pode usar até duas manobras por ataque. Ao tirar descanso curto, pode trocar qualquer manobra conhecida. O lance de defesa de cada manobra está listado nela mesma.\n\nAs Manobras Táticas referenciadas aqui não tiveram seu texto completo localizado na fonte extraída — apenas os nomes: Investida Superior, Riposta Superior, Altura Superior, Supressão Superior, Manobras de Superioridade, Avanço Tático, Precisão Superior, Fuga Tática, Substituição Tática, Aparo Tático, Ataque Tático, Técnica Tática." },
        { nivel: 3, nome: "Mestre de Táticas", descricao: "A partir do 3º nível, diferentemente de outros shinobi, sua capacidade de controlar um combate vem do seu controle magistral do campo de batalha e da perspicácia tática. Pode se beneficiar de até duas manobras por ataque ou lançamento de jutsu. Além disso, uma vez por turno, pode gastar um dado de Superioridade para conceder a si mesmo ou a um aliado em raio de 9 metros um bônus para a próxima rolagem de d20 igual ao resultado (uma criatura só pode se beneficiar uma vez por descanso longo). A partir do 6º nível, sempre que rolar um 20 natural em uma verificação de habilidade, de perícia ou lance de defesa, recupera 1 dado de Superioridade." },
        { nivel: 3, nome: "Manobra de Assinatura", descricao: "Também no 3º nível, você aprendeu a utilizar suas manobras muito melhor que outros shinobi. Selecione uma manobra conhecida com a palavra-chave Tático. Não gasta mais o Dado de Superioridade nela; em vez disso, ao usá-la, role um d4, podendo usá-la uma vez por turno. Pode selecionar uma segunda manobra a partir do 9º nível. Pode trocar todas as Manobras de Assinatura selecionadas ao completar um descanso." },
        { nivel: 6, nome: "Superioridade Tática", descricao: "A partir do 6º nível, você se dedicou a se tornar o shinobi mais bem preparado em uma sala cheia de shinobi que alguns considerariam superiores até mesmo a você. Selecione uma manobra de uma das subclasses de Batedor (Árbitro, Assalto, Clonagem, Barreira, Desbravador, Fantasma), aprendendo-a sem contar no limite (se tiver a palavra-chave Especializado, não pode usá-la nem obter seus benefícios). Pode selecionar mais uma manobra dessas subclasses no 14º e no 20º nível." },
        { nivel: 9, nome: "Especialista em Tudo, Especialista em Nada", descricao: "A partir do 9º nível, pode se beneficiar de duas Generalizações à sua escolha de uma vez com a característica de classe Jack de Todos os Ofícios, Mestre de Nenhum." },
        { nivel: 14, nome: "Técnica de Assinatura Dominada", descricao: "No 14º nível, pode ganhar o benefício de uma característica adicional concedida por Técnica de Assinatura." },
        { nivel: 17, nome: "Jutsu de Assinatura Dominado", descricao: "No 17º nível, pode escolher o benefício final concedido por Jutsu de Assinatura." },
        { nivel: 20, nome: "Táticas Inigualáveis", descricao: "No 20º nível, pode se beneficiar de qualquer número de manobras por ataque. Além disso, pode se beneficiar de uma Generalização adicional concedida por Jack de Todos os Ofícios, Mestre de Nenhum." },
      ],
    },
    {
      key: "batedor-trapaceiro",
      nome: "Batedor Trapaceiro",
      classeKey: "ninja-batedor",
      descricaoIntro: "O Scout-Nin que escolhe se tornar um Trickster tornou-se fiel a si mesmo e àqueles que o cercam. Ao aceitar quem realmente são, adquiriram a capacidade de manifestar a melhor versão de si mesmos, embora de forma mais romantizada, usando esse poder para ajudá-los na vida, tanto dentro quanto fora de combate.",
      features: [
        { nivel: 3, nome: "Despertar da Alma Vazia", descricao: "A partir do 3º nível, você aprende uma técnica especial de Fuinjutsu para criar um construto de chakra conhecido como Alma Vazia (Void Soul), manifestação de seu verdadeiro eu, que pode ser invocada como apoio dentro e fora de combate. Pode nomeá-la; ela sempre obedece ao seu comando. É convocada como ação bônus, ocupando seu espaço ao lado; é visível para criaturas que moldam chakra. Enquanto convocada, pode calcular sua CA usando Carisma no lugar de Destreza. Você a comanda gastando suas Ações, Ações Bônus e Reações.\n\nRegras da Alma Vazia: tem um número de jutsu conhecido igual ao seu bônus de proficiência, só acessando jutsu para os quais você se qualificaria (mais uma palavra-chave de liberação de natureza ou Médica à qual você não tem acesso); pode trocar o jutsu conhecido ao ganhar nível; usa os próprios escores de habilidade para se qualificar; esses jutsu somam-se à sua lista de conhecidos, mas só a Alma Vazia pode lançá-los; velocidade igual à sua (se você terminar o turno a mais de 36 metros dela, ela é reinvocada em seu espaço); usa seu chakra ao lançar jutsu; usa suas proficiências de lance de defesa; se você e ela fizerem lance de defesa contra o mesmo efeito, faz-se apenas um, sofrendo o efeito uma vez; se ela receber dano, você não precisa testar concentração; pode ser descartada como ação bônus no seu turno ou ao ficar inconsciente. Os escores de habilidade dela vêm da força de sua Personalidade — ela não tem pontuações, só modificadores; você ganha pontos iguais ao seu modificador de Carisma x3 para aumentar qualquer modificador dela em +1 (máximo +6)." },
        { nivel: 3, nome: "Trapaceiro Superior", descricao: "A partir do 3º nível, você aprende manobras alimentadas por um Dado de Superioridade (d6). Aprende três manobras à escolha (catálogo do recurso não capturado na fonte extraída — ver nota abaixo), ganhando mais com o nível (Dados de Superioridade / Manobras Conhecidas: 3º-5º: 3/3; 6º-7º: 4/3; 8º: 4/4; 9º-11º: 5/4; 12º: 6/4; 13º-14º: 6/5; 15º-17º: 7/5; 18º-20º: 8/6). Só pode usar uma manobra por ataque. Ao tirar descanso longo, pode trocar uma manobra conhecida. Um dado é gasto quando usado; todos os gastos são recuperados ao terminar um descanso curto ou longo.\n\nAs Manobras de Trapaça referenciadas aqui não tiveram seu texto completo localizado na fonte extraída — apenas os nomes: Debilitar: Rakunda, Aumento de Poder: Carga, Debilitar: Tarunda, Aumento de Poder: Concentrar, Debilitar: Sukunda, Aumento de Poder: Foco, Ramp Up: Rakukaja, Aumento de Velocidade: Tarukaja, Aumento de Velocidade: Sukukaja, Suprema: Revolução." },
        { nivel: 6, nome: "Amarração da Alma dos Trapaceiros", descricao: "A partir do 6º nível, você aprende a se fundir com sua Alma Vazia, tornando-se seu eu verdadeiro e plenamente realizado. Como ação bônus, pode se fundir com ela por até 1 minuto; enquanto fundido, é tratado como se tivesse convocado a Alma Vazia (mas não pode invocá-la separadamente). A forma termina antecipadamente se você ficar inconsciente ou morrer; a fusão se manifesta como um capacete ou máscara. Usável uma vez por descanso curto (gastando 1 dado de Superioridade para reusar). Benefícios enquanto fundido:\n\nPotencial de Trapaceiro: uma vez por turno, ao conseguir acerto crítico, rolar 20 natural em um teste de habilidade, ou um hostil falhar criticamente contra seu Genjutsu, recupera 2 dados de Superioridade.\n\nForça dos Trapaceiros: selecione um modificador de habilidade da Alma Vazia e aumente o seu para corresponder, ignorando sua pontuação normal.\n\nEspírito de Trapaceiro: vantagem em lances de defesa de Sabedoria e Carisma e em verificações de habilidade.\n\nPalavras dos Trapaceiros: uma vez por turno, influencie uma criatura em batalha — aliada ganha +1d6 em verificação/defesa/ataque; hostil tem sua próxima verificação/defesa/ataque reduzida pela metade de 1d6; usável um número de vezes igual ao seu modificador de Carisma por descanso longo." },
        { nivel: 9, nome: "Ascensor de Calor", descricao: "A partir do 9º nível, sua capacidade de arrastar inimigos ou de melhorar os corações de seus aliados se fortaleceu. Ao usar uma Manobra de Trapaceiro em uma criatura, pode, como parte da mesma ação, usar outra manobra visando a mesma criatura. A manobra adicional deve ajudar ou atrapalhar o alvo de acordo com o efeito da manobra desencadeadora (se impulsiona/aumenta/ajuda, a adicional deve fazer o mesmo; se penaliza/reduz/prejudica, a adicional deve fazer o mesmo). Deve gastar um dado de Superioridade normalmente." },
        { nivel: 14, nome: "Aumento de Força de Vontade", descricao: "A partir do 14º nível, ao lançar um jutsu sem sua Alma Vazia ativa, pode invocá-la temporariamente para que ela lance o jutsu por você, ignorando qualquer selo de mão exigido. O jutsu causa dano adicional igual ao dobro do seu modificador de Carisma, ou aumenta a CD pela metade do modificador (arredondado para baixo). Alternativamente, se estiver se beneficiando da Amarração da Alma dos Trapaceiros, ambos lançam o jutsu simultaneamente, recebendo o benefício anterior mais um bônus de ataque e dano igual ao seu modificador de Carisma. Usável um número de vezes igual ao seu modificador de Carisma por descanso longo; sem usos restantes, pode gastar 1 dado de Superioridade para usá-lo mais uma vez." },
        { nivel: 17, nome: "Mudança de Coração", descricao: "A partir do 17º nível, sua Alma Vazia ganha imunidade a ataques não aprimorados por chakra ou resistência a dois tipos de dano à sua escolha. Alternativamente, enquanto se beneficia da Amarração da Alma dos Trapaceiros, ganha um dos benefícios abaixo (trocável ao completar um descanso longo):\n\nMessias: quando uma criatura em raio de 18 metros é reduzida a 0 PV ou menos, como reação, gaste 1 dado de Superioridade para que ela caia a 1 PV e ganhe PV temporários iguais a 5x o resultado.\n\nIzanagi: ao gastar um dado de Superioridade em um aliado, se o total combinado do d20 dele e do dado for 20 ou mais, trata-se como 20 natural.\n\nSatanael: seu dado de Superioridade e o dado de Palavras dos Trapaceiros tornam-se d8." },
        { nivel: 20, nome: "Domínio de Si Mesmo", descricao: "A partir do 20º nível, enquanto sua Alma Vazia estiver convocada ou você estiver se beneficiando da Amarração da Alma dos Trapaceiros, você e ela ganham imunidade às condições Encantado, Medo, Enlouquecido, Atordoado e Enfraquecido." },
      ],
    },
  ],
};
