import type { ClassProgressionDefinition } from "@/lib/classProgression/types";

/**
 * Progressão completa do Ninja Cozinheiro — "Observações do Orochimaru"
 * (compêndio de Classes), p.290-320. Complementa o resumo em
 * catalog/classes.ts com a tabela nível-a-nível (1-20), as características
 * por extenso e as 11 subclasses de "Focos de Culinária" (escolhida no 2º
 * nível). Distâncias em pés da fonte foram convertidas para metros (5 pés
 * = 1,5 m), como no restante do catálogo.
 *
 * Notas sobre a fonte:
 * - Várias características têm nomes divergentes entre a tabela de nível
 *   e o corpo do texto; usado aqui o nome do corpo do texto: "Perícia em
 *   Ferramentas" (tabela: "Especialização em ferramentas"), "Guerra e
 *   Comida" (tabela: "Guerra e alimentos"), "Sabor Inigualável" (tabela:
 *   "Gosto inigualável").
 * - A linha do 18º nível veio corrompida na fonte; os valores de Dado de
 *   Cozinha/Jutsu Conhecidos/Rank foram interpolados a partir das linhas
 *   vizinhas (17º e 19º nível).
 * - A subclasse "Chef Patissier" está incompleta: apenas suas
 *   características de 2º nível foram localizadas na fonte (em dois
 *   trechos, remontados aqui); as características de 5º, 9º, 13º e 17º
 *   nível não aparecem em nenhum trecho extraído.
 * - A subclasse "Mão que Ajuda" também está incompleta: suas
 *   características de 2º nível não foram localizadas (a fonte começa
 *   diretamente no 5º nível), e sua característica de 17º nível
 *   ("Doce Miasha") foi cortada no meio da frase.
 * - Em "Herbalista", "Spectre Cooks" e "Mixologista", as opções de
 *   propriedade de arma do 11º nível (Bônus de Infusão de Ferramenta)
 *   não foram localizadas na fonte extraída.
 * - A subclasse "Mixologista" referencia uma "Tabela do Misturador da
 *   Loucura" (1d100) com os efeitos de cada bebida aleatória; essa tabela
 *   não foi transcrita em nenhum trecho extraído (apenas sua existência e
 *   localização aproximada no livro foram identificadas) — não incluída.
 */
export const progressaoNinjaCozinheiro: ClassProgressionDefinition = {
  classeKey: "ninja-cozinheiro",
  nomeGrupoSubclasse: "Focos de Culinária",
  nivelEscolhaSubclasse: 2,

  levels: [
    { nivel: 1, bonusProficiencia: 3, caracteristicas: "Infusão de Ferramentas de Cozinha, Lanches de Shinobi",
      colunasExtras: { "Dado de Cozinha": "1d4", "Jutsu Conhecidos": "6", "Rank Mais Alto do Jutsu": "Rank-D" } },
    { nivel: 2, bonusProficiencia: 3, caracteristicas: "Foco na Culinária, Alimento para a Alma",
      colunasExtras: { "Dado de Cozinha": "1d4", "Jutsu Conhecidos": "7", "Rank Mais Alto do Jutsu": "Rank-D" } },
    { nivel: 3, bonusProficiencia: 3, caracteristicas: "Perícia em Ferramentas",
      colunasExtras: { "Dado de Cozinha": "1d4", "Jutsu Conhecidos": "8", "Rank Mais Alto do Jutsu": "Rank-D" } },
    { nivel: 4, bonusProficiencia: 4, caracteristicas: "Melhoria/talento na pontuação de habilidade",
      colunasExtras: { "Dado de Cozinha": "1d4", "Jutsu Conhecidos": "8", "Rank Mais Alto do Jutsu": "Rank-D" } },
    { nivel: 5, bonusProficiencia: 4, caracteristicas: "Foco na Culinária (2)",
      colunasExtras: { "Dado de Cozinha": "1d6", "Jutsu Conhecidos": "9", "Rank Mais Alto do Jutsu": "Rank-C" } },
    { nivel: 6, bonusProficiencia: 4, caracteristicas: "Infusão de Ferramentas de Cozinha (2), Aroma Errante",
      colunasExtras: { "Dado de Cozinha": "1d6", "Jutsu Conhecidos": "10", "Rank Mais Alto do Jutsu": "Rank-C" } },
    { nivel: 7, bonusProficiencia: 5, caracteristicas: "Guerra e Comida",
      colunasExtras: { "Dado de Cozinha": "1d6", "Jutsu Conhecidos": "11", "Rank Mais Alto do Jutsu": "Rank-C" } },
    { nivel: 8, bonusProficiencia: 5, caracteristicas: "Melhoria/talento na pontuação de habilidade",
      colunasExtras: { "Dado de Cozinha": "1d6", "Jutsu Conhecidos": "11", "Rank Mais Alto do Jutsu": "Rank-C" } },
    { nivel: 9, bonusProficiencia: 5, caracteristicas: "Foco na Culinária (3)",
      colunasExtras: { "Dado de Cozinha": "1d8", "Jutsu Conhecidos": "12", "Rank Mais Alto do Jutsu": "Rank-B" } },
    { nivel: 10, bonusProficiencia: 6, caracteristicas: "Estômago de Ferro",
      colunasExtras: { "Dado de Cozinha": "1d8", "Jutsu Conhecidos": "13", "Rank Mais Alto do Jutsu": "Rank-B" } },
    { nivel: 11, bonusProficiencia: 6, caracteristicas: "Infusão de Ferramentas de Cozinha (3)",
      colunasExtras: { "Dado de Cozinha": "1d8", "Jutsu Conhecidos": "14", "Rank Mais Alto do Jutsu": "Rank-B" } },
    { nivel: 12, bonusProficiencia: 6, caracteristicas: "Melhoria/talento na pontuação de habilidade",
      colunasExtras: { "Dado de Cozinha": "1d8", "Jutsu Conhecidos": "14", "Rank Mais Alto do Jutsu": "Rank-B" } },
    { nivel: 13, bonusProficiencia: 7, caracteristicas: "Foco na Culinária (4)",
      colunasExtras: { "Dado de Cozinha": "1d10", "Jutsu Conhecidos": "15", "Rank Mais Alto do Jutsu": "Rank-A" } },
    { nivel: 14, bonusProficiencia: 7, caracteristicas: "Estômago de Ferro (2), Aroma Errante (2)",
      colunasExtras: { "Dado de Cozinha": "1d10", "Jutsu Conhecidos": "16", "Rank Mais Alto do Jutsu": "Rank-A" } },
    { nivel: 15, bonusProficiencia: 7, caracteristicas: "Alimento para a Alma (2), Guerra e Comida (2)",
      colunasExtras: { "Dado de Cozinha": "1d10", "Jutsu Conhecidos": "17", "Rank Mais Alto do Jutsu": "Rank-A" } },
    { nivel: 16, bonusProficiencia: 8, caracteristicas: "Melhoria/talento na pontuação de habilidade",
      colunasExtras: { "Dado de Cozinha": "1d10", "Jutsu Conhecidos": "17", "Rank Mais Alto do Jutsu": "Rank-A" } },
    { nivel: 17, bonusProficiencia: 8, caracteristicas: "Foco na Culinária (5)",
      colunasExtras: { "Dado de Cozinha": "1d12", "Jutsu Conhecidos": "18", "Rank Mais Alto do Jutsu": "Rank-S" } },
    { nivel: 18, bonusProficiencia: 8, caracteristicas: "-",
      colunasExtras: { "Dado de Cozinha": "1d12", "Jutsu Conhecidos": "19", "Rank Mais Alto do Jutsu": "Rank-S" } },
    { nivel: 19, bonusProficiencia: 9, caracteristicas: "Melhoria/talento na pontuação de habilidade",
      colunasExtras: { "Dado de Cozinha": "1d12", "Jutsu Conhecidos": "20", "Rank Mais Alto do Jutsu": "Rank-S" } },
    { nivel: 20, bonusProficiencia: 9, caracteristicas: "Sabor Inigualável",
      colunasExtras: { "Dado de Cozinha": "1d12", "Jutsu Conhecidos": "20", "Rank Mais Alto do Jutsu": "Rank-S" } },
  ],

  features: [
    {
      nivel: 1,
      nome: "Infusão de Ferramentas de Cozinha",
      descricao: "A partir do 1º nível, você aprende a infundir chakra em utensílios de cozinha, usáveis em combate além de suas funções normais. Você ganha um utensílio de cozinha (frigideira ou outro item à sua escolha), no qual é proficiente; ele causa dano igual ao seu Dado de Cozinha, e você pode usar Inteligência em vez de Força para ataque e dano. Criaturas não proficientes com utensílios de cozinha não podem usar seus recursos.\n\nNo 1º nível, escolha um tipo de dano (Contundente, Perfurante ou Cortante) e uma propriedade: Bloqueio, Oculto, Pesado (o dano passa a ser 2x seu Dado de Cozinha) ou Mortal. No 6º nível, ganha uma propriedade adicional: Leve (incompatível com Pesado), Arremessado (13,5/27 metros), Crítico, Desarmado ou Viagem. No 11º nível, ganha outra propriedade adicional: Alcance, Ataque Múltiplo, Desarmar ou Agarrar.",
    },
    {
      nivel: 1,
      nome: "Lanches de Shinobi",
      descricao: "No 1º nível, ao completar um descanso curto ou longo, você pode criar um número de lanches igual ao seu bônus de proficiência + Inteligência, de qualquer receita conhecida, com ingredientes secretos que concedem efeitos. Cada lanche mantém sua potência por 12 horas ou até seu próximo descanso, quando estraga. A maioria usa o Dado de Cozinha (começa em 1d4, cresce com o nível). Um lanche só pode ter um ingrediente secreto por vez; podem ser distribuídos entre você e criaturas aliadas/dispostas. Consumir custa uma ação de interação com objeto (para si) ou ação bônus (para dar a outra criatura). Uma criatura não pode se beneficiar de mais de um lanche por vez, nem de um segundo com duração enquanto o primeiro durar (salvo indicação contrária).\n\nIngredientes secretos conhecidos no 1º nível: Creme de Fluxo de Chakra (role 2x o Dado de Cozinha; ganha chakra temporário igual ao resultado; mínimo por dado igual ao modificador de Carisma a partir do 11º nível); Molho Farto (role 3x o Dado de Cozinha; recupera PV iguais ao resultado, mesmo mínimo a partir do 11º); Pedras de Sódio (soma o resultado ao próximo lance de defesa); Curry Picante (soma o resultado às próximas rolagens de ataque e dano); Creme Não Batido (soma o resultado à próxima verificação de habilidade); Arroz Sushi (bônus de velocidade de natação igual a 5x o resultado por 1 minuto, e respira debaixo d'água na hora seguinte); Suco de Goiaba (benefícios de um descanso sem dormir, se usado em até 4h após um descanso; usar duas vezes em 24h causa sono forçado de 16h); Pimentas Furiosas (perde paladar/olfato por 1h; no minuto seguinte, ao causar dano corpo a corpo, soma o Dado de Cozinha ao dano, mínimo igual ao modificador de Carisma); Pimentas Pretas (bônus de velocidade igual a 10x o resultado no minuto seguinte); Pasta Vegetariana (escolhe dois tipos de dano: resistência a um, vulnerabilidade a outro, por turnos iguais ao resultado); Pesto Salgado (consumível como parte da rolagem de iniciativa; bônus de iniciativa igual ao resultado); Chá Calmante (remove uma condição entre Encantado, Temido, Enlouquecido ou Confuso); Slama de Banana (imunidade a uma condição Elemental ou Física escolhida, por rodadas iguais ao resultado); Chakra de Mistura de Trilha (reduz o custo de chakra do próximo jutsu lançado pelo resultado; em jutsu de concentração, reduz só o custo inicial).",
    },
    {
      nivel: 2,
      nome: "Foco na Culinária",
      descricao: "A partir do 2º nível, você seleciona um Foco de Culinária (sua subclasse), que concede características no 2º nível e novamente no 5º, 9º, 13º e 17º. Junto com o estilo, você aprende ingredientes secretos adicionais incorporáveis aos seus Lanches de Shinobi.",
    },
    {
      nivel: 2,
      nome: "Alimento para a Alma",
      descricao: "A partir do 2º nível, sempre que completar um descanso curto ou longo, selecione um atributo. Todos os aliados dispostos ganham vantagem em sua primeira verificação de habilidade e lance de defesa que use esse atributo.",
    },
    {
      nivel: 3,
      nome: "Perícia em Ferramentas",
      descricao: "A partir do 3º nível, selecione uma habilidade e uma Ferramenta Ninja em que seja proficiente. Você ganha experiência (dobra o bônus de proficiência) na habilidade e na ferramenta escolhidas.",
    },
    {
      nivel: 4,
      nome: "Melhoria/Talento de Pontuação de Habilidade",
      descricao: "Ao atingir o 4º nível, e novamente no 8º, 12º, 16º e 19º, você ganha +1 em um valor de habilidade e um Talento de sua escolha para o qual se qualifique. Um valor de habilidade não pode ser aumentado acima de 20 usando este recurso.",
    },
    {
      nivel: 6,
      nome: "Aroma Errante",
      descricao: "A partir do 6º nível, você ganha uma aura constante que incorpora sua personalidade. Escolha duas auras conhecidas, mas só pode ter uma ativa por vez (ação bônus para trocar). No 14º nível, aprende mais duas auras. É preciso estar consciente para conceder os bônus.\n\nAuras disponíveis: Mão Amiga (criaturas a até 9 metros não podem ter desvantagem em lances de defesa); Mão Restauradora (cura adicional igual a 2x o modificador de Carisma, mínimo +1, a até 4,5 metros); Ira do Cozinheiro (dano adicional igual ao dobro do modificador de Carisma, mínimo +1, a 4,5 metros); Tiro Preciso (vantagem na primeira rolagem de ataque por turno, a 9 metros); Brilhando Através da Dor (reduz o dano recebido em valor igual ao modificador de Carisma, mínimo +1, a 9 metros); Proteção do Cozinheiro (resistência a um tipo de dano escolhido, a 4,5 metros); Saia Dessa! (vantagem em lances de defesa contra Encantado, Temido e Berserk, a 4,5 metros); Entrar na Linha (+4,5 metros de velocidade, estendido a aliados que iniciem o turno a até 9 metros); Todos Nós Trabalhamos Juntos (permite comer um lanche como ação livre quando o dano de um ataque/jutsu hostil for reduzido a 0, a 4,5 metros); Rally! (imunidade a ser derrubado, forçado a se mover ou teletransportado sem consentimento, a 9 metros); Perfume Habilidoso (soma um Dado de Cozinha a verificações de habilidade que usem o atributo escolhido por Alimento para a Alma, a 9 metros); Passo da Brisa (movimento não reduzido a menos da metade, imunidade a terreno difícil, ignora efeitos de área, a 4,5 metros); Bloqueio Poderoso (aumento de CA igual à metade do modificador de Carisma, arredondado para baixo, a 1,5 metro).",
    },
    {
      nivel: 7,
      nome: "Guerra e Comida",
      descricao: "A partir do 7º nível, você domina a habilidade de preparar pratos no meio da batalha. Como ação, gaste um uso do seu Kit de Culinária para ganhar o benefício de Lanches de Shinobi como se tivesse completado um descanso, criando um número de lanches igual ao seu modificador de Inteligência. Todas as criaturas voluntárias à sua escolha em raio de 9 metros podem receber esses lanches como se você os tivesse dado a elas. Uma vez por descanso longo (duas vezes a partir do 15º nível).",
    },
    {
      nivel: 10,
      nome: "Estômago de Ferro",
      descricao: "A partir do 10º nível, você identifica alimentos ou bebidas venenosos apenas com uma olhada, e ganha vantagem em lances de defesa contra envenenamento ou a condição Envenenado. A partir do 14º nível, sempre que um aliado completar um descanso a até 9 metros de você, ele ganha vantagem em lances de defesa contra envenenamento ou Envenenado pelas próximas 8 horas.",
    },
    {
      nivel: 20,
      nome: "Sabor Inigualável",
      descricao: "No 20º nível, quando uma criatura se beneficia pela primeira vez, após um descanso, de um Lanche Shinobi atualmente ativo, role seu Dado de Cozinha. Ela ganha todos os efeitos: recupera PV iguais ao dobro do resultado; ganha chakra temporário igual ao dobro do resultado; +2 de CA por 1 minuto; vantagem em todos os lances de defesa nos quais não é proficiente por 1 minuto; e uma ação bônus adicional em cada turno por 1 minuto.",
    },
  ],

  subclasses: [
    {
      key: "cozinheiro-de-batalha",
      nome: "Cozinheiro de Batalha",
      classeKey: "ninja-cozinheiro",
      descricaoIntro: "Os Cooking-Nin que se concentram em se tornar cozinheiros de batalha aprendem a lutar no meio dos campos de batalha com suas ferramentas de culinária enquanto apoiam seus aliados na luta, subjugando seus adversários com uma enxurrada de ataques e estimulando seus aliados com lanches estimulantes.",
      features: [
        { nivel: 2, nome: "Bônus de Infusão de Ferramentas", descricao: "Você ganha uma segunda arma de infusão de ferramentas, com aparência dura e cruel. No 2º nível, escolha um tipo de dano (Contundente, Perfurante ou Cortante) e uma propriedade (a arma causa dano igual ao seu Dado de Cozinha, podendo usar Inteligência em vez de Força): Golpe Poderoso (ao acertar com Bukijutsu ou com esta arma, soma seu Dado de Cozinha ao dano); Mudança de Modo (ação bônus alterna entre modo leve — propriedade Leve e +2 de CA — e modo pesado — um dado de dano extra, mas Duas Mãos e Pesada); Bloqueio Defensivo (ao ser atingido, role como reação seu Dado de Cozinha e reduza o acerto pela metade do resultado). A partir do 6º nível, ganha propriedade adicional: Ataque Múltiplo; Arremessado (13,5/27 metros); Aparo Indefeso (quando um ataque falhar, faz com que acerte como reação, recebendo o dano máximo, e pode lançar um Bukijutsu Rank C ou inferior como ação além da reação); Cuspe Elemental (como reação ao usar Bukijutsu/ataque com este utensílio, altera o dano para Raio, Fogo ou Frio, causando +1d10 desse elemento). A partir do 11º nível, ganha outra propriedade: Exploração de Fraquezas (a arma causa dano máximo a uma criatura vulnerável ao tipo de dano dela)." },
        { nivel: 2, nome: "Lanches de Combate", descricao: "No 2º nível, você aprende ingredientes secretos adicionais: Molho Fireball Zip (seu chakra assume a natureza de Fogo; ganha a habilidade de lançar Liberação de Fogo: Bola de Fogo Rank C no minuto seguinte, ignorando requisitos de palavra-chave e componentes, pela metade do custo; se não lançar ao menos uma vez, sofre 6d6 de dano de fogo irresistível; alternativamente, pode forçar uma criatura a comer o lanche com um ataque de Ninjutsu corpo a corpo, causando 6d6 de dano de fogo irresistível; pode lançar no Rank B a partir do 11º nível, Rank A a partir do 16º); Croque Madame (role o Dado de Cozinha; bônus de CA igual ao resultado por 1 minuto, reduzido em 1 a cada dano sofrido ou resistência falha); Veludo Vermelho (consumível como reação ao ser atingido por Bukijutsu/arma branca a 1,5 metro; role o dobro do Dado de Cozinha contra o dano da arma do atacante — se maior, cancela o Bukijutsu do alvo); Creme Brûlée (role o Dado de Cozinha; consumível como reação ao rolar dano, causando dano máximo em um número de dados igual ao resultado); Meu Estilo (a partir do 5º nível, pode usar Carisma em vez de Força ao lançar Bukijutsu)." },
        { nivel: 9, nome: "Aura de Combate", descricao: "A partir do 9º nível, você aprende uma aura extra, constantemente ativa, combinável com outra ativada ao mesmo tempo. Sempre que você ou um aliado a até 9 metros rolar o dano de um ataque, pode somar seu Dado de Cozinha ao dano, uma vez por turno." },
        { nivel: 13, nome: "Ataque Extra Exclusivo", descricao: "A partir do 13º nível, você pode atacar duas vezes, em vez de uma, ao realizar a ação de Ataque; se lançar um Bukijutsu como ação, pode fazer um ataque corpo a corpo como ação bônus." },
        { nivel: 17, nome: "Mestre do Jantar e dos Dados", descricao: "A partir do 17º nível, você ganha +2 nas rolagens de ataque e verificações de habilidade com sua arma Bônus de Infusão. Acertos críticos com seus utensílios de cozinha não podem sofrer reação e dobram seu modificador de habilidade nas rolagens de dano." },
      ],
    },
    {
      key: "chefe-de-cozinha-entremeador",
      nome: "Chefe de Cozinha Entremeador",
      classeKey: "ninja-cozinheiro",
      descricaoIntro: "Cozinheiros-Nin que se concentram em se tornar entremetier aprendem a cozinhar com uma série de diferentes massas macias e duras, valorizando a velocidade e a iniciativa.",
      features: [
        { nivel: 2, nome: "Rápido e Furtivo", descricao: "Você pode usar Inteligência em vez de Destreza para rolagens de iniciativa." },
        { nivel: 2, nome: "Bônus de Infusão de Ferramenta", descricao: "Você ganha uma segunda arma de infusão de ferramentas: uma ferramenta de cozinha leve e fácil de usar. No 2º nível, escolha um tipo de dano e uma propriedade (dano igual ao Dado de Cozinha, Inteligência no lugar de Força): Leve; Carga (ao usar Disparada, pode usar ação bônus para atacar com vantagem uma criatura ao final do movimento); Demônio da Velocidade (+3 metros de velocidade e +1d6 de dano extra no primeiro ataque que acertar a cada turno). A partir do 6º nível, propriedade adicional: Sorteio Crítico (na primeira rodada de combate, ataques com armas brancas obtêm crítico com 17+ contra criatura que ainda não agiu); Velocidade do Arquidemônio (+4,5 metros de velocidade e +1d8 de dano extra no primeiro ataque por turno); Precisão (+1 para acertar e +1 no dano). A partir do 11º nível, propriedade adicional: Punição de Saque (na primeira rodada de combate, ao acertar criatura que ainda não agiu, ela fica em desvantagem em lances de defesa até o início do turno dela); Velocidade do Deus-Demônio (+3 metros de velocidade e +1d10 de dano extra no primeiro ataque por turno)." },
        { nivel: 2, nome: "Lanches Rápidos", descricao: "A partir do 2º nível, você aprende ingredientes secretos adicionais; todos os lanches desta subclasse podem ser consumidos como ação livre ou como parte da rolagem de iniciativa: Prosciutto Bruschetta (role o Dado de Cozinha; na iniciativa, soma à verificação e ganha bônus de velocidade igual a 5x o resultado até o fim do primeiro turno; fora da iniciativa, vantagem no próximo ataque); Bolinho de Massa Suculento (role duas vezes; na iniciativa, escolhe uma criatura hostil visível e ganha bônus de CA e resistência igual à metade do resultado contra ela até o fim do segundo turno dela; fora da iniciativa, soma a rolagem ao próximo ataque com arma); Bocconcini Picante (role três vezes; na iniciativa, ganha uma reação adicional usável no minuto seguinte; fora da iniciativa, ganha PV e chakra temporários iguais ao resultado); Cacau Quente (role três vezes; na iniciativa, resistência a dano de fogo e vento no minuto seguinte; fora da iniciativa, pode rerrolar sua iniciativa somando o dobro ao resultado, tratando-o como seu primeiro turno novamente)." },
        { nivel: 5, nome: "Primeiro na Fila", descricao: "A partir do 5º nível, sempre que você e uma criatura hostil rolarem iniciativa, some +5 ao seu resultado (+10 a partir do 11º nível). Você também tem vantagem em qualquer ataque contra uma criatura que ainda não tenha agido." },
        { nivel: 9, nome: "Aura de Velocidade", descricao: "A partir do 9º nível, você ganha uma aura constante, combinável com outra ativada ao mesmo tempo. Sempre que você ou um aliado a até 9 metros rolar iniciativa, ganha um valor extra igual ao seu modificador de Carisma (mínimo +1); precisa estar consciente para conceder o bônus. Você também incrusta sal em suas ferramentas: se uma criatura estiver se concentrando em um jutsu quando você a acertar com elas, ela testa concentração em desvantagem." },
        { nivel: 13, nome: "Preparar a Mesa", descricao: "A partir do 13º nível, ao realizar uma ação de prontidão, pode prepará-la como ação bônus ou ação principal. Pode optar por não gastar a reação para desencadeá-la, ao custo de 1 lanche." },
        { nivel: 17, nome: "Antes de Tudo", descricao: "A partir do 17º nível, independentemente do resultado da sua iniciativa ou de ser surpreendido, você sempre age primeiro em combate; depois, age novamente seguindo a contagem normal de iniciativa (conta como ganhar 2 turnos na primeira rodada)." },
      ],
    },
    {
      key: "chef-patissier",
      nome: "Chef Patissier",
      classeKey: "ninja-cozinheiro",
      descricaoIntro: "Os Cozinheiros-Nin que se concentram em se tornar Pâtissier aprendem a cozinhar com uma série de diferentes massas macias e duras. Subclasse incompleta na fonte extraída: apenas as características de 2º nível foram localizadas; as de 5º, 9º, 13º e 17º não aparecem em nenhum trecho do livro lido.",
      features: [
        { nivel: 2, nome: "Cheiro Doce", descricao: "Ao escolher este Foco a partir do 2º nível, sua constante experimentação com sabores doces deixa você com um aroma único, que se espalha em raio de 3 metros ao seu redor. Verificações de Carisma contra criaturas neutras ou amigáveis são feitas com vantagem." },
        { nivel: 2, nome: "Bônus de Infusão de Ferramenta", descricao: "Você ganha uma segunda arma de infusão de ferramenta: uma ferramenta de cozinha não ameaçadora, como uma frigideira ou rolo de massa. No 2º nível, escolha um tipo de dano e uma propriedade (dano igual ao Dado de Cozinha, Inteligência no lugar de Força): Bloqueio; Foco de Cura (quando uma criatura recupera PV de um jutsu/recurso seu, recupera PV extra iguais ao seu Dado de Cozinha); Salto em Pé (como reação a ser atacado, sem armadura pesada, salta para frente/cima fazendo o ataque falhar, cobrindo metros iguais ao seu modificador de Inteligência + bônus de proficiência, e faz um único ataque com arma contra um alvo como parte da mesma ação); Guarda Ampla (criaturas em raio de 3 metros ganham +1 de CA); Tapinha nas Costas (como parte da ação de Ataque, mira um aliado disposto, infundindo chakra pela arma; ele ganha PV iguais ao triplo do seu Dado de Cozinha). A partir do 11º nível, ganha propriedade adicional: Mega HP Up (quando uma criatura recupera PV enquanto você segura esta arma, também pode remover um grau de uma condição que a afete); Assuma a Liderança (pode abrir mão da sua reação no turno para dar a uma criatura em raio de 9 metros uma reação extra no turno dela)." },
        { nivel: 2, nome: "Lanches Fofos", descricao: "No 2º nível, você aprende ingredientes secretos adicionais: Pasta de Feijão de Baunilha (role o Dado de Cozinha quatro vezes; molho doce consumível como reação ao receber dano, reduzindo o dano pelo resultado); Torta de Limão (molho picante consumível como reação ao receber dano, antes de rolar os dados de dano; na primeira vez em cada turno em que atacar a criatura desencadeadora com arma no minuto seguinte, ganha +1 no alcance de ameaça crítica e soma 3 Dados de Cozinha ao dano); Maracujá (role o Dado de Cozinha três vezes; consumível como reação quando você seria reduzido a 0 PV — em vez disso, é reduzido a 1 e recupera PV iguais ao resultado somado ao seu modificador de Carisma; uma criatura só pode receber os efeitos deste lanche duas vezes por descanso longo); Sal de Laranja (role o Dado de Cozinha quatro vezes; o usuário ganha PV iguais ao resultado somado ao seu modificador de Carisma, e você ganha PV iguais à metade do resultado)." },
      ],
    },
    {
      key: "mao-que-ajuda",
      nome: "Mão que Ajuda",
      classeKey: "ninja-cozinheiro",
      descricaoIntro: "Subclasse focada em cura e apoio através do Carisma, unindo culinária e liberação médica. Subclasse incompleta na fonte extraída: suas características de 2º nível não foram localizadas (a fonte começa diretamente no 5º nível).",
      features: [
        { nivel: 5, nome: "Mão que Ajuda", descricao: "Graças ao seu desejo de ajudar os outros, você tem talento natural para a cura. Com a liberação Médica, pode aprender qualquer jutsu que recupere PV ou forneça PV temporários, usando Carisma como atributo de lançamento. Ao curar uma criatura com um jutsu, pode, como parte da mesma ação, alimentá-la com um lanche (se estiver no alcance). No 11º nível, soma seu modificador de Carisma à cura que fizer." },
        { nivel: 9, nome: "Aura Encantadora", descricao: "Você ganha uma aura constante, combinável com outra ativada ao mesmo tempo. Sempre que você ou um aliado a até 9 metros fizer uma verificação de habilidade baseada em Carisma, ganha uma quantidade extra igual ao seu modificador de Carisma (mínimo +1). Além disso, sempre que uma criatura recuperar PV dentro da sua aura, ganha uma quantidade adicional igual ao seu Dado de Cozinha." },
        { nivel: 13, nome: "Corrida de Açúcar", descricao: "Quando uma criatura se beneficia de um Lanche de Shinobi concedido por esta subclasse, ela recebe uma descarga de energia: além dos efeitos do lanche, ganha uma ação adicional no próximo turno (ataque com arma, Correr, Desengajar, Esconder-se ou usar um objeto). Usável por descanso curto um número de vezes igual ao seu modificador de Carisma (mínimo 1)." },
        { nivel: 17, nome: "Doce Miasha", descricao: "Você ganha um benefício adicional à sua Aura Encantadora: sempre que uma criatura hostil atacar alguém dentro da sua aura, role seu Dado de Cozinha e reduza o ataque dessa criatura (o restante da descrição foi cortado na fonte extraída — não foi possível determinar em quanto o ataque é reduzido nem se há efeito adicional)." },
      ],
    },
    {
      key: "herbalista",
      nome: "Herbalista",
      classeKey: "ninja-cozinheiro",
      descricaoIntro: "O Cozinheiro-Nin que se concentra em se tornar um Herbalista aprende sobre as maravilhas de certas ervas e plantas para aprimorar seus alimentos com o poder dos ingredientes naturais.",
      features: [
        { nivel: 2, nome: "Névoa Gasosa", descricao: "Você pode usar Carisma em vez de Sabedoria para calcular seu bônus de ataque de Genjutsu e sua CD de salvamento." },
        { nivel: 2, nome: "Bônus de Infusão de Ferramenta", descricao: "Você ganha uma segunda arma de infusão: um cachimbo ou objeto fumegante. No 2º nível, escolha um tipo de dano e uma propriedade (dano igual ao Dado de Cozinha, Inteligência no lugar de Força): Respiração Profunda (como ação livre ao lançar um Genjutsu, ele ganha a palavra-chave Inalado e vira área de efeito de 4,5 metros); Não Sabia Que Você Era Frio Assim (como reação a um ataque contra você, sopra fumaça nos olhos do atacante, concedendo +3 de CA até o fim do próximo turno); Erva no Cachimbo (pode 'carregar' até dois jutsu Rank C, sem custo, durante um descanso). A partir do 6º nível, propriedade adicional: Fumaça Constante (a sala onde você ficar por 5+ minutos segurando a arma fica coberta de névoa, como Liberação de Água: Névoa Oculta); Inalação Rápida (jutsu Inalados podem ser lançados como ação bônus, um número de vezes igual ao modificador de Carisma); Erva Inalada (+1 na CD de jutsu com a palavra-chave Inalado enquanto empunhar o item); Respiração Mais Profunda (aumenta a área de Respiração Profunda para 9 metros e permite trocar a resistência para Constituição); Inspiração Áspera (dano adicional de 2 Dados de Cozinha em Genjutsu Inalado). A partir do 11º nível, o utensílio ganha mais uma propriedade adicional (as opções específicas não foram localizadas na fonte extraída)." },
        { nivel: 2, nome: "Lanches à Base de Ervas", descricao: "Ao escolher este Foco, você aprende ingredientes secretos adicionais: Manteiga Indica (ação, libera uma nuvem de fumaça em cone de 9 metros; criaturas no cone testam Constituição contra sua CD de Genjutsu ou ficam Intoxicadas — Envenenadas, Desaceleradas e Atordoadas por 1 minuto, com nova tentativa a cada turno — até consumir outro lanche com este ingrediente); Suco de Sativa (encerra imediatamente as condições Berserk, Encantado, Temido, Atordoado e Enfraquecido); Licor Híbrido (role o Dado de Cozinha 5 vezes; o usuário ganha esse total em PV temporários por 1 minuto, e enquanto os tiver não pode ser desacelerado nem ter a velocidade reduzida); Sal Conicoide (só pode ser consumido ao completar um descanso curto, convertendo-o em descanso longo; uma vez por semana)." },
        { nivel: 5, nome: "Repouso e Relaxamento", descricao: "Você encontrou uma especiaria herbácea que acalma tendências agressivas ao ser queimada. Descanso: ao terminar um descanso sob a névoa da especiaria, você e os participantes aumentam PV máximo e atual em 2 Dados de Cozinha por 8 horas ou até o próximo descanso (uma vez por dia por criatura). Relaxamento: como ação, acenda a especiaria criando névoa volátil em raio de 13,5 metros; criaturas hostis na área testam Constituição contra sua CD de Genjutsu ou ficam Incapacitadas por 1d4+1 rodadas (termina se sofrerem dano, forem forçadas a resistência por efeito hostil, ou se um aliado que veem sendo atacado tiver o efeito encerrado); usável um número de vezes igual ao seu modificador de Carisma." },
        { nivel: 9, nome: "Aura Inebriada", descricao: "Aura constante, combinável com outra. Você e aliados em raio de 9 metros têm vantagem em resistências contra Genjutsu. Você também ganha +1 na CD de jutsu com a palavra-chave Inalado." },
        { nivel: 13, nome: "Vibe Killer", descricao: "Quando uma criatura tenta resistência ou verificação de habilidade para encerrar um Genjutsu que a afeta, você pode gastar sua reação para forçá-la a rolar novamente, usando o pior resultado. Usável um número de vezes igual ao seu modificador de Carisma por descanso curto." },
        { nivel: 17, nome: "Botânico Incomparável", descricao: "Quando uma criatura faz um lance de defesa contra um Genjutsu seu com a palavra-chave Inalado, role seu Dado de Cozinha e ela reduz sua defesa em metade do resultado. Uma criatura só pode ter sua defesa reduzida assim uma vez por turno." },
      ],
    },
    {
      key: "cozinheiro-fry",
      nome: "Cozinheiro Fry",
      classeKey: "ninja-cozinheiro",
      descricaoIntro: "Os Cooking-Nin que se concentram em se tornar Fry Cooks priorizam o sabor acima de tudo. Sua comida, embora deliciosa, desgasta o corpo com o tempo, e esses cozinheiros usam isso a seu favor na batalha.",
      features: [
        { nivel: 2, nome: "Água e Óleo se Misturam", descricao: "Você ganha a Liberação de Natureza da Água e pode aprender jutsu com essa palavra-chave. Também ganha a habilidade de aprender e lançar jutsu de liberação Médica, mas eles devem causar dano de Ácido; se já possuir essa liberação, ganha um jutsu adicional de Liberação de Água." },
        { nivel: 2, nome: "Bônus de Infusão de Ferramenta", descricao: "Você ganha uma segunda arma de infusão: um par de luvas de fritadeira bem ajustadas. No 2º nível, a arma causa dano Ácido; escolha uma propriedade (dano igual ao Dado de Cozinha, Constituição no lugar de Força) e ganha a propriedade Desarmado: Converter (ao causar dano de Frio ou Fogo, pode mudar para Ácido e +1 no dado de dano; se o efeito também conceder uma condição, ela pode se tornar Corroído); Punho Fritante (ao causar dano com Taijutsu, pode mudar para Ácido e +1 dado de dano); Fry Flip (ao lançar jutsu com palavra-chave Liberação de Água, aumenta o alcance em 4,5 metros e +1 dado de dano). A partir do 6º nível, propriedade adicional: Óleo Aprimorado (+1 na CD ao lançar jutsu de Liberação de Água enquanto empunha o item); Absorção de Ácido (pode usar ácido/substância oleosa em vez de água em jutsu de água, aumentando a etapa de dano em +1; vale para efeitos que criem área de ácido); Ferrão Ácido (ao causar a condição Corroído, aumenta o dado de dano para d8 e a CD de remoção em +3). A partir do 11º nível, propriedade adicional: Explosão de Ácido (ao lançar jutsu de Liberação de Água causando dano ácido, libera névoa ácida de 3 metros até o fim do próximo turno, duas vezes por descanso longo; aliados na névoa tratam o jutsu como se houvesse fonte de água por perto, reduzindo o custo em -2, mínimo metade); Obliteração Ácida (ao lançar Taijutsu com essa arma causando dano ácido, pode usar Constituição em vez do atributo normal)." },
        { nivel: 2, nome: "Lanches Fritos", descricao: "Ao escolher este Foco, você aprende ingredientes secretos adicionais: Massa Frita com Canela (role 1 Dado de Cozinha, rerrolando 1s/2s e usando o segundo resultado; ataques contra o usuário são feitos com desvantagem por um número de ataques igual ao resultado); Takoyaki Frito (role 1 Dado de Cozinha; o usuário deixa uma camada escorregadia de óleo em cada espaço por onde passa até o fim do próximo turno; criaturas que tentem passar testam Destreza contra sua CD de Ninjutsu ou sofrem dano de ácido igual a 1 Dado de Cozinha, ficam de bruços e cobertas de óleo — perdendo resistência a ácido/fogo e sofrendo dado extra desses tipos — até o fim do próximo turno); Arroz Frito (consumível como reação a uma resistência; escolhe dois lances de defesa e, por 1 minuto, soma metade de um Dado de Cozinha a eles — pode escolher o mesmo duas vezes, ganhando vantagem nele; duas vezes por descanso); Costeleta de Tonkatsu (por 1 minuto, ação bônus extra por turno — ataque desarmado/com arma, Desengajar ou Arrastar-se — e +5x o resultado do Dado de Cozinha de velocidade; duas vezes por descanso)." },
        { nivel: 5, nome: "Revigore os Amigos", descricao: "Durante um descanso curto, você pode fritar um número de pílulas (chakra, sangue ou ração militar) igual ao seu bônus de proficiência. Elas ganham o prefixo \"Fried\" e, ao consumir, o usuário ganha uma quantidade adicional do recurso restaurado igual à média de 2 do seu Dado de Cozinha. Após 12 horas, as pílulas fritas perdem a crocância e o resultado é reduzido à metade ao serem consumidas (não podem ser fritas novamente). Além disso, você dobra o número de graus de Corroído que uma criatura pode ter por vez." },
        { nivel: 9, nome: "Lado Ensolarado Para Cima", descricao: "Aura de 4,5 metros constante que prejudica inimigos. Criaturas hostis que iniciam ou entram na aura ficam revestidas de óleo; sempre que recebem dano de Ácido, Água ou Fogo, sofrem dano adicional de 2 Dados de Cozinha, ficando cobertas de óleo até o fim do próximo turno. Inimigos dentro da aura não podem remover graus de Corroído." },
        { nivel: 13, nome: "A Crosta Perfeita", descricao: "Os Lanches Fritos, antes consumíveis uma vez por descanso, agora podem ser consumidos três vezes por descanso. As pílulas fritas de Revigore os Amigos permanecem crocantes por 24 horas e, ao perder a crocância, não têm mais o resultado reduzido à metade." },
        { nivel: 17, nome: "Sempre Pronto", descricao: "Você é imune à condição Surpreendido. Ao rolar iniciativa, pode consumir um Lanche Frito ou Pílula Frita, ou jogá-lo a um aliado em raio de 9 metros para que o consuma imediatamente." },
      ],
    },
    {
      key: "alquimista",
      nome: "Alquimista",
      classeKey: "ninja-cozinheiro",
      descricaoIntro: "Você aprendeu a torcer e alterar o chakra a seu bel-prazer, fazendo poções, mexendo com os próprios elementos e até alterando seu próprio corpo.",
      features: [
        { nivel: 2, nome: "Dobra da Natureza", descricao: "Em vez de focar em lanches, você aprende a moldar os elementos dentro de seu jutsu e lanches. No 2º nível, enquanto segurar sua Arma Alquimista (utensílio de cozinha desta subclasse), escolha entre as Naturezas Fogo, Luz, Vento, Água ou Terra, e um jutsu Rank C ou inferior que conheça desse elemento para receber aumentos adicionais (no 6º e 11º nível, pode escolher um efeito adicional e um jutsu de qualquer rank conhecido). Opções: Aprimorar a Natureza (gasta um uso de lanche para aumentar a CD do jutsu em metade da rolagem do Dado de Cozinha, arredondado para baixo); Aprimorar Poder (dano adicional igual ao Dado de Cozinha; se o jutsu atingir múltiplos alvos, soma-se apenas uma vez); Aprimorar Cura (aumenta a cura/PV temporário concedido em valor igual ao Dado de Cozinha); Controle Elemental (role o Dado de Cozinha para reduzir o custo do jutsu pela metade, um número de vezes por descanso longo igual ao modificador de Carisma)." },
        { nivel: 2, nome: "Bônus de Infusão de Ferramenta", descricao: "Você ganha sua Arma Alquimista (aparência livre: punho de metal, chama saindo de um buraco, etc.). No 2º nível, o tipo de dano passa a ser o da natureza escolhida; escolha uma propriedade (dano igual ao Dado de Cozinha, Inteligência no lugar de Força): Elemento Alquimista (ao lançar jutsu do mesmo tipo de dano da arma, soma o Dado de Cozinha ao dano); Armazenamento de Chakra (armazena 5 de chakra na arma por descanso longo, usável só para jutsu da Liberação de Natureza escolhida); Fluxo de Elemento (jutsu do elemento escolhido ganha +6 metros de alcance, ou +3 metros de área se for efeito em área). A partir do 6º nível, propriedade adicional: Armazenamento de Chakra Aumentado (armazena mais 10 de chakra, acumulando com o anterior); Elemento Quickend (alcance 9/18 metros; pode lançar como ação bônus em vez de ação um número de vezes por descanso longo igual ao modificador de Carisma); Exploração de Fraqueza (dano de liberação de natureza contra criatura vulnerável causa o dano máximo). A partir do 11º nível, propriedade adicional: Controle de Alquimistas (ao lançar jutsu do mesmo tipo de dano da arma, reduz o custo conforme o rank — D:1, C:2, B:3, A:4, S:5); Mega Armazenamento de Chakra (armazena mais 10 de chakra, acumulando com os anteriores); Passagem (ignora resistência ao seu dano; se a criatura for imune, passa a ter apenas resistência)." },
        { nivel: 5, nome: "Vamos Lá, Experimente", descricao: "Você aprendeu a usar os elementos também em seus lanches. Ao preparar lanches ao fim de um descanso, escolha um número igual ao seu modificador de Inteligência para aplicar uma das opções: Descanse sua Mente (refaz instantaneamente uma resistência contra Genjutsu/Ninjutsu com +1d4); Curar seu Corpo (cura 2 rolagens do Dado de Cozinha); Cura Interior (recupera chakra igual a 1 rolagem do Dado de Cozinha); Deixe o Fogo Queimar (próximo ataque que causar dano soma dano de fogo extra igual ao Dado de Cozinha); Fluir como Água (+6 metros de velocidade); Duro como uma Rocha (PV temporários iguais a 3 rolagens do Dado de Cozinha); Atacar como um Raio (efeitos da ação Correr instantaneamente); Voar com o Vento (velocidade de voo igual à de movimento por um número de turnos igual à rolagem do Dado de Cozinha)." },
        { nivel: 9, nome: "Aura de Troca Equivalente", descricao: "Aura constante que representa seu elemento. Você e criaturas em raio de 4,5 metros reduzem o custo de jutsu que lancem com uma Liberação de Natureza que você possui, em valor igual ao rank (D:1, C:2, B:3, A:4, S:5). Além disso, criaturas podem gastar 1 de chakra para causar 2 de dano extra ao lançar jutsu dentro da aura." },
        { nivel: 13, nome: "Dobra Dupla", descricao: "Você escolhe um segundo tipo elemental para sua Dobra da Natureza, que recebe os mesmos aumentos adicionais e conta como elemento de Dobra da Natureza para todas as suas outras características." },
        { nivel: 17, nome: "Em Contato", descricao: "Sempre que descansar completamente, você pode se sintonizar com o ambiente; como ação de turno completo, libera essa energia, ganhando por um número de turnos igual a uma rolagem do Dado de Cozinha (mínimo = modificador de Inteligência): dano adicional de 4 rolagens do Dado de Cozinha em ataques que causem dano do elemento da Dobra da Natureza; +1 na CD ao lançar jutsu desse elemento; vantagem nos dois primeiros ataques de cada turno. Ao terminar, ganha 2 níveis de Exaustão e 1 de Lentidão até o próximo descanso curto ou longo." },
      ],
    },
    {
      key: "mixologista",
      nome: "Mixologista",
      classeKey: "ninja-cozinheiro",
      descricaoIntro: "Você domina a maneira de criar e preparar drinques na hora, que nem sempre são exatamente o que você quer, mas a prática leva à perfeição. Subclasse voltada para o acaso, portanto pode não ser para todos os grupos.",
      features: [
        { nivel: 2, nome: "Bônus de Infusão de Ferramenta", descricao: "Você ganha uma segunda arma de infusão: uma arma misturadora (parece uma xícara com tampa; ao arremessar, a tampa se derrama como uma granada). No 2º nível, o tipo de dano pode ser Fogo ou Água; escolha uma propriedade (dano igual ao Dado de Cozinha). A arma começa como arma de longo alcance (9/27 metros) e ganha a propriedade Bomba: ao atingir um alvo, explode em raio de 4,5 metros e é destruída; pode ser lançada em espaço desocupado no alcance; criaturas no raio (exceto o alvo) testam Destreza contra sua CD de Ninjutsu, recebendo metade do dano em sucesso. Propriedades (2º nível): Ataque Múltiplo; Agitação da Xícara (dado de dano extra no 2º nível, mais um no 5º, mais um no 13º); Amplo Alcance (arremesso 18/36 metros, área de efeito 9 metros de raio); Reação Elemental (se você tiver uma Liberação de Natureza, a explosão causa esse tipo de dano; falha na resistência de Destreza concede condição conforme o dano: Fogo=Queimado, Vento=Sangramento, Terra=Machucado, Água=Resfriado, Raio=Choque); Líquido Drenante (pode causar dano ao chakra do alvo em vez de PV); Big Boom (área +9 metros; a bomba causa o triplo de dano a estruturas/construções). A partir do 6º nível, propriedade adicional: Combustível para o Fogo (ao arremessar a arma, pode gastar lanches; cada um soma 2 Dados de Cozinha extras ao dano); Segurança em Primeiro Lugar (escolhe um número de criaturas igual ao modificador de Carisma na área que não recebem dano da bomba); Bebida Chamativa (a explosão pisca cores brilhantes; criaturas testam Constituição ou ficam cegas até o fim do próximo turno). A partir do 11º nível, ganha propriedade adicional de arma (as opções específicas não foram localizadas na fonte extraída)." },
        { nivel: 2, nome: "Misturador de Loucura", descricao: "Como ação bônus, você prepara bebidas rapidamente, rolando 1d100 e criando uma bebida conforme o resultado (Tabela do Misturador da Loucura — não transcrita na fonte extraída; apenas sua existência e localização aproximada no livro foram identificadas). Para criar uma bebida, gasta um lanche; pode dá-la a si mesmo ou a outra criatura, inclusive tentando forçá-la a beber via rolagem de ataque com o bônus da arma de infusão. O resultado pode ficar oculto até a bebida ser consumida; o criador pode fazer uma verificação de Intuição CD 22 para descobrir o efeito criado." },
        { nivel: 5, nome: "Explosão de Sabor!", descricao: "Você sabe alterar os efeitos da sua Bomba (Bônus de Infusão de Ferramenta). Como ação livre no seu turno, altere a bomba para uma das opções: Milkshake (dano de frio; força resistência de Constituição em vez de Destreza; falha reduz a velocidade em 3 metros até o fim do próximo turno e concede 2 graus de Frio por um número de turnos igual à rolagem do Dado de Cozinha); B-52 Flamejante (incendeia o licor antes de arremessar; dano de fogo; a área fica em chamas até o início do próximo turno; falha na resistência de Destreza concede 2 graus de Queimado; criaturas que terminem o turno na área recebem metade do dano da bomba); Limonada Elétrica (dano de raio; o alvo e criaturas que falharem na resistência não podem usar reações até o fim do próximo turno); Licor Puro! (não causa dano; cobre criaturas na área com licor pegajoso e inflamável; na próxima vez que uma criatura revestida sofrer dano de fogo, recebe +1d6 por dado de dano de fogo rolado, até metade do seu nível de Ninja Cozinheiro — removível mergulhando em água); Bloody Mary (ao preparar, pode infundir com seu próprio sangue e chakra: para cada 1d10 de dano sofrido, aumenta o dano da arma em 1d8); Charming Tend (em vez de dano, força resistência de Carisma; falha concede 3 graus de Encantado até você causar dano à criatura)." },
        { nivel: 9, nome: "Eu Sei o que Estou Fazendo", descricao: "Aura constante. Você e outras criaturas em raio de 9 metros somam um bônus de acerto ao usar armas de arremesso igual à metade do seu modificador de Carisma (arredondado para cima)." },
        { nivel: 13, nome: "Bebida Dupla!", descricao: "Você pode escolher dois efeitos de Explosão de Sabor em vez de apenas um. Se isso mudar o tipo de resistência ou de dano, escolha uma das duas opções; se um dos efeitos fizer a bomba não causar dano, ela não causa dano, mas aplica ambos os efeitos." },
        { nivel: 17, nome: "Controle Total", descricao: "Ao rolar na Tabela do Misturador da Loucura ou em Explosão de Sabor, você pode rolar com vantagem e escolher qual dos dois efeitos aplicar." },
      ],
    },
    {
      key: "spectre-cooks",
      nome: "Spectre Cooks (Sabor Azedo)",
      classeKey: "ninja-cozinheiro",
      descricaoIntro: "Os Cooking-Nin que se concentram em se tornar Sour Tastes não cozinham para se divertir ou sobreviver. Em vez disso, criam misturas tóxicas para exterminar discretamente seus inimigos. Semelhante ao trabalho dos Hunter-Nin, os Spectre Cooks assassinam nas sombras.",
      features: [
        { nivel: 2, nome: "Eu Espero que Você Morra", descricao: "Você ganha a habilidade de aprender jutsu com a palavra-chave Médico, mas somente os que causam dano por veneno, infligem a condição Envenenado, ou curam/ajudam a curar condições." },
        { nivel: 2, nome: "Bônus de Infusão de Ferramenta", descricao: "Você ganha uma segunda arma de infusão de ferramenta (pode ser uma faca enferrujada, o ferrão de um animal, etc.). No 2º nível, escolha um tipo de dano (Contundente, Perfurante ou Cortante); a ferramenta causa dano de veneno igual ao seu Dado de Cozinha, pode ser usada para Bukijutsu do tipo escolhido, e você pode usar Inteligência no lugar de Força. Escolha uma propriedade: Lâmina de Veneno (qualquer Bukijutsu lançado com ela tem o tipo de dano alterado para veneno); Duas Faces (ao causar dano com a ferramenta, impede que o alvo recupere PV ou remova condições infligidas por você no início do próximo turno dele); Intenção Maligna (soma seu modificador de Carisma a todo dano de veneno que causar). A partir do 6º nível, propriedade adicional: Ataque Múltiplo; Lâmina Revestida (uma vez por turno, ao causar 20+ de dano de veneno em um único ataque, força a Constituição do alvo contra sua CD de Ninjutsu/Bukijutsu — falha = 1 grau de Envenenado); Punhalada Pelas Costas (ao atacar uma criatura com um aliado seu a até 1,5 metro dela, causa dano extra igual a 3x seu Dado de Cozinha). A partir do 11º nível, ganha mais uma propriedade adicional (as opções específicas não foram localizadas na fonte extraída)." },
        { nivel: 2, nome: "Lanches Envenenados", descricao: "Você aprende ingredientes secretos adicionais: Cianeto (não pode ser usado em combate; deve ser infundido secretamente — teste de Furtividade contra a CD do Mestre — em uma refeição/bebida já preparada, consumível por um número de criaturas igual ao seu bônus de proficiência; quem consome testa Constituição: sucesso = nenhum efeito nocivo além de um gosto azedo estranho, sem perceber a tentativa; falha = fica Envenenada, com dificuldade para respirar, só percebendo o envenenamento no início do turno após duas rodadas; após 1 minuto nessas condições fica inconsciente e deve fazer um arremesso de morte a cada dano sofrido pela condição enquanto sufoca — conta como jutsu Rank B, oculto de detecção por jutsu Rank C ou inferior e não rastreável até você); Guloseima de Café (aumenta a velocidade do consumidor em 3,5 metros e permite Desengajar e Esconder-se como ação bônus); Cogumelos Revitalizantes (cura todos os graus de Envenenado, Paralisado ou Enfraquecido; se estava a 0 PV, recupera 1 PV e não pode cair abaixo de 1 até o fim do próximo turno); Hortelã Tóxica (o consumidor recebe imediatamente 2 Dados de Cozinha de dano de veneno; uma vez por turno, como ação, durante o minuto seguinte, pode lançar Liberação Médica: Névoa Venenosa Rank C, usando o ataque e a CD do lanche ou do consumidor)." },
        { nivel: 5, nome: "Licença para Matar", descricao: "Quando causar 15 ou mais de dano de Veneno em uma única instância, pode forçar resistência de Constituição contra sua CD de Ninjutsu ou Taijutsu; falha = fica Envenenada por 1 minuto. Máximo uma vez por turno. A partir do 13º nível: quando causa dano de Veneno a uma criatura com 2 ou mais graus de Envenenado e ela falha nesse teste, pode torná-la Envenenada novamente (além de já estar) ou aumentar o dano da condição em 1 passo durante o período." },
        { nivel: 9, nome: "Inspire", descricao: "Sua experimentação com venenos contaminou o ar ao seu redor, mas seus aliados se acostumaram. Você ganha acesso a duas auras, mas só pode ter uma ativa por vez (ação bônus para trocar; ativar/desativar a aura ativa também é ação ou ação bônus): Tóxico (criaturas hostis em raio de 4,5 metros no início do seu turno testam Constituição contra sua CD de Ninjutsu; falha = Xd6 de dano de veneno, X = seu modificador de Inteligência ou Carisma); Enfraquecimento (idem, falha = 1 grau de Enfraquecido)." },
        { nivel: 13, nome: "Olho Dourado", descricao: "Quando um aliado consome um de seus Lanches Ácidos, ele ganha resistência a dano de Veneno e vantagem contra Veneno/Envenenado pelo próximo minuto. Além disso, você ignora resistência à condição Envenenado com seus Lanches Ácidos (trata imunidade como resistência). Quando uma criatura faz um lance de defesa contra um jutsu Médico que cause dano de Veneno, ou contra um veneno seu, pode aplicar penalidade de -1d6 a esse lance, duas vezes por descanso longo." },
        { nivel: 17, nome: "Fórmula Aperfeiçoada", descricao: "Você ignora resistência e imunidade ao dano de Veneno, e ignora resistência às condições Envenenado e Enfraquecido (trata imunidade como resistência). Além disso, durante um descanso curto, selecione um Lanche Ácido: ele sempre está preparado, mesmo quando todos os lanches acabarem." },
      ],
    },
    {
      key: "cozinheiro-de-show",
      nome: "Cozinheiro de Show",
      classeKey: "ninja-cozinheiro",
      descricaoIntro: "Os Cozinheiros-Nin que se concentram em se tornar cozinheiros de show se esforçam para agradar a todos os sentidos por meio de exibições impressionantes de proezas culinárias que empolgam os espectadores, atraindo-os ainda mais para a refeição que está por vir.",
      features: [
        { nivel: 2, nome: "Dê a Eles um Show", descricao: "Você aprendeu a apimentar sua culinária com dramaticidade. Em vez de fazer um lanche na cozinha, você o faz na frente de quem vai comê-lo. Como ação, conceda os benefícios de um lanche a duas criaturas que possam vê-lo em raio de 9 metros, gastando o lanche no processo (compartilha o uso com Lanches de Shinobi). A partir do 9º nível, pode usar como ação bônus." },
        { nivel: 2, nome: "Bônus de Infusão de Ferramenta", descricao: "Você ganha uma segunda arma de infusão: uma ferramenta de cozinha chamativa e vistosa. No 2º nível, causa um tipo de dano à escolha igual ao Dado de Cozinha; pode usar Inteligência em vez de Força para ataque e dano, e Carisma em vez de Sabedoria para Genjutsu enquanto a segura. Escolha uma propriedade: Show Chamativo (enquanto segura a arma, usa Inteligência para Predomínio e Acrobacia em vez do atributo normal); Flashy Bang (ao lançar um Genjutsu com palavra-chave Visual, pode causar uma explosão chamativa — criaturas hostis em raio de 1,5 metro do alvo original também fazem o lance de defesa como se fossem alvo); Hora do Show (ao usar Dê a Eles um Show, pode escolher pessoas em raio de 13,5 metros em vez de 9). A partir do 6º nível, propriedade adicional: Explosão Reluzente (ao lançar jutsu com palavra-chave Visual enquanto segura o item, a CD aumenta +1); Agora Você Está Vendo (ao conjurar jutsu sem a palavra-chave Visual, pode dar a ele essa palavra-chave); Golpe Reluzente (nas rolagens de ataque com essa arma, pode usar seu modificador de Genjutsu em vez de Inteligência, e aumenta o dado de dano em 1 passo). A partir do 11º nível, propriedade adicional: Armagedom Chamativo (ao lançar um Genjutsu Visual visando a si mesmo ou aliado no alcance, pode, como parte da ação, alimentá-lo com um lanche); Estilo Ofuscante (quando você cega uma criatura, ao fim do turno dela ela sofre dano de fogo igual ao dobro do seu Dado de Cozinha)." },
        { nivel: 2, nome: "Lanches Grandiosos", descricao: "Você aprende ingredientes secretos adicionais, usáveis apenas por meio de Dê a Eles um Show: Taco de Caviar (role o Dado de Cozinha; ao observar este lanche, reduz o dano recebido no valor rolado por 1 minuto); Trufa Negra (ao observar, ganha 18 metros de visão de chakra por 1 minuto); Sorvete de Cereja com Folha de Ouro (role o Dado de Cozinha; ao observar, obtém os benefícios de Disparada e Desengajar por um número de rodadas igual ao resultado); Macaroons de Coco (ao observar, ganha vantagem no próximo lance de defesa que fizer no minuto seguinte); Bolos Espiralados (quando uma criatura faz um lance de defesa contra um Genjutsu Visual, pode, como reação, usar este petisco e reduzir o lance dela em metade de uma rolagem do Dado de Cozinha; pode ser usado sem Dê a Eles um Show)." },
        { nivel: 5, nome: "Um Banquete para os Olhos", descricao: "Quando você usa Dê a Eles um Show, os inimigos no alcance testam Sabedoria contra sua CD de Genjutsu como se fossem alvo de um Genjutsu Visual, ficando cegos até o fim do próximo turno em falha. Além disso, enquanto estiverem cegos por qualquer um de seus efeitos, qualquer Genjutsu Visual que você lançar ainda pode afetá-los." },
        { nivel: 9, nome: "Uma Exibição Satisfatória", descricao: "Sempre que usar Dê a Eles um Show, você também pode se dar os benefícios do lanche, um número de vezes igual ao seu modificador de Carisma. Você também ganha uma aura constante de 4,5 metros (combinável com outra ativa): sempre que uma criatura hostil fizer resistência contra um Genjutsu Visual dentro dela, reduz a rolagem em valor igual ao rank do Genjutsu (D-C: -1, B-A: -2, S: -3)." },
        { nivel: 13, nome: "Grande Final", descricao: "Ao usar Dê a Eles um Show, criaturas que não sejam você ganham os benefícios do lanche como se você tivesse rolado o máximo do dado. Criaturas hostis no alcance afetadas por Um Banquete para os Olhos fazem essa verificação com desvantagem. Uma vez por descanso longo (mais um uso a partir do 17º nível)." },
        { nivel: 17, nome: "Agradar Multidões", descricao: "O alcance de Dê a Eles um Show aumenta para 18 metros, e os inimigos no alcance testam Sabedoria contra sua CD de Genjutsu como se afetados por um Genjutsu Visual, ficando deslumbrados e cegos até o fim do próximo turno em falha. Além disso, três criaturas (além de você) podem se beneficiar da observação dos seus lanches." },
      ],
    },
    {
      key: "vendedor-de-creme-glace",
      nome: "Vendedor de Creme Glacê",
      classeKey: "ninja-cozinheiro",
      descricaoIntro: "Os Cozinheiros-Nin que se concentram em se tornar um \"vendeur crème glacée\" tentam se concentrar mais em alimentos frios e refrigerados do que em quentes, usando uma mistura de liberação de água para gelar a competição.",
      features: [
        { nivel: 2, nome: "Delícia de Gelo", descricao: "Você aprendeu a criar uma aura fria com seus lanches, além de aprender a fazer comida congelada. Você aprende a palavra-chave Liberação de Água; se já a tiver, aprende um jutsu extra dessa liberação." },
        { nivel: 2, nome: "Bônus de Infusão de Ferramenta", descricao: "Você ganha uma segunda arma de infusão: uma ferramenta de cozinha voltada para o gelo (aura gelada ou colher de sorvete). No 2º nível, ela causa dano de Frio igual ao seu Dado de Cozinha, e você pode usar Inteligência em vez de Força. Escolha uma propriedade: Toque de Frio (ao atingir uma criatura com esta arma, pode acionar todos os graus de Frio no alvo, causando dano como se ela tivesse começado o turno com esse Frio; uma vez por turno); Gélido (ao lançar jutsu de Liberação de Água que inflige condição, pode mudar essa condição e todos os graus para Frio; alcance 9/18 metros); Pesado (a arma causa dois Dados de Cozinha em vez de um). A partir do 6º nível, propriedade adicional: Gelo Aprimorado (ao causar dano de Frio, uma criatura imune se torna resistente, e você causa dano normal a uma criatura que seria resistente); Quebra-Gelo (aumenta o dado de dano de Frio em 1 passo); Frio Estalante (ao causar dano com um jutsu de água que causa Frio, soma seu modificador de Carisma). A partir do 11º nível, propriedade adicional: Gelo Potente (dobra a quantidade de graus de Resfriamento que pode causar de uma vez, aumentando todos os outros efeitos de resfriamento); Congelamento Universal (sempre que atinge uma criatura com esta arma, inflige 1 grau de Resfriamento)." },
        { nivel: 2, nome: "Lanches Congelados", descricao: "Você aprende ingredientes secretos adicionais, com toque gelado: Sorvete de Barra de Daim (consumível como reação ao infligir 1 grau de Frio; role seu Dado de Cozinha uma vez e inflija graus extras iguais a 1/4 dos dados rolados); Profiteroles Congelados (consumível como reação quando você é alvo de uma jogada de ataque; um escudo congelado reveste seu corpo); Sanduíche de Sorvete (consumível como reação quando você for causar dano de Frio com um ataque ou efeito; role o Dado de Cozinha 4 vezes e cause dano adicional igual ao resultado); Cone de Neve (transforma temporariamente sua Liberação de Água em neve gelada, permitindo lançar Fuinjutsu: Campo de Captura Congelado uma vez no minuto seguinte, ignorando requisitos de palavra-chave e componentes; se não lançar ao menos uma vez, sofre 6d6 de dano de fogo irresistível; alternativamente, pode forçar uma criatura a comer este lanche com um ataque de Ninjutsu corpo a corpo a 1,5 metro — em acerto, ela é alimentada à força, o petisco cobre seu corpo com gelo espesso, causando 2 graus de Resfriamento e imobilizando-a até o fim do próximo turno)." },
        { nivel: 5, nome: "Gelo Entorpecente", descricao: "Sua afinidade com o gelo faz seus inimigos sofrerem mais do que o normal com os efeitos de frio que você usa. Além disso, quando uma criatura recebe dano de gelo, ela deixa uma área de 1,5 metro de piso congelado onde se encontra; essa área se torna terreno difícil até sofrer dano de fogo ou se passarem 10 minutos." },
        { nivel: 9, nome: "Aura de Frio", descricao: "Você ganha constantemente uma aura gelada de 3,5 metros (combinável com outra ativa). Sempre que uma criatura hostil começar o turno ou se mover dentro dela, deve testar Força contra sua CD de Ninjutsu (a fonte não especifica a consequência da falha neste teste — trecho ausente no material original)." },
        { nivel: 13, nome: "Alma do Inverno", descricao: "Você aprendeu a moldar e usar o gelo em todo o seu potencial. Se usar um jutsu de água que criaria uma área de água, pode fazer com que ele crie gelo ou neve. Além disso, em uma área de muita neve e gelo, pode controlá-la: como ação no seu turno, cria pontes, armas de neve temporárias que imitam as normais, barreiras e outros efeitos não hostis (a critério do Mestre) em raio de 36 metros. Alternativamente, pode usar como reação ao custo de um lanche." },
        { nivel: 17, nome: "Superaquecimento", descricao: "Você ganha resistência a dano de Frio. Quando lança um jutsu que causa dano de Frio, qualquer criatura que falhar no lance de defesa também é envolta em gelo, ficando presa até que ela ou um aliado a até 1,5 metro gaste uma ação para um lance de defesa de Força contra sua CD de Ninjutsu. Usável um número de vezes igual ao seu modificador de Carisma por descanso longo." },
      ],
    },
  ],
};
